### ISSUE TITLE
CentralHeatPumpSystem / ChillerHeater Misbehavior

### ISSUE THREAD

**Issue by srijanthecynosure** [NREL/EnergyPlus#10065]
Issue overview
--------------
The ChillerHeater system in the latest versions seem to have some issue while in heating or simulataneous htg/clg mode. I read through couple of threads on unmet hours and Github but did not find any resolution for those. After noticing the misconduct in my detailed complex model, I just carried out the simulation for the example file in EnergyPlus 'CentralChillerHeaterSystem_Simultaneous_Cooling_Heating' and noticed similar misbehavior. The issue I notice is whenever it is running in mode '2 (Heating Only)' the electricity consumption is too high, i.e. it kind of runs at full capacity even at low loads. The EIR as fuct of PRL in the output shows always ~0.99 regardless of the load on that module. Thus the electricity consumption is too high for even small loads. This issue can be more easily spotted if system timestep is made same as zone timestep so that there is no averaging due to timestep difference. I saw similar issue reported at
https://unmethours.com/question/45860/central-heat-pump-heating-mode-power-input-is-constant/
Also, in mode '3(simultaneous)' for many hours it does not report any electricity in either heating or cooling, i.e. zero electric consumption but still meeting load. That especially happens when the PLR is <0.85 (never at PLR 1). This issue is more pronounced in larger model but still there in example file. I saw similar issue was reported https://unmethours.com/question/35582/centralheatpump-not-always-recording-electricity-consumption/
Attached some graphs to show the issue.
Is there any aspect that I am missing or is it still a pending issue?
Thanks in advance!

### Details
Some additional details for this issue (if relevant):
Windows 10
Found in both v9.6 and v22 of EnergyPlus
[ - Unmethours link or helpdesk ticket number](https://unmethours.com/question/35582/centralheatpump-not-always-recording-electricity-consumption/)
![1](https://github.com/NREL/EnergyPlus/assets/53383888/c1266e18-b461-44b5-a097-ef009cc745f8)
![2](https://github.com/NREL/EnergyPlus/assets/53383888/664aa633-64a8-4a12-98cb-d19aedfdc56a)

**Comment by mjwitte** [comment]
@srijandidwania I have confirmed that the logic for part load ratio during heating mode is flawed. I do not see any possible workaround. It should be possible to have a fix in place for v23.2. All operating modes will be reviewed and corrected as needed.

**Comment by srijanthecynosure** [comment]
> @srijandidwania I have confirmed that the logic for part load ratio during heating mode is flawed. I do not see any possible workaround. It should be possible to have a fix in place for v23.2. All operating modes will be reviewed and corrected as needed.

Thankyou for confirming. Looking forward for the fix to avoid postprocessing on output files. It will need to be corrected in modes 2,3&5. Modes 1 and 4 (mostly cooling) seems to work good.

**Comment by srijanthecynosure** [comment]
> @srijandidwania I have confirmed that the logic for part load ratio during heating mode is flawed. I do not see any possible workaround. It should be possible to have a fix in place for v23.2. All operating modes will be reviewed and corrected as needed.

@mjwitte Seems like the new version 23.2 did not get this issue fixed. Just wondering if this is under the hood. There seems to be numerous issues with the chiller heater module and requires fixes. Thanks!

**Comment by mitchute** [comment]
See https://github.com/NREL/EnergyPlus/issues/7838 for potentially related issue.

**Comment by RKStrand** [comment]
(Note: This is written partially as an update but also partially as a reminder to myself because the code in this model is fairly complex.)

Current theory for the power constant issue above (first graph): it appears that in operation modes 2 (heating only with no heat recovery) and 5 (heating dominant with heat recovery), the variable CHPower which is used to make the first estimate of QCondenser, but when QCondenser is updated, CHPower is never recalculated and it stays at the value at "available capacity".  Since the output variables for heating electric power is set equal to CHPower for those modes, this explains why it is staying constant at roughly the capacity of the unit.  This needs to be fixed. (Update: actually, it's more complicated than just recalculating CHPower.  To back out the power, you have to know the QEvaporator which is based on the performance maps.  You can't just apply a fraction and go.  And it's an issue in more than one place.  So, I know what the source of the problem is, but the actual solution might end up being complicated based on what I am seeing at the moment.)

Still need to track down the cause of the issue in mode 3 (heat recovery mode) not reporting unit electric in some situations. (Update: it seems like there are some issues with how the Mode is assigned in certain situations and as a result in some of the logic.  Still trying to track down an IDF that demonstrates the problem beyond just seeing some issues in the code that don't make sense.)

**Comment by srijanthecynosure** [comment]
Great, the corrections appear to be very much in-line with the issues I had noticed. Thanks @mjwitte @RKStrand
