### ISSUE TITLE
UFAD Code Inconsistencies in Plume Power Calculations

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#10088]
Issue overview
--------------
@amirroth noted the following inconsistencies in the UFAD code.

1. The steam equipment convective summation is reset to zero inside the loop (for both the exterior and interior models).
https://github.com/NREL/EnergyPlus/blob/3ce85f9cde01190b8ee923e56f7b9606350fd53a/src/EnergyPlus/UFADManager.cc#L417-L422
https://github.com/NREL/EnergyPlus/blob/3ce85f9cde01190b8ee923e56f7b9606350fd53a/src/EnergyPlus/UFADManager.cc#L625-L630

2. When calculating the convective plume power, the equipment design level is multiplied by `.FractionConvected` for the interior model (first snipped above), but not for the exterior model (second snippet). This is the same across all equipment types. Seems like both models should use `.FractionConvected`. The engineering reference descriptions for this calculation use identical terms with `conv` subscripts.

The code has been this way since these features were first added [here](https://github.com/NREL/EnergyPlusArchive/commit/8fd87048ed0ed2c328a2cad581cacfbdc330c0f1#diff-e89bfdffca8ef2d108573498a880025022146e5dc24dd265e0c9a2c8cf9b4a7a).

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 23.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mjwitte Yes, these two items definitely look problematic, and I agree with your assessment.  Interestingly, due to some slick work in this area by @amirroth, who by the way also noticed these two issues, the code looks nothing like what it did only 2 months ago.  Which is kinda too bad, because some really cool code that switched between the interior and exterior model (can't wait to try those complex-style assignment statements!) will simply go away now because they should both be the same.  And yes, the steam should have been reset before the loop, not inside it.  This is next on my hit list for bug fixes, so barring any unforeseen problems, this should be ready for review late this week or early next.
