### ISSUE TITLE
Outdoor Air Schedule Name in DesignSpecification:OutdoorAir does not work

### ISSUE THREAD

**Issue by keigo-nomura** [NREL/EnergyPlus#10101]
Issue overview
--------------
As per the title. Outdoor Air Schedule Name in DesignSpecification:OutdoorAir does not change outdoor air flow rate. Please refer to the Unmethours link below for more details on the issue.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: V23-1-0
 - Unmethours link: [Outdoor Air Schedule Name in DesignSpecification:OutdoorAir does not work](https://unmethours.com/question/92981/outdoor-air-schedule-name-in-designspecificationoutdoorair-does-not-work/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Taking the 5ZoneFanCoilDOASCool_rev.idf  example you shared:

```diff
AirTerminal:SingleDuct:VAV:NoReheat,
    SPACE1-1 DOAS Air Terminal,  !- Name
    ,                        !- Availability Schedule Name
    SPACE1-1 DOAS Supply Inlet,  !- Air Outlet Node Name
    SPACE1-1 Zone Equip Inlet,  !- Air Inlet Node Name
    autosize,                !- Maximum Air Flow Rate {m3/s}
-   Constant,                !- Zone Minimum Air Flow Input Method
-   1.0,                     !- Constant Minimum Air Flow Fraction
    ,                        !- Fixed Minimum Air Flow Rate {m3/s}
    ,                        !- Minimum Air Flow Fraction Schedule Name
+   SZ DSOA SPACE1-1;        !- Design Specification Outdoor Air Object Name
```

https://github.com/NREL/EnergyPlus/blob/07b51a2c1ca55df2ec5ff297ef9514aa5ce4236a/src/EnergyPlus/SingleDuct.cc#L3953-L3962

CalcOAMassFlow correctly calculates it to be zero because of the OutdoorAirAvailSched.  But:

```
(lldb) p MassFlow
(Real64) $10 = 0.12210386490935213
(lldb) p MassFlowBasedOnOA
(Real64) $11 = 0
(lldb) p this->sd_airterminalInlet.AirMassFlowRateMinAvail
(Real64) $12 = 0.12210386490935213
(lldb) p this->sd_airterminalInlet.AirMassFlowRateMaxAvail
(Real64) $13 = 0.12210386490935213
```

So it's always going to be 0.12 anyways because the Minimum Air Flow Fraction is constant at 1.0.

You'll see a change in results (but still not what you probably expect) if you set this to 0.0. If you want to model this properly, you also probably want to add a Controller:MechanicalVentilation object on the AirLoopHVAC's Controller:OutdoorAir, and list the zones + DSOAs onto that Controller:MV.

**Comment by mjwitte** [comment]
This is working as designed, but could probably use some documentation updates to help clarify (I/O Reference and IDD notes).
See [answer here](https://unmethours.com/question/92981/outdoor-air-schedule-name-in-designspecificationoutdoorair-does-not-work/?answer=95358#post-id-95358) for more details.
