### ISSUE TITLE
Inconsistent Water Flow Rates in SwimmingPool:Indoor

### ISSUE THREAD

**Issue by keigo-nomura** [NREL/EnergyPlus#10102]
Issue overview
--------------
First of all, it's not clear whether SwimmingPool:Indoor component allows constant water flow or not.
When we model a plant loop withSwimmingPool:Indoor and Pump:ConstantSpeed, **System Node Mass Flow Rate** of **Pool Water Inlet Node** and **Indoor Pool Inlet Water Mass Flow Rate** are inconsistent. Please refer to the Unmethours link below for more details on the issue.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: V23-1-0
 - Unmethours link: [Inconsistent Water Flow Rates in SwimmingPool:Indoor](https://unmethours.com/question/93010/inconsistent-water-flow-rates-in-swimmingpoolindoor/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@keigo-nomura I've already posted an answer on Unmethours, but I will also post something here.  If you look at the IO Ref, it specifically says that the maximum flow rate will be adjusted to get the actual flow rate.  Given that it doesn't vary the inlet temperature, it has to modify the flow rate to get the correct heat addition to meet the setpoint.  At least, that is what was implemented when the swimming pool was added.  As you point out, there are other possibilities.  It's possible that I could add something under the guise of a "defect" that is really a small scale new feature.  The IO Freeze is coming up very soon (one week from today) so if you can specify what you are looking for, I can see what I can do.  No guarantees but it's still potential possible to get something in.

**Comment by RKStrand** [comment]
@keigo-nomura This issue has the "defect file added" checked, but I'm not seeing a file listed.  I also don't see one in EnergyPlusDevSupport listed under this issue number.  Was this issue related to an existing file in the test suite or your own file?  If your own file, would you be willing to share it?  Thanks!

**Comment by keigo-nomura** [comment]
@RKStrand The link of my own file is on the UnmetHours page.

**Comment by RKStrand** [comment]
@keigo-nomura Thanks for letting me know that the file was on the UnmetHours page.  I downloaded it and have been doing some digging.  It appears that there is an assumption built into the swimming pool that the plant loop will figure out what is happening, but that isn't happening the way it was anticipated.  I simplified the secondary demand loop to be a single branch with no connection components to eliminate any potential concern that those are causing an issue.  It doesn't seem like they are.  What I am seeing in the simplified branch layout is that the inlet flow to the pool is the flow rate of the loop (set by the secondary loop pump), but the outlet flow from the pool has the lower flow rate.  That gets transferred to the outlet node of the secondary demand side, but when the secondary supply side runs, it seems to overwrite that back to the pump flow rate.  Clearly, that can't be correct because it doesn't even conserve mass flow through the loop.  However, when I put a bypass in parallel to the swimming pool, the mass flows do balance because the excess goes through the bypass.  I'll keep looking at this.  The lack of flow balance is clearly a problem that needs to be addressed now.  Whether I can get the flow you want when there is no bypass, I am not sure, but I will do my best.  If it needs a new input, at least some of this would need to wait for the next release.

**Comment by RKStrand** [comment]
@keigo-nomura Well, this was more complex that I thought it would be, but I believe that I have fixed this issue (see pull request https://github.com/NREL/EnergyPlus/pull/10196).  Before the fix, the inlet and outlet flow rate for the pool did not match when there was no bypass present.  After the fix, without a bypass, the flow rates going into and out of the pool are both equal to the flow rate established by the loop.  Internally, there is an implied bypass and three-way value that manages the flow.  So, the outlet temperature for the pool will not equal the pool water temperature in this case.  Rather it will be based on a simple energy balance for the water that actually goes through the pool and the water that goes through the implied bypass.  Assuming this goes in, you should see that in the upcoming Version 23.2 release.  In the meantime, you can simply establish a bypass branch in parallel to the swimming pool as a temporary fix.  That works with the current version of EnergyPlus.

**Comment by RKStrand** [comment]
@keigo-nomura This unfortunately did not make the release.  The solution I presented was viewed as not correct from the standpoint of how the code operates in the HVAC portion of the simulation.  So, I will be working on a different solution in hopes of finding a permanent fix.  You can still establish a bypass as noted above to get a temporary "fix" to the problem.  Sorry for any confusion or false hope as a result of the above comments.  Next time, I won't say it's fixed until it's actually merged in.

**Comment by keigo-nomura** [comment]
@RKStrand It's ok. Thank you for tackling this issue.
