### ISSUE TITLE
VRF cooling issue: same cooling power with different min-speed curve at low cooling load

### ISSUE THREAD

**Issue by yujiex** [NREL/EnergyPlus#10105]
Issue overview
--------------

**Cycling issue at the lowest fan speed**

The two idf files reproducing this problem is derived from the "US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf". They differ at the performance curves at the lowest compressor speed, the speed_1920.idf is created by removing the lowest speed as follows:

![image](https://github.com/NREL/EnergyPlus/assets/13421161/cf578bb8-3aa8-4c78-a24d-adf46463f79e)

Row 2-7 shows the simulation results when the minimum compressor minimum speed is 900 with speed curve 1. Row 9-14 shows the simulation results when the compressor minimum speed is 1920 and using performance curve 2. Note that the capacity curves of speed levels are in the order of ascending capacity. We can see that even if the two settings have different compressor curves for the minimum speed, they output the same cooling rates, yet very different cooling electricity rate and COP. The heat pump runtime fraction and cycling ratio are 1 in both cases.  For the same cooling demand (both the zone and outdoor temperature are the same), if it runs fulltime in speed_900.idf, it should only run part of the time in speed_1920.idf, as its min capacity is larger than the former. They can't both run fulltime. 

![image](https://github.com/NREL/EnergyPlus/assets/13421161/b2d548d4-f5a4-4018-9033-91d61beecaa3)
 
### Defect files

[simulation_with_different_speeed_update.zip](https://github.com/NREL/EnergyPlus/files/14543997/simulation_with_different_speeed_update.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac 13.3)
 - Version of EnergyPlus (22.2)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@yujiex The only difference between these two idfs is the compressor speed at load index 1.
![image](https://github.com/NREL/EnergyPlus/assets/4991075/07e54569-e1c8-4e3f-be6e-14cb931c44f0)
I would not expect any change in results (other than the reported "VRF Heat Pump Compressor Rotating Speed", because the compressor speed is just a reporting proxy for the interpolated load index. The curves are the real driver of capacity and power consumption for each load index.

**Comment by yujiex** [comment]
> @yujiex The only difference between these two idfs is the compressor speed at load index 1. ![image](https://private-user-images.githubusercontent.com/4991075/310991690-07e54569-e1c8-4e3f-be6e-14cb931c44f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzU3MDMsIm5iZiI6MTcwOTgzNTQwMywicGF0aCI6Ii80OTkxMDc1LzMxMDk5MTY5MC0wN2U1NDU2OS1lMWM4LTRlM2YtYmU2ZS0xNGNiOTMxYzQ0ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMTgxNjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODAzN2FjYzA4NjBjNzI3YzljYTRjYjBhZmUxYTBjMTE2Y2RjMTRkNDBjZmIwMmMxOTgxMzkzZjljN2Y4YzM4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.90dIqYgEzxUUMl0zNm7SGQUW2higmPWYKkvCZWDDunM) I would not expect any change in results (other than the reported "VRF Heat Pump Compressor Rotating Speed", because the compressor speed is just a reporting proxy for the interpolated load index. The curves are the real driver of capacity and power consumption for each load index.

Hi @mjwitte, they also differ in the curves. The min-speed = 900 one uses Spd1Cooling and Spd1Power curves, while the min-speed = 1320 one uses Spd2Cooling and Spd2Power ones.

**Comment by mjwitte** [comment]
The ones in the zip file do not have different curves. If I change the curve, then I *do* get different results for "VRF HEAT PUMP:VRF Heat Pump Cycling Ratio" and power consumption and COP.  I would expect the same cooling delivered to the zone either way. These inputs should only change the compressor power consumption and related outputs since it will adjust speed and/or cycling ratio to match the load request from the zones. I'm looking at time stamp 07/06 2:10:00 (this is with different load 1 speed and curves):

![image](https://github.com/NREL/EnergyPlus/assets/4991075/ba572187-e3e7-487d-971c-17e5f97d0d97)
![image](https://github.com/NREL/EnergyPlus/assets/4991075/94a269ee-b4ec-4588-8931-e09bd7335de2)

**Comment by yujiex** [comment]
> same cooling delivered to the zone either way

I uploaded the correct version of the test files with different curves for the lowest speed. 
Let me double-check the delivered heat to the zone.

**Comment by yujiex** [comment]
I just pushed a commit with cycling ratio multiplied to the OUCondHeatRelease variable. The difference in the condenser heat release rate output is smaller. @mjwitte 

![image](https://github.com/NREL/EnergyPlus/assets/13421161/17a82a1c-193d-4960-97bb-2dfdafff5e2c)
