### ISSUE TITLE
CheckConvexity throws Surface is Non-Convex warnings regardless of ShadowCalculation settings

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#10299]
Issue overview
--------------
User file with PixelCounting is throwing warnings like this:
```
   ** Warning ** CheckConvexity: Zone="CEILING VOID ZONE A.A.4.1", Surface="CEILING VOID A.A.4.1:INTERZONE A.A.5.1:3" is non-convex.
   **   ~~~   ** ...vertex 3 to vertex 4 to vertex 5
   **   ~~~   ** ...vertex 3=[45.72,36.58,15.75]
   **   ~~~   ** ...vertex 4=[36.58,36.58,15.75]
   **   ~~~   ** ...vertex 5=[36.58,45.72,15.75]
```

1. The documentation mentions that zone convexity doesn't matter with PixelCounting but it does not mention surface convexity. @nealkruis says pixel counting should not care about convexity. (also see https://github.com/NREL/EnergyPlus/issues/9972#issuecomment-1739133806).
2. The documentation for Polygon Clipping Algorithm implies that these warnings should only be active when using ConvexWeilerAtherton.
3. Is there some other reason (e.g. daylighting, diffuse shading, or other geometric calculations) that would warrant a non-convex surface warning here?

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 23.2
 - Helpdesk ticket 16495

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@RKStrand (or whomever takes this) I think this just needs another condition here to skip the warning if Shading Calculation Method is PixelCounting, or if using PolygonClipping if Polygon Clipping Algorithm = SutherlandHodgman or SlaterBarskyandSutherlandHodgman. Or more simply, warn only if using PolygonClipping with ConvexWeilerAtherton.

The same defect file could be used to test if these warnings are currently showing with PolygonClipping  with SutherlandHodgman and SlaterBarskyandSutherlandHodgman. And maybe compare some shadowing results across all the algorithms?

https://github.com/NREL/EnergyPlus/blob/e2c430549a6c69dd555668fa10b0fdc18883a873/src/EnergyPlus/SurfaceGeometry.cc#L15682-L15689

**Comment by RKStrand** [comment]
@mjwitte Update: hmmm, this is not as simple as just adding a new check.  That would be a solution except when I tested the addition of checks like you suggested I discovered that GetShadowingInput which reads the ShadowCalculation input has not yet been called.  So, CheckConvexity doesn't know yet what method is being used.  And you can't simply move up GetShadowingInput because it needs to know the zone list and surface information for some of the checks that it performs.  So, I may have to split apart the functionality of GetShadowingInput to do the reading in one place and the processing of zone/surface info where GetShadowingInput is currently done.  Interesting.

**Comment by rraustad** [comment]
@RKStrand it may be too early to move GetZoneData and GetSurfaceData to init_state as in #10585 (because there may be more to do before that can happen) but keep in mind what init_state is trying to accomplish. Read in getInputs early so as not to have these types of issues in the future.  See lines 572-582 of EnergyPlusData.cc in that pull request to see where that effort is headed.

**Comment by RKStrand** [comment]
> @RKStrand it may be too early to move GetZoneData and GetSurfaceData to init_state as in #10585 (because there may be more to do before that can happen) but keep in mind what init_state is trying to accomplish. Read in getInputs early so as not to have these types of issues in the future. See lines 572-582 of EnergyPlusData.cc in that pull request to see where that effort is headed.

@rraustad Thanks for reminding me about work that you are currently doing.  Now that you mentioned it here, I do remember there was a short discussion on this during the last iteration call.  It would be really nice if we could eliminate these "order dependent" initializations.  I'm not 100% what I can do here since I haven't looked in detail at what you have been doing yet, but I like that concept if it's possible.  In your work, have you had to do much in the way of separating out the reading of data from one-time initializations/checks that often accompany those gets?  That is sort of what I think I am facing here.

**Comment by mjwitte** [comment]
For this it would likely be much easier to move reading ShadowCalculation input to `init_state` instead of GetZoneData.

**Comment by RKStrand** [comment]
@mjwitte Definitely agree with you on that.  I am looking at separating the current get in ShadowCalculation into two things once I fully understand all of the inits that are also happening in there.  Having taken a quick look at what @rraustad is doing with fluid properties, it would be good to get the "get" stuff moved to the init_state.  I like how what @rraustad is doing over in #10585 is getting rid of the multiple calls to the get input routine.  Makes a lot of sense.

**Comment by rraustad** [comment]
@RKStrand I have not had to split out getInput reads versus getInput processing since #10585 is very preliminary and did not require that type of change. The bigger issue was unit test updates. However, IMO, I would like to ensure data integrity as much as possible (i.e., is this a valid zone name, etc.). That of course would require reading the inputs and performing the normal checks on integrity. How much processing is required in the various getInputs will just need to be learned over time while moving things to init_state. I'm not sure where this will end up in the long run but I do think getting the order of the init_state calls correct in EnergyPlusData.cc will eliminate a lot of "splitting up getInput processing". Only time will tell. I would say move forward with whatever you think is best at this point and then pulling that new code into init_state in the future will just have to deal with whatever you wind up with. If you feel using the init_state method will help here, feel free to do so.

**Comment by RKStrand** [comment]
Documentation modifications about convex surfaces is being handled as part of #9972 (same assignee: @RKStrand)
