### ISSUE TITLE
Vector error when zone has no surfaces

### ISSUE THREAD

**Issue by TRLiang** [NREL/EnergyPlus#10305]
Program Version,EnergyPlus, Version 23.1.0-87ed9199d4, YMD=2023.11.20 18:36,
   ************* Beginning Zone Sizing Calculations
   ** Severe  ** vector too long
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 1 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  0.07sec

**Comment by mjwitte** [comment]
@TRLiang In this idf file (see helpdesk ticket 16529) zone PLENUM-1 has no surfaces. There is a logic error in function `GetSurfaceData` which fails for this case. The workaround is to add a dummy adiabatic surface to zone PLENUM-1, or to change the AirLoopHVAC:ReturnPlenum to an AirLoopHVAC:ZoneMixer.

Once that is fixed, this error is thrown:
```
   ** Severe  ** DemandManager:Thermostats="COOLING PLANT" invalid Thermostat Name="ALLCONTROLLEDZONES" not found.
   ** Severe  ** DemandManager:Thermostats="COOLING PLANT" invalid value for number of loads.
   **   ~~~   ** Number of loads is calculated to be less than one. Demand manager must have at least one load assigned.
   **  Fatal  ** Errors found in processing input for demand managers. Preceding condition causes termination.
```
The DemandManager does not support Zone List Names, each thermostat name must be listed here.

Defect file in EnergyPlusDevSupport\DefectFiles

**Comment by mjwitte** [comment]
@jasondegraw Is it possible to add more context to these types of `vector` errors?
```
** Severe ** vector too long
```

**Comment by jmarrec** [comment]
This the C++ STL that issues this message, via EPVector

It uses `std::vector<T>::operator[]` (no bounds checking) in release and `std::vector<T>::at()` in Debug:

https://github.com/NREL/EnergyPlus/blob/321d7d1e31bf2c316d7108d230260b13404d4a44/src/EnergyPlus/EPVector.hh#L61-L86



On GCC Debug for eg, I get `  ** Severe  ** vector::_M_range_check: __n (which is 18446744073709551614) >= this->size() (which is 47)`. 
That very large number is because we implicitly convert int(-1) to an unsigned long.

In GCC Release: `** Severe  ** vector::_M_fill_insert`

https://github.com/NREL/EnergyPlus/blob/321d7d1e31bf2c316d7108d230260b13404d4a44/src/EnergyPlus/SurfaceGeometry.cc#L2334

We could just define our own check with a clearer error message, but then we'd always be paying the runtime check.
