### ISSUE TITLE
"Nominal Min/Max Number of People" in People Internal Gains Nominal table includes effect of design day schedules

### ISSUE THREAD

**Issue by eringold** [NREL/EnergyPlus#10314]
Issue overview
--------------
The fields ['Nominal Minimum/Maximum Number of People' ](https://bigladdersoftware.com/epx/docs/23-2/output-details-and-examples/eplusout-eio.html#field-nominal-minimum-number-of-people) of the People Internal Gains Nominal table in the Initialization Summary Report are described as: 

>This numeric field is the calculated maximum number of people based on the number of people field * the maxnimum value (annual) for the people schedule. It may be useful in diagnosing errors that occur during simulation.

The inclusion of "(annual)" implies the people schedule values are only the Simulation Run Period schedules values. However, inspecting these values compared to model input, as well as inspecting the source code reveals that:
1. `thisPeople.NomMaxNumberPeople` is calculed using `SchMax` here: https://github.com/NREL/EnergyPlus/blob/4ccd87a62126858f1b7b61dde81c31b476775693/src/EnergyPlus/InternalHeatGains.cc#L499-L500
2. `SchMax` is obtained from the function `GetMaxScheduleValue` here:
https://github.com/NREL/EnergyPlus/blob/4ccd87a62126858f1b7b61dde81c31b476775693/src/EnergyPlus/InternalHeatGains.cc#L357
3.  [`GetScheduleMaxValue`](https://github.com/NREL/EnergyPlus/blob/4ccd87a62126858f1b7b61dde81c31b476775693/src/EnergyPlus/ScheduleManager.cc#L4402) simply gets the maximum value of all Schedule:Days referenced by the schedule, **including Summer/Winter Design Day Types**.

So for the common case of People schedules with Summer design day schedules set to 1, Winter to 0, and 'annual' some fractional occupancy profile, currently the 'Nominal Minimum/Maximum Number of People' will simply reflect zero or the design people level (which is [already included](https://bigladdersoftware.com/epx/docs/23-2/output-details-and-examples/eplusout-eio.html#field-number-of-people) in the table). 

I believe there is value in having EnergyPlus report out the maximum nominal number of people in the model during the simulation run period (without having to analyze timeseries outputs or parse the input file, and it seems like that was the intent of these columns in the People Internal Gains Nominal table, but the implementation does not match. I suspect what's needed is a modification of `GetScheduleMaxValue` that ignores SummerDesignDay and WinterDesignDay DayTypes.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): Found in 23.1.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
Related to this problem, if the SummerDesignDay or WinterDesignDay are not specified in a Schedule:Compact, then it appears that zero is the default value for the missing values which means that the "minimum people" column shows zero even if the rest of the schedule is always greater than zero.

**Comment by JasonGlazer** [comment]
@eringold after working on resolving this issue for a little while I would like to propose a solution and wonder what you think of it. Unfortunately,  just changing the functionality of GetScheduleMaxValue and GetScheduleMinValue has cascading impacts because that function is used when sizing and in that case, the design day values are important. One file that clearly demonstrates this is DOASDualDuctSchool.idf. An example of how the results of this function are used is for  computing the outdoor air although it applies to any load that looks at the maximum value. As an alternative, I'm thinking of adding new columns to the EIO "People Internal Gains Nominal" report which would also show up in the InitializationSummary. The two columns

- Nominal Minimum Number of People
- Nominal Maximum Number of People

would be replaced by more explicit:

- Minimum Number of People for All Daytypes
- Maximum Number of People for All Daytypes
- Minimum Number of People for Weekdays
- Maximum Number of People for Weekdays
- Minimum Number of People for Weekends/Holidays
- Maximum Number of People for Weekends /Holidays
- Minimum Number of People for Design Days
- Maximum Number of People for Design Days

I would update the documentation to be consistent. What do you think?

I am also considering making similar changes to other EIO reports like Lighting Internal Gains Nominal and ElectricalEquipment Internal Gains Nominal since they have a similar structure. Does that make sense?

**Comment by eringold** [comment]
@JasonGlazer I think those column changes would suffice. My use case was an easy way to get maximum building runtime occupancy, and these proposed columns would facilitate that.  And extending to other internal gains makes sense too.

Thanks for fixing!

**Comment by JasonGlazer** [comment]
@eringold please take a look at #10437 and let me know if you see any problems.

**Comment by eringold** [comment]
@JasonGlazer I don't see any problems with the PR, except I think it should also include an update to the ['Output Details and Example'](https://github.com/NREL/EnergyPlus/blob/0b106a07b7da98302fe6b70dc9c13ee8842cf9f1/doc/output-details-and-examples/src/output-files/eplusout-eio.tex#L1126-L1133) documentation.

**Comment by JasonGlazer** [comment]
Thanks for the reminder.
