### ISSUE TITLE
EnergyPlus Stuck with Unhandeled Exception

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#10386]
Issue overview
--------------
The [attached IDF file](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/Example_ZeroCapacityCoil.idf) has an input error where the variable speed DX cooling coil capacity is specified 0 value, then EnergyPlus seems to be stuck at "Initializing Simulation" step. When I ran the IDF in debug environment, I see an "Exception Unhandled" error at line 1353 of VariableSpeedCoils.cc where the capacity ratio is calculated. I guess it is a divide by 0 error. 
![image](https://github.com/NREL/EnergyPlus/assets/7797674/1b02035c-e4b2-4711-baf8-bf9b7cd652e8)

![image](https://github.com/NREL/EnergyPlus/assets/7797674/4cb7bdce-0bb3-43c5-900a-b384540a5d71)

In this case, instead of program being stuck, I think there should be an error reported, or at least crash the calculation. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10 64 Bit)
 - Version of EnergyPlus (23.2)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Defect file added ([list location of defect file here](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/Example_ZeroCapacityCoil.idf))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@TiejunWu In my analysis of this, clearly the capacity being set to zero is causing a problem.  Setting the capacity to a non-zero value fixes the problem, but the code should flag for this automatically rather than have an infinite loop occur.  While I do not get a divide by zero here, but rather elsewhere, I do see that this then leads to an infinite loop in a psychometrics routine.  Either way, the problem is when the user has set the capacity to zero and that clearly does not match the intent of the code.  I will fix this when the input is read in and this should resolve the issue.
