### ISSUE TITLE
WaterUse:Connections node volume flow rate does not match WaterUse:Equipment volume flow rate

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#10443]
Issue overview
--------------
A user noticed that the node volume flow rate did not match expected results when using WaterUse:Connections object.

HelpDesk ticket 16611 uses a Schedule:Compact with a 0.5 fraction all day.

![image](https://github.com/NREL/EnergyPlus/assets/5778156/41a84ada-3f02-4e6f-9af9-732c8219e8d5)

  WaterUse:Equipment,
    ZN_1_FLR_1_SEC_1SHW_DEFAULT,  !- Name
    SHW_DEFAULT,             !- End-Use Subcategory
    0.012291667,     !- Peak Flow Rate {m3/s}
    BLDG_SWH_SCH,            !- Flow Rate Fraction Schedule Name

  Schedule:Compact,
    BLDG_SWH_SCH,            !- Name
    Fraction,                !- Schedule Type Limits Name
    Through: 12/31,          !- Field 1
    For: AllDays, !- Field 2
    Until: 24:00,0.5;       !- Field 91

The water use equipment hot water flow rate is the expected value, however, the water use connections object shows a different water volume flow rate.

![image](https://github.com/NREL/EnergyPlus/assets/5778156/7da813a8-9e39-48ad-8719-81c656f38384)

Changing the WaterUse:Equipment calculation to use actual water temperature got closer but did not match exactly and now the water use equipment volume flow rate does not match the user inputs.

        this->TotalMassFlowRate = this->TotalVolFlowRate * Psychrometrics::RhoH2O(Constant::InitConvTemp);
        this->TotalMassFlowRate = this->TotalVolFlowRate * Psychrometrics::RhoH2O(this->TargetTemp);

![image](https://github.com/NREL/EnergyPlus/assets/5778156/241c930f-8312-4c0a-a01f-cb62cf90de0b)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ([5ZoneVAV-ChilledWaterStorage-Mixed_Modified.zip](https://github.com/NREL/EnergyPlus/files/14668019/5ZoneVAV-ChilledWaterStorage-Mixed_Modified.zip))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
In looking at this, it seems like the issue might be a difference between the plant loop and the water use routines?  The water use routines use InitConvTemp consistently to avoid the problems internally, but when the plant does calculations, it's probably using whatever the temperature is at the node.  So, internally in water use, everything is happy and consistent, but then the node gets calculated and this consistency is broken because density is being calculated at a different temperature.  That's my current theory after some initial research.  So, perhaps an adjustment of the volumetric flow rate to account for those densities at different temperatures would eliminate the difference in volumetric flow rate?  Though there would still be differences in water mass flow rate if those were compared??

**Comment by RKStrand** [comment]
Oh, now I think I see what is going on here.  The mass flow rates are in fact the same between the nodes and components.  And both use the same temperature to calculate the density (InitConvTemp).  The difference however is that the water use routine is using Psychrometrics::RhoH2O (an equation) while the node routine is using GetDensityGlycol (a linear interpolation) for water.  The equation is sending back roughly 1000 while the glycol routine is sending back roughly  999.898.  Since the same temperature is being used, both routines get constant values and the ratio between the two never changes.  That was also the case for the ratio of the two volumetric flow rates--always the same ratio.  I get that both are "correct" but since there are slight differences they can't be used interchangeably like this.  I'm sure the thought when putting together the water use module was to just use the available psych routine since it was a guarantee that it would always be water.  Looks like maybe some work was done here at some point but it missed water use which is a slightly different animal.  I think the best solution here is to convert the calls in water use to use the fluid property routines like everything else--just "hard wired" for water.  @rraustad Thoughts?

**Comment by rraustad** [comment]
@RKStrand if using the same calls for density fixes this then that sounds like the correct fix.
