### ISSUE TITLE
Fan Energy Index (FEI) calculations use reference standard air density at elevation instead of at sea level

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#10509]
Issue overview
--------------
Work on node initializations (#10485) revealed an issue with fan FEI calculations. The reference standard air density should be at sea level and the fan inlet air density should be a moist air density at some reference temperature and humidity ratio (e.g., 21 C and 50%).

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@rraustad I want to make sure that I am interpreting this correctly.  Are you saying that the fan inlet air density should effectively be a constant calculated at 21C, 50%RH for all cases and the sea level standard density should be calculated at 20C, 0%RH like the standard density (StdRhoAir)?  ANSI/ACMA 208-18 says that the density ratio is the fan inlet density divided by standard density (1.2kg/m3) which is almost the same as density at sea level.  Are you saying that this should be based on a "design" inlet air density because it's only used for reporting?  Again, just trying to make sure I'm not misinterpreting anything that you are saying or what is in the standard before moving forward with a potential solution.

**Comment by rraustad** [comment]
This was discussed during #10485 and the question is, what is the rho in the (rho / rho, std) calculation? Where rho is the fan inlet condition and passed into the FEI function. It seems 1) the rho is (was?) calculated using 0 C, and 2) what inlet air condition should be used for the FEI calculation so early in the simulation (when node information has not yet been initialized)?

**Comment by RKStrand** [comment]
I see that I should have gone back and looked at the other work that resulted in this defect.  Thanks for the additional insight here.  I understand why the value of 21C is being referenced, since a density of 1.2 kg/m3 corresponds to a temperature of 21C as I think you said in the comments to #10485.  So, the ratio would be that the density of air at "inlet" conditions of 21C, 50% RH to the density of air at standard-ish conditions at 21C, 0% RH?  Or should we use 1.2 kg/m3 directly since that is what the standard says?

Here is what I propose:

1. Use the standard air density of 1.2 kg/m3 within the report_fei function.
2. Not pass in the air density to report_fei.  Rather, calculate it based on 21C, 50% RH.
3. Make changes needed to implement that, add a unit test, and make sure any documentation agrees with this and references the ANSI/ACMA standard.
4. Check how this impacts the output--I think that this is just for a report so the changes should be limited to that report, right?

Thoughts?

**Comment by rraustad** [comment]
I think this is a sound plan. 21 C is arbitrary but it's the same temperature used in the standard density calculation using moist air and at altitude. So (rho / rho, std) becomes a moist air at altitude adjustment. I don't know of a way to figure out a "typical" fan inlet condition based on where the fan is located and under typical loads and inlet conditions. Yes, these changes should be limited to diffs in the FEI report.

Maybe others would also have some input on this subject: @nealkruis @mjwitte @tanaya-mankad @EnergyArchmage @yujiex @JasonGlazer @dareumnam @hongtz68 @jcyuan2020 @nagappanchidambaram @yzhou601 @Nigusse @lgu1234 @lymereJ @larryscheier
