### ISSUE TITLE
IDF file causing segfault

### ISSUE THREAD

**Issue by egreyadsk** [NREL/EnergyPlus#10555]
Issue overview
--------------
The attached IDF file is causing a segfault.  It takes a couple hours before the error happens.

### Details
Some additional details for this issue (if relevant):
 - Windows 10 Enterprise
 - 23.1.0-87ed9199d4

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added  [in.zip](https://github.com/user-attachments/files/15778219/in.zip)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by egreyadsk** [comment]
@marklemay @MatthewSteen  FYI, this is logged by Autodesk.

**Comment by jmarrec** [comment]
I don't think anyone is especially looking forward to waiting for a couple of hours to reproduce a crash.
Especially if you consider that if you attach a debugger, you're running in debug mode, so that's going to be like 10 hours waiting to catch a stacktrace.

@egreyadsk , can you please provide **any** additional information?
stdout/stderr + eplusout.err would be great if possible.

When does it happen? During Sizing? During the annual runperiod? If so, which months? Can we reproduce by just running a couple of days around that time?

**Comment by mjwitte** [comment]
This looks similar to #10490 but this doesn't have more spaces than zones, so it can't have more solar enclosure than zone. It does trip on the same convexity assert, but that's a side note. I'll run this with the branch for #10498 to see if and where it fails there.

**Comment by mjwitte** [comment]
I can confirm that the file runs to completion with a release build of the branch for #10498, which is good yet puzzling.
@marklemay Does this idf have interior windows?

**Comment by mjwitte** [comment]
Found the problem, and it was fixed in v24.1. In v23.1 it fails with a stack overflow when the old `QsortC` function tried to sort the meter names, all 16,311 of them in this file. This function was replaced with a map in https://github.com/NREL/EnergyPlus/pull/10347, thanks @amirroth !

How are there so many meters? There are 1393 spaces and 1393 zones. These generate a lot of submeters for both spaces and zones. I can't think of a workaround for v23.1 other than reducing the number of spaces and zones. Or move to v24.1.

**Comment by egreyadsk** [comment]
Thanks @mjwitte and @jmarrec for looking at this.

**Comment by MatthewSteen** [comment]
@egreyadsk this fix will be included in the next build of the OpenStudio CLI For Revit (OpenStudio 3.8.0, EnergyPlus 24.1) since it was fixed in EP 24.1.

**Comment by egreyadsk** [comment]
Thanks @MatthewSteen, that's good to know.
