### ISSUE TITLE
epfilter contains old field names (CR #8044)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#2822]
## 
#### Description

LKL, 3/11/2010
As I was updating for AirTerminal:SingleDuct:VAV:Reheat, I noticed that some of the "field names" generated still contain the old "KEY--Component" 

The code should be reviewed for older field names and updated.

MJW 26 May 2011
All of the "KEY --" field names have been updated.  And some others:

Update selected field names in :
SingleDuct:SeriesPIU:Reheat, was "Reheat coil air inlet node (fan outlet node)"
SingleDuct:ParallelPIU:Reheat, was "Reheat Coil Air Node Name Inlet Node Name"
Fan:\* (all field names are now current)
AirLoopHVAC:SupplyPath/AirLoopHVAC:ReturnPath, was "KEY--System Component Type", "Controlled Component Name"
AirLoopHVAC:OutdoorAirSystem:EquipmentList, was "Controlled Component Name"
PlantEquipmentList and CondenserEquipmentList, was "KEY--Plant Equip" and "Equip Name"
ZoneHVAC:FourPipeFanCoil, various old field names

Glazer - 2012-Mar-23
Partially addressed only - added developer flag in ExpandObjects for displaying warning when field names are not consistent with the IDD field names. Made changes to some objects but considerable additional work is needed to change other field names.
## 

Last build tested: `10.03.10 V5.0.0.021`

**Comment by mjwitte** [comment]
As mentioned above, this flag can be used to identify invalid field names for debugging purposes.
! The following is a flag used by developers only to enable
! code that checks if the field names that are written out
! to the expanded.idf file use fields that exist in the IDD.
! It also enables the entire IDD being read instead of only
! the HVACTemplate objects. It will affect speed so it should
! be set to off for distribution to users.
LOGICAL :: checkOutputFieldNamesAgainstIDD = .false.
INTEGER :: checkObjectIndex = 0

**Comment by Myoldmopar** [comment]
Dang, that's a nice feature!

**Comment by JasonGlazer** [comment]
The ExpandObjects.exe is a preprocessor for EnergyPlus that looks for specific objects within an in.idf file and converts them into objects that the EnergyPlus.exe actually processes. The objects that it processes all start with the the text "HVACTemplate:" and includes HVACTemplate:Thermostat, HVACTemplate:Zone:VAV, etc. For each HVACTemplate object, usually many normal EnergyPlus objects are created. Since ExpandObjects was written so long ago it contains field names for each of these created objects that are no longer up to date with the current fields names shown in the Energy+.idd file. 

It creates a file called expanded.idf which contains the new IDF file with the converted IDF objects and the expandedidf.err file that lists any errors it encountered during the conversion process. Both of these are normally managed by batch files to use the expanded.idf file instead of the in.idf and to merge expandedidf.err with the normal error files.

To fix this issue, the ExpandObjects source code which is located in the epfilter.f90 file needs to be modified. This is a Fortran source file so make sure that when you used CMake that the BUILD_FORTRAN option was checked. You also need to open the source file: 

.\src\ExpandObjects\epfilter.f90

using either File Open in Visual Studio or with a separate editor. 

The first thing to do is to flip checkOutputFieldNamesAgainstIDD from .false. to .true. (that is how Fortran shows Boolean constants) which is on line 287. Build the ExpandObjects_build subproject. It should create a new ExpandObjects.exe with a current timestamp in Build\Products. Take an example file that is in the testfiles directory that starts with HVACTemplate and copy it into Build\Products and rename it in.idf. Open a command window and type ExpandObjects. It should say something like:

```
ExpandObjects Started.
******* checkOutputFieldNamesAgainstIDD Enabled ***********
 Begin reading Energy+.idd file.
 Done reading Energy+.idd file.
ExpandObjects Finished with Error(s). Time:     0.719
```

If you open the expandedidf.err file with a text editor it should list all the field names that it wrote that are wrong. If you did this with the HVACTemplate-5ZoneVAVWaterCooled.idf file you should get an file that shows:

```
ExpandObjects: For object: "Fan:VariableVolume" field name not found: "Fan Efficiency"
ExpandObjects: For object: "Fan:VariableVolume" field name not found: "Fan Power Coefficient 2"
ExpandObjects: For object: "OutdoorAir:Mixer" field name not found: "Outside Air Stream Node Name"
ExpandObjects: For object: "Controller:OutdoorAir" field name not found: "Economizer Maximum Limit Dewpoint Temperature (C)"
ExpandObjects: For object: "Boiler:HotWater" field name not found: "Design Boiler Water Outlet Temp"
ExpandObjects: For object: "Boiler:HotWater" field name not found: "Max Design Boiler Water Flow Rate"
ExpandObjects: For object: "Boiler:HotWater" field name not found: "Water Inlet Node Name"
ExpandObjects: For object: "Boiler:HotWater" field name not found: "Water Outlet Node Name"
ExpandObjects: For object: "Boiler:HotWater" field name not found: "Temp Upper Limit Water Outlet"
...
```

If you open the Energy+.idd file you will notice that the Fan:VariableVolume object does not a field called "Fan Efficiency" but instead the field is called "Fan Total Efficiency".  To fix this look in the epfilter.f90 source code and serach first for lines that say:

```
    CALL CreateNewObj('Fan:VariableVolume')
```

The fields are added in order that they appear in an IDF file so the second field to be added says:

```
    CALL AddToObjFld('Fan Efficiency', base + vsReturnEfficiencyOff,' ')
```

This needs to be changed to 'Fan Total Efficiency'. This will probably happen multiple times in the epfilter.f90 source file. Remember that the fields are in order so if you cannot figure out what field a field name corresponds to, figure out which number field it is and it should correspond with that count in the current IDD file. The expanded.idf file actually shows the error message right after the field that is a problem.  Another approach is to open the expanded.idf file in IDF Editor and make a little change and save it back out (use File..Save Options..Original with New at Bottom to not change the order) and compare the files and look for the Fan:VariableVolume object and see how it was chanaged.

When you make these changes, build ExpandObjects_build again, and run the ExpandObjects at the command line, the error message related to that field should no longer be shown.

You should try this with each HVACTemplate*.idf file to make sure you have made all the field name changes for each HVACTemplate objects.

After you are done with fixing these, please set checkOutputFieldNamesAgainstIDD to .false. again since it is a little slower when set to .true.

**Comment by mjwitte** [comment]
There is also a large set of test files with HVACTemplate variations that are not yet in github.  These could be added as an extended test set.  I can provide them directly for this work.
