### ISSUE TITLE
Questions about defaults supply temp and humidity ratio setpoints in HVACTemplate:System:DOAS (CR #8594)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3367]
## 
#### Description

From Don Shirey 06 Jul 2011

> Another question for you.
> 
> The default cooling coil design setpoint (cooling supply air setpoint temperature) is 12.8C.
> 
> The default dehumidification setpoint is 0.00924 kg/kg... which is equivalent to 12.8C dewpoint temperature (55F).
> 
> If the cooling coil has any type of bypass factor (>  0) and the target supply air temperature is 

12.8C, then the dewpoint temperature of the supply air will be less than 12.8C.  So, as long as the cooling coil has sufficient capacity, the discharge air dewpoint should always be less than the setpoint of 0.00924 kg/kg (12.8C).  When I run a simulation with these defaults, I don't see any overcooling... which I guess is expected.
Well, if the coil sizing works as expected, it will have an apparatus 
dewpoint lower than 55, so that the resulting mix of bypassed with 
cooled air results in saturated at 55 - not sure if that's possible.  
I'm easy on these - what would you choose?  For a humid climate chilled 
water system (which was my basis in this case for defaults), what would 
a typical coil design condition be?  As I read your comments, seems the 
default should be more like a 50F dewpoint perhaps?  The other problem 
is that the coil sizing is going to break if the target dry bulb supply 
is combined with the target dehum humrat as the coil sizing - doesn't 
make sense at that point.  Need another input for coil design dry bulb?

Mike

> When I reduce the dehumidification setpoint to say 0.008 kg/kg, I start seeing "overcooling" (as expected), and then reheat since the default Heating Coil Design Setpoint (heating supply air temperature) is 12.2C.
> 
> I guess I'm just wondering if you wanted the default dehumidification setpoint to be 12.8C, same as the cooling coil design temperature of 12.8C?  I guess it's really up to the user to select the necessary dehumidification setpoint --- you can't really guess a "correct" value .... so maybe you set the two values equal to avoid extra dehumidification initially and then the user will see that they need to carefully consider the appropriate dehumidification setpoint that is needed for their system design and modify the input value accordingly?
> 
> Thanks,
> 
> Don

Not sure I agree with your assessment.  When in 1st stage cooling with constant air flow rate but coil bypass, I have never seen a "blended" supply air temp (mixed plus bypass) down at 55F.  For a 50/50 coil split, under 1st stage you might get 53F off lower coil plus 75F (if no OA) bypass air.... which will blend to about 64F.  With both stages on, you get 55F (roughly).

MJW 16 Apr 2012
Don:

For this one, you are correct that the defaults of 12.8C fixed dry bulb
cooling setpoint and 12.8C dewpoint for RH control will results in
little or no overcooling, because meeting the 12.8C dry bulb setpoint
would almost always also meet the humidity setpoint.

What would likely change in this case, if dehumidification control is
set to yes, is that the dry bulb control would likely be higher than
12.8C, either because it's set to outdoor air reset, or on a schedule.

Do you have any further thoughts on this?  Is the default dry-bulb
setpoint higher than typical applications?  Or should the default
control type be changed to OA reset?  Or should this just stand as-is?
## 

External Ref: e-mail from Don Shirey
Last build tested: `11.10.12 V7.0.0.025`

**Comment by Myoldmopar** [comment]
@rraustad Is this worth changing?

**Comment by rraustad** [comment]
Is it worth changing? When latent sizing is added this should address itself. If we never get there, we might consider a lower default.

The question is can we live with complaints about lack of dehumidification capacity (which is easily resolved by entering a value instead of leaving a field blank) or should we consider a change in a default value to serve associated inputs (CoolReheat*). We can't serve all users with a default but the default should provide some impact, it sounds here as if it doesn't. Also keep in mind that a change in the default will not address all dehumidification needs and could lead to oversized, or still undersized cooling coils since we have no idea of latent loads at this point. 

I would suggest changing the default if there is no difference in coil sizing between None and CoolReheat. Otherwise it's a stab in the dark.

I would not be opposed to dropping this a degree or two (just so there is an impact between None and CoolReheat*). What value to use is unknown but 50F sounds reasonable. Mike has a point about sizing getting broken if we are not careful. There are already intermittent problems with the SHR autosizing calculation as it now stands.

What is the supply air humidity ratio when None or Multimode is chosen? I wonder if ensuring that SA T/w is on the saturation curve would fix the DX coil SHR autosize calculation where the RA/ADP line would nearly always cross the saturation curve but could still fail with cool and moist inlet condition? I'd have to check the calculations to see when this fails.

```
 HVACTemplate:System:DedicatedOutdoorAir,
  N6, \field Cooling Coil Design Setpoint
     \note  Used for sizing and as constant setpoint if no Cooling Coil Setpoint Schedule Name is specified.
     \default 12.8
     \units C
  A16, \field Dehumidification Control Type
     \key None
     \key CoolReheatHeatingCoil
     \key CoolReheatDesuperheater
     \key Multimode
     \default None
  N23, \field Dehumidification Setpoint
     \note The supply air humidity ratio for dehumidification control.
     \note Default of 0.00924 kgWater/kgDryAir is equivalent to 12.8C (55F) dewpoint.
     \note Ignored if Dehumidification Setpoint Schedule specified below
     \type real
     \minimum 0.0
     \maximum 1.0
     \default 0.00924
     \units kgWater/kgDryAir
```

**Comment by mjwitte** [comment]
@rraustad I think part of the problem/confusion is that the same value "Dehumidification Setpoint" is used for both sizing and control (if the Dehumidification Setpoint Schedule is left blank).  I'm OK with lowering the default to an equivalent 50F dewpoint.  And I would be open to changing it to be a variable default dependent on the None/CoolReheat setting.  Do you have an info on typical practice in humid climates for DOAS setpoints?
