### ISSUE TITLE
Update mean radiant temperature ( MRT ) section in Engineering Reference. (CR #8696)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3469]
## 
#### Description

MJW 22 Dec 2011
User asked . . .

---

We are getting very different PMV results from two different simulation programs and wish to judge which is modelling closest to the requirements of ISO7730 and then why the results are different. This alternate package cites CIBSE guide A (which in turn cites ISO7726) as its source for MRT calculation, so it would be helpful to know whether EnergyPlus cites the same document.
## The discussion on page 962 of the eng-ref seems to describe how the Mean radiant temperature is averaged, depending on which model the user selects, but I can't seem to find information on how the mean radiant temperature is arrived at to begin with (if that makes sense). Tr (mean radiant temperature) is an input to the formulae, not a result of the formulae.

Not sure what version of docs the users is looking at, in v7, this discussion starts on pdf p. 1033.  There are equations for Tr which is the resulting MRT used in the thermal comfort calcs, but I don't see an equation for Tr-avg which is the Zone averaged MRT.  Also, the existing equations and text seem to be a mix of real equations plus source code snippets using fortran variable names without any definitions.  
1.  So, this whole section could use a review and edit, 
2.  but most importantly add the equation for zone averaged MRT which is (from Rick's reply):

Here is the equation that is used for the "zone averaged" MRT in EnergyPlus.

MRT = Sum [(emissivity(i)_area(i)_temperature(i)] / Sum [(emissivity(i)*area(i)]

Sum[] is the summation over all surfaces (i=1 to the number of surfaces in a zone). So it is essentially the summation of the product of each surface emissivity times area times temperature divided by the summation of the product of each surface emissivity times area.
1.  Double-check the reference citations - Linda's comment:  "Note that ISO 7730 (I think it's a typo) is cited there in the references section. (I think it's a typo how it is cited)."
## 

External Ref: Ticket 5125
Last build tested: `11.12.19 V7.1.0.001`

**Comment by mjwitte** [comment]
Also note that the I/O Reference describes MRT in words

> Zone Mean Radiant Temperature [C]
> The Mean Radiant Temperature (MRT) in degrees Celsius of a space is a measure of the combined effects of temperatures of surfaces within that space. Specifically it is the surface area × emissivity weighted average of the zone inside surface temperatures (ref. Surface Inside Temperature), where emissivity is the Thermal Absorptance of the inside material layer of each surface.

And in the Engineering Ref section referenced above, the equations for the surface-weighted and angle factor MRTs do not include emissivity.  The source code should be checked to be sure.

**Comment by mjwitte** [comment]
Relevant functions are [HeatBalanceSurfaceManager::CalculateZoneMRT](https://github.com/NREL/EnergyPlus/blob/7e24f8abc0c396da442795ecae964d3981c5e2fd/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L4166-L4242), [ThermalComfort::CalcRadTemp](https://github.com/NREL/EnergyPlus/blob/4506b3995e2a0b2ec020310b9ab10285da81c25d/src/EnergyPlus/ThermalComfort.cc#L2140-L2162), and [ThermalComfort::CalcAngleFactorMRT](https://github.com/NREL/EnergyPlus/blob/4506b3995e2a0b2ec020310b9ab10285da81c25d/src/EnergyPlus/ThermalComfort.cc#L2010-L2021).
Looking at this code confirms that the surface-weighted and angle factor MRTs do _not_ include emissivity, and that the zone MRT calculation matched the equation in the first comment above.

**Comment by RKStrand** [comment]
@mjwitte It's on my hit list to take care of this in the near future (at least before the next release).  I have several other bugs (code and documentation) that I will be working on.  For some reason, it is not yet in PivotalTracker so I will add that as soon as possible and assign myself as the responsible party.  Thanks for reminding me about this documentation bug.  I will also look into whether or not this should be elevated to a code bug.  I don't remember the reason why there are different forms of the MRT equation and will have to see if I can track down the references which I might not have.

**Comment by RKStrand** [comment]
@mjwitte Ok, now I have looked at this a bit more and can comment on this.  I believe that based on the code and the documentation (which does show equations for all three) there they line up with each other.  I don't know about a typo in the ISO reference as I have not tracked down that yet.  So, I don't know if there is much of a defect there.  All three MRT calculations are possible ways to fine-tune the MRT part of the thermal comfort calculation.  The standard MRT and the "zone averaged" are the same thing so at most maybe this needs to be clarified.  The surface weighted MRT is a chance to allow someone to quickly place the person "near" a surface without having to come up with view factors.  It's an approximation not intended to be exact.  The view factor based calculation is a way to get a more exact location for the person.  As I see it, the flaw of the surface weighted is that the surface in focus has more than 50% impact because it affects the standard MRT.  In addition, neither the surface weighted nor the view factor based MRT incorporate the emissivity.  So, the question is whether this is appropriate or not.  The equations are there in the documentation and its clear that neither one uses emissivity.  So, if we are good with that, then I'm not sure if there is much here.  If we aren't good with that, then this would become a code bug that would require the emissivity to be included in both of these calculations.

**Comment by RKStrand** [comment]
@mjwitte Now that the 8.8 release is behind us, do you have any thoughts on the above post?  Do we need to convert this into a code and documentation change?  I'm looking for things to knock out in the short term and this is a good candidate.  Thanks!

**Comment by mjwitte** [comment]
@RKStrand Not sure if emissivity should be included in the SurfaceWeighted and AngleFactor methods.  My first inclination would be yes for AngleFactor because the view factors are geometry-based and they are independent of materials.  but the I/O Ref description for ComfortViewFactorAngles is clear that the "Angle Factor" inputs are the weighting that is used and they must add up to 1.0.  So, that would argue against adding emissivity to the weighting.  But referring to these as view factors or angle factors is misleading since it's technically more than that if the surfaces have different emissivities.  I'm talking in circles here.  Do we have another source to reference for a pattern to follow?

**Comment by RKStrand** [comment]
@mjwitte Ok, so I went back to the ASHRAE Handbook of Fundamentals, to see what the industry standard says on this.  The angle factor calculation is a simplification of a simplification.  First, the linear version of the equation is a simplification of the equation that is based on fourth order temperatures.  Basically, replace the linear temperature terms with temperature to the fourth.  However, that in itself is still a simplification because that equation assumes that all of the surfaces are black body surfaces since most building materials have emissivities close to unity.  So are we good with those simplifications or do they make us feel like simplifications are counter to what EnergyPlus tries to do--the best possible simulation?

If we are not satisfied with this, then I will need to develop something that takes emissivities into account.  In addition, if we are doing this, then I should also relook at the surface weighted option and fine-tune that as well.  That takes the average of a single surface temperature and the remaining MRT.  It does not include emissivities either and probably should.  It should also remove the single surface from the MRT since it is otherwise counting it in both terms which is not correct.

What do you think?  Should I leave it alone or tackle this?  I'm up for it and will work on it very soon if there is agreement that this should be done.

**Comment by mjwitte** [comment]
That's a tough call.  As long as the documentation is clear as to what the angle factors mean, I don't think it matters much if the factors include the emissivity effect or if that's added from the materials.  From a purist perspective, if we want this to be responsive to a material change, then we should modify the function to add the material emissivity to the angle factor. But I'm ok with that one as-is.

The surface weighted option, again, could be left as-is with clear documentation.  But there's a stronger argument for at least changing that to average the surface temp with a zone  MRT that removes the single surface so it's not overweighted.  If you change the other method to use emissivities, then this one should be changed also.

At this point, I lean to the middle: leave the emissivities out and just correct the MRT for the surface weighted option.

**Comment by RKStrand** [comment]
@mjwitte Proceeding with the changes to both the surface weighted option and the angle factor option.  If we really want the best calculation procedures in EnergyPlus and we know this isn't fully correct, then we should fix it.  Working on this now and will also update docs to reflect these changes.

**Comment by Myoldmopar** [comment]
Closed via #6407
