### ISSUE TITLE
Interior movable insulation not working in user's file. (CR #8778)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3551]
###### Added on 2012-03-14 11:31 by @lklawrie
--
#### Description
Note that movable insulation is listed under our "advanced surface concepts" and we warn in the description that interior movable insulation hasn't been tested.

input file: 8778-

MJW 21 Mar 2012
Was unassiigned - RKS?

--
External Ref: ticket 5599
Last build tested: `12.02.28 V7.1.0.004`

**Comment by RKStrand** [comment]
@mjwitte Ok, so I ran this with the latest code having updated the input file to V8.4.  What I am seeing is the file runs but it does produce a severe error.  Basically, the user is trying to use movable insulation on a surface that has a radiant system.  That option is not allowed and throws a severe error in the current code.  I'm not sure what the original "doesn't work" symptom was, but it's clear from the error file that a warning is being produced and rightfully so.  Maybe at some point if there is some interest we can add the ability to have movable insulation and a radiant system but I'm not sure why someone would even want interior movable insulation on a radiant system.

However, I think the fact that a severe error is generated but the program continues to run is an error.  It should print the severe error and then it should fatal out.  Right now, it just produces the error and keeps going assuming that the movable insulation is there.  So, the results are bogus.

Here is what I propose: fix the severe error to be produced all the time, add an additional continuation message that gives a bit more detail about why this is a problem, and then add a fatal error so that the user has to fix this.  All fixed as a low complexity bug.  What do you think?

**Comment by mjwitte** [comment]
@RKStrand I just ran the original defect file with v7.1 and it fatals out

```
   ** Severe  ** GetCondFDInput: MaterialProperty:PhaseChange="PCM BOARD FB35", non increasing Temperatures. Temperatures must be strictly increasing.
   **   ~~~   ** ...occurs first at item=[5], value=[0.00].
   ** Severe  ** GetCondFDInput: MaterialProperty:PhaseChange="PCM BOARD FB35", non increasing Enthalpy.
   **   ~~~   ** ...occurs first at item=[5], value=[0.00].
   **   ~~~   ** ...These values may be Cp (Specific Heat) rather than Enthalpy.  Please correct.
   **  Fatal  ** GetCondFDInput: Errors found getting ConductionFiniteDifference properties. Program terminates.
```

Given what you found, you can either just close this and move on, or do as you suggest above and change the current error to be fatal.

**Comment by RKStrand** [comment]
@mjwitte Oh yeah, I forgot that I had to fix the input file to get passed that error.  It was extra junk that the user didn't need in the input file.  Basically, I deleted a couple of lines in the input file that weren't needed (four lines with zero values for parameters) and the file then ran.

I think I am going to go ahead with the plan and implement my proposed fix above.  It really should not allow the calculations to continue.

**Comment by RKStrand** [comment]
Also implementing the new error messages in the combination of exterior movable insulation and embedded source/sink so that it produces a very similar error message sequence as interior movable insulation with embedded source/sink surfaces.  Exterior combo was already a fatal so now both are identical in what they say and do.  Making it possible to have movable insulation with a radiant system is a potential development idea, but I do not see this as something that anyone is wanting to do right now.

**Comment by EnergyArchmage** [comment]
fixed by https://github.com/NREL/EnergyPlus/pull/5731

**Comment by RKStrand** [comment]
@EnergyArchmage Thanks for reviewing this, Brent!
