### ISSUE TITLE
scan further for version & allow user to override beginning version (CR #8836)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3609]
###### Added on 2012-04-25 06:55 by @lklawrie
--
#### Description
Two separate issues and may not work for lists of files.

1) Scan further for version object -- e.g. reference buildings were too far in to be automatically in a list converted from V7

2) if there is no version, allow the user to pick the "start version".

--
External Ref: transitioning v7 files and others
Last build tested: `12.04.17 V7.1.0.008`

**Comment by Myoldmopar** [comment]
@JasonGlazer I added the 8.4 milestone here, but if you feel this is not relevant anymore or too much for this release, please remove it.

**Comment by JasonGlazer** [comment]
@Myoldmopar It would be a good one to finish up. @mjwitte

**Comment by JasonGlazer** [comment]
@Myoldmopar and @mjwitte I was thinking about working on this issue but part (2)  "if there is no version, allow the user to pick the start version." is probably more than a quick bug fix since it requires actually changing the type of the GUI controls. I am not sure about messing with it just prior to a release. The first part (1) "Scan further..." I can do for the 8.4 release without a problem if that is wanted.

If I only addressed (1) and not (2) would that still be important enough to be marked as part of the 8.4.0 milestone?

If so, I will split the two into two separate issues and get (1) done. If not, I will just leave the entire thing for the next release and I will try to address it earlier in the cycle.

**Comment by mjwitte** [comment]
@JasonGlazer I'd say just scan the whole file and skip the dialog.

**Comment by JasonGlazer** [comment]
@mjwitte So you are suggesting that I do (1) and not worry about (2) at all?

**Comment by mjwitte** [comment]
Correct.

**Comment by JasonGlazer** [comment]
@mjwitte It looks like the current version of IDFVersionUpdater already scans the entire file no matter how large it is, so (1) is already done. I tested it by moving the VERSION object to the end of the HospitalLowEnergy.idf and it found it just fine.  

I guess I will just close this issue since (1) is already in the code and (2) was no longer wanted.

**Comment by mjwitte** [comment]
@JasonGlazer Oh, I was thinking EP-Launch.  Doesn't IDFVersionUpdater already let you choose the starting version?  Or is it just the ending version?  I can see where the option to choose a version for an entire list might be useful, but this can stay closed and see if anyone asks for it again.

**Comment by JasonGlazer** [comment]
IDFVersionUpdater searches for the starting version and presents a list of possible ending versions (with the default being the most recent). 

By the way, EP-Launch does just scan the first 500 lines. I could change that very easily should I post a new issue about changing that?

**Comment by mjwitte** [comment]
Yes, it would be nice for EP-Launch to scan the entire file.

**Comment by JasonGlazer** [comment]
I just created #5193 to address the EP-Launch version scanning limit.
