### ISSUE TITLE
Thermal comfort relative humidity calcs not using correct dry bulb temperature with room air models (CR #9236)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4007]
###### Added on 2013-06-04 16:13 by @mjwitte
--
#### Description
Brent:  Assigning to you, but feel free to reassign.  Mike

MJW 04 June 2013
User reporting Fanger PMV in a simulation with displacement ventilation, getting unreasonable PMV results.  User deduced (with some effort) that the relative humidity for the comfort calcs is using the mean air temperature instead of the air model comfort temperature.  After looking at the code briefly, it appears that the user is correct.

Search ThermalComfort.f90 for occurences of RelHum:
587:            RelHum = PsyRhFnTdbWPb(MAT(ZoneNum),ZoneAirHumRat(ZoneNum),OutBaroPress)
589:            RelHum = PsyRhFnTdbWPb(ZTAVComf(ZoneNum),ZoneAirHumRatAvgComf(ZoneNum), OutBaroPress)
849:    RelHum  = PsyRhFnTdbWPb(ZTAV(ZoneNum),ZoneAirHumRat(ZoneNum),OutBaroPress)
1259:     RelHum  = PsyRhFnTdbWPb(ZTAV(ZoneNum),ZoneAirHumRat(ZoneNum),OutBaroPress)

Mix of MAT, ZTAV, and ZTAVComf.  Prior to these are IF blocks that set AirTemp which appears to be used in the comfort calcs, so maybe the fix is as simple as using AirTemp in all of the RelHum calcs?  But not clear.

Also, some are using ZoneAirHumRat.  Should these all be ZoneAirHumRatAvgComf?

And should we add a new output variable for the RH used in comfort calcs?

Inputs: 9236-*
Weather: None, design days only

Verification info:  Not completely sure how to verify this from output.  For times when theRoom Air Zone Thermal Comfort Effective Air Temperature is < than the Zone Mean Air Temperature, I would expect the fixed version to calculate a higher comfort RH, and so the PMV should be higher.  Opposite if Comfort Temp is > MAT.

These test files only test the displacement vent room air model with Fanger PMV.  A thorough test should check other comfort models with other room air models.  Also, these same files using the Mixed room air model (default) should give same comfort results before and after fix?

--
External Ref: Ticket 8097
Last build tested: `13.04.30 V8.0.0.008 - rerelease`

**Comment by JasonGlazer** [comment]
Update to confirm if lines of code still show same variation in C++ codebase:

682:    RelHum = PsyRhFnTdbWPb( MAT( ZoneNum ), ZoneAirHumRat( ZoneNum ), OutBaroPress );
684: RelHum = PsyRhFnTdbWPb( ZTAVComf( ZoneNum ), ZoneAirHumRatAvgComf( ZoneNum ), OutBaroPress );
967: RelHum = PsyRhFnTdbWPb( ZTAV( ZoneNum ), ZoneAirHumRat( ZoneNum ), OutBaroPress );
1399: RelHum = PsyRhFnTdbWPb( ZTAV( ZoneNum ), ZoneAirHumRat( ZoneNum ), OutBaroPress );

Looks like this issue has not been addressed.

**Comment by JasonGlazer** [comment]
Using ZoneAirHumRatAvgComf across all instances of the RelHum equation looks reasonable and was changed. Prior to each of these, a variable called AirTemp is set that appears to be more aligned with the intent and is used in other equations later related to the air temperature in the zone. Given that AirTemp was used in each instance except for the first because in that case MAT() was not part of the process of setting AirTemp so it was left alone.

**Comment by RKStrand** [comment]
@JasonGlazer Based on what you wrote and what I am seeing in the code, I think your proposed fixes sound reasonable and would be what I would have done.  Based on my recollection of the origins of this module, variables like AirTemp were used locally so that things like MAT or ZTAV or whatever did not proliferate through the code and to make the algorithm more clear.  Some stuff has been added since the original versions in F90, but I'm not sure where this discrepancy crept into the code.  In any case, I agree with what you are proposing.

**Comment by JasonGlazer** [comment]
Thanks @RKStrand

**Comment by Myoldmopar** [comment]
Closed via #5440
