### ISSUE TITLE
A new  EMS actuator was added for pump pressure. (CR #9353)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4124]
###### Added on 2013-10-24 14:52 by Brent Griffith
--
#### Description
User requests EMS actuator on pump head. 

[BG 10-4-2013]  checked in source code.  Uses same model as for plant pressure rise.    Pointing to Edwin for verification.  I wonder if the formulation used for plant presssure-based simulation is correct, but used the same approach for this EMS override.  It seem this is throwing away part load performance information included in the pump input. 

Specifically I wonder if the value for TotalEffic can be adjusted for part load coefficietns (for variable speed).

--
External Ref: ticket 7272
Addressed in `13.11.20 V8.1.0.009 - rerelease` by Brent Griffith
Last build tested: `13.10.18 V8.1.0.008`

**Comment by Myoldmopar** [comment]
I see where this was added [here](https://github.com/NREL/EnergyPlusArchive/commit/d2bbe0ee38642f482bda35a289aac088991561a1).  

For the pressure based modeling, I think it is OK. In the power-correction pressure simulation, the efficiency is still used to translate required pump (fluid) power into required pump input.  In the curve based pressure simulation, I believe the curve inputs themselves are created with the efficiency already built-in, so that it is represented properly.
