### ISSUE TITLE
Rainfall is handled differently between weather file values and Site:Precipitation water manager values. (CR #9382)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4153]
## 
#### Description

From LKL 2013.11.13 Email:

So, the rainfall (either by inclusion on the weather file directlly or with the precip flags) on the weather file is set when the "get current weather" is called (which is before the zone time step).

All it really does, I believe, is set the "is raining" flag which in turn takes the convection coefficient for the surfaces to 1000 or something like that.

The Site:Precipitation - rainfall rate/amount is used in the water manager -- at the system timestep.

If you wanted to have the Site:Precipitation amount/rate set the israining flag, you would have to reconcile the zone vs system timestep thing.  And, of course, be able to influence the surface heat balance calculation.

2013.11.13 ESL:

Creating this suggestion CR to keep track of this for later improvements.
## 

Last build tested: `13.10.18 V8.1.0.008`

**Comment by mjwitte** [comment]
As of [this commit](https://github.com/NREL/EnergyPlusArchive/commit/15bb22b4d121c4a8c185243334b253bdbc8b6770) in April 2012, the liquid precipitation amounts in the epw file are not use for anything. Closing this, see #4714 for more details.

**Comment by mjwitte** [comment]
This was not addressed yet. Reopening.

**Comment by mjwitte** [comment]
@yujiex When merging #9177 I noticed the link to this issue. Apparently, I closed this years ago and pointed to #4714 without reading this carefully. There's one piece of this rainfall puzzle that is still missing. Site:Precipitation sets the current rainfall rate and depth (overriding any epw precipitation data), but it's not setting `state.dataEnvrn->IsRain`. That's the point of this issue.

Adding Ouput:Variable, Environment:Site Rain Status to 5ZoneWaterSystems shows that this is the same with or without Site:Precipitation. Since we've moved Site:Precipitation into WeatherManager, it should be straightforward to address this. Questions would be:
1. Should `TodayIsRain` be set to true when Site:Precipitation is > 0.0, or > some threshold value, like 1.5mm? I see a comment in Weather manager that apparently was active code at one time, but then removed: .or. LiquidPrecipitation >= .8d0)  ! > .8 mm  I don't know if there's some rule in the weather data world for this.
2. Should the RunPeriod "Use Weather File Rain Indicators" control this? We could change the field name to "Use Rain Indicators"?
3. Looking at WeatherManager, where `LiquidPrecipitation` is set to 1.5mm `if ((state.dataEnvrn->LiquidPrecipitation == 0) && (state.dataEnvrn->IsRain))`. This should be checking `state.dataWeatherManager->TodayIsRain` because `IsRain` isn't set for the current timestep until after the call to `UpdatePrecipitation`.
4. Also the accumulation of Precip from Weather File happens before this correction.
5. And this check should honor `state.dataWeatherManager->UseRainValues` and skip the 1.5mm if it's false.
6. And because this code executes every timestep, if the goal is 1.5mm for the hour, this should be set to 1.5/NumberOfTimestepsPerHour?

And you thought you were done with all of this. Sorry.
And according to USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw, apparently it only rains in April in Chicagoland?!

**Comment by yujiex** [comment]
@mjwitte Sorry, I missed addressing this. I'll work on fixing it now.

**Comment by yujiex** [comment]
Hi @mjwitte Currently it seems TodayIsRain gets value from TomorrowIsRain
`state.dataWeatherManager->TodayIsRain = state.dataWeatherManager->TomorrowIsRain`
Then TomorrowIsRain is updated like this in WeatherManager
```
                    state.dataWeatherManager->TomorrowIsRain(CurTimeStep, hour) = false;
                    if (PresWeathObs == 0) {
                        if (PresWeathConds(1) < 9 || PresWeathConds(2) < 9 || PresWeathConds(3) < 9)
                            state.dataWeatherManager->TomorrowIsRain(CurTimeStep, hour) = true;
                    } else {
                        state.dataWeatherManager->TomorrowIsRain(CurTimeStep, hour) = false;
                    }
```

Where PresWeathConds corresponds to the "Present Weather Codes" epw field according to the EnergyPlus Auxiliary Programs documentation.

Table 2.16 has the meaning of the codes
PresWeathConds(1) is the occurrence of Thunderstorm, Tornado, or Squall
PresWeathConds(2) is the occurrence of Rain
PresWeathConds(3) is the occurrence of Rain Squalls,Drizzle, or Freezing Drizzle

Do you think we should add a check on the precipitation depth (LiquidPrecip here) as well? But wouldn't the precipitation depth show up anyways in the calculation later on? Any thoughts?

**Comment by mjwitte** [comment]
No. I don't think we want to touch any of that. I would focus on the rain logic in `SetCurrentWeather` and possibly in `UpdatePrecipitation`.

**Comment by yujiex** [comment]
Got you. I'll focus on these instead.

**Comment by amirroth** [comment]
This is like an Escape Room.
