### ISSUE TITLE
Determine guidance on optional arguments

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4250]
@DeadParrot @mjwitte @rraustad @lefticus @kbenne 

A recent commit revealed there was some confusion about how to properly handle optional args.  I guess there are 3 stages in this:
0) The Optional class introduced during the automated translation
1) The current best-practice which we should be doing in new code, and ?perhaps trying to migrate current code to as we go on?
2) The eventual OO strategy

I looked in the wiki and didn't see guidance right away, so I just wanted a gathering of the minds here to specify what we should be doing at this, 1) stage.  Once we decide, I can update the wiki accordingly.

**Comment by DeadParrot** [comment]
@Myoldmopar we took a first look at this issue in SF. My perspective:
- The use of ObjexxFCL::Optional should decrease over time both to be more C++ native and avoid the small performance hit.
  - The large number of optional arguments in some EnergyPlus interfaces are a Fortran-ism that should get better as a side effect of OO migration so it may be most efficient to leave them alone until a module is refactored to OO rather than doing the large job of replacing them now.
- Continuing to use Optional where it is already in use is not terrible for now but is best avoided in new interfaces/modules.
- Migration options:
  - If the function can operate correctly with a default value for the argument then C++ default argument usage is preferred. The default would have to be either an OK value to use or an out of normal domain "sentinel" value that means "nothing passed". C++ default arguments can be intermixed with Optional arguments at the end of an argument list so a function does not have to be fully migrated all at once and new arguments can be added with C++ style.
    - Default argument values should avoid expensive construction such as `std::string const & s = ""`
  - If there are only 1 or 2 arguments that may or may not be present overloaded functions should be considered instead of default arguments.
- There are circumstances where Optional or the similar boost::optional can be useful but there are usually cleaner, OO ways to handle this.

I am happy to look at specific situations and make suggestions. Unfortunately, there isn't one best canonical migration for all situations.

**Comment by Myoldmopar** [comment]
OK, sounds like there isn't really any action items here.  @DeadParrot provided the above information that is valuable.  I think things will stay as-is, then for new development and when larger restructuring gets underway, optionals will be highly frowned upon.  Closing this.

**Comment by DeadParrot** [comment]
@Myoldmopar A gradual migration away from Optional seems logical: they are not a huge source of bugs or slowness. I removed a set of Optionals that did have a mild performance hit in the recent RegulaFalsi/Residual revamp.

Should I copy the migration advice to the Development Tips wiki page?

**Comment by Myoldmopar** [comment]
That would be great @DeadParrot.  Thanks!

**Comment by DeadParrot** [comment]
@Myoldmopar Done.
