### ISSUE TITLE
Surface Inside Temperature not clear with Movable Insulation - possible error in calculation

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4432]
Helpdesk Ticket 7095

Code appears to be reporting the base surface inside temp. Checking with Brent and Rick to confirm.
 Michael J. Witte on 22 February 2013 03:40 AM

User was never answered - been six months - needs a CR. Reference e-mail from RKS to MJW on FEb 25, 2013
 Michael J. Witte on 20 August 2013 05:45 PM

Is this addressed in Rick's fix for interior movable insulation?
 Linda Lawrie on 16 October 2013 07:52 PM

From RKS on 25 Feb 2013 - Yeah, well, it's "temporary" but then movable insulation uses it to differentiate between base and movable insulation surface temperature. My guess is that only a handful of people know this (a majority on this email). So, Mike, I think your interpretation is correct and the report probably needs correcting for the limited cases when these two temperatures are not identical. Or course, this is going from memory, but what Mike writes sounds like a reasonable explanation. Sorry that it takes a while to get a response from me at the moment. (reference e-mail thread for more details when posting new issue)
 Michael J. Witte on 07 May 2014 04:29 PM (Edited by Michael J. Witte on 07 May 2014 04:29 PM)

Helia Taheri
User
Posted on: 15 February 2013 09:09 AM
Hi again Dear Linda,

 I have another question:
 When I have an inside movable insulation and I calculate the Surface Inside Temperature, the software will give me the temperature of the main surface or the temperature of the inside movable insulation? 

 Thanks
 Helia

**Comment by RKStrand** [comment]
@mjwitte (A few years later...) So, after looking at another movable insulation issue, I came across this one and thought I'd look at it further.  The code is convoluted to be sure and explaining this can also be confusing.

I'll try to simplify things with a diagram for interior movable insulation:

zone side | movable insulation | remaining construction | other side (exterior, etc.)
................|................................|.......................................|........................................
................|................................|.......................................|........................................
................|................................|.......................................|........................................
.............. MI ......................... SurfI ............................... SurfO

So, MI is the side of the interior movable insulation facing the zone, SurfI is the side of the interior movable insulation facing the remaining construction layers, and SurfO is the exterior side of the entire thing facing whatever is on the other side.

Inside the code, the temperature at MI is calculated in variable TempSurfInTemp and the temperature at SurfI is calculated in TempSurfIn.  I believe that is correct based on the equations for TempSurfIn and TempSurfInTemp and also because TempSurfIn is used in updating the thermal histories which would have to be done at SurfI using the temperature at that point.

As far as what is reported, it's the temperature at SurfI.  It gets reported as the inside face surface temperature.  That agrees with your comment on 2/22/13.

And as far as I can tell, there is no reporting of the temperature at MI.  The information is available and the code could be updated to produce this information.  Would this be useful to add?

Perhaps a bigger issue is that I am not seeing documentation on the inside movable insulation.  That's a bit odd.  It seems like all of the stuff in the Engineering Reference talks about outside movable insulation.  This omission needs to be fixed.

What are your thoughts on adding the variables and the relevant documentation for inside movable insulation?
