### ISSUE TITLE
Linux installer issues

### ISSUE THREAD

**Issue by sclegg** [NREL/EnergyPlus#4573]
The following problems occur with installation for Debian Wheezy.

There are a number issues regarding the linux installer.

+ dos2unix is no longer provided by the package so this leads to a broken link which were formed in the package maker files ./cmake/darwinpostflight.sh.in and ./cmake/CPack.STGZ_Header.sh.in.

+ The forming of the symbolic links to the programs and the directory permissions performed by /cmake/darwinpostflight.sh.in is done (in ./cmake/Install.cmake) only for Apple, this should also be for packages built with linux as well.

+ Most of the install files are not created. They are created by moving `include(cmake/Install.cmake)`  outside the BUILD_PACKAGE condition in ./CMakeLists.txt.

+ From what I understand (from cmake/CPack.STGZ_Header.sh.in), the preferred installation directory structure is: 
            /usr/local/EnergyPlus-8-2-2/
with the program files symbolically linked from
            /usr/local/bin
Currently, the default install from cmake is /usr/local/ without a package directory. I feel this should be automated to either add the defaulted package directory as a cmake option, or, install in the package subdirectory. 
The created links and permission changes in darwinpostflight.sh.in are only applied in the package making process. A similar process may be included in the install.

**Comment by kbenne** [comment]
"Currently, the default install from cmake is /usr/local/ without a package directory. I feel this should be automated to either add the defaulted package directory as a cmake option, or, install in the package subdirectory. "  - We are not supporting the install target right now except in support build package.  Although this comment does shed light on the next one.

"Most of the install files are not created. They are created by moving include(cmake/Install.cmake) outside the BUILD_PACKAGE condition in ./CMakeLists.txt."   - This is by design turn on BUILD_PACKAGE.
