### ISSUE TITLE
WindowMaterial:Glazing with Front Side Solar Reflectance=Zero is Opaque

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4580]
Helpdesk Ticket 10008
From user:
The Front and Back Side Solar Reflectance at Normal Incidence field of the WindowMaterial:Glazing allows the 0 value. But, When I use it, I have no solar energy crossing the windows. If I used the value 0.001, results are correct. Is it a bug, or the idd file needs to be update to prohibit the 0 Value.

**Comment by JasonGlazer** [comment]
The bug was original posted for EnergyPlus 8.2.0. This was reproduced using EnergyPlus 8.4.0 and the same issue still exists.

**Comment by JasonGlazer** [comment]
@hongtz68 I think this issue may be related to code you added in 2010 and I would like your advice on how to fix it. The issue is that when both Front Side Solar Reflectance at Normal Incidence and Back Side Solar Reflectance at Normal Incidence of WindowMaterial:Glazing are set to zero the output variables:
- Surface Window Total Glazing Layers Absorbed Solar Radiation Rate
- Surface Window Total Glazing Layers Absorbed Shortwave Radiation Rate
- Surface Window Total Absorbed Shortwave Radiation Rate Layer 1
- Surface Window Transmitted Solar Radiation Rate 
- Surface Window Transmitted Beam Solar Radiation Rate 
- Surface Window Transmitted Beam To Beam Solar Radiation Rate 
- Surface Window Transmitted Beam To Diffuse Solar Radiation Rate
- Surface Window Transmitted Diffuse Solar Radiation Rate
- Surface Window Heat Gain Rate 
- Surface Window Heat Loss Rate

Always show zero. This seems to be due to Construct().TransDiff being zero and the code that accumulates these variables either does not get exercised or is multiplied by Construct().TransDiff

First question: Should these output variables be zero?

Second question: Should Construct().TransDiff be zero when Front and Back Side Solar Reflectance at Normal Incidence is zero?

Third question: Any advice on how to fix this?

**Comment by vidanovic** [comment]
@JasonGlazer Do you know if user had spectral data or just single value assigned to WindowMaterial:Glazing?

**Comment by JasonGlazer** [comment]
Single value, here is the WindowMaterial:Glazing

```
  WindowMaterial:Glazing,
    10000,                   !- Name
    SpectralAverage,         !- Optical Data Type
    ,                        !- Window Glass Spectral Data Set Name
    .003,                    !- Thickness {m}
    .999,                    !- Solar Transmittance at Normal Incidence
    0,                       !- Front Side Solar Reflectance at Normal Incidence
    0,                       !- Back Side Solar Reflectance at Normal Incidence
    .898,                    !- Visible Transmittance at Normal Incidence
    .081,                    !- Front Side Visible Reflectance at Normal Incidence
    .081,                    !- Back Side Visible Reflectance at Normal Incidence
    0,                       !- Infrared Transmittance at Normal Incidence
    .84,                     !- Front Side Infrared Hemispherical Emissivity
    .84,                     !- Back Side Infrared Hemispherical Emissivity
    .9,                      !- Conductivity {W/m-K}
    1;                       !- Dirt Correction Factor for Solar and Visible Transmittance
```

The entire input file is at:

https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/4000s/4580

**Comment by JasonGlazer** [comment]
@vidanovic I am planning on working on this some more today. Would it be possible to at least answer the first two questions?

**Comment by vidanovic** [comment]
Sure. Some of these variables are used only by BSDF type of window. At least that was the case when I developed BSDF. For example, "Surface Window Total Absorbed Shortwave Radiation Rate Layer 1" should produce zero in this case. However, keep in mind that this is not zero. Transmitted solar radiation rate should definitely not be zero since value is set to 1.
You can try to debug this by going into SolarShading.cc on this line:

WinTransBmSolar( SurfNum ) = ( TBmBm + TBmDif ) \* SunLitFract \* CosInc \* Surface( SurfNum ).Area \* InOutProjSLFracMult;

TBmBm should have value different from zero. Make sure that SunLitFract is equal to 1. If I recall correctly, that variable is used to calculate fraction of the area that window is hit by the Sun. So if you do not have exterior blocking surfaces, this fraction should be equal to 1.

Lastly, I suspect on this routine:

TBmBm = POLYF( 1.0, Construct( ConstrNumBare ).TransSolBeamCoef( {1,6} ) );

I suspect that TBmBm have some meaningful value when T=0.999 and as soon as you set T=1, it will produce incorrect results.

NOTE: Make sure that you are operating with correct type of window since there are some big IF branches for different type of windows :)

Let me know how this worked. I will try to catch some time today to debug this and try to see where is the problem.

**Comment by JasonGlazer** [comment]
Thanks Simon. I am really not very familiar with the window solar calcs so any guidance you could provide would be appreciated.

**Comment by vidanovic** [comment]
No problem. BTW, I have just confirmed that problem is in this line:

TBmBm = POLYF( CosInc, Construct( ConstrNum ).TransSolBeamCoef( {1,6} ) );

(SolarShading.cc around 5600th line). Im looking now into that interpolation and why is it producing such a different results for close values. Will let you know...

**Comment by vidanovic** [comment]
@JasonGlazer 
I have found the problem. It is in WindowManager routine named TransAndReflAtPhi.

Scroll down to following lines of code:

tmp7 = -abf;
if ( tmp7 != 0.0 ) {
  expmabfdivcgf = std::exp( tmp7 / cgf );
} else {
  expmabfdivcgf = 0.0;
}
  tmp8 = -2.0 \* abf;
if ( tmp8 != 0.0 ) {
  expm2abfdivcgf = std::exp( tmp8 / cgf );
} else {
  expm2abfdivcgf = 0.0;
}

problem here is that if branch is examining tmp7 and tmp8 while it should take care that cgf is not zero.  If tmp7 and tmp8 are zero, then expmabfdivcgf MUST be equal to 1.

So, correction should look like:

tmp7 = -abf;
if ( cdf != 0.0 ) {
  expmabfdivcgf = std::exp( tmp7 / cgf );
} else {
  expmabfdivcgf = 0.0;
}
  tmp8 = -2.0 \* abf;
if ( cgf != 0.0 ) {
  expm2abfdivcgf = std::exp( tmp8 / cgf );
} else {
  expm2abfdivcgf = 0.0;
}

Do you have time to post this fix and run tests? I would expect different results for all the cases when reflectance is equal to zero.  Hopefully, there were not many cases like this.

**Comment by JasonGlazer** [comment]
Thank you very much for tracking down the problem and coming up with a solution. I do have time to post the fix and look through the test results. Hopefully we won't find anything unexpected.

**Comment by JasonGlazer** [comment]
@vidanovic  in that same area of code, there are a bunch of 

if (x != 0) {}

statements that look like they are trying to protect for divide by zero situations except that the variables referenced in the if statement are not the ones used the denominators. Given that seems to be the gist of the the fix you suggested, have you looked at the others and made sure they are ok?

**Comment by vidanovic** [comment]
No, I did not. For now, I would not change those since it can produce unexpected results.

**Comment by JasonGlazer** [comment]
This looks like it solves most of the problems. I just did some testing of the original bug file and I think this addresses 
- Surface Window Transmitted Solar Radiation Rate [W](Hourly)  
- Surface Window Transmitted Beam Solar Radiation Rate [W](Hourly)  
- Surface Window Transmitted Beam To Beam Solar Radiation Rate [W](Hourly)  
- Surface Window Transmitted Beam To Diffuse Solar Radiation Rate [W](Hourly)  
- Surface Window Transmitted Diffuse Solar Radiation Rate [W](Hourly)  
- Surface Window Heat Gain Rate [W](Hourly)

But now the values of do not seem to be quite correct:
- Surface Window Total Glazing Layers Absorbed Solar Radiation Rate [W](Hourly) 
- Surface Window Total Glazing Layers Absorbed Shortwave Radiation Rate [W](Hourly) 
- Surface Window Total Absorbed Shortwave Radiation Rate Layer 1 [W](Hourly)

They are not zero but very close (usually on the order of 1e-12). The test file without the bug shows these values range from 0.2 to 8.5.

**Comment by JasonGlazer** [comment]
@vidanovic I just committed the code change you suggested in #5312

**Comment by vidanovic** [comment]
That does seem like some floating error. Let me take a look.

**Comment by vidanovic** [comment]
I would leave it like that for now. Need to sit down and take a look at equations. What it is not clear to me is why all those equations are missing glass thickness. They should have glass thickness involved. Equation that calculates absorbtance is one of those that should have the thickness.
However, all those equations are old and we do have new model in OPTICS that Im working on to extract into library so it can be used by EnergyPlus as well.

**Comment by JasonGlazer** [comment]
@vidanovic I still can't figure out the Absorbed Radiation Rate part of this bug. I spent some time today trying to trace back through all the equations but (as you know) there are a lot of them and a lot that use cryptic three letter variable names. Any suggestions would be appreciated.

**Comment by JasonGlazer** [comment]
@vidanovic @hongtz68 I looked at this issue again and have not been able to make any progress with the problem with the remaining variable. Any chance of either of you looking at it soon?

**Comment by JasonGlazer** [comment]
@vidanovic @hongtz68 I know it has been a while since you looked at this. Any chance now that the holidays are over that one of you could take a look at the issue and provide some advice?

**Comment by mjwitte** [comment]
Close via #5312
