### ISSUE TITLE
another SolarShading 'contains( i )' assertion violation

### ISSUE THREAD

**Issue by Geof23** [NREL/EnergyPlus#4676]
Getting an assertion violation in a few models (re: https://github.com/NREL/EnergyPlus/commit/7489c48b34d78c895fad1b3569b50893f3f400de)

EnergyPlus: /home/gsawaya/dev/ep_git/EnergyPlusTeam/third_party/ObjexxFCL/src/ObjexxFCL/FArray1.hh:1133: T& ObjexxFCL::FArray1< <template-parameter\
-1-1> >::operator()(int) [with T = bool]: Assertion `contains( i )' failed.

Here's a stack trace:

>in raise of /lib/x86_64-linux-gnu/libc.so.6
1 in abort of /lib/x86_64-linux-gnu/libc.so.6
2 in ?? of /lib/x86_64-linux-gnu/libc.so.6
3 in __assert_fail of /lib/x86_64-linux-gnu/libc.so.6
4 in ObjexxFCL::FArray1<bool>::operator() of /home/gsawaya/dev/ep_git/EnergyPlusTeam/third_party/ObjexxFCL/src/ObjexxFCL/FArray1.hh:1133
5 in EnergyPlus::SolarShading::ReportSurfaceErrors of /home/gsawaya/dev/ep_git/EnergyPlusTeam/src/EnergyPlus/SolarShading.cc:9399
6 in EnergyPlus::EndEnergyPlus of /home/gsawaya/dev/ep_git/EnergyPlusTeam/src/EnergyPlus/UtilityRoutines.cc:416
7 in EnergyPlusPgm of /home/gsawaya/dev/ep_git/EnergyPlusTeam/src/EnergyPlus/EnergyPlusPgm.cc:437
8 in main of /home/gsawaya/dev/ep_git/EnergyPlusTeam/src/EnergyPlus/main.cc:6

It occurs accessing TrackTooManyFigures

**Comment by DeadParrot** [comment]
@Geof23 OK, this looks like my goof in a big batch of performance tuning from Oct. I left in a line incrementing NumTooManyFigures that should have been removed:
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L3146

If I don't hear otherwise I'll push the fix to a PR today and it should get into develop soon-ish.
