### ISSUE TITLE
Ice storage example file performance curve lower limit

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4710]
A user has indicated that the example files for ice storage include chiller performance curves that don't go down low enough on the lower limit.  This should be:
- [ ] verified,
- [ ] understood as to why it is so,
- [ ] researched to determine if the limits are OK to go lower without changing the curve coefficients, and
- [ ] updated if needed to a better curve fit

I'll get things started by verifying this, but am happy to hear any thoughts from @EnergyArchmage or others on this as it moves forward.

**Comment by mjwitte** [comment]
@Myoldmopar Max/Min limits on curve inputs are dangerous.  Yes, they protect against exercising a curve in flaky territory, but they silently clip conditions and allow equipment to falsely operate at the clipped condition when, for example, condenser water temps may be sky high.  From my perspective, they shouldn't be used at all.  Limits on output are far better to protect against a wild curve.  That said, we should add a warning system in the curve manager to accumulate recurring warnings for every time that a limit is exceeded.  It can be relegated to extrawarnings if desired, but it would be very informative. (Conincidentally, I just had this discussion with some users last week.)

Also, note that the curve-fit spreadsheet tools insert these limits automatically and set them to match the range of the input data - thus suppressing any extrapolation.  I contend that's a bad idea.  Others have disagreed.

**Comment by Myoldmopar** [comment]
Thanks for starting off the conversation @mjwitte!  That's helpful.  I guess I don't have enough data yet to argue either way.  I've been told for so long that extrapolation is evil, but using a curve at the wrong point is certainly just as bad.  

For this particular issue, I'm specifically going to try to figure out whether the curves used in the ice storage example(s) are able to go lower and they were just _accidentally_ assigned too high of a lower limit or not.  For the sake of an example file, it's probably suitable to move the lower limit down, assuming the curve doesn't explode down there, since the example need not be tied to a specific piece of equipment.  Might be more on assisting the user generate a curve for a real piece of equipment for their case.

**Comment by EnergyArchmage** [comment]
Well virtually all curves in use are not really broad enough and not many folks don't seem to know or care.  
I agree that the silent clipping of input into curves is a problem.   But since input data ranges in general are so constrained such warnings would become ever-present.  
To inform some curve development, I just happened to be working up some custom EMS reporting to generate min/max ranges for cooling coil curve independent variables . This shows for example that in the medium office reference building the condenser entering drybulb, during times of cooling operation, the y value ranges from -16.7 to 46.1C (whereas input range is 10.0 to 50.0C).  I think such results could be collected for each performance curve/table and used in an output summary that gives an idea of how the curve was really called and compare to its input range limits.
