### ISSUE TITLE
InitVentilatedSlab Initialize total areas - for loop looks wrong

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4720]
For loop here https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/VentilatedSlab.cc#L1158

// Initialize total areas for all radiant systems
			for ( RadNum = 1; RadNum <= NumOfVentSlabs; ++RadNum ) {
				VentSlab( Item ).TotalSurfaceArea = 0.0;
				for ( SurfNum = 1; SurfNum <= VentSlab( Item ).NumOfSurfaces; ++SurfNum ) {
					VentSlab( Item ).TotalSurfaceArea += Surface( VentSlab( Item ).SurfacePtr( SurfNum ) ).Area;
				}
			}

Note how RadNum is never used inside the for loop . . . methinks "Item" should be "RadNum" here.  Need  to build a test file to determine a symptom to show this is incorrect.

**Comment by mjwitte** [comment]
Similar loops for low temp radiant systems confirm the suggested fix.

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/LowTempRadiantSystem.cc#L1514

Good news is that .TotalSurfaceArea is never used for ventilated slabs.  So, keep it for future use?  Or delete this loop and the variable altogether?

**Comment by Nigusse** [comment]
Replacing "Item" by "RadNum" index variable solves the problem.  I Just tested it using an example file.  As Mike suggested above this variable (VentSlab( ).TotalSurfaceArea) is not used at all in the model.  However, I suggest to leave it there because, a similar variable is used to Autosize length of Low Temperature Radiant Panel.  I am open for either option. What is your thought @mjwitte @ @Myoldmopar?

**Comment by mjwitte** [comment]
@Nigusse I'm fine with leaving it as you suggest.

**Comment by Myoldmopar** [comment]
Closed via #5432
