### ISSUE TITLE
Packaging fails to find idd

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4724]
The CLI change of the idd location seems to have broken ```make package```.

CMake Error at /home/elee/EnergyPlus/GitHub/EnergyPlusTeamBranch2/builds/doctools/d/cmake_install.cmake:40 (file):
  file INSTALL cannot find
  ".../builds/doctools/d/Energy+.idd".

Just need to add Products/ in there.

@nealkruis @kbenne @lefticus

**Comment by mjwitte** [comment]
@Myoldmopar Or can we put the IDD back where it used to be?

**Comment by Myoldmopar** [comment]
@mjwitte I have no preference.  I'm not sure what the driving force was behind moving it into Products/.  @nealkruis?

**Comment by mjwitte** [comment]
Or if it must stay in Products, can we get cmake to set the windows VS target directory for debug to Products/?  @kbenne

**Comment by nealkruis** [comment]
The CLI expects the IDD to be in the same directory as the executable by default. It is convenient to have the build structure reflect the install structure as close as possible for the sake of CI testing.

**Comment by kbenne** [comment]
@nealkruis the thing is that IDEs produce a subdirectory Default / Release under products so you might not be positioning the IDD next to the EXE.  I thought we discussed this and I the tests were and are passing so I didn't worry any more about it.

**Comment by mjwitte** [comment]
@nealkruis But it's not in the same directory.  IDD lands in \Products.  And the executables are in \Products\debug or release

**Comment by kbenne** [comment]
@mjwitte it is probably possible to put the idd under debug / release but it is tricky because in IDEs that determination is made at compile time not configure time.  http://www.cmake.org/cmake/help/v3.1/command/add_custom_command.html can use "generator expressions" to account for this.  I'll see about working that up if this is what you all want.

**Comment by nealkruis** [comment]
I recall addressing this problem already. I'm trying to track down what went wrong.

**Comment by Myoldmopar** [comment]
But you wouldn't want the idd in debug/release either, right?  The "Current working directory" when you hit debug in Visual Studio is going to be the base <cmake_build_dir>, isn't it?  Whether it is in Products/ or Products/Debug/, you would still have to add command line switches to the debugger to have it find the right one.

**Comment by mjwitte** [comment]
I liked it where it was.  But I already had to customize some run scripts previously to run a freshly compile EnergyPlus, because I didn't have all the pieces all in the same place.  Neither of the options we're discussing here make it like an install folder.  But my scripts got broken when the IDD moved (well, not really, because some old IDD kept sitting there and I didn't realize I wasn't using the latest until things got too far out of phase).  So, anyway, whatever we do here, we should let everybody know how it turned out so they can clean out old IDDs and update any run scripts as needed.

**Comment by nealkruis** [comment]
Ok. Turns out my [fix](https://github.com/NREL/EnergyPlus/blob/develop/cmake/RunSimulation.cmake#L23) wasn't as ideal, and only fixed the problem through CTest. I was playing around with generator expressions in CMake but never arrived at a great solution.

My preference would be to get the IDD in the executable directory ("Products" for command line builds, configuration directory for IDE builds) using a custom command post energyplus build. I can spend a little more time looking into this.

If it's not doable, then I think the IDD belongs in the "Products" directory. Having it in the top build directory alone makes no sense to me.

**Comment by mjwitte** [comment]
I'm not sure it's good to have it show up in different places depending on the build method.  But I'll let you and @Myoldmopar and @kbenne figure this out.  Another question for all of you, including @nealkruis   When I first tried to run a debugger session with the new CLI code in place, it wasn't finding the IDD and so it would start, throw a message in the output window and exit immediately.  I couldn't find a way to keep the output window open to see what the problem was and ended up single-stepping to find out it was quitting after it didn't find the IDD.  There's a showfatalerror here

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CommandLineInterface.cc#L406

But I don't think the err file is open yet at that point, so it bombs out.  Seems there shouldn't be any calls to showfatalerror (or the like) inside the CLI?  Can these types of failures somehow cause a break in debug?

**Comment by kbenne** [comment]
Based on how the program works now, that it expects idd next to executable, it seems like using the config (debug / release) sub directory is wise since that is where the executable will be.  Unless there are strong objections I will try to make that happen.  In an installed environment I don't think this is the best thing.  Windows platform aside, resources next to executables breaks convention.  Executable are more appropriately in $PREFIX/bin and resources more appropriately in $PREFIX/share.  But that is a larger discussion and change that I don't think we should entertain right now.

In any case note that the CLI responds to -i to specify the idd location.  For debugging purposes, if you aren't using the ctests, -i might be handy.

**Comment by nealkruis** [comment]
@mjwitte errors related to missing input files (IDF, EPW, or IDD) are printed to stdout. Printing to stdout or stderr is standard for command line programs. You can change your shell scripts to pipe the stdout to a file if you want to see what went wrong.

**Comment by mjwitte** [comment]
@kbenne After some digging I found how to enter command line arguments to be used in the VS interactive debugger, if it's necessary as a last resort we'll need to add it to the readme instructions.  But the CLI was supposed to be transparent so I could still do everything the same without any arguments.

@nealkruis DisplayString messages go to standard output, but I haven't figured out how to get VS to keep that window open so I can read it - it pops up - messages fly by - and it closes.  But I'm still doubtful that the two calls to ShowFatalError in CommandLineInterface.cc will work, because I don't see the err output file getting opened inside CommandLineInterface.  You should setup a test that hits those to be sure.

**Comment by nealkruis** [comment]
@mjwitte the calls to ShowFatalError occur after the ERR file name has been set, so everything should be fine.
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CommandLineInterface.cc#L300

If you want to pipe your stdout to a file, you can follow the directions here:
http://stackoverflow.com/questions/2683249/redirect-stdout-and-stderr-to-the-output-debug-console-of-microsoft-visual-studi

**Comment by kbenne** [comment]
https://github.com/NREL/EnergyPlus/commit/0fed1ff0b265feafcd7334c571cab9a9d04c305a

**Comment by mjwitte** [comment]
@nealkruis Ok - I see the first call to showfatalerror opens the err file.  So, would you object to adding a call to ShowFatalError before every exit(EXIT_FAILURE); in CommandLineInterface?   At least the ones that occur after the ERR file name has been set?

**Comment by mbadams5** [comment]
@nealkruis I just noticed this and it is a random question, why use exit()? I don't think exit() would have any negative effects in this case but I haven't looked hard. This also isn't related to the IDD issue.

this is just the first example.. https://github.com/NREL/EnergyPlus/blob/7f48b257316191c67239136685b46bc00cae213b/src/EnergyPlus/CommandLineInterface.cc#L148

https://stackoverflow.com/questions/461449/return-statement-vs-exit-in-main

**Comment by nealkruis** [comment]
@mbadams5 This is the same strategy we are using for fatal errors. What are the alternatives? Returns won't work since we are not in main().

**Comment by mbadams5** [comment]
@nealkruis You could propagate the return up to main()... Your ProcessArgs returns int and is called from main(). But I haven't looked hard or thought hard about this. I just off hand noticed. I'll try to look into it this weekend and maybe talk with you outside of this thread.

**Comment by nealkruis** [comment]
@mjwitte I can certainly add fatal errors anywhere after the ERR name has been set. My thinking is that the errors prior are all related to issues with misuse of the command line interface, and not necessarily EnergyPlus itself. I am going for consistency - CLI errors print only to stdout, EnergyPlus errors print to ERR.

There are nuances related to what the CLI knows about the error file before it runs into a problem. We could look into sending all of the error messages to stderr. This wouldn't rely on knowing what the ERR should be called before messages are printed.

This is probably a bigger discussion better suited for a different forum.

**Comment by mjwitte** [comment]
@kbenne I've added this clarification up above:
 If the CLI is running in legacymode then it looks for the IDD in the current working directory.  If it's *not* in legacy mode, then it defaults to the executable directory if -i is not set.

So, for development environments with no arguments, it's in legacymode and it's fine to have a single copy of the IDD, we just need to know where (and I'm fine with \Products) and make it clear in the readme instructions.
