### ISSUE TITLE
Need to change Sizing:System IDD default

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4747]
The IDD choice for the following needs to be changed to default to OnOff, and the Transition tool needs to re-run.

A11; \Central Cooling Capacity Control Method
      \note Method used to control the coil's output
      \type choice
      \key VAV
      \key Bypass
      \key VT
      \key OnOff
      \default VAV

**Comment by Myoldmopar** [comment]
Note this will likely cause minor diffs similar to those that were accepted when #4635 was merged.

**Comment by mjwitte** [comment]
@Myoldmopar But I thought @wfbuhl said it wouldn't change anything.  I'm confused.  Do we really want to change this?  And my whole question was whether HVACTemplate should be writing something other than VAV for all of these (which is what it currently will do, write VAV).

**Comment by Myoldmopar** [comment]
I took that to mean that if we had used OnOff as the default from the beginning, we wouldn't have actually been seeing all those tiny diffs.  And then changing it and re-transitioning would "undo" those diffs.  Maybe I misinterpreted.  

@wfbuhl?

**Comment by wfbuhl** [comment]
"OnOff" will reproduce our old calculation: that is, use the peak system
air flow rate to size the cooling coil. "VAV" uses the air flow rate at the
at the central cooling coil peak load to size the coil. Using "OnOff" as
the default will mean that there are no diffs. But I don't see what the
issue is with diffs: it is not as if we are trying to make every upgrade
give the same results as previously. In any case, the correct input for
this field depends on the system type. Since we are not going to go through
all the test files and change the input for this field by hand, it is
probably best to use the backward compatible choice of "OnOff", which could
just as well have been named "ConstantVolume". It is the most conservative
sizing choice.

Fred

**Comment by mjwitte** [comment]
@wfbuhl So, for a constant volume system, wouldn't these two options produce the same result?  And we should think about the naming of OnOff vs ConstantVolume.  I don't recall the initial discussions of where the OnOff name came from.

**Comment by wfbuhl** [comment]
These options are for sizing. You are telling the system sizing calculation
what kind of system you have. Then it uses that info to size the coil.

There are not many constant volume reheat systems around anymore. There are
more cycling system, it seems to me. If you want to change it to CV, that's
fine with me. There would be a few lines of code to change.

Fred



On Mon, Feb 23, 2015 at 12:37 PM, Michael J. Witte <notifications@github.com

**Comment by mjwitte** [comment]
@wfbuhl No, I'm fine with the OnOff terminology, just trying to understand the nuances.  Not to be negative, but I don't think the implications of this field will be immediately obvious with either keyword, so it will need explanation.  The bigger question is if we want to change the default and change the idfs.

**Comment by Myoldmopar** [comment]
I vote to change the default to onoff, even though it's added work for me.
I think it's the right move.

**Comment by mjwitte** [comment]
@Myoldmopar Then we need to change HVACTemplate.  We can go with the no-impact OnOff everywhere, or stick our necks out and use VAV as appropriate.

**Comment by Myoldmopar** [comment]
No impact for this release. Improving detection on system type can be added
later.

**Comment by mjwitte** [comment]
@Myoldmopar So, will you make the replacements in expandobjects?  It should be very straightforward.

**Comment by Myoldmopar** [comment]
Yes

**Comment by wfbuhl** [comment]
Thank you Edwin
