### ISSUE TITLE
Need to add 8.2 idd file and install commands

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4780]
The 8.2 idd needs to be included for the version updater to work.  Add that file from the last release and update the CMake commands accordingly.

**Comment by mjwitte** [comment]
@Myoldmopar @kbenne Tried to transition a file using the v8.2.9 install.  In addition to the missing v8-2-0 idd, the transition utility is looking for v8-3-0 idd but the one that's installed in the IDFVersionUpdater folder is v8-2-9 idd. 
 Also, EP-Launch single file transition menu option doesn't work, because it's still under the old mindset that 8.2.9 means this is major version 8.2, so ti's looking for transition Transition-V8-1-0-to-V8-2-0.exe
@JasonGlazer Could we change that logic in EP-Launch?

**Comment by mjwitte** [comment]
@Myoldmopar And when I renamed v8-2-9 idd to v8-3-0 idd transition ran, but the version stamp on the transitioned file says 8.2, not 8.3 as I expected.  That's because we aren't writing the minor version number and the "new" version is 8.2.9.  Not sure what the right solution is, but it's going to be a problem for people that have been transitioning things for these iteration releases and their file all have a version 8.2 object but the files are beyond 8.2.

**Comment by JasonGlazer** [comment]
@mjwitte We can certainly update EP-Launch. What should the new logic be? Once we figure that out, it should probably be an new issue.
