### ISSUE TITLE
EnergyPlus cannot handle non-convex surfaces in shading calculations

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#4839]
I don't believe that either of the shadow algorithms in E+ can handle non-convex casting surfaces.  With more and more input files coming from CAD tools this is too restrictive of a constraint.  Can we either 1) triangulate these surfaces internal to E+ or 2) implement some other algorithm that does not have this constraint?

**Comment by mjwitte** [comment]
@macumber Triangulation might be possible.  There is already code in place to triangulate surfaces for dxf output, but the hard part comes in relating the triangulated pieces back to the original surface which might hold windows or other subsurfaces, etc.  So, the triangulated parts would need to be done as a side calc then the average solar placed on the base?  Or something like that.  For many years now, there have been various proposals and hopes to replace the entire shading calc engine, but none have materialized.  @hongtz68 @EnergyArchmage Comments?

**Comment by chriswmackey** [comment]
I don't have too much to offer in terms of a solution but I just wanted to say how incredibly lovely it would be to have this capability.  This has been at the top of my E+ wish list for a few years now and even an option that exported the E+ solar calc to Radiance would be immensely helpful.  Perhaps a Radiance export is more of a possibility now that most E+ interfaces (including OpenStudio) install the two side-by-side.

**Comment by aaron-boranian** [comment]
Problem: Full interior solar distribution isn’t handled correctly for concave zones.

Solution: Re-engineer the solar distribution and shading algorithms following some of the examples from computer graphics calculations.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/9314436)

**Comment by aaron-boranian** [comment]
Problem: ?? (Help define by commenting)

Depends on: http://energyplus.uservoice.com/forums/258860-energyplus/suggestions/9314436-calculate-interior-solar-distribution-for-concave

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9310410)

**Comment by jasondegraw** [comment]
The concerns brought up here may be addressed by the ongoing GPU shading work (@mbadams5?)

**Comment by chriswmackey** [comment]
That would be great if this gets addressed in some way shape or form, @jasondegraw .

After re-reading this post, I also wanted to confirm that triangulation of the surfaces does not seem to solve the issue and it seems to be related to non-convex zone geometry rather than non-convex surface geometry.  At the least, I can report that I still get a CHKBKS error with a model that does not have any non-convex surfaces but a non-convex zone geometry [as defined in the E+ reference here](https://bigladdersoftware.com/epx/docs/9-0/input-output-reference/group-simulation-parameters.html#field-solar-distribution).  I am happy to post a link to the idf if it helps clarify.

Also, please correct me if I am wrong that this issue is about the CHKBKS error that E+ throws with non-convex zone geometry.

**Comment by shorowit** [comment]
The new PixelCounting method in E+ 9.3 removes limitations of non-convex surfaces. Seems like this issue has been addressed.
