### ISSUE TITLE
Parametric preprocessor deletes more idf files than it should

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4842]
When testing a user's file that included parametrics, a similarly named idf file was deleted.  The parametrics were in MyFile.idf and the file which got deleted was named MyFile-LowerSupplySetpoint.idf

**Comment by JasonGlazer** [comment]
@mjwitte Were you using the RunParam.bat batch file or EP-Launch?

**Comment by mjwitte** [comment]
ep-launch if I remember correctly

**Comment by JasonGlazer** [comment]
@mjwitte I can reproduce the problem using EP-Launch and I think it is just a EP-Launch problem when ParametricPreprocessor is invoked. Right now EP-Launch simulates anything called MyFile-*.idf. If MyFile-LowerSupplySetpoint.idf was not even created by the ParametricPreprocessor it is deleted because otherwise it would simulated again. I will revise this so that EP-Launch only runs files that are created by the ParametricPreprocessor.
