### ISSUE TITLE
Suggestion: add distribution system outdoor air load in zone sizing

### ISSUE THREAD

**Issue by ecoeficiente** [NREL/EnergyPlus#4933]
When using mechanical ventilation without conditioning (not cooling or heating) or DOAS with air setpoints below zone setpoints (just to precondition outdoor air), zone equipment is undersized because it does not take into account air distribution system load.

I think that optional fields could be implemented in zone sizing, such as:
- **_Cooling Design Outdoor Air Supply Temperature**_: _Conditioned/Outdoor Temperature/Temperature Setpoint_.
- **_Heating Design Outdoor Air Supply Temperature**_: _Conditioned/Outdoor Temperature/Temperature Setpoint_.

_Conditioned_ option will work just as it's doing now.

This options would work together with (or be within) _DesignSpecification:OutdoorAir_.

**Comment by Myoldmopar** [comment]
@wfbuhl Is this addressed by your DOAS changes (#5002)

**Comment by mjwitte** [comment]
@ecoeficiente New DOAS sizing fields were added to Sizing:Zone in #5002 in v8.4.0 (Sept 2015). Closing this issue.

**Comment by aaron-boranian** [comment]
**Account for DOAS air when sizing zone units**

If you have a DOAS system in E+ (eg Fan Coils of any kind, radiators, etc) combined with a ventilation system, E+ does not currently take into account heating and/or cooling effects of the DOAS air when sizing the zone units (coils and fans)

This is a gross error. It is very common in DOAS systems for the air to be conditioned for dehumidification, meaning that air could be supplied from the DOAS system as low as say 13C / 55F and at 50-100% above the minimum ventilation rate (for dehumidification).

The zone units do not account for this load in sizing, meaning that cooling components are over-sized and heating components are undersized.

If a system is designed with separate DOAS ventilation and zone units then the zone units must be sized with the DOAS air included (at the very least fix the under-sized coils!!!)

The way it is currently implemented is very counter-intuitive because it adjusts the space loads rather than showing how it is one of the active ways the system manages the space load to maintain the design conditions.

Most practitioners would not consider the ventilation impact of the DOAS air to be incorporated into the space loads. They would expect this impact to be tracked as an HVAC load in the space that provides some kind of contribution in adding or removing both sensible and latent heat.

If this was implemented properly we would expect to see:

- Space loads that are consistent across all air-based HVAC options with the same setpoints
- Clear reporting on the sizing load contributions of both the zone equipment and the DOAS air
- If it’s included as a setting it should be the default. Very few users would go looking for this as an option – everyone would expect it to be applied.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/20298838)

**NOTE**: This may be related to issue #6243. Would @mjwitte like to chime in?
