### ISSUE TITLE
Uninitialized EMS variable should cause severe error

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#4943]
I would think that EnergyPlus should loudly and severely error out during the simulation when an EMS variable is used before being initialized -- there's no circumstance under which a user should ever want EnergyPlus to silently continue and use a default value. This can cause unexpected simulation results.

The user could get into this situation because:
1. They misspelled a variable.
2. They use a variable in an expression but simply forgot to initialize the variable's value.
3. They use a variable in an EMS:Program but forgot to create an EMS:Sensor for this variable.

Some discussion of this has already occurred over email.

@Myoldmopar said: "I guess you'd have to add a flag to the runtime language value type here: https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/DataRuntimeLanguage.hh#L423.  (Could be the wrong struct, just my initial scrounging)

A bool initially set to false that flips to true when it is _set_ and throws an error if it is _used_ while false seems like a good idea.  Any thoughts/concerns with that type of fix, Brent?  Or maybe this is already somewhat implemented but disabled or..."

@EnergyArchmage said: "Well I suppose it would be possible but the parser was never designed for this. The variables are initialized to zero when parsed.  So it is not accurate to say they are not initialized.  Since there is only one type, double, there didn't seem a good reason to require declarations. Spelling mistakes are a problem for users but...  This would be a fairly large effort I think."

**Comment by mjwitte** [comment]
This is closely related to #4404

**Comment by EnergyArchmage** [comment]
@shorowit I have worked out code changes to report errors to the EDD file when an uninitialized variable is used, in this branch https://github.com/NREL/EnergyPlus/tree/4943-EMS-Trap-Unitialized-Variables

Do you think that checking the EDD file for such errors is sufficient or _must_ it also show in ERR file? 

For other math errors, like divide-by-zero or too-large-an-exponential, we only report to the EDD file and not also the ERR file.  If Output:EnergyManagementSystem is set to ErrorsOnly the new Erl errors should be obvious if users are checking the EDD at least a little bit. 

I do not think it a good idea to throw loud severe errors (which are supposed to be fatal) to the ERR file because there are valid reasons an unitialized variable will get used early in the simulation.  I think it would be impossible to get the example files to run without throwing the error During Sizing.   For many types of EMS applications there are serious chicken-and-egg problems that cause a program to execute before all the setup is complete.  The relative timing of calling points, input setup, autosizing, HVAC component model delays, etc. often means that EMS initialization programs have not yet executed.   For example the main initialization calling point for BeginNewEnvironment doesn't get called during sizing.   We simply cannot setup everything before everything else.

**Comment by mjwitte** [comment]
@EnergyArchmage Would it be safe to say that any use of an uninitialized variable after sizing and after warmup is a real problem that should throw a severe?

**Comment by shorowit** [comment]
@EnergyArchmage Great! I'm glad to hear that you think you've found a straightforward implementation.

If the ERR file is intended to report EnergyPlus errors, then I would think users expect either EMS errors (uninitialized or math errors; others?) or source code errors to appear in it. The difference between the two is largely superficial. But I'm sure that's not the answer you wanted to hear.

Now that you raise the EMS math error issue, I'm actually surprised to hear that these errors weren't already being reported in the ERR file -- or, more importantly, weren't preventing the simulation from running successfully. What value is EMS assigning for divide by zero errors -- zero? This makes me nervous for our software; I need to start double-checking EDD files for our simulations now. Along with the original request, I'd push for these kinds of math errors to become fatal EnergyPlus errors as well.

**Comment by EnergyArchmage** [comment]
Okay, I have this working fairly well now, in branch 4943-EMS-Trap-Unitialized-Variables.  Although I am still a little skeptical about throwing all these fatals, I have to admit this has uncovered a lot of flaws in the test suite files and it should be very valuable.  

The main behavior change that will annoy is going to be from unused arguments in the function "@CurveValue", now they will throw fatals whereas before a dummy of 0.0 didn't bother anything.  Virtually every user input file that uses "@CurveValue" are likely to fail because it takes arguments for up to 5 independent variables and the guidance was to pad the list with dummys.  

The remaining outstanding tasks are
-  provide more context for the line of EMS code that threw the error. 
-  update documentation to explain about the new need to initialize.
-  unit test
-  see if issue 4404 can be combined here

**Comment by mjwitte** [comment]
@EnergyArchmage Any chance that the arguments to @CurveValue can be treated as a special case to avoid unnecessary errors?

**Comment by shorowit** [comment]
Brent, let me know when you want some testing of this. We use quite a bit of EMS in our BEopt input files (though we will hopefully reduce the amount of EMS we need over time!). It seems like we should wait for your first outstanding task to be implemented, otherwise we'll have no context for tracking down errors reported.

**Comment by EnergyArchmage** [comment]
HI @shorowit, If you still want to do some testing, I have improved the error reporting to show where in the Erl program code the problem happened, in this commit
https://github.com/NREL/EnergyPlus/commit/f2fa712a08ac7393b898ab6d279e331cae284f36

**Comment by EnergyArchmage** [comment]
Okay, with this commit, https://github.com/NREL/EnergyPlus/commit/47a50eab056b493bad21074d28001a9a5684a958, I think all the desired changes are done.  Also fixes #4404, now suppresses fatal for CurveValue, 
remaining tasks: 
- [x] unit tests
- [x] documentation changes

**Comment by shorowit** [comment]
@EnergyArchmage This is great! Unfortunately, I'm fairly strapped for time at the moment. Would it be useful if I provided test IDFs generated from BEopt that cover a variety of different EMS programs? I could send that over pretty quickly.

**Comment by Myoldmopar** [comment]
Closed via #5660

**Comment by shorowit** [comment]
FYI, I'm finally getting around to testing this with our BEopt IDFs and it is super useful. Thanks again for implementing it, @EnergyArchmage.
