### ISSUE TITLE
AirLoopHVAC:UnitaryHeatPump:WaterToAir with Cycling flow mode causing Temp out of Range warnings

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4964]
This particular file has 80 AirLoopHVAC:UnitaryHeatPump:WaterToAir systems, all using the default Heat Pump Coil Water Flow Mode = Cycling which adjusts the source water flow rate proportional to the heat pump PLR.  This generates thousands of these warnings:

   *\* Warning *\* GetSpecificHeatGlycol: Temperature is out of range (too high) for fluid [WATER] specific heat **

Changing the coil flow mode to ConstantOnDemand eliminates these warnings.  It may be that the inputs to these heat pumps are bad, or the Cycling flow logic needs some adjustment to overheating the water.

**Comment by rraustad** [comment]
I see a defect folder 4963 and 4967. This was a long time ago so maybe just go with the example file? I think the water side delta T needs to be that at full flow since water flow is adjust by PLR. When using cycling mode, the output is average fluid flow rate (full flow \* PLR) and full load outlet temperature, at least that's how we do it on the air-side to conserve energy. I'll check to see how outlet water temp is calculated.

**Comment by mjwitte** [comment]
Closed via #5691
