### ISSUE TITLE
DX heating coil defrost operation causes increase in coil COP

### ISSUE THREAD

**Issue by ejhw** [NREL/EnergyPlus#4973]
I have noticed that DX heating coil defrost operation causes an unexpected increase in coil COP (applies to both SingleSpeed and MultiSpeed coils; not tested for VariableSpeed). The following plots are from testing a MultiSpeed coil with identical performance curves for the two speeds and no part load cycling losses.

This issue is best seen by plotting hourly coil COP (calculated as `Heating Coil Total Heating Energy` / `Heating Coil Electric Energy`) against the outdoor drybulb temperature. There is an increase in COP of ~0.5 for temperatures below 0ºC, when defrost operates. Compare this to the COP values resulting from the EIR vs. T curve output (shown in blue). I can't think of any reason why defrost operation should increase the coil COP. 
![screen shot 2015-06-17 at 4 06 28 pm](https://cloud.githubusercontent.com/assets/1276021/8219925/e37ef0a6-150a-11e5-8bb2-cd449c76e27c.png)

The same effect can be seen when looking at a time-series plot:
![screen shot 2015-06-17 at 4 06 40 pm](https://cloud.githubusercontent.com/assets/1276021/8219926/e65fa090-150a-11e5-9e30-5ce6ac0d44ae.png)
![screen shot 2015-06-17 at 4 06 46 pm](https://cloud.githubusercontent.com/assets/1276021/8219927/e8331ad2-150a-11e5-8b51-b0171f7f77be.png)

The above results are using `Resistive` defrost with `Timed` control, but I see the same effect for `ReverseCycle` defrost and using `OnDemand` control. I confirmed that changing the maximum defrost temperature changes the temperature below which this increase in COP occurs.

idf and associated files to be uploaded by @nmerket.

**Comment by nmerket** [comment]
Defect files are at
https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/4000s/4973

**Comment by ejhw** [comment]
#### Relevant excerpt from the Engineering Reference (SingleSpeed coil):

![screen shot 2015-06-18 at 2 04 40 pm](https://cloud.githubusercontent.com/assets/1276021/8240877/0875a0a4-15c3-11e5-99df-8f6fb037b1be.png)

**Comment by nmerket** [comment]
I think the problem is happening somewhere in [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/DXCoils.cc#L10640-L10668). (Note so I can find it later.)

**Comment by nmerket** [comment]
Okay, I found out [where this is happening](https://github.com/NREL/EnergyPlus/blob/405295034523d273e87403a268c96107e2c0d224/src/EnergyPlus/DXCoils.cc#L10646).

``` c++
                // Check outdoor temperature to determine of defrost is active
                if ( OutdoorDryBulb <= DXCoil( DXCoilNum ).MaxOATDefrost ) {
                    // Calculate defrost adjustment factors depending on defrost control type
                    if ( DXCoil( DXCoilNum ).DefrostControl == Timed ) {
                        FractionalDefrostTime = DXCoil( DXCoilNum ).DefrostTime;
                        if ( FractionalDefrostTime > 0.0 ) {
                            HeatingCapacityMultiplier = 0.909 - 107.33 * OutdoorCoildw;
                            InputPowerMultiplier = 0.90 - 36.45 * OutdoorCoildw;
                        }
                    } else { //else defrost control is on-demand
                        FractionalDefrostTime = 1.0 / ( 1.0 + 0.01446 / OutdoorCoildw );
                        HeatingCapacityMultiplier = 0.875 * ( 1.0 - FractionalDefrostTime );
                        InputPowerMultiplier = 0.954 * ( 1.0 - FractionalDefrostTime );
                    }

```

In the debugger it becomes fairly obvious that when the defrost is on the COP increases by a factor of `1 / InputPowerMultiplier`. That's what's causing the change. I'm now digging through the Engineering documentation to figure out _why_. If that's obvious to anyone reading this, feel free to chime in.

@ejhw @jonwinkler

**Comment by nmerket** [comment]
It looks like this is working as expected/documented. The `InputPowerMultiplier` calculation comes from DOE2.1E, which has been around a while. 

From the Engineering Reference Manual:

<hr/>

#### Frost Adjustment Factors

Frost formation on the outdoor coil, and the need to periodically defrost this coil, has a significant impact on heating capacity and energy use by the DX heating system. If the outdoor air dry-bulb temperature is below the specified maximum temperature for defrost operation, then the model calculates adjustment factors for heating capacity and input power due to frost formation, and the fractional defrost time period, depending on the defrost strategy and defrost control type specified for the heating coil. This method of accounting for the impacts of frosting/defrost was taken from the model used in DOE-2.1E (ESTSC 2001, Miller and Jaster 1985).

The model first estimates the outdoor coil temperature according to a linear empirical relationship with outdoor air dry-bulb temperature as the independent variable.

![codecogseqn](https://cloud.githubusercontent.com/assets/5325034/8583781/a73a820c-258d-11e5-95e2-2eab4c9b9081.gif)

The difference between the outdoor air humidity ratio (from the weather file) and the saturated air humidity ratio at the estimated outdoor coil temperature is then calculated, and this value is used as an indication of frost formation on the outdoor coil.

![codecogseqn 1](https://cloud.githubusercontent.com/assets/5325034/8583801/c8a76004-258d-11e5-94ea-4f379e983c17.gif)

Frost formation on the outdoor coil must be periodically removed. The fraction of compressor runtime when the coil is being defrosted is either entered by the user (for timed defrost) or is calculated by the model (for on-demand defrost) using an empirical equation and ![codecogseqn 5](https://cloud.githubusercontent.com/assets/5325034/8583859/3c4e173c-258e-11e5-846e-e93eb245596c.gif). Adjustment factors to total heating coil capacity and input power due to frost formation on the outdoor coil are also calculated by empirical models with ![codecogseqn 5](https://cloud.githubusercontent.com/assets/5325034/8583859/3c4e173c-258e-11e5-846e-e93eb245596c.gif) or fractional defrost time period as the independent variable. The defrost time period fraction and adjustment factors due to frost formation on the outdoor coil vary depending on the defrost control type as shown below.

_Timed Defrost_:

![codecogseqn 2](https://cloud.githubusercontent.com/assets/5325034/8583819/f60ad38c-258d-11e5-9648-18b71ec81cb4.gif)

![codecogseqn 3](https://cloud.githubusercontent.com/assets/5325034/8583828/056f861a-258e-11e5-8ed2-84c93cc06a67.gif)

![codecogseqn 4](https://cloud.githubusercontent.com/assets/5325034/8583837/17108f68-258e-11e5-836f-80b8d1aa33b9.gif)

_On-Demand Defrost_:

![codecogseqn 6](https://cloud.githubusercontent.com/assets/5325034/8583879/6ea2978a-258e-11e5-85ea-4e080329f5fc.gif)

![codecogseqn 7](https://cloud.githubusercontent.com/assets/5325034/8583891/7cb1e434-258e-11e5-9900-45723aa2c211.gif)

![codecogseqn 8](https://cloud.githubusercontent.com/assets/5325034/8583904/9ef79b60-258e-11e5-9861-2a25a4d4cb5e.gif)

If the outdoor air dry-bulb temperature is above the specified maximum temperature for defrost operation, the fractional defrost time period is set to zero and the heating capacity/input power multipliers are set to unity.

**Comment by ejhw** [comment]
For on-demand defrost, the ratio of `HeatingCapacityMultiplier` to `InputPowerMultiplier` is always 0.92, so wouldn't that always decrease the COP?
Where do you see that the COP is increased by a factor of `1 / InputPowerMultiplier`?

**Comment by nmerket** [comment]
![codecogseqn 9](https://cloud.githubusercontent.com/assets/5325034/8601361/dd123276-2628-11e5-9659-681efd654d46.gif)

There isn't a variable directly named `COP` in this model. But, when I take that `InputPowerMultiplier` and multiply it by the COP, I get the COP from the EIR curve.

**Comment by ejhw** [comment]
In other words, if you divide the COP from the EIR curve by the `InputPowerMultiplier`, you get the operational COP as reported. This doesn't seem right because the COP should also be multiplied by the `HeatingCapacityMultiplier`.

Like you said, there isn't a variable named `COP`, so this probably means that <i>P<sub>in</sub></i> is getting multiplied by the `InputPowerMultiplier`, but <i>Q<sub>heatpump</sub></i> is not getting multiplied by the `HeatingCapacityMultiplier`.

**Comment by nmerket** [comment]
Found the problem and fixed it for `Coil:Heating:DX:MultiSpeed`. Explanation and results are [here](http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/4969350/notebooks/defrostcop.ipynb)

**Comment by mjwitte** [comment]
@rraustad FYI.

**Comment by rraustad** [comment]
I can't leave a comment in the code compare. Mostly this appears correct, but only from the perspective that the COP now lines up with the performance curves.

This line (DXCoils line 10907) seems suspect:
DXCoil( DXCoilNum ).ElecHeatingPower = TotCap / HeatingCapacityMultiplier \* EIR \* DXCoil( DXCoilNum ).HeatingCoilRuntimeFraction \* InputPowerMultiplier;

The issue is COP is calculated incorrectly. Here the power is artificially increased (i.e., TotCap is now non-adjusted capacity) so that COP comes out correct. This seems wrong. How can the total capacity be greater than the rated capacity? If anything, the RTF should be increased to account for lower heating capacity (which I think the model did).

Instead, the COP calculation should be adjusted to include the impact on heating capacity and power.

I need to be able to put comments in places where I think calculations should be adjusted.

**Comment by kbenne** [comment]
@rraustad  There are two cases I had the same issue adding line comments.  In one case I wasn't logged in.  That is probably not the case here, because you just left this comment.  The other is sometimes the code compare is scrolled slightly to the right, and the little plus buttons to add comments are off screen.  Try scrolling to the left.

**Comment by nmerket** [comment]
@rraustad After making the change in the commit you just reviewed, I realized that the way the variables are used is kind of misleading. I made a few more changes in that branch to make it more clear what I was doing. See pull request #5025 for the complete picture.

**Comment by rraustad** [comment]
I think it's because I'm reviewing in a branch compare and not a pull request compare. I scroll all the way to the left and all I can do is click on a line number which highlights the line. Moving the cursor around doesn't show the blue + square. We can flesh this out in a PR. I see you just posted a PR.

**Comment by shenb** [comment]
I checked VariableSpeed coil doesn't have the same problem.
