### ISSUE TITLE
Parallel fan powered terminal unit fan controls need option to cycle with thermostat

### ISSUE THREAD

**Issue by rongpengzhang** [NREL/EnergyPlus#4989]
Currently, the input is for a minimum damper position at or below which the zone fan turns on. This leaves the fan on during deadband hours and potentially always during nighttime hours when the damper is closed! In most real systems and in DOE2, the fan is controlled thermostatically so that it can be used as the first stage of heating, before the reheat coil is energized. So that would require a separate terminal fan Tstat schedule or maybe just an input for offset from the heating Tstat.

**Comment by mjwitte** [comment]
Also, allow Maximum Secondary Air Flow Rate to be specified as a fraction of the primary flow rate.

**Comment by mjwitte** [comment]
User reports that the changes in #5879 still have some issues:

Made the following changes to use the new Night Cycle Availability Manager.
1.      Using the “CycleOnAnyCoolingOrHeatingZone” control type option.
2.      Put all zones in to the zone list “CoolingZones”.
3.      Put VAV reheat terminal zones to the zone list “Heating Zones”
4.      Put all PIU zones into the “Heating Fan Only Zones”

Testing result shows that the zone lists in Night Cycle Availability Manager work:
  a.      Keeping central AHU fan off during unoccupied period when any of the zones on the “heating fan only” Zones call for heating.
  b.      Activate central AHU fan when any zone on the “Cooling Zones” call for cooling during unoccupied period
  c.      Activate central AHU fan when any zone on the “Heating Zones” call for heating during unoccupied period

There are still two issues remaining:
1.      Parallel PIU fan still seem to be running during some cooling operation and deadband operation periods (when the primary air flow ratio is low). Ideally we would like the fan to be operating only when zone thermostat calls for heating.
2.      During unoccupied period, it seems like if any of the PIU zones call for heating, PIU fans for all zones cycle on. What we expect is only PIU fan in the zones that call for heating cycles on, others remain off.

_Defect file added to EnergyPlusDevSupport/DefectFiles._

**Comment by mjwitte** [comment]
Issue 2 above can be seen in the defect file output for time  01/06  04:40:00, Space 2-1 falls below setpoint and then in the next timestep all of the zone fans turn on.  The other zones have baseboard heat which keeps them at setpoint.  Space 2-1 has undersized baseboard.  For this to work, however, the baseboard needs to run first for heating, otherwise the PIU will think it should be serving the heating load.  Second flavor of defect file added.

_Update_
The defect files did not have Fan On Flow Fraction = 0.0 which is required to access the improved controls.  With that changed, issue 2 above is resolved.  But issue 1 above is still happening - see 07/19 14:00 - 14:50.  The night cycle manager status is 2 (central fan turned on) but the Space2-1 PIU Fan is operating - it should be off because the zone temperature is above the heating setpoint of 18.33.  Later in the day, starting at 16:34, the fan does come on because the zone has cooled off enough to require some reheat.

**Comment by Myoldmopar** [comment]
Closed via #5918
