### ISSUE TITLE
Output folder does not exist and specified location does not have write permission

### ISSUE THREAD

**Issue by mbadams5** [NREL/EnergyPlus#5063]
This is tangentially related to #5062.

When I run EnergyPlus through the CLI from the /Applications/EnergyPlus-8-3-0 folder AND the specified outputs folder does not exist and the desired location is in a folder without write permission the following error happens.

```
computer_name:EnergyPlus-8-3-0 user_name$ ./energyplus -a -r -d Outputs/ -w WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw ExampleFiles/RefBldgMediumOfficeNew2004_Chicago.idf 
Trying to display error: " **  Fatal  ** EnergyPlus: Could not open output debug file: Outputs/eplusout.dbg."
Trying to display error: " **  Fatal  ** ShowErrorMessage: Could not open file Outputs/eplusout.err for output (write)."
...
Trying to display error: " **  Fatal  ** ShowErrorMessage: Could not open file Outputs/eplusout.err for output (write)."
Segmentation fault: 11
```

It seems like the CLI gets in an infinite loop and eventually stack overflows (!!). There should be better error messages and it shouldn't stack overflow. I think exiting the program with an appropriate error message informing the user to create the folder is probably the correct approach.

fyi @kbenne @Myoldmopar

**Comment by nealkruis** [comment]
To clarify a bit: EnergyPlus starts hanging well after the CLI is done processing. This could be a problem in older versions of EnergyPlus as well.

**Comment by kbenne** [comment]
@nealkruis the thing is that I don't think older versions had any expectation of working from a read only directory. The installer sets the ExampleFiles directory to writable for this reason. I guess maybe if you were using an ini file?

**Comment by mbadams5** [comment]
@kbenne I don't know if you intended your comment for this issue or the other issue. Regarding this issue, I think exiting EnergyPlus if the Output directory is read only is valid as long as there is an appropriate error message and no longer a segmentation fault.

**Comment by nealkruis** [comment]
I can confirm that this was also happening with older versions of EnergyPlus (pre-CLI).

**Comment by nealkruis** [comment]
This is happening because all non-zero io status flags result in a call to [ShowFatalError](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CommandLineInterface.cc#L456), which calls to [ShowErrorMessage](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/UtilityRoutines.cc#L1509), which will [check the status of the ERR file](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/UtilityRoutines.cc#L1561) and call [ShowFatalError](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/UtilityRoutines.cc#L1564) again if it can't access the ERR file. The cycle then repeats until eventually segfaulting.

To solve this, we need to start distinguishing permission violations from other non-zero io status flags. @DeadParrot I took some time to look at the values of `ios` in `gio`, but it wasn't very clear to me what the actual exceptions were. Is it possible to add comments or make an explicit enumeration that is more readable than simply the numbers?

Are these the same as the [Fortran file status codes](https://software.intel.com/en-us/node/510890)?

**Comment by nealkruis** [comment]
`if (status == 600)` seems to do the trick.

**Comment by DeadParrot** [comment]
These are Intel Fortran error codes. They are not standardized in Fortran
(absurd!) but I could put together a list. A non-Fortran i/o package and
non -global file objects would be a good long term goal.

Stuart

**Comment by mbadams5** [comment]
@DeadParrot Any update? The `if (status == 600)` works for me when testing. If that isn't the appropriate value to check for a permission exception then what is the correct value? Since the CI came back clean, i'd like to keep this moving unless there is a compelling reason to hang on.

**Comment by DeadParrot** [comment]
Out of the office but I think the 600 error is for permission errors so for
now that is prob safe.

Stuart
