### ISSUE TITLE
DST causing unexpected result on date when schedule changes

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5155]
Helpdesk ticket 10742
This is the schedule in question.

```
! Schedule: Arrêt charge E 706
Schedule:Compact, 
Arrêt charge E 706, 
Fraction,
Through: 2 Aug,
For: Weekdays Weekends Holidays WinterDesignDay SummerDesignDay,
Until: 24:00, 1,
For: AllOtherDays,
Until: 24:00, 1,
Through: 3 Aug,
For: Weekdays Weekends Holidays WinterDesignDay SummerDesignDay,
Until: 15:00, 1,
Until: 24:00, 0,
For: AllOtherDays,
Until: 24:00, 0,
```

On Aug 3, from 23:00-24:00, it should be zero, but it's showing 1.

**Comment by rraustad** [comment]
Not sure if what I see in another file is the same issue as this or not so am including here. If I find a different solution I'll split these out.
Added defect file 5515-PTACvsAIRLOOP-Pri.idf.

I find that the special days are not accounted for correctly. For example, if New Years day, MLK, and presidents day are included in the input and the simulation starts on a Sunday, then all these should fall on a Monday. The second 2 holidays do not.

    ! <N:US Federal>
    RunPeriodControl:SpecialDays,
      New Year's Day,                         !- Name
      January 01,                             !- Start Date
      1,                                      !- Duration {days}
      Holiday;                                !- Special Day Type

    ! <N:US Federal>
    RunPeriodControl:SpecialDays,
      Martin Luther King,                     !- Name
      3rd Monday in January,                  !- Start Date
      1,                                      !- Duration {days}
      Holiday;                                !- Special Day Type

    ! <N:US Federal>
    RunPeriodControl:SpecialDays,
      President's Day,                        !- Name
      3rd Monday in February,                 !- Start Date
      1,                                      !- Duration {days}
      Holiday;                                !- Special Day Type

![e holidaysarewrong](https://user-images.githubusercontent.com/5778156/31146848-e482c65e-a855-11e7-8650-7e775fba9210.png)

Update: 2/17 in above figure is Fri, still wrong.

The fix for this is to save the monthly start day in the Environment.MonWeekDay array.

line 1144 of WeatherManager.cc I added Environment(Envrn).MonWeekDay = MonWeekDay; in 2 places.
Also noticed that use of the Loop variable here is incorrect since it's outside the for loop. Well maybe not since the loop breaks out when correct period is found, so Loop does equal the correct DataPeriod.

Line 1144:

        cTotalEnvDays = RoundSigDigits( Environment( Envrn ).TotalDays );
        if ( Environment( Envrn ).DayOfWeek == 0 ) { // Uses Weather file start
            gio::write( OutputFileInits, EnvNameFormat ) << Environment( Envrn ).Title << kindOfRunPeriod << StDate << EnDate << ValidDayNames( ThisWeekDay ) << cTotalEnvDays << "UseWeatherFile" << AlpUseDST << AlpUseSpec << ApWkRule << AlpUseRain << AlpUseSnow;
            TWeekDay = ThisWeekDay;
            MonWeekDay = DataPeriods( Loop ).MonWeekDay;
            Environment( Envrn ).MonWeekDay = MonWeekDay; --- here
        } else {
            gio::write( OutputFileInits, EnvNameFormat ) << Environment( Envrn ).Title << kindOfRunPeriod << StDate << EnDate << ValidDayNames( Environment( Envrn ).DayOfWeek ) << cTotalEnvDays << "Use RunPeriod Specified Day" << AlpUseDST << AlpUseSpec << ApWkRule << AlpUseRain << AlpUseSnow;
            TWeekDay = Environment( Envrn ).DayOfWeek;
            MonWeekDay = Environment( Envrn ).MonWeekDay;
        }
    } else { // just in case
        if ( Environment( Envrn ).DayOfWeek == 0 ) { // Uses Weather file start
            TWeekDay = ThisWeekDay;
            MonWeekDay = DataPeriods( Loop ).MonWeekDay;
            Environment( Envrn ).MonWeekDay = MonWeekDay; --- and here
        } else {
            TWeekDay = Environment( Envrn ).DayOfWeek;
            MonWeekDay = Environment( Envrn ).MonWeekDay;
        }
    }

With this change the result is:

![e holidaysarewrong_fixed](https://user-images.githubusercontent.com/5778156/31147192-0fd36f10-a857-11e7-9e50-0fb2789880b2.png)

**Comment by rraustad** [comment]
Holiday issue is resolved in V9.2:
![image](https://user-images.githubusercontent.com/5778156/63212626-78470c80-c0d5-11e9-84cb-4e05ba1f01e9.png)

**Comment by rraustad** [comment]
Issue with schedule off after 15:00 on Aug 3 is still a problem. Updated 5155 defect file in.idf to run in V9.2.

![image](https://user-images.githubusercontent.com/5778156/63214301-99632980-c0e4-11e9-8ef4-dcf2ec3ff60f.png)

**Comment by rraustad** [comment]
Ah, this is a unique schedule where value= 1 prior to hour Aug 3, 15:00 and 0 thereafter.

So at hour 24 during daylight savings time, HourOfDay (24) + DSTIndicator (1) = 25

        WhichHour = HourOfDay + DSTIndicator;

which goes to the elseif and hour of day is now 1 (25-24) so it's looking at hour 1 (which is a schedule value of 1). This assumes that this schedule is used for the next day (i.e., hr 25 = hour 1 of next day). However, DaySchedulePointer (42) is only used on Aug 3. Prior to Aug 3 it's DaySchedulePointer = 51 and after Aug 3 it's DaySchedulePointer = 55.

```
            if (WhichHour <= 24) {
                Schedule(ScheduleIndex).CurrentValue = DaySchedule(DaySchedulePointer).TSValue(TimeStep, WhichHour);
            } else if (TimeStep <= NumOfTimeStepInHour) {
                Schedule(ScheduleIndex).CurrentValue = DaySchedule(DaySchedulePointer).TSValue(TimeStep, WhichHour - 24);
            } else {
                Schedule(ScheduleIndex).CurrentValue = DaySchedule(DaySchedulePointer).TSValue(NumOfTimeStepInHour, WhichHour - 24);
            }
``` 

So the code should have looked at hr = 1 of DaySchedulePointer(55).

![image](https://user-images.githubusercontent.com/5778156/63215564-6fb2fe00-c0f6-11e9-8de5-9bef55461852.png)


After making a correction:

![image](https://user-images.githubusercontent.com/5778156/63215554-4e521200-c0f6-11e9-9db6-9d71088add9d.png)
