### ISSUE TITLE
Ground HX crash problem introduced recently?

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5203]
Defect files from 4972, PlantModel6 and PlantModel6-CondenserLoop crash with an array bounds error.  The files may have been transitioned badly, but they ran in v8.3.3 and crash now.

**Comment by Myoldmopar** [comment]
When running the PlantModel6 file in release version 8.3.0, it throws this warning:

```
   ** Warning ** GroundHeatExchanger:Vertical="VERTICAL GHE JL2015", invalid value in field.
   **   ~~~   ** ...Maximum Length of Simulation less than RunPeriod Request
   **   ~~~   ** Requested input=0 will be set to 1
```

Looking at the input, I see this:

```
    0.0254,                  !- Pipe Thickness {m}
    0.00243,                 !- Maximum Length of Simulation
    5,                       !- G-Function Reference Ratio {dimensionless}
```

Which is obviously wrong.  This is the problem with the idf. But it isn't due to the transition utility itself.  I took an 8.2.0 file `GSHP-GLHE.idf` and ran it through the release 8.2.0 - 8.3.0 transition utility, and it comes out with a proper maximum length of simulation.

```
    2.41285E-03,             !- Pipe Thickness {m}
    2,                       !- Maximum Length of Simulation
    0.0005,                  !- G-Function Reference Ratio {dimensionless}
```

This doesn't explain the recent change to a hard crash, but it does verify it isn't the transition utility itself.

**Comment by Myoldmopar** [comment]
@energyarchmage can you confirm whether this has **anything** to do with transition? I transitioned that file above using release utilities and it worked perfectly. I think maybe that file might have been transitioned within a release cycle or something. I don't know, but I _couldn't_ reproduce that.

**Comment by mitchute** [comment]
@Myoldmopar I just ran this through IDFVersionUpdater using fresh transition builds from my machine, however, I am seeing the error. The only changes to the GHX:Vert object I see was adding `{years}` to the max length sim comment. Should there be more than this? Is there more that I need to do other than build the Fortran files and use them with IDFVersionUpdater and the correct IDDs?

I'm seeing the fatal error [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/GroundHeatExchangers.cc#L1033) because `prevTimeSteps` is not initialized. I haven't tracked down what would be causing this now.

**Comment by mitchute** [comment]
@Myoldmopar @mjwitte @EnergyArchmage Scratch what I just said.

I tracked the problem back to [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/GroundHeatExchangers.cc#L1452) and [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/GroundHeatExchangers.cc#L1452). These numbers are not matching with the fields in the IDF. 

Looking at the IDF again, the design flow rate = 0.000303 field is duplicated, which corresponds to the max flow rate field that was removed previously. You can also tell that something is off in the transition because the ln(t/ts) - GFunction pair comments are not balanced.

I'm not sure if this is really a transition issue, or if I just missed something transitioning the file.

**Comment by Myoldmopar** [comment]
@mmatts @EnergyArchmage @mjwitte 

So I took the 8.2 GSHP-GLHE file, transitioned it up with the release version of Transition 8.2-8.3, and ran it with 8.3.  No error.  I think something went awry with the transition of that defect file.

Can you recommend some idd \minimum or \maximum; or some protection in the code, that would keep it from hard crashing due to bad input?  It's a little difficult because they are a bunch of real-value inputs in a row, so it's hard to say they are out of order or anything.  Since the g-function array is allocated based on the number of inputs, maybe we could enforce that it is an integer? Maybe that would be a clue something went wrong with the inputs?

**Comment by mjwitte** [comment]
Seems better to find how it got to using prevTimeStep before it was initialized than to try to infer something from input values.

**Comment by mitchute** [comment]
@Myoldmopar yes, I can take a look at that.

@mjwitte it was uninitialized because the IDD was offset by one with the "max flow rate" field which was eliminated previously. That caused it to look at the 0.0245 number for allocating the arrays, instead of the next field which is where it was supposed to be looking. I will take a look again at what went wrong with transition on that file and look at adding some error catches to the code.

**Comment by EnergyArchmage** [comment]
I'd guess that defect file was not properly transitioned.  This was from a user and maybe they hadn't fully updated their input file creation system for Ver8.3.  One could speculate that because the file actually ran without complaining they might not noticed the input change.   

In the IDD, I would at least increase this minimum from >0 to 1.0, since that is implied by the \required-field in the first pair. 

  N15,  \field Number of Data Pairs of the G Function
        \required-field
        \minimum> 0.0
 should be
        \minimum 1.0

That would have caught this one, and may be enough to trap this bad input file ( if you want to be sneaky). 

I think you could do a check that the total number of numbers returned from get input is consistent with the value in N15.   GIven that you have 15 numbers up to and including N15, then the value in 15 tells you what you need to know how long the object should be.  The NumNumbers returned should be 15 + N15 \* 2, and if it isn't then throw a warning, maybe even fatal.

**Comment by mitchute** [comment]
@mjwitte @Myoldmopar @EnergyArchmage 

I agree that something was already wrong with the file, which is probably why transition didn't work. I verified that 8.2 and 8.3 files transition up correctly.

This pull request should address the issues we had. Let me know if you have any issues during review.

**Comment by mjwitte** [comment]
OK.  Thanks for the much ado about nothing.  It will be more robust now.
