### ISSUE TITLE
Warning about <6 surfaces in a zone should be changed to <5 or even eliminated

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5261]
Helpdesk ticket 10857
*\* Warning *\* GetSurfaceData: The total number of floors, walls, roofs and
internal mass surfaces in Zone ZONE 8
*\* ~~~ *\* is < 6. This may cause an inaccurate zone heat balance
calculation"

There are many 5 surface zone configurations that are valid enclosures.  One could even have 4 triangles to enclose a zone.  In theory a single-surface zone should be fine, but this warning was introduced to protect against bad interior radiant exchange (if I remember correctly).

**Comment by mjwitte** [comment]
May need to create a defect file - not sure if any example files have a simple attic zone with gable roofs that would have only five surfaces.

**Comment by EnergyArchmage** [comment]
I support eliminating this warning.  The only context it makes sense is if one is assuming that all zones are a six-sided box.

**Comment by RKStrand** [comment]
@mjwitte @EnergyArchmage Ok, so I am looking at this now and see three potential approaches.  One would be to just delete the check and not worry about it.  Another would be to simply reduce the number to 4 as Mike points out that a four surface zone is possible in theory. A final approach would be to simply check to make sure that there is at least ONE surface in the zone and severe out if that is violated since without a surface there is no zone.
What do you all think?  I'm happy to implement any of those solutions or another one that is reasonable.

**Comment by mjwitte** [comment]
@RKStrand Since the zone air mass is really the "zone", one could argue that a zone with no surfaces could also be valid, but it would be useful to have a warning if a zone has zero surfaces.

**Comment by mjwitte** [comment]
@RKStrand But I haven't tried a zone like that - there may be other places that quit with zero surfaces.

**Comment by RKStrand** [comment]
@mjwitte @EnergyArchmage Mike, you are absolutely right.  The zone is actually the air and not the surfaces (pardon me while I work out a few cobwebs in my brain...).  In fact, not too much removed from the error message in question, there is a condition that checks for a zero surface zone--it accepts it as valid and moves on.  So, yes, a zero surface zone is ok by design.  What's your vote for modifying this code to address the "bug"?

**Comment by EnergyArchmage** [comment]
I am fine with deleting the check and not worrying about it.  The check is too crude for its purpose, you could have 6 surfaces all in the same plane and have a lousy IR setup. 

I think the deeper reason for the <6 check is that the simplistic method for determining IR view factors becomes less and less like to do an okay job as the zone becomes less enclosed.  Maybe there could be some more sophisticated checks on the resulting view factor matrix and some warning to replace this one.  But if the zone has few or no surfaces then the user probably doesn't care about thermal radiation anyway.

**Comment by JasonGlazer** [comment]
I don't think the purpose of the warning is to imply that zones with fewer surfaces are not allowed but instead to tell people that have put together an IDF file in haste that they missed attaching the surfaces to the proper zone. I guess I see it as more of a way to remind the 99% of people that were intending to have a zone with six surfaces that something is wrong rather than tell the 1% of people that were intentionally putting together a four or five surface zone that there is a problem. Maybe it just needs to be reworded to be something like "Typically zones have at least six surfaces associated with them but zone X does not."

**Comment by RKStrand** [comment]
@JasonGlazer That seems like a pretty reasonable approach to me.  It could also be reworded to give the user some idea of what the consequences might be beyond the "inaccuracies".  It's really not known what the exact implication will be, but telling the user via a warning that their zone has a potential "hole" in it isn't all that bad of an idea.
@mjwitte @EnergyArchmage What do you think?

**Comment by mjwitte** [comment]
I would only be open to that if it's active with displayextrawarnings, otherwise it should be silent.

**Comment by EnergyArchmage** [comment]
sounds like lipstick on yet-another-superflous warning. The orginal ticket here did have a valid enclosure with 5 surfaces and it should be silent. A peaked attic if I recall and is totally expected. 

I think the view factor matrix could be analyzed to determine if there is a hole that is so bad the IR scene is suspect and that could/should trigger a warning (but still continue).  I realize that would take some serious engineering and algorithm development and may be out of scope.  Again, the problem is the <6 surface check is not good enough to be used to issue a warning about accuracy.

**Comment by RKStrand** [comment]
@EnergyArchmage @mjwitte @JasonGlazer I agree with Brent.  The real issue is whether a "hole" in the definition is going to cause a problem with IR calculations and the <6 check is not sufficient for this.  Any serious engineering/algorithm would be beyond the scope of a bug fix (especially a low complexity bug fix as this is currently labeled).  I will do some looking at the code to see what I can find and report back here.

**Comment by RKStrand** [comment]
@mjwitte @EnergyArchmage @JasonGlazer Ok, so here is what I found out with a quick review of the code.  There is already a check in the internal radiation routines for a minimum number of surface enclosures.  Here is the warning for the check that is made:

ShowWarningError( "Surfaces in Zone=\"" + Zone( ZoneNum ).Name + "\" do not define an enclosure." );
ShowContinueError( "Number of surfaces <= 3, view factors are set to force reciprocity." );

So, anything less than a four surface enclosure should result in this warning because an enclosure is not possible with only 3 or fewer flat surfaces.

My proposal: eliminate the <6 check completely and leave the <=3 check with some improved language so that the user who is not familiar with "reciprocity" has a little better idea what the "issue" is and what the result might be.

What do you all say?

**Comment by RKStrand** [comment]
@EnergyArchmage I'm not sure there is much to do beyond what the current IR code does.  It does its best to apply reciprocity and completeness and then moves on.  I guess the only other possible things would be to perhaps have a special case for 3 or fewer surfaces to manually do something different in an attempt to enforce reciprocity and completeness.  However, I'm not sure how much value there is in such an additional algorithm or how many people would be interested in that.

**Comment by mjwitte** [comment]
> My proposal: eliminate the <6 check completely and leave the <=3 check with some improved language so that the user who is not familiar with "reciprocity" has a little better idea what the "issue" is and what the result might be.

:+1:

**Comment by mjwitte** [comment]
Close via #5716

**Comment by mjwitte** [comment]
Closed via #5716
