### ISSUE TITLE
Outdoor Air Summary report improvements

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5298]
Helpdesk ticket 10907 (and others)
Users often find it difficult to compare the outdoor air delivered for proposed vs baseline simulations.  The logical place to look is the Outdoor Air Summary Report and the component sizing report.

The component sizing report shows the minimum outdoor air flow rates for Controller:OutdoorAir objects that have autosized OA flow rates, but there is no building total.  But this would only cover air handlers, not zone equipment.  OA flow rates show up in some other tables as well, but again, no building totals.

The Outdoor Air Summary report has average and minimum OA flow rates during occupied hours listed by zone, reported as ACH.  I would be helpful to add flow in CFM or m3/s to these tables, and to add a total row for the entire building.

Economizers can cloud the issue as well.  Is it useful to report what the minimum flows would be if the economizer was not operating?

Before tackling this, some users and LEED reviewers should be consulted to find out exactly what type of output would be useful for showing that the "two alternatives are delivering the same amount of outside air".

**Comment by mjwitte** [comment]
@JasonGlazer It may be too late to tackle this one before the feature freeze, but even a partial addition of OA volume flow rates at standard density with a total row might be helpful at this point.  Or perhaps we build a custom monthly table as a starting point.

**Comment by anchapin** [comment]
Any updates on this issue? This would be very helpful for LEED Reviewers. The total minimum OA for the building needs to be compared between the Baseline and Proposed Case models.

**Comment by EnergyArchmage** [comment]
Another improvement here is that the Controller:OutdoorAir component sizing summary only shows values if the min/mas were autosized.  If the user enters a hard value the table is empty.   The hard value should be reported as well when not autosized

**Comment by anchapin** [comment]
I would suggest including design (not including the economizer mode where OA may equal SA) and minimum (to check that area ventilation requirement is modeled correctly if DCV is included) occupied ventilation by system (both zone level and air handlers) and a total for the building in the Outdoor Air Summary report. Alternatively, if it would make more sense, this information could be included in a new report. You could label the new report as ASHRAE 62 Ventilation Summary, Mechanical Ventilation Summary, etc. I used to be a LEED Reviewer and this information would have been very helpful to me.

**Comment by jmarrec** [comment]
Thinking about tabular reports (hence forgetting about tables of hour versus month (weekends v weekends too) showing OA numbers), I would say that two metrics would be useful:

* total outdoor air volume (m3) for the run period, per zone and building
* total outdoor air volume when economizer is off*

That would help see whether the deviation in absolute numbers are off because of economizer or not.
It would require setting a new output variable to keep track of OA only when econ isn't running, so annoying and probably tedious but doable.

*It does somewhat follow what @mjwitte said on the issue itself, with a slight difference, Mike's solution of tracking OA if econ wasn't running is probably harder to implement

Quick two cents really...
