### ISSUE TITLE
Swimming pool - unrealistic volume of makeup water

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5382]
Helpdesk ticket 10943
From user: (have not verified this, defect files added to devsupport)
The makeup water per month is around 37635677 m3 (KL) per month and i'm simulating only one 25m pool.
I have attached the excel sheet. I have audited several aquatic centres (most of them have at least three pools) and they have an average water usage of 2000 -4000 KL (m3) per month.I think that there might be some conversion or decimal errors.

**Comment by mitchute** [comment]
@mjwitte It looks like the bug is here: https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SwimmingPool.cc#L1318-L1332

Should be dividing by `Density` to get kg and kg/s. Correcting that gets the numbers down in a range consistent with user expectations.

Fix here: 9894facadb9e1ca03ab1fe8df3fe531e33f03427

**Comment by mjwitte** [comment]
@mitchute Of course.  Two of us reviewed those functions at the time they went in and didn't see the inversion.

**Comment by Myoldmopar** [comment]
Closed via #5474
