### ISSUE TITLE
Construction:InternalSource Tube Spacing should be half of distance between tubes in 2D model

### ISSUE THREAD

**Issue by sebastienbrideau** [NREL/EnergyPlus#5429]
I had found this a while back and discussed with Rick Strand.  He said that he'd let the development team know but I think that it may have fallen through the cracks.

The 2D LowTemperatureRadiant model uses symmetry around the tube axis and halfway between the tubes (so that only half of the distance between the tubes is modelled).

I discuss this in a paper here
http://www.tandfonline.com/doi/abs/10.1080/19401493.2015.1027065

This is explained in the code: DataHeatBalance.hh line 1035-1037
ThicknessPerpend is defined.

But then, in HeatBalanceManager.cc line 3856, the value given to ThicknessPerpend is not divided by two (it's taken straight from the IDF file which states "tube spacing").

Either, the tube spacing in the IDF editor should be redefined as half of the tube spacing, or the code should be modified so that ThicknessPerpend is divided by two.

I'm not familiar with C++, or github and I am not an advanced E+ user, so I would appreciate if someone would verify this.

Cheers

**Comment by mitchute** [comment]
@mjwitte @Myoldmopar I reviewed the CTF and LowTempRadiant source and did not find anything to account for the `ThicknessPerpend` variable needing to be half of the tube spacing. 538e5e73219ac809f07b610a91487c95fec54b37 corrects this. Let me know if you have other ideas or want to discuss it further.

**Comment by mjwitte** [comment]
@RKStrand ?

**Comment by RKStrand** [comment]
Looks like a reasonable fix to me.  It's basically what I would have done had I gotten to it first.

**Comment by mitchute** [comment]
@RKStrand @mjwitte  do you have any suggestion on testing, or do we just accept the diffs for something like this?
@Myoldmopar what sort of unit test do you want on this?

**Comment by RKStrand** [comment]
@mitchute @mjwitte What I would suggest is to run whatever tests you are doing by comparing what the old version did with the new version.  So, in the corrected version, you are taking the width and dividing by 2 to correct the fact that its half the distance between the pipes not the pipe separation that is used for the calculation.  Run any cases with the old version using twice the width and then compare to the new version of E+ with the correct width.  They should hopefully give you the same result as I think that is the only thing that E+ uses this pipe spacing term for.  You could also run the new version of E+ with both cases to see how far off things were just out of curiosity.  The reality is we won't know what the diffs would be so that is why I think we have to simply verify the correction.  Hope this helps.

**Comment by mitchute** [comment]
@RKStrand adjusting the width to account for the previous pipe spacing error yields identical results, as expected. Testing the changes locally, from the meter files I am seeing about an 8% decrease in plant electricity use `Electricity:Plant [J]` for design day runs. Over an annual simulation it averages out to around a 6% decrease. This is for `RadLoTempHydrHeatCool2D.idf`

**Comment by RKStrand** [comment]
@mitchute If the results are identical after accounting for the spacing error, then that's probably a pretty good indication that the fix is fine.  One other thing you could potentially test if you wanted to take it a step further.  Look at three cases: 1-D, 2-D with the error, 2-D after the correction.  Look at the temperature internal to the source (or the water loop temperature out of the slab).  Compare the three to see if the trend makes sense.  Is the design day difference only in cooling or in heating as well?  I was of the impression that heating should not be affected all that much by the 2-D because boiler performance isn't affected by water loop temperature, or so I thought.  In any case, the fact that you are getting identical results with the test you ran should pretty much verify that the fix is correct--the rest of my comment here is if you want to go one step further and is probably more of "academic" interest.  Thanks for looking at this and correcting it!

**Comment by mitchute** [comment]
@RKStrand it looks like the design day differences are in heating only. Heating shows about an 8% decrease, while cooling shows less that a 1% increase.

A few comparison plots for `RadLoTempHydrHeatCool2D.idf`` for 1D and 2D w/wo the error.

![east_jan](https://cloud.githubusercontent.com/assets/2985979/12827695/82b737d6-cb46-11e5-9d51-5016b58cf245.png)

![east_july](https://cloud.githubusercontent.com/assets/2985979/12827853/584fbd5a-cb47-11e5-949d-9bf68b3fba6a.png)

Is it correct that when the flow is off, the outlet temps go to the cooling and heating water setpoints (10 deg C and 60 deg C, respectively)? Heating and cooling energy go to 0 during no-flow, so maybe it doesn't matter.

**Comment by RKStrand** [comment]
@mitchute The trend that the heating design day is displaying matches the trend that I would expect to see.  Unfortunately, the cooling design day trend is difficult to determine because of the condensation controls which appear to be shutting the system off.  As a result, the outlet temperature and flow rates are bouncing around in a manner that is difficult to decipher.  The way to get around that and get a good, discernible trend is to turn the condensation controls to OFF rather than letting them default to SimpleOff.  OFF will keep the radiant system running no matter what condensation is predicted.

To answer your questions, yes, when the flow is off, the outlet temperatures will be determined by the inlet temperatures (simply passed through).  And yes, since there is no flow, the energy is zero so it doesn't really matter what the temperature is, but the outlet gets set to the inlet to avoid any confusion (hopefully).

**Comment by mitchute** [comment]
@RKStrand Here is the first week in July with condensation set to OFF.
![east_july](https://cloud.githubusercontent.com/assets/2985979/12858521/3c5045be-cc16-11e5-89d8-d620fc9b113c.png)

**Comment by RKStrand** [comment]
@mitchute Thanks for running that case and posting the data for the first week of July.  I think in general the trends are pretty believable and in line with what might be expected when correcting this error.  It's not perfect in part because the system is not turning on at the same time across the three different cases.  However, I think there is enough evidence here to say that the correction made is appropriate and is producing believable results.  I don't see anything that would prevent this from moving forward as a valid fix.

**Comment by mitchute** [comment]
@RKStrand thanks for taking the time to review this!

@Myoldmopar let me know if you want a unit test.

**Comment by Myoldmopar** [comment]
Closed by #5470
