### ISSUE TITLE
Dual unit reporting in html

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#5435]
OpenStudio would benefit from having dual unit output in E+, https://github.com/NREL/OpenStudio/issues/2039#issuecomment-174350980

Is it possible to have E+ write html files in both SI and IP units and have the SQL file output in SI units?  One option is to allow the user to specify separate units for the html and SQL reports.  Another option is to always write the html in SI and in IP.  How hard is this to implement?

**Comment by macumber** [comment]
@mbadams5 @kbenne

**Comment by macumber** [comment]
Also, I know there are a bunch of other output files, I think users are mainly interested in getting the html file in IP units, OpenStudio only really cares that the SQL file is in SI units.

**Comment by mjwitte** [comment]
@JasonGlazer Would it be straightforward to decouple the html and SQL output units?  e.g.  html in IP with SQL in SI.

**Comment by JasonGlazer** [comment]
It would not be easy because the SQL output is a call near the end of each routine that generates the tables and at that point the unit conversions have all be done. I think the cleanest approach might be to call all the routines that generate the tables twice once with IP and once with SI and we would need to add some logic to each one to write out only the HTML (and other text formats) or the SQL output.

**Comment by shorowit** [comment]
The above PR was merged, which suggests this was addressed. Please reopen if I am mistaken.

**Comment by JasonGlazer** [comment]
@shorowit I think you are right.
