### ISSUE TITLE
Follow-up for Electric Service Refactor Merge

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5499]
We merged in the electric service refactor branch (#5437) somewhat abruptly because of the IO freeze and the many defects that the branch fixed.  @DeadParrot had some concerns about the source code changes that we didn't have a chance to address because of the freeze, but I don't want to disregard them.  

@EnergyArchmage, can you make a list of your known final issues (eng ref fixups) and @DeadParrot, can you make a list of your issues with the branch, both as comments on this issue?  We will have them addressed right away during this bug-fix period.

**Comment by EnergyArchmage** [comment]
Things left to do
- [x] Eng Reference, explain storage dispatch, etc
- [x] Another integration testfile with complex set of load centers, increase code coverage

**Comment by DeadParrot** [comment]
I don't have the overview for this code that I would need to review the higher-level design so I can only comment on some code issues/questions that arise as I look it over. Here are a few things I observed in a quick pass:
- [ ] Making constructors private is not necessary even if normal instantiation is via a factory: I wouldn't bother with private unless non-factory instantiation is somehow intrinsically broken.
- [ ] If default and copy (and inconsistently move) constructors are private why are some string argument constructors public?
- [ ] The string argument constructors don't use member initialization syntax but they should.
- [ ] There are string and vector arguments passed by value, which is almost certainly a performance bug in this context.
- [ ] Passing the Nmb and OneNmb vectors to rainflow by value looks like a bug: they are set but not used internally and nothing is returned. How does this pass a unit test?
- [ ] Private data members should have some name decoration, like `widget_`, so that accessors can be added later, like `widget()`.
- [ ] Non-POD types are default constructed automatically so skip constructor initializations like `name( "" ),`.
- [ ] Default constructors are inline but probably don't need to be for performance reasons.
- [ ] Remove commented out argument array dimensioning code.
- [ ] Not a big fan of the `this->` everywhere inside classes but I know @Myoldmopar likes this so it is probably time to make a code guideline choice on, well, this (sorry!).

If we arrange it with @lgentile I can do a proper review and work with @EnergyArchmage to make sure I understand all the intent and that he understands the reasons for the code suggestions.

**Comment by EnergyArchmage** [comment]
I am certainly open to a proper review and such to improve the C++.  I’ll need some more specific information as to how exactly to alter code to address these comments.  I believe @lgentile will support this work.
The overview here is that I was tasked to add some features and fixes for a number of issues related to this section of code.  I knew I would have to recode a lot of it so decided to do a pass at refactoring to be more OO, but ended up doing way more than planned.  This refactor is well out ahead of the design policy and decisions that need to be made.  One sort of nice aspect is that the electric power service system modeling is a much smaller subsystem than others inside EnergyPlus and might provide a relatively approachable opportunity to design how the OO hierarchy should be handled.  
The transformer and kinetic battery models were not originally my implementations and it was not in scope to completely rewrite these models.   I do not know much about them. 

Here is a crude sketch of the objects and relationships.  There are no base classes or virtual classes.  

![oodiagrams](https://cloud.githubusercontent.com/assets/8754769/13300405/21ab4ee8-dafd-11e5-816d-fc5ae89d34f0.png)

**Comment by DeadParrot** [comment]
@EnergyArchmage OK, I'll try to get the OK to work with you on this since no one else is jumping in. While we wait to get started maybe look at my items, esp. the bug?, and make any relevant changes or note your questions. We'll probably want to do a call to give me the background for this after I read the relevant md files.

**Comment by EnergyArchmage** [comment]
these items have been address in PR https://github.com/NREL/EnergyPlus/pull/5512

Ready for review ( @DeadParrot )

**Comment by Myoldmopar** [comment]
Closed via #5512
