### ISSUE TITLE
Update Packaging

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5579]
Need to consider alternatives to PackageMaker, and maybe NSIS?

This looks promising on Mac: http://s.sudre.free.fr/Software/Packages/about.html

Not sure on Windows.  Maybe NSIS is still fine, but worth a look.

On Linux, I don't see why the shell script installer should be replaced.  I like it.

**Comment by jmarrec** [comment]
My two cents: on Linux, while the shell script does works fine for installing and uninstalling (it puts `uninstall.sh` in the installation folder), I'd like a `.deb` package better, because I could `sudo apt install Energyplus.deb` and it would therefore be handled like the rest of my packages (I could search for it in my apt list, do apt remove, etc)

**Comment by jmarrec** [comment]
QtIFW is implement for all 3 plaftorms now.
