### ISSUE TITLE
EAp2-4/5. Performance Rating Method Compliance Table grouped Receptacle Loads

### ISSUE THREAD

**Issue by ecoeficiente** [NREL/EnergyPlus#5599]
## Issue overview

In _Output:Table:SummaryReports_, _EAp2-4/5. Performance Rating Method Compliance_ table, Receptacle Equipment includes unregulated loads (at least this happens with _Fans-Parking Garaje_, have not checked the rest). However, in _LEED Minimum Energy Performance Calculator_ excel (the one to be filled for a submittal), receptacle equipment is separated from other end-uses such as _Fans-Parking Garaje_.

Solution: In that table, _Receptacle Equipment_ should substract other end-uses if they exist (_Fans-Parking Garaje_, _Cooking_, etc) and Total line should sum up all the lines (now it only accounts for receptacle equipment, not to double count other end-uses).

**Comment by JasonGlazer** [comment]
I believe this was addressed already in #5580 which will be part of the next release. @ecoeficiente if you have a test file that shows the problem, you can send it to me at jglazer at gard dot com and I will test it with the fixed version. Otherwise, you could download and compile the latest code and try it yourself it you want. I am closing the issue. If you find that it is not been fixed, please reopen it.
