### ISSUE TITLE
User file trips on new fan coil control warnings "Cold Water control failed in fan coil unit"

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5612]
## Issue overview

User post:
I've transitioned an IDF from Energyplus V 8.4 to V 8.5 and I now receive a large number of warnings from the 5 fan coil units located on ground floor of the building. The warnings are as below

```
** Warning ** Cold Water control failed in fan coil unit FCU_G1A_G1B FAN COIL
** ~~~ ** Iteration limit exceeded in calculating water flow rate 
** ~~~ ** ..Water flow rate set to last iteration value 
```

The files are identical other than the version. I'd like to understand what's causing the warnings.

MJW Notes:
The overall results for energy use and thermostat setpoint not met are nearly identical, so that's good.
So why are these warnings tripping?  Is it something about this file, or something wrong in the control algorithm?
### Details

Some additional details for this issue (if relevant):
- Win64
- EnergyPlus 8.5.0
- Helpdesk ticket 11247
- These warnings were added as part of the fan coil unit control upgrades in #5539 
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
@DeadParrot [This](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5612) V8.5 defect file asserts in DataSurfaces at line 578. Can you have a look? Why does this file run in V8.5, with surface errors that don't seem horrible, yet stops in the debugger? What does it mean when xb <= xbe + tol fails? Not sorted properly? What is the developer suppose to fix in the code to avoid this?

**Comment by DeadParrot** [comment]
@rraustad This assertion indicates that a surface with crossing edges is probably present. The simplest example of that would be a rectangle where you twist one end by 180 degrees and end up with an hourglass shape. You could add a debug print statement to find out which surface is to blame if it isn't clear.

This should really be caught upstream of the assertion test with an "always on" runtime (not assert) test and the intent was that I would make this and some other upgrades to the surface geometry checks since we have other exposures, but I don't currently have a task for this work. The new `PierceSurface` function uses this Surface2D construct for high performance nonconvex and many-vertex surface support and the algorithm depends on surfaces not having edge crossings: @mjwitte assured me that such surfaces are not allowed in EnergyPlus although we haven't previously caught them.

I hope that is helpful. If you find no screwy surfaces in the case let me know -- we can relax the assertion tolerances if necessary although that will let more bad ones through.

**Comment by rraustad** [comment]
The warning is tripped because the load is very small. The non-linearity of the coil model means that RegulaFalsi makes an initial guess that is somewhat far from the solution and takes small steps to get there. The fix is to use tighter bounds to zoom in on the capacity vs flow curve. It took 1 iteration once the limits were tightened. 
PT #119934203

**Comment by rraustad** [comment]
PR https://github.com/NREL/EnergyPlus/pull/5671

**Comment by mjwitte** [comment]
Close via #5671
