### ISSUE TITLE
HeatExchanger:FluidToFluid won't allow Chiller to run if min delta-T is above zero

### ISSUE THREAD

**Issue by asparke2** [NREL/EnergyPlus#5626]
## Issue overview

See [this unmet hours post](https://unmethours.com/question/14619/waterside-economizer-integrated-with-chiller-min-temperature-difference-not-zero/).  If you have a non-integrated waterside economizer (in parallel with the chiller), and you set the `Minimum Temperature Difference to Activate Heat Exchanger` in the `HeatExchanger:FluidToFluid` to anything above zero the chiller won't run and eventually the plant loop temp will rise to the point that the simulation fails.  I ran into the same issue in this very simplified plant-only model [ws_econ_non_integrated.idf.txt](https://github.com/NREL/EnergyPlus/files/232643/ws_econ_non_integrated.idf.txt).  If you set the field back to zero it runs as expected.
### Details
- E+ 8.5

defect file at 

https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/5000s/5626/5626_ws_econ_defect.idf

**Comment by chandangsharma** [comment]
My two cents while running into same issue with water side economizer. In _PlantCondLoopOperation.cc_, EnergyPlus only looks for (`Tsensor < TinLowLimit`) to decide whether chiller should be off for free cooling. It doesn't take into account temperature tolerance input in "HeatExchanger:FluidToFluid" object. While in _PlantHeatExchangerFluidToFluid.cc_, `TempControlTol` is also taken in to account. There can't seem to be any workaround for this problem.

After making following changes in source code, the results seem to make much more sense now. I couldn't run the test suite but these changes are expected to throw diffs.

InitFluidHeatExchanger
`PlantLoop( LoopNum2 ).LoopSide( LoopSideNum ).Branch( BranchNum ).Comp( LoopCompNum ).FreeCoolCntrlMinCntrlTemp = Node( FluidHX( CompNum ).SetPointNodeNum ).TempSetPoint - FluidHX(CompNum).TempControlTol;`

ControlFluidHeatExchanger

```
If (!ChillerShutDown)
   Supply and demand side mass flow rates are set to max values
   SetComponentFlowRate
else
   if (DeltaTCooling > FluidHX(CompNum).TempControlTol) {
      Supply and demand side mass flow rates are set to max values
      SetComponentFlowRate
   else
      Supply and demand side mass flow rates are set to zero
      SetComponentFlowRate
   endif
endif
```

**Comment by EnergyArchmage** [comment]
I agree with Chandan here, code changes pushed to this branch

https://github.com/NREL/EnergyPlus/tree/5626-Plant-HX-min-DT

**Comment by EnergyArchmage** [comment]
see pull request #5834

**Comment by EnergyArchmage** [comment]
There seems to be some confusion over of "Integrated" vs "Non-integrated."  This issue's description describes a non-integrated economizer while using CoolingSetpointOnOffWithComponentOverride.  The control mode CoolingSetpointOnOffWithComponentOverride is intended for "Integrated." ( This is replicating old HeatExchanger:Hydronic.)  The "ComponentOverride" means able to shut down the chiller and is the thing that is integrated in the modeling.  (Any of the various other HX control schemes for cooling would be used for non-integrated water side economizer, and the machines not in parallel). 

 The historical behavior was that either the chiller or the HX would run, but not both.  With the devices in parallel, the flow would either go through the chiller or the HX, but not split flow between the two when both machines request flow. The on/off control of the HX is always sloppy wrt setpoint control.   

So separate from the min delta T issue (for which @Chandangsharma suggestion seems excellent) , there is a question of what the behavior of an integrated water side economizer should be.  

@Chandangsharma suggested logic block allows both the chiller and economizer to run at the same time, when conditions are such that the chiller is not quite shut down but the HX can do some beneficial cooling.  The  [unmet hours post](https://unmethours.com/question/14619/waterside-economizer-integrated-with-chiller-min-temperature-difference-not-zero/)  also indicates an expectation that the integrated economizer run along with the chiller.   Although this may save some energy, it doesn't work all that well because the load dispatch doesn't know about both devices and usually misses the chilled water setpoint (at least in the example file FreeCoolingChiller which is showing diffs that need to be explained).  

So I am having trouble deciding what to do...  Should CoolingSetpointOnOffWithComponentOverride behavior be changed to allow both to run at the same time as part of this issue?

**Comment by mjwitte** [comment]
Closed via #5834

**Comment by aaron-boranian** [comment]
Water-to-water heat exchanger should be allowed to be on plant demand side

Water-to-water heat exchanger should be allowed to be on plant demand side. We tried to user this object to model water-cooled economizer with primary-secondary loop. Because the water-to-water heat exchanger currently can only be on the supply size, the inlet temperature is low and cannot capture the savings when the water-side economizer is on the demand side.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/14843427)

**Comment by mdahlhausen** [comment]
@asparke2 @mjwitte @EnergyArchmage 
I'm running into this issue again in EnergyPlus 9.1 with both an integrated (in series with chiller, HX before pump on chilled water loop) and non-integrated economizer (in parallel with chiller, HX on its own supply branch).

In the integrated case, the chiller will not run if the minimum delta-T is above zero.
In the non-integrated case, the HX will not run if the minimum delta-T is above zero.

I suggest re-opening this issue.  I can provide example .osm or .idf files as necessary.
