### ISSUE TITLE
Site:WaterMainsTemperature Default

### ISSUE THREAD

**Issue by matthew-larson** [NREL/EnergyPlus#5675]
## Issue overview

Based on the Engineering Reference, 'If there is no Site:WaterMainsTemperature object in the input file, a default constant value of 10 C is assumed.'  I have found that the actual calculated profile for the water mains temperature is significantly higher for the majority of climates, resulting in an overestimate of domestic hot water use if no Site:WaterMainsTemperature object is in the input file.  The graph below shows the water mains temperature profile for the Chicago-O’Hare TMY2 weather file, which many of the Reference Buildings and Example Files are based on.  I recommend adjusting the default value to somewhere closer to 12 C, or the average water mains temperature based on the profile for the Chicago-O’Hare TMY2 weather file, when no Site:WaterMainsTemperature object is in the input file to better reflect the majority of climates.

![water_mains](https://cloud.githubusercontent.com/assets/17144687/15436142/9d2e7478-1e7d-11e6-93a6-43747ab7a1a6.png)

**Comment by shorowit** [comment]
EnergyPlus implements a good correlation method that provides varying mains temperatures throughout the year. Unfortunately, it requires the user to do some calculations based on the weather file in order to provide the appropriate inputs to EnergyPlus. It'd be nice if there was an "enhanced correlation" method that didn't require any inputs and operated based on the supplied weather file. That would be a much better default.

On a related note, if there is no Site:WaterMainsTemperature object, no warning is provided to the user. (As noted, a constant temperature is assumed, which is a poor assumption.) It'd be nice if a warning is provided as is done for other similar situations like this one:

> Warning: GetHTSurfaceData: Surfaces with interface to Ground found but no "Ground Temperatures" were input.
>  Found first in surface=SURFACE 1
>  Defaults, constant throughout the year of (18.0) will be used.

**Comment by mjwitte** [comment]
It should be possible to make the default automatically get the values from the weather file.  Site:GroundTemperature:FCfactorMethod already does that.

**Comment by Nigusse** [comment]
There are two separate issues here:
(1) Add autosizing option for the two numeric input fields by processing weather file:
-   N1 , \field Annual Average Outdoor Air Temperature
-   N2 ; \field Maximum Difference In Monthly Average Outdoor Air Temperatures
- the Calculation Method input field should be set to 'Correlation' when these input fields are set to autosize

(2) When 'If there is no Site:WaterMainsTemperature object in the input file, a default constant value of 10 C is assumed. There are two option how to address this issue.
 - (1) set the Calculation Method input field to 'Correlation' and autosize the two input fields
 - (2) Add a new Calculation Method key choice 'EnhancedCorrelation' (suggested by Scott Shorowit) and 
set the new calculation method as default and the two input fields will also be autosized.

I suspect the second issue will result large diffs and should be tackled may be separately after addressing the first issue. @mjwitte @shorowit @Myoldmopar your thoughts.

**Comment by mjwitte** [comment]
@Nigusse Rather than autosizing the temperature fields, I would add a new calculation option as suggested by @shorowit but name it "CorrelationFromWeatherFile". When this is selected the other two inputs are ignored rather than "autosized" or "autocalulate".  

In the eio output these values can be reported (maybe they already are) regardless of whether they were input or obtained from the epw file.

I'm ok with making CorrelationFromWeatherFile the default (even when there is no Site:WaterMainsTemperature object) even though this will cause significant diffs.  But it will fail if the simulation is run without an epw file (I know, that's not typical usage, but it is still supported) so what's the fallback if that's the case? @matthew-larson

**Comment by shorowit** [comment]
👍 to @mjwitte's suggestions.

**Comment by Myoldmopar** [comment]
Closed via #6771
