### ISSUE TITLE
Validation Report Build Problems

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5689]
- I couldn't get the validation reports to find Python3 on my Mac.  I use Python 2 by default, so my /usr/local/bin/python is 2.  I have brewed 3, so I do have a binary at /usr/local/bin/python3.  But find_package doesn't seem to want to find it.  I was able to fake it out, by letting the build process pull down the ValidationReports repo, and attempt a configure, then I went into the CMake cache file and planted the path to the python3 executable as a new entry.  It worked, but that's super hacky.  Just need to hint it to first look for python3 binaries.
- I hit a Python unhandled exception when it is trying to do some spreadsheet reading and such.  More information is available on a separate [comment](https://github.com/NREL/EnergyPlus/issues/5686#issuecomment-222166785), but in summary, there is a function called `resolve`, and it tries to do a subtraction operation between a str and a float.

**Comment by Myoldmopar** [comment]
@lefticus I don't want to assign this to you, but would love your thoughts on both matters.

**Comment by lefticus** [comment]
@Myoldmopar 

So, first comment: the validation system was only ever tested and deployed on Linux. I believe we determined that only automatically executing on one platform was necessary IIRC.
- Your best bet to be able to better control the version of python used would be to find it and pass it down to the external project here: https://github.com/NREL/EnergyPlus/blob/develop/CMakeLists.txt#L224-L235
-  It's not surprising that you had to manually install the python modules for matplotlib and such since they are only installed by the decent_ci for Linux https://github.com/lefticus/decent_ci_runner/blob/master/linux/packages.yaml#L54-L58 (see "first comment")
- Your issue with 'str' - 'int' well, that doesn't make any sense and the line number you quote implies that you aren't looking at the full debug stack: https://github.com/NREL/EnergyPlusValidationReports/blob/master/template_engine/template_engine_impl.py#L789 or something. It kind of implies to me that something when wrong in generating the CSV inputs for the validation docs. Maybe something changed in EnergyPlus to cause this? I don't know. Without the full debug stack (and a double check to make sure this is _not_ an issue on Linux and somehow isolated to a different version of a python module on MacOS)... (See "first comment" above, again)

**Comment by jmarrec** [comment]
@Myoldmopar Is this still a thing?

The wiki for windows [here](https://github.com/NREL/EnergyPlus/wiki/BuildingEnergyPlus#windows) mentions

> Install the latest Python 2 release. Python 3 may not work with all of the build scripts

In my experience that doesn't appear true, everything appears to work with python 3 (but I may not have tested 100% of the build options and therefore supporting scripts). According to your issue here, it seems some scripts may only work with Python 3.

Worth noting that if you use a recent enough CMake (released in the last 8 months after [this merge](https://gitlab.kitware.com/cmake/cmake/merge_requests/1819), then it will:
* Look for Python 3 first, and fall back on python 2 if not*
* Be able to find homebrew python on mac, but also anaconda python on windows, etc

Note: *If everything works with python 3, then you could also specify that you only want Python3 in changing https://github.com/NREL/EnergyPlus/blob/develop/CMakeLists.txt#L71

**Comment by Myoldmopar** [comment]
The validation reports are now generated in a different way entirely, this is not relevant anymore.  Thanks @jmarrec
