### ISSUE TITLE
Remove jsoncpp from thirdparty

### ISSUE THREAD

**Issue by nxtruong** [NREL/EnergyPlus#5780]
## Issue overview

It seems to me that thirdparty/jsoncpp is not used anywhere in the code, and the current code in jsoncpp looks pretty outdated compared to the current jsoncpp I found on github. I would suggest removing jsoncpp from the code tree, unless there is a plan to use it in the future. In the latter case, forgive me for creating this unnecessary issue.

**Comment by Myoldmopar** [comment]
We had a [discussion](https://github.com/NREL/EnergyPlus/pull/4955) last year and decided jsoncpp was the right tool for the job.  Moving forward, we're going to be adding JSON input to EnergyPlus, so the library has undergone further scrutiny.  At the point that is pushed forward, we will either update jsoncpp to a good version, or change to a different library, removing jsoncpp so that we don't have multiple json libs.  I don't think it's necessary to keep this issue open, but thanks for bringing it up!
