### ISSUE TITLE
OA controller economizer schedule and min OA flow autosizing

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5846]
## Issue overview
1. In Controller:OutdoorAir, in PR #5794, it was originally proposed that the "Time of Day Economizer Control Schedule Name" be changed to allow any economizer type to be schedule off.  Currently, this schedule only adds TOD economizer operation on top of any other specified economizer type.  Given that several example files have a base economizer plus TOD operation, it is now proposed that a new economizer availability schedule field be added to allow the base economizer to be scheduled off as desired.
2. In Controller:OutdoorAir, the "Minimum Outdoor Air Flow Rate" field can be autosized.  It will autosize to whatever OA flow rate flows down from the relevant Sizing:System and/or Sizing:Zone objects.  The typical default usage is to set up a DesignSpecification:OutdoorAir object for each zone type with some flow/person and flow/area specified, using the "Sum" method and then reference this in Sizing:Zone.  This will autosize the "Minimum Outdoor Air Flow Rate" using the design occupancy and the zone area.  If the user then specifies a Controller:MechanicalVentilation object with DCV or an IAQ method, the autosized Minimum Outdoor Air Flow Rate value would then silently (without warning) prevent any OA flow rate less than the area flow plus per-person flow at design occupancy, thus limiting the effectiveness of the DCV control (likely preventing any DCV operation at all).  Options for improving this:
   - Check the final value of Minimum Outdoor Air Flow Rate (autosized or user-specified) against the Controller:MechanicalVentilation inputs and issue a warning if the Minimum Outdoor Air Flow Rate is too high.  But what is too high?
*New warning added in #8136*
   - Add more options to DesignSpecification:OutdoorAir or to allow different specs for the minimum OA flow rate in this situation.
   - Add more columns to the outdoor air summary table report to indicate how much OA flow would have been required by DCV vs "standard" OA flow vs economizer operation vs final. 
*Note that this will happen as part of the OA Summary Report enhancements in #7629.*
   - Other thoughts?
### Details

Some additional details for this issue (if relevant):
- Version of EnergyPlus (v8.6.0)
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lymereJ** [comment]
@mjwitte, I am working on a model where I ran into the issue you describe in 2., I have been trying to follow the comments in the pull request to see if it has been fixed in EnergyPlus 8.8.0. It appears that it hasn't, is that correct?

In my model, if I leave the "Minimum Outdoor Air Flow Rate" of the Controller:OutdoorAir to autosize, the system is always providing the OA flow sized using the VRP for heating (which results in a higher OA flow than for cooling) even when DCV is activated. If I manually set the "Minimum Outdoor Air Flow Rate" of the Controller:OutdoorAir to 0, DCV works but the flow at maximum occupancy is not based on the one calculated  using the VRP but based on the ZoneSum. My Controller:MechanicalVentilation "System Outdoor Air Method" is set to VentilationRateProcedure, same for my Sizing:System. Is that something you have noticed as well? Or, does it sound like something might be wrong with my implementation? 

Thanks.
