### ISSUE TITLE
SolarCollector:UnglazedTranspired setting exterior temp to 0 when no flow

### ISSUE THREAD

**Issue by rmcclung** [NREL/EnergyPlus#6082]
When using SolarCollectro:UnglazedTranspired to preheat out door air for an air handler, and that air handler has no OA flow (at night, for example), the Solar Collector Air temperatures are set to zero, which sets the temperature of the associated wall surface to zero instead of the outdoor air temp, which increases/decreases heat loss through the assembly.

*See #6139 for more details. The heat transfer was correct but the zero output was misleading.*

**Comment by EnergyArchmage** [comment]
The surface heat transfer should be switching to use the passive model when flow is zero.

**Comment by mjwitte** [comment]
@rmcclung Do you have a test file that shows a problem here?  There is a pending change to the code, #6139, that sets the leaving air temperature from the collector to the average ambient instead of zero when the collector is off.  But this isn't changing any surface temperatures, because the passive baffle code was already using the ambient conditions.  I just want to be sure the fix is covering everything it needs to.
(fyi, @Nigusse )

**Comment by rmcclung** [comment]
Hi Micheal,

Unfortunately, I’ve made a lot of changes to that file since, I can’t seem to reproduce the problem anymore.

Ruth

**Comment by mjwitte** [comment]
Closed via #6139
