### ISSUE TITLE
PTAC heating coil is off when there is no zone heating load and supply fan is continuous mode

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6095]
Issue overview
--------------
User has two files which both use baseboard as the primary heat source with a PTAC running second for heating.  One simulation uses hot water baseboard and a hot water heating coil in the PTAC, and it controls fairly well (not perfect, but no unmet heating hours).  The second one has electric baseboard and a gas heating coil in the PTAC.  The PTAC heating coil rarely operates and there are many unmet heating hours.  Tried swapping in an electric heating coil on one PTAC and got a similar result.

Run with Chicago Midway AP weather.  January 19, mid-day is a good example of several hours where the setpoint is not met with the gas heating PTAC.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus 8.7.0-78a111df4a
 - Helpdesk ticket number 11960

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
@mjwitte Testing shows that the HW baseboard mostly does not have enough capacity to meet the heating load, hence the PTAC kicks in to deliver the remaining heating load. On the otherhand the electric bb has enough capacity (always) to meet the heating load, hence the PTAC gas heating coils is off. Since the PTAC in both cases have a constant volume fan with continuous operating schedule, then the PTACs blow cold air to the zone that causes Heating Setpoint Not Met for the electric bb test case. I modified the electric bb test case to cycling fan and run the file, and all the Heating Setpoint Not Met went away. So, this behavior is is expected. If HW bb meets the heating load, then the HW bb and PTAC  combination would show the same behavior as the electric BB and PTAC with gas heating coil combination.  Now the question is why the HW bb does not meet the heating load? Note that both bbs use the 80.0% of their auto-sized heating capacity.

**Comment by mjwitte** [comment]
@Nigusse But the PTAC gas heating coil should have run to offset the cold ventilation air with continuous fan.  So, the alternate case is to swap the electric bb into the case with the HW PTAC coil and see if the HW coil runs as expected.  If not, then it's a more general problem with the heating coil control in the PTAC (not specific to the gas coil).

**Comment by Nigusse** [comment]
@mjwitte Ok. will test the electric bb with HW PTAC coil.

**Comment by Nigusse** [comment]
@mjwitte The electric bb with HW PTAC coil showed the same problem. Looking at the code for the PTUnit the zone load control doesn't correct for the impact of cold ventilation with continuous fan. I will make changes to the code to account for that.

**Comment by Myoldmopar** [comment]
Closed via #6120
