### ISSUE TITLE
2 speed operation with Air Economizer in UnitarySystem 

### ISSUE THREAD

**Issue by energysims** [NREL/EnergyPlus#6109]
Issue overview
--------------
Current economizer operation in unitary system with multispeed fan does not impact fan speed.  Economizer only operation is limited to low speed operation and economizer plus compressor operation is limited to low speed unless both compressors operate. Current energy codes require unitary equipment over 5 tons to have economizers with two stages of economizer only operation, first at low fan speed and then at high fan speed, and then to integrated operation.  Three of three manufacturers checked run the fan at high speed when economizer and stage one compression are operating.

### Details

This is a short term fix to better capture typical economizer operation.  

Fan speed during economizer operation.
  1) run minimum speed with economizer, if unable to meet load then,
  2) increase speed (step through speeds or ramp VSD) with economizer, if unable to meet load then,
  3) high speed fan with 100% economizer + 1 stage compressor.  If unable to meet load then,
4) high speed fan with 100% economizer + additional compressor.  In smallish equipment this last stage is typically not available except when no economizer is operating.

This operation would better align with currently available equipment though further development work in this area should be considered.  One issue impacting the above sequence is that the thermostat control is often a 2 stage cooling thermostat.  At least one manufacturer starts step 2 above when the stage 2 cooling signal is passed, and operates for a time (default 5 minutes) after which if the stage 2 cooling signal is not dropped (unlikely in that time) it turns on the compressor.  A longer term more flexible solution would likely involve the ability to specify alternate fan sequences for economizer only and integrated economizer operation.

**Comment by rraustad** [comment]
Easier said than done. Simply increasing the fan speed would not change the return path flow rate during these iteration's. Is it possible to "set" the mixer return node flow rate during this iteration procedure? Probably. Are there some restrictions to setting the return node flow rate due to exhaust fan operation, TU max flow limits, etc.? Also probably.

Is there a clear path to implement something like this? 
- The OA controller would have to be modeled at (called from) the same time as the UnitarySystem. I like this, we need to move in that direction.
- The mixer return node mass flow rate would have to be "tricked" during this procedure. This is a little scary to be setting node conditions for those outside the UnitarySystem boundary.
- Any equipment between the mixer and UnitarySystem (rare) would also have to be modeled.
- The previous sounds like iterating on the main branch components would to the trick (from within the UnitarySystem)
- Other than that it seems simple.

**Comment by mjwitte** [comment]
>  Simply increasing the fan speed would not change the return path flow rate during these iteration's

*If* the economizer is at 100% OA, then return flow rate doesn't matter.  And I'm guessing that the proposed control sequence is assuming 100% OA during step 2.  @energysims Is that correct?

@energysims replied:
Generally yes but where there was a year round cooling needed the dampers should modulate to keep the supply air temperature at the specified temperature.

**Comment by md-kennedy** [comment]
One issue with the above sequence is is that high speed economizer is likely to only be needed when the ambient is pretty warm and in that case going to high speed fan likely is an energy waster.  Which is why it would be nice to somehow specify whether there is a high speed economizer step or not.

Another issue that a more general solution might address is some units are coming with a very low speed ventilation mode, followed by two cooling/econo stages.   Also to clarify, in non-economizer cooling the fan would run at low speed for the 1st stage of cooling.

**Comment by rraustad** [comment]
@md-kennedy is there a sequence of operations provided with those units that we can use as a template?

**Comment by aaron-boranian** [comment]
**2 speed Operation with Air Economizer in UnitarySystem**

Current economizer operation in unitary system with multispeed fan does not impact fan speed. Economizer only operation is limited to low speed operation and economizer plus compressor operation is limited to low speed unless both compressors operate. Current energy codes require unitary equipment over 5 tons to have economizers with two stages of economizer only operation, first at low fan speed and then at high fan speed, and then to integrated operation. Three of three manufacturers checked run the fan at high speed when economizer and stage one compression are operating.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/20306353) feedback from @mjwitte

**Comment by md-kennedy** [comment]
Here is one SOQ for staged volume fan speeds:
 **Ventilation (FS.VN)** This configuration defines the fan speed used in Ventilation (fan-only) mode.
 **Free Cool Lo (FS.E1).** This configuration defines the initial fan speed used when in Free Cooling. The fan will stay at this configured speed whenever the damper is being used for free cooling. If the damper is at 100% for 5 minutes the fan will ramp to max speed. It is locked there until the actual damper position falls below 75% at which time it will ramp back down to this configured speed
**Mech Cooling (FS.CL)** This configuration defines the intermediate fan speed used when one stage mechanical cooling is being requested. Fan speed is based on how many cooling stages the unit has, how many cooling stages are being requested, and how many reheat stages are being requested. If the unit only has one circuit of cooling, then the fan speed will be FS.MX whenever that stage is requested. If the unit has more than one circuit of cooling but only one is being requested, the fan speed will be set to this FS.CL. **Any time more than one stage is requested the fan speed will be set to FS.MX.** This would include all Econo + one stage compressor hours.

**Comment by rraustad** [comment]
I found this [here](http://hvac-talk.com/vbb/showthread.php?478472-Economizer-Sequence-of-Operation). 

You shouldn't control DX by AHU supply temp. I know engineers write up this junk because they don't have to replace compressors 3 years later. The dampers must remain closed any time the DX is on. Your OA may be cooler than the return air but the TXV needs the load to control right and not flood or short cycle the unit. We usually try to let the dampers do the cooling but close them any time the DX is on, or OA is above 65 degrees if you don't have enthalpy.

OA>65 DX only
OA<65 OAD & DX but close when DX is on (If OAD cannot keep up switch from supply loop to space/return loop when DX is on)
OA<55 OAD only
Also possibly OA<(?) hold OAD @ minimum.

Use lots of delays & minimum runtimes on DX


Also mentioned was "The new Honeywell W7200 series of economizer controls (circa 2004) have
all kinds of options now, like demand controlled ventilation (DCV)
input from a CO2 sensor." and found a table sequence of operations [here](https://customer.honeywell.com/resources/techlit/TechLitDocuments/62-0000s/62-0331.pdf)

![economizercontrols2spd](https://user-images.githubusercontent.com/5778156/43873253-e1d22ffc-9b53-11e8-9e55-9cc00a7f9c49.jpg)

**Comment by mjwitte** [comment]
@lymereJ Regarding the NFP for this, have you considered the implementation details? There are other problems related to unitary systems and OA systems. @rraustad Has proposed one approach in https://github.com/NREL/EnergyPlus/pull/9029, but this not a perfect solution per this [comment](https://github.com/NREL/EnergyPlus/pull/9029/files#r698682112). I suspect the economizer feature will run into similar issues.

**Comment by lymereJ** [comment]
Addressed in #9987.
