### ISSUE TITLE
Zone exhaust fan impacts zone air balance incorrectly

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6119]
Issue overview
--------------
Fan:ZoneExhaust should have no impact on the conditions or load in a zone that is served only by zone equipment (unless used with AirflowNetwork or ZoneAirMassFlowConservation).  The exhaust fan should simply consume electricity, and it is assumed that the user has specified infiltration or interzone mixing to offset the exhaust flow.

A user reports that a single zone model with four pipe fan coil (no outdoor air flow) and zone exhaust fan does not produce reasonable results.  With zone equipment, one would expect that the "balanced flow" schedule for the exhaust fan would have no impact, but it changes the results significantly.  There are three test files, one with no exhaust fan, one with exhaust fan and balanced flow=0, and another with exhaust fan and balanced flow = 1.  These *should* all produce the same results (other than the exhaust fan electricity), but they do not.

### Workaround ###
Delete the exhaust fan and use ElectricEquipment with 1.0 Fraction Lost to model the fan power.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v8.7.0
 - Helpdesk ticket number 11987

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added DevSupport\DefectFiles use Sacramento weather.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lgu1234** [comment]
@mjwitte I tested two files with an exhaust: one with exhaust fan and balanced flow=0, and another with exhaust fan and balanced flow = 1. When the schedule value > 0, the fan module calculates:

				if ( Fan( FanNum ).BalancedFractSchedNum > 0 ) {
					BalancedExhMassFlow = UnbalExhMassFlow * GetCurrentScheduleValue( Fan( FanNum ).BalancedFractSchedNum );
					UnbalExhMassFlow = UnbalExhMassFlow - BalancedExhMassFlow;

When BalancedExhMassFlow > 0, it becomes a part of ExhMassFlowRate in the CorrectZoneHumRat function of the ZoneTempPredictorCorrector
			ExhMassFlowRate -= ZoneEquipConfig( ZoneEquipConfigNum ).ZoneExhBalanced; // Balanced exhaust flow assumes there are other flows providing makeup air such as mixing or infiltration, so subtract it here

Please look at the comments at the end of statement. The program assume the balance exhaust will introduce additional infiltration. Since one case at balanced flow=0 does not introduce additional infiltration, and the other at balanced flow=1 introduces additional infiltration, the differences are expected as designed.

If I assume this is true, this item was not used in the CorrectZoneAirTemp function. Do we need to introduce it?

**Comment by lgu1234** [comment]
@mjwitte I forgot to report my test runs. When I commented the line:

//			ExhMassFlowRate -= ZoneEquipConfig( ZoneEquipConfigNum ).ZoneExhBalanced; // Balanced exhaust flow assumes there are other flows providing makeup air such as mixing or infiltration, so subtract it here

I ran both cased with an exhaust fan and different balanced flow schedules, the differences only occur in an output variable:
CORE_ZN THERMAL ZONE RETURN AIR NODE:System Node Standard Density Volume Flow Rate [m3/s](Hourly)
Max delta difference: 6.92E-17
Max perc difference: 100.00%
Count of diffs out of bounds: 0
 Time of Max delta diff: 07/21  04:00:00
 Time of Max perc diff: 07/21  04:00:00

Although I don't expect any differences, I don't think I need to find why, because the differences with different schedule values are expected and as designed.

**Comment by mjwitte** [comment]
@lgu1234 It does not assume that balanced exhaust will "introduce additional infiltration".  It assumes that the additional infiltration has been specified by the user and as such doesn't require the OA damper to provide that makeup air (in the case of an airloop).  The differences are not as designed.  Remember this is all with ZoneAirMassFlowConservation off.

**Comment by lgu1234** [comment]
@mjwitte If the difference is not designed, the input in the last field in the Fan:Fan:ZoneExhaust is not meaningful:

    FlowUnBalancedSched;       !- Balanced Exhaust Fraction Schedule Name

If I comments two lines in the Update function in the Fan model, the same results were obtained:
				if ( Fan( FanNum ).BalancedFractSchedNum > 0 ) {
//					BalancedExhMassFlow = UnbalExhMassFlow * GetCurrentScheduleValue( Fan( FanNum ).BalancedFractSchedNum );
//					UnbalExhMassFlow = UnbalExhMassFlow - BalancedExhMassFlow;
				} else {

Is this as expected?

**Comment by mjwitte** [comment]
My understanding is that it is supposed to be meaningful *only* for airloop systems.  For a zone with only zone HVAC equipment, it should have no impact.  With an airloop system it will alter the return flow and also chance the amount of OA expected from the central air loop.  For this defect file, you said deleting that line change the return air flow.  The line *should* be changing return flow if there is an airloop, but the return flow should always be zero for this file.

The line you commented out was added by me in #4804.  It appears that fixed one problem but may have created another or wasn't general enough for this case.

**Comment by lgu1234** [comment]
@mjwitte The ZoneEquipConfig has a variable: AirLoopNum. I have a thought to deal with the zone equipment only. If ZoneEquipConfig(x).AirLooNum = 0, no exhaust mass flow from exhaust fan will be added in the function of CorrectZoneHumRat. What do you think?

**Comment by mjwitte** [comment]
Maybe, but I'm not sure.  But remember that should not be the case when the exhaust fan is included in the Airflownetwork or ZoneAirMassConservation is active.

**Comment by mjwitte** [comment]
@lgu1234 As mentioned previously, I have two other defect files which may or may not be related to this issue.
In both of these files, there is a central VAV system with zone hvac equipment added to represent a perimeter air handler serving the same zones.  I tried both ideal loads, and ZoneHVAC:OutdoorAirUnit.  These should have changed the zone load resulting in a change in VAV airflow rates, but instead, the VAV dampers went to almost full flow all the time - even in winter.  These files have been added to the defect files folder for 6119.  Use Grand Rapids, MI weather.

**Comment by lgu1234** [comment]
@mjwitte I ran 3 new test files with and without my fix and no differences were found. Then I checked input files and found no exhaust fans are used. Since my fix is related to exhaust mass flow rate handling, the problems from the 3 new test files are not related to this issue. I suggest to make a new issue to address the problems.

I also ran the VAVplusIdealLoads.idf and checked results to see what happens. Below is a picture to show zone air temperature, setpoint, and ideal system supply air temperature and mass flow rate in the first design summer day:

![picture1](https://user-images.githubusercontent.com/5970656/26980816-3e2bab72-4d01-11e7-8ab2-4099273f9f80.jpg)

Here is my observation.  The zone air temperature is at 20C, lower than the cooling setpoint at 23.3. However, the ideal system is on to provide additional cooling. Based on HVAC system operation procedure, a central VAV air loop system should be on first, while an ideal system as zone equipment should be acted as a supplemental system. Since the zone air temperature is already below the cooling setpoint, the ideal system should not be on. What do you think?

**Comment by mjwitte** [comment]
@lgu1234 I haven't looked closely at your fix, so it is acting exclusively on exhaust fan nodes, not exhaust nodes in general.  For this ideal loads case, the intent is for ideal loads to run first to model a perimeter system that runs during occupied hours without any connection to the zone thermostat.  The VAV system is connected to the thermostat and provides additional cooling as needed.  So, if the zone temp is below the cooling setpoint, the VAV box (without reheat) should be running at minimum flow, not full flow.  That's the puzzle.

**Comment by lgu1234** [comment]
@mjwitte Here is my thinking about logic. EnergyPlus calls AirLoop first, then zone equipment. Zone load is predicted by Predictor. My quess is that an AirLoop see all loads first to determine mass flow rate at full, not remaining rate after an ideal system. However, the ideal system has Priority 1 and is forced to turn on. In this way, both AirLoop and ideal system turn on, so that that is why the zones are overcooled and the puzzle occurs.

When I looked at operation hours when the ideal system is not available, damper positions vary properly.

Please let me know your opinion.

**Comment by mjwitte** [comment]
Either way, the VAV dampers should not be wide open - the zone is cold.  What happens with the VAV dampers is the zone equipment order is reversed?

**Comment by lgu1234** [comment]
Mike:

 

I changed priority of both VAV Terminal and IdealSystem. Results do not change (may be slightly):

 

ZoneHVAC:EquipmentList,

    S Perimeter 6 Equipment, !- Name

    ZoneHVAC:IdealLoadsAirSystem,  !- Zone Equipment 1 Object Type

    S Perimeter 6 Ideal Loads Air System,  !- Zone Equipment 1 Name

    2,                       !- Zone Equipment 1 Cooling Sequence

    2,                       !- Zone Equipment 1 Heating or No-Load Sequence

    ZoneHVAC:AirDistributionUnit,  !- Zone Equipment 2 Object Type

    S Perimeter 6 ATU,       !- Zone Equipment 2 Name

    1,                       !- Zone Equipment 2 Cooling Sequence

    1;                       !- Zone Equipment 2 Heating or No-Load Sequence

 

Then I find some zones have ideal system and VAV ATU, some zone may have ATU only:

 

ZoneHVAC:EquipmentList,

    Toilets 6 Equipment,     !- Name

    ZoneHVAC:AirDistributionUnit,  !- Zone Equipment 1 Object Type

    Toilets 6 ATU,           !- Zone Equipment 1 Name

    1,                       !- Zone Equipment 1 Cooling Sequence

    1;                       !- Zone Equipment 1 Heating or No-Load Sequence

 

I reduces maximum airflow rate for each IdealSystem to 0.001. Results are back to normal. Zone air temperatures are close to the setpoints, and damper positions vary every time step with minimum value at 0.5.

 

I think the problem may come from ideal systems. Since the VAV central system can meet loads, ideal system becomes problematic.

 

Thanks.

 

Gu

**Comment by mjwitte** [comment]
The same thing happens with the zone oa system. I still think it's a mass balance or exhaust node accounting error.  To eliminate load interactions we could change the oa systems to provide neutral air.


-------- Original message --------

**Comment by lgu1234** [comment]
@mjwitte  It may be from exhaust nodes, but not from exhaust fans. That is why I suggested to make a new issue.

**Comment by mjwitte** [comment]
Closed via #6133
