### ISSUE TITLE
PIU doesn't set the ADU inlet node num

### ISSUE THREAD

**Issue by lymereJ** [NREL/EnergyPlus#6427]
Issue overview
--------------
The air distribution inlet node num is initialized [here](https://github.com/NREL/EnergyPlus/blob/973b46637653ab47301b7c9e8d29de06b8e406ad/src/EnergyPlus/ZoneAirLoopEquipmentManager.cc#L323) but is never updated. This affects the calculations done by the mechanical ventilation controller. The supply mass flow rate passed to the mechanical ventilation controller is never incremented by the primary mass flow of the PIU units, hence an incorrect system supply mass flow rate is used for the calculations of the ventilation flow rates (for example, VRP).

@mjwitte and I exchanged a few messages via the helpdesk, his last message summarizes the issue pretty well:

>Looks like the PIU has *never* set the ADU inlet node num.
>
>Looking at the code prior to v8.8 changes, this line is there as a comment in PoweredInductionUnits::GetPIUs, was line 596 then
>
>// AirDistUnit(ADUNum)%InletNodeNum = PIU(PIUNum)%InletNodeNum
>
>https://github.com/NREL/EnergyPlus/blame/bb16db32963d6e56325dfd51297e42a75e240ff3/src/EnergyPlus/PoweredInductionUnits.cc#L596
>
>
>For v8.8, this block was moved (by me) and copied to a second place.
>
>https://github.com/NREL/EnergyPlus/commit/8d2cbf82be0358f0977d58148fe56c89e1e76a50#diff-a649c9900f7e0de68c516ad1c22b01c7R441
>https://github.com/NREL/EnergyPlus/commit/8d2cbf82be0358f0977d58148fe56c89e1e76a50#diff-a649c9900f7e0de68c516ad1c22b01c7R587
>
>The commented line was deleted in one place, still there in the other. Little did I know that this line was needed all along, except with PIU( PIUNum ).PriAirInNode.
>
>Looking back in the fortran version archive, this line was commented out from the very beginning. I can't explain why. 

### Details
 - Helpdesk ticket number: 12378

**Comment by Nigusse** [comment]
I tried two things for this issue:

(1) First I attempted to set node number to the air distribution inlet node. This is not straightforward because, unlike other air terminal units, PIUs have two inlet nodes and the air distribution code structure is not setup to handle two inlet nodes. Any ways I managed to connect to the PIU's mixed mixed air outlet node but that did not make any difference on the problem reported. 

(2) Second, I wanted to verify/confirm the mass conservation problem reported for PIU between the two inlet streams, and the mixed air outlet and the ADU outlet nodes. Sum of the mass flow rates of the primary air and secondary air of the PIU exactly matches the mass flow rate at the mixer outlet node and ADU outlet node. This confirms that the mass conservation around PIU is working correctly. From the email thread and looking at the attached files I think the user was comparing volume flow rates of the two inlet streams of PIU and ADU outlet stream. Volume flow rate calculated at current density should not be used for verifying "conservation" of flows because of difference in air density at nodes. Then I changed the volume flow rate output variables in the idf to standard density and rerun the model. The sum of volume flow rates of the primary and secondary air matched that of the outlet node exactly.  I verified this in develop and V8.8 both gave the same result. I suggest that we communicate this to the user to use the volume flow rate reported at standard density instead of current density for their verification. If this does not solve their problem, then we will look the issue again. What do you think @mjwitte ?

**Comment by lymereJ** [comment]
@Nigusse -

Thank you for following up on this issue! I should have probably provided a little bit more background. I noticed that when using PIUs the ventilation rates based on the VRP method calculated by the Controller Mechanical Ventilation did not align with manual calculations I put together (in the spreadsheet I sent to the helpdesk) whereas the manual calculations did align with the same model but with standard VAV boxes instead of PIUs. I run the PIU model using a debug version of EnergyPlus and noticed that the discrepancy between my manual calculations and what is calculated by EnergyPlus seem to come from the fact that the mass supply flow rate passed to the Control Mechanical Ventilation is always 0 kg/s when PIUs are used. I worked backwards from there and noticed that this was due to the fact that the air distribution inlet node num is initialized but never updated, hence the mass flow rate of 0 kg/s. @mjwitte confirmed it as per the message I quoted in my first post here. I was not attempting to verify the mass flow conservation through the PIU.

**Comment by Nigusse** [comment]
@lymereJ I was able to set inlet node number to the to ADU but that did not resolve the problem. There are other issues that I am tracking down now. I will update you the progress.

**Comment by lymereJ** [comment]
Great! Thank you.

**Comment by Myoldmopar** [comment]
Closed via #6446
