### ISSUE TITLE
Enhance ZoneEarthtube object capabilities

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6627]
Problem: While EnergyPlus does have an earth tube model, there are several improvements that could increase the accuracy of the predictions made by the model. The following are potential areas of improvement in the model:

1.	The existing earth tube model does not consider the time lag between the earth tube inlet and outlet air. The model assumes that the time when the outlet air comes out of the earth tube is the same as that when the inlet air enters the earth tube, despite the fact that there is a time lag in reality.

2.	The existing earth tube model does not consider the effect of the presence of the pipe on the soil temperature in the pipe vicinity. The model assumes that the soil temperature and the pipe surface temperature are uniform in the axial direction. There is also no accounting for when more than a single tube is present and how the presence of multiple tubes impacts the local soil conditions.

3.	The existing model considers only the sensible heat transfer between the pipe and the soil. It does not consider the mass balance (moisture balance) between the pipe and the soil.

Rationale: Correcting the issues noted above would increase the confidence in the users in the results presented by EnergyPlus and might lead to more designers using the program and/or this model.

Solution: Modify the existing earth tube model to account for the effect of time lag, the impact of the earth tube on the local soil and thus potentially on other tubes in the vicinity, and the potential latent effects of the earth tube on air passing through it.

Context: See legacy enhancement list item Ventilation_2007_01.doc

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/14151156) feedback from @RKStrand

**Comment by JohnNelsonsGITHub** [comment]
Item 2 above is critically important.  In climates with cold winters and moderate summers, we use earth tubes to preheat ventilation air all winter, which works very well (earth tubes followed by ERVs nearly eliminate all heating of ventilation air).  This approach also creates a store of coolth in the ground, by cooling the soil surrounding the earth tubes.  If we are judicious in the use of earth tube air (E.g., bypass the earth tubes in the spring/early summer), the stored coolth is adequate to cool ventilation air very effectively.  Currently, this effect is not captured at all in the earth tube object.  There is zero sensitivity in summer results as to whether or not cold air passed through the earth tubes all winter.  We would use this object far more if it captured these effects.

**Comment by RKStrand** [comment]
@JohnNelsonsGITHub I am currently working on the first phase of an enhancement to the earth tube model.  The project is very limited scope and is an attempt to deal with heat storage in the ground by allowing temperature variation vertically.  This is not intended to address all of the potential improvements in the model due to the fact that not a lot of funding was devoted to this during the current FY.  @nealkruis suggested that I contact you to see what your thoughts were on what is being proposed.  You can find the current proposal at:

https://github.com/NREL/EnergyPlus/blob/5114327-EarthTube1DVerticalEnhancement/design/FY2023/NFP-EarthTube-1DEnhancement.md

https://github.com/NREL/EnergyPlus/blob/5114327-EarthTube1DVerticalEnhancement/design/FY2023/earth_tube_solution_space_diagram.png

This was discussed yesterday during a team meeting and one change will be to include the soil at the earth tube depth rather than have a massless node there.  Do you have any thoughts on what I am proposing?

Thanks in advance for your input!

**Comment by JohnNelsonsGITHub** [comment]
Hi Rick,
I appreciate you reaching out and would be happy to help along the way.  I'd have to keep my involvement low, but comments may be useful to you.

Its great to hear this work is underway, even if in limited scope at the moment.

In application, one of the aspects we look at is bringing cold air through the earth tubes in the winter and really cooling the ground.  Then we might bypass the earth tubes in the spring when OA temperatures are favorable.  Typically, we'll also have heat recovery so we can play with the amount of bypass (more than one way to get the desired temperature in the spring).  Bypassing the earth tube in the spring and early summer preserves the coolth of the ground which enhances the cooling potential later in the summer.  Could this be incorporated?  It's a really hard problem to solve.  We also look at how much a night purge could 'recharge' the cooling potential in the summer.  There seems to be a lack of data around all of this for earth tubes, as you all noted in the testing/validation/data sources section.  That said, our geoexchange engineers do that kind of analysis with geothermal, and I wonder if any of the validation around that could be useful.

Heat transfer in the direction of the air flow would also be very important, as there is much more heat transfer in the early stretches of the earth tube and more constant temperatures toward the end.  When we've done labyrinths with KIVA for ground transfer, we've seen sensitivity to how small we make the zones (we haven't fully tested sensitivity, but all else the same, 5' long zones produced better results than 20' long zones).


Best Regards,







John Nelson 
Associate, Design Analytics
Oakland, 
CA, 
United States
T +1 510.663.2070 x2146
Introba.com
 | LinkedIn
We are now Introba! Learn more at introba.com.
I work flexibly and may send emails outside of working hours. I don’t expect a response or action outside your own working hours.
This email may contain confidential and/or privileged information. If you are not the intended recipient or have received this email in error, please notify the sender immediately and destroy this email. Any unauthorized copying, disclosure or distribution of the information contained on this email is prohibited.

**Comment by RKStrand** [comment]
@JohnNelsonsGITHub Thanks for your comments!  I understand that your involvement would be limited and appreciate the feedback that you have given.  It sounds like important issues to you are the potential for bypassing the earth tube at certain times and also modeling the variation of temperature along the earth tube.  The variation along the earth tube axially is something that has been identified as a potential future enhancement.  The bypass issue is interesting and has not been discussed yet.  I think there would probably need to be more investment in how the earth tube hooks up to the building--possibly connecting it to the HVAC system or at least having some control decisions made.  I'm not aware of any other equipment in EnergyPlus that does that sort of control, so that would have to be looked at specifically.  In any case, I do feel like the current proposal to look at vertical temperature variation as a result of the earth tube would potentially capture the temperature variation between seasons.  Do you use the air sent through the earth tube in winter to the HVAC system as a way of preheating the outside air or do you simply pass cold air through the earth tube and then dump it outside to simply cool off the ground more in "off season"?  While the work on earth tube is not fully planned out yet beyond this year, the more information we get together now will provide for a better implementation plan in future development cycles.

In any case, if you have any further questions or concerns about what we are currently trying to do or thoughts on what future work should include, please let us know.  Thanks again for your valuable input!

**Comment by RKStrand** [comment]
For now in GitHub, this will reference the first enhancement to the earth tube--the vertical model.  After this is merged into develop, a new GitHub issue will be started to keep this issue active with remaining potential development projects.
