### ISSUE TITLE
CMake should not allow integration tests to run without BUILD_FORTRAN activated

### ISSUE THREAD

**Issue by michael-okeefe** [NREL/EnergyPlus#6833]
Issue overview
--------------
If a new developer does not check the BUILD_FORTRAN configuration option on a new EnergyPlus build environment on windows but does select BUILD_TESTING, the integration tests will attempt to run without indication that the required FORTRAN packages are missing. This results in a confusing situation where the majority of integration tests fail with no indication as to the root cause.

### Details
Some additional details for this issue (if relevant):
 - Windows
 - EnergyPlus v8.9

**Comment by jmarrec** [comment]
This was tricky to track down, but that's actually not the problem really.

The integration test actually won't run some tests unless BUILD_FORTRAN is enabled, see [testfiles/CMakeLists.txt](https://github.com/NREL/EnergyPlus/blob/develop/testfiles/CMakeLists.txt#L624)

The problem is actually a simple flag, `-r` which is passed to the CLI when the test are run. -r means "Call ReadVarEso", which unless you actually build fortran you don't have, see https://github.com/NREL/EnergyPlus/blob/develop/cmake/ProjectMacros.cmake#L95:L99

----

I don't think this "-r" flag is needed unless you also enable `ENABLE_REGRESSION_TESTING`, which includes parsing the ESO for diffs (so you need ReadVarEso).

Another side effect might be for PERFORMANCE_TESTS, we may want to keep that "-r" flag in order to keep things level with past tests.
