### ISSUE TITLE
Sync Kiva convection algorithms with EnergyPlus user-specified algorithm

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#6938]
Currently, Kiva uses only the TARP algorithm for convection. We can replace the TARP algorithm in Kiva with a virtual function that can be set by the calling program.

Requested by Carrier team.

**Comment by JimPegues** [comment]
To elaborate on this ... Replacing the TARP algorithm with a virtual function set by the calling program allows the convention model used in KIVA to be synchronized with the convection model used by the room.  For example, suppose a room is supplied by a forced air HVAC system such as VAV.  The room would be modeled to use the 'ceiling diffuser' convection model since wall, ceiling, floor surfaces in the room will experienced forced convection.  When the room also contains ground connected elements like slab on grade floor, basement floor, or basement wall, modeled via KIVA those surfaces will automatically use the TARP model representing natural convection, and as a result will likely underestimate the convective heat flow between the surface and the room air.  If KIVA could use the same convection model as used for the rest of the room, that would synchronize convection modeling between KIVA and the rest of the room, and enhance the accuracy of load calculations.  Allowing the calling program (EnergyPlus) to specify convention via a virtual function allows this synchronization of convection algorithms.  (Jim Pegues, Carrier Corporation, 9/7/2018)

**Comment by Myoldmopar** [comment]
Closed via #7202
