### ISSUE TITLE
No section for HybridModel:Zone model in Eng. and Inputoutput Reference documents

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6947]
There is no section for HybridModel:Zone in the engineering and inputoutput reference documentation. Originally posted in issue #5997.
- "[ ] I/O Ref section for HybridModel:Zone is not in the pdf.  The source files were added in #5882 but there's no line in overview.tex to input the new file into the document?"

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
There's one possibly incomplete section in I/O there: https://github.com/jmarrec/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-hybrid-model.tex

It doesn't have the Output variables. A cursory look at the code base indicates that one variable should be there: https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/HeatBalanceManager.cc#L5142
"Zone Infiltration Hybrid Model Air Change Rate"

Interestingly enough, if I look at the the example file HybridZoneModel.idf, and add the request for Output:VariableDictionary, it's not in the RDD, while the Flag should be initialized [here](https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/HybridModel.cc#L163) since there are objects that have `Calculate Zone Internal Thermal Mass` or `Calculate Zone Air Infiltration Rate` enabled.


(Also it seems quite weird to me that this object would bear begin/end day and month. It should read that from the RunPeriod)

**Comment by xuanluo113** [comment]
@mjwitte I checked the documentation and it seems the original documents are merged.

https://bigladdersoftware.com/epx/docs/9-0/engineering-reference/hybrid-model.html
https://bigladdersoftware.com/epx/docs/9-0/input-output-reference/group-hybrid-model.html

source code at

https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-hybrid-model.tex
https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/alternative-modeling-processes/hybrid-model.tex

**Comment by mjwitte** [comment]
Per @Nigusse above "there's no line in overview.tex to input the new file into the document"

**Comment by Myoldmopar** [comment]
Is this fixed by #7094 ?

**Comment by mjwitte** [comment]
Yes, closed via #7094.
