### ISSUE TITLE
Evaporative Cooler doesn't appear to work when connected to ATU:SingleDuct:CV:NoReheat

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#6997]
Issue overview
--------------

One of openstudio-resources regression test, evaporative_cooling.osm, shows widly varying results after I replaced all `ATU:SingleDuct:Uncontrolled` with `ATU:SingleDuct:ConstantVolume:NoReheat`.

I cleaned up two files so they produce a clear diff. The "Transition" one has ATU:Uncontrolled. The "270_900" has ATU:CV:NoReheat. I don't see any other differences in the file.

[evaporative_cooling_270_900_cleaned.idf.txt](https://github.com/NREL/EnergyPlus/files/2450186/evaporative_cooling_270_900_cleaned.idf.txt)
[evaporative_cooling_Transition_cleaned.idf.txt](https://github.com/NREL/EnergyPlus/files/2450182/evaporative_cooling_Transition_cleaned.idf.txt)

Running them with IL_Chicago, you can see that the ATU:CV:NoReheat one has almost zero water consumption, so I think the evap cooler isn't working:

![image](https://user-images.githubusercontent.com/5479063/46534370-37248000-c8a8-11e8-8809-cabeb7c4119c.png)

### Details
Some additional details for this issue (if relevant):
 - Platform: Ubuntu
 - Version of EnergyPlus: 9.0.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
These files have conflicting SetpointManager:MixedAir objects which are in a different order in the 270_900 file.  When the conflicting managers for system 1 are reordered to match the original file, then the results align. OpenStudio should not be writing these pairs of conflicting setpoint managers. In fact, the *correct* answer is the one with near zero evap cooler operation. For example, in the "transition" file, the first pair of conflicting setpoint managers for system 1 are:
```
SetpointManager:MixedAir,
Node 18 OS Default SPM, !- Name
Temperature,
Node 12, !- Reference Setpoint Node Name
Node 20, !- Fan Inlet Node Name
Node 121, !- Fan Outlet Node Name
Node 18; !- Setpoint Node or NodeList Name

SetpointManager:MixedAir,
Setpoint Manager Mixed Air 3, !- Name
Temperature,
Node 12, !- Reference Setpoint Node Name
Node 20, !- Fan Inlet Node Name
Node 12, !- Fan Outlet Node Name
Node 18; !- Setpoint Node or NodeList Name
```
The actual fan outlet node is 121, so the second SPM here is wrong, and because it appears later in the idf, it wins the conflict. Deleting the incorrect SPM produces the result with near zero evap cooler operation. With the DX cooling coil upstream of the evap coolers controlling to the same setpoint temperature (less fan heat) as the evap coolers, it's not clear what the control intent is for this file.

In any case, the change in results is due to the reordering of the conflicting setpoint managers, not the change in terminal unit type.
That said - there are some differences in sizing results at the airloop level that may need to be addressed. For this file it doesn't result in any coil sizing differences, just the reported heat flow rates.
```
ATU:Uncontrolled
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Sum of Air Terminal Maximum Heating Flow Rates [m3/s], 3.24369
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Sum of Air Terminal Minimum Heating Flow Rates [m3/s], 3.24369
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Sum of Air Terminal Maximum Flow Rates [m3/s], 3.24369
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Adjusted Heating Design Air Flow Rate [m3/s], 3.24369
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Adjusted Cooling Design Air Flow Rate [m3/s], 3.24369
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Adjusted Main Design Air Flow Rate [m3/s], 3.24369
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, User Heating Air Flow Ratio [], 1.00000
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Calculated Heating Air Flow Ratio [], 1.00000
 
ATU:CV:NoReheat
Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Sum of Air Terminal Maximum Heating Flow Rates [m3/s], 0.00000
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Sum of Air Terminal Minimum Heating Flow Rates [m3/s], 0.00000
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Sum of Air Terminal Maximum Flow Rates [m3/s], 3.24369
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Adjusted Heating Design Air Flow Rate [m3/s], 2.68981
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Adjusted Cooling Design Air Flow Rate [m3/s], 3.24369
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Adjusted Main Design Air Flow Rate [m3/s], 3.24369
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, User Heating Air Flow Ratio [], 1.00000
 Component Sizing Information, AirLoopHVAC, AIR LOOP HVAC 1, Calculated Heating Air Flow Ratio [], 0.82925
```

**Comment by jmarrec** [comment]
Thanks Mike. I did already identify there were duplicated SPMs and I fixed it in https://github.com/NREL/OpenStudio/commit/e62069f951c41b264e7eab0e121ffcc3aff0ce19

But I didn’t notice that they weren’t exactly the same in some occasions.
