### ISSUE TITLE
Duplicate sections in documentation

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7027]
Issue overview
--------------

* Site:GroundTemperature:FCfactorMethod
    * https://github.com/jmarrec/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-surface-construction-elements.tex#L3903

    * https://github.com/jmarrec/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-location-climate-weather-file-access.tex#L1589

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
Removed the duplicate section group-surface-construction-elements.tex.  It made more sense to delete that one since the other location had other Site: input syntax.  Since this section deals with a Site: input, it made more sense to leave it there than surrounded by Construction and Material syntax.

**Comment by Myoldmopar** [comment]
Closed with #7340
