### ISSUE TITLE
EMS DayOfWeek index not matching documentation

### ISSUE THREAD

**Issue by antoine-galataud** [NREL/EnergyPlus#7030]
EnergyPlus version: 8.8

I've a simple EMS program that outputs DayOfWeek, DayOfMonth, Month and Year built-in variables. These variables are read by a script that simply prints them. Here is the part of the script itself

`print('{} {}/{}/{}'.format(dayOfWeek, dayOfMonth, month, year))`

Sample output:

```
3.0 1.0/1.0/1986.0
...
4.0 2.0/1.0/1986.0
...
5.0 3.0/1.0/1986.0
...
```

(year is 1986 because of weather file used: `USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw`)

Here, according to [documentation](https://bigladdersoftware.com/epx/docs/8-8/ems-application-guide/variables.html#built-in-variables) that states range is `1-7 (1 = Sun, 2 = Mon, …)`, 1st of January is a Tuesday.

However, looking at year 1986 calendar, 1st of January was a Wednesday. 

Am I missing something?

**Comment by mjwitte** [comment]
> (year is 1986 because of weather file used: USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw

Prior to v9.0, EnergyPlus, the year number did not control the calendar days.  Significant changes were made for date handling [here](https://github.com/NREL/EnergyPlus/pull/6478) for v9.0.

Check the `RunPeriod` input for "Day of Week for Start Day". It can be set to a specfic day of the week, or it may be "UseWeatherFile" which is the default.

If it is UseWeatherFile, then check the headers at the top of the epw file. The `DATA PERIODS` line sets the starting day type. Here is an example from the Chicago TMY3 epw:
```
DATA PERIODS,1,1,Data,Sunday, 1/ 1,12/31
```

**Comment by jasondegraw** [comment]
@mjwitte closed this before I could respond, but I'm pretty sure that this is expected behavior. As he indicated, changes were made for 9.0 to use the `RunPeriod` object to determine the start day of the week and to get a start year that matches up as legitimate calendar date. In 9.0, if you specify that you're simulating 1986, then the start day of the week will be Wednesday.

For versions 8.9 and previous, date correctness was not very strictly enforced, so you can (under certain circumstances) simulate 1986 and start on a Tuesday. If you look in that EPW, you'll see more than one year (1986, 1977, 1985, ...) due to the way that the TMY EPWs are constructed. So I'd argue that you're probably simulating some year (e.g. 2013) that starts on a Tuesday and not 1986. If you want certainty, I'd need to see your IDF.

For version 8.9 and previous, finer control over the dates of simulation is offered by the `RunPeriod:CustomRange` object. This will apply additional constraints to your EPW, but if you can't upgrade to 9.0 and you need to have "correct" dates, that's going to be the way to go.

**Comment by antoine-galataud** [comment]
Thanks @jasondegraw and @mjwitte. Appreciate your help.
