### ISSUE TITLE
Chiller always requests full condenser flow regardless of flow mode or pump type

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7111]
Issue overview
--------------
User file with `Chiller:Electric:EIR` always requests full condenser flow rate, regardless of chiller flow mode, with variable speed towers and variable speed condenser pump.
Should this happen?
If so, should there be an additional flow mode to allow variable flow condenser?

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.0.1
 - [Unmethours 35540](https://unmethours.com/question/35540/condenser-loop-pumpvariablespeed-always-running/) link and helpdesk ticket 13133.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSuppor\DefectFiles\7000s\7111
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Certainly looks like this should be an option. How to control it is another question. Here's one article about that:
https://www.csemag.com/articles/control-sequences-for-chilled-water-systems/

**Comment by dmitry-ivanov-mm** [comment]
Hi there,

Is there a way to raise the priority of this issue? It hasn't been addressed since 2018 and makes results for the variable-speed condenser loop very inaccurate. At the same time variable-speed condenser loops are very common design.

Just trying to attract attention to this issue :)

Cheers

**Comment by giorgiolupato** [comment]
> Hi there,
> 
> Is there a way to raise the priority of this issue? It hasn't been addressed since 2018 and makes results for the variable-speed condenser loop very inaccurate. At the same time variable-speed condenser loops are very common design.
> 
> Just trying to attract attention to this issue :)
> 
> Cheers

Hi, unfortunately this is not a complete solution, but it can be a workaround (it's not perfect at all).

https://unmethours.com/question/40084/condenser-water-flow-rate-with-ems-energyplus/

**Comment by keigo-nomura** [comment]
Still unresolved?

This is a problem not only when using cooling towers, but also when using seawater cooling by PlantComponent:TemperatureSource. Unlike cooling towers, it is not possible to make a compromise of variable tower fans instead of variable condenser water.

Or variable condenser flow is possible with any other chiller objects?

Hope this issue won't be left unattended forever.

**Comment by keigo-nomura** [comment]
Great to hear that. Will the new feature be available in v24.2.0?

**Comment by lymereJ** [comment]
Yes. Note that the ASHRAE 205 chiller object doesn't include this feature but will be implemented a bit later.
