### ISSUE TITLE
Lower strictness in zone volume calculations for gbXML sourced files

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#7132]
A draft study showed that one issue that EnergyPlus had when importing Revit data (via gbXML and OpenStudio) is that the zone volumes could not be computed because Revit exported the coordinates assuming thickness and EnergyPlus expects the wall coordinates to exactly match to be considered fully enclosed.

 - Version of EnergyPlus (either 8.9 or 9.01)

The Georgia Tech report is in DevSupport

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
So what's the expectation for a fix here?  That EnergyPlus be less lenient about the enclosed zone calculations?  Or that EnergyPlus somehow seam the surfaces together to make a zone?  My gut reaction is that the data is simply not valid for EnergyPlus.

**Comment by JasonGlazer** [comment]
I'm not sure, but my first impression is that surfaces should be "pulled in" toward the centroid until they end up forming an enclosed space (without "leaks") and calculate the corresponding volume.

**Comment by jasondegraw** [comment]
I don't think that "pulling in" is going to work except in very simple cases. I don't recall off of the top of my head if gbXML has a way to store a precomputed volume value, but that's probably going to be the best solution.

**Comment by Myoldmopar** [comment]
That seems like we are reaching outside of the responsibilities of the simulation engine.

**Comment by JasonGlazer** [comment]
That was one of the reasons I wasn't sure if this should be considered a defect or not.

**Comment by Myoldmopar** [comment]
Understood, and I didn't intend to shut the idea down, just thinking outloud.  I don't want to keep people from trying to get stuff into E+, so if there is anything we can do to make E+ more amenable, it would be great to keep discussing, as long as it is appropriate for the simulation engine itself.

**Comment by jasondegraw** [comment]
Looked it up, gbXML can represent the volume apart from what E+ can calculate (looks like the easiest way is via spaces), so it should be possible to avoid geometric heuristics with the right input.

**Comment by JasonGlazer** [comment]
I requested the files from the draft report. If they include the calculated volume input from Revit that would be the simplest solution. Although if they do, it should already be working that way.

**Comment by jasondegraw** [comment]
I'm on my phone, so I could be misreading the schema, but it looks like "volume" is a required element in "space", so the information should be there. If that's the case, then we should close this issue and possibly raise it with OpenStudio.

**Comment by JasonGlazer** [comment]
See files demonstrating this issue at:

https://github.com/GreenBuildingXML/Level3Validation_Phase1

Also in DevSupport under the issue number.

**Comment by jasondegraw** [comment]
@JasonGlazer The XMLs at that link that I checked all have the volumes precalculated and included in the file, so to me this is a translation issue, not an E+ issue. I'm not seeing a compelling reason to keep this open (here) as an issue.

**Comment by JasonGlazer** [comment]
@jasondegraw so what do you recommend to address the issues raised in the Georgia Tech report?

**Comment by jasondegraw** [comment]
@JasonGlazer As @Myoldmopar suggested above, input with flawed geometry is just not valid input. There is a solution, and that is to improve the translation since the necessary information for E+ to run a simulation is included in the gbXML. The path forward is to improve the translation, which is being done here:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/gbxml/ReverseTranslator.cpp

I won't link within the file because there's a PR that could be merged soon that'll mess up all the line numbers, but in the `ReverseTranslator::translateSpace` function the volume is not translated. That needs to be translated, and probably some other things will need to be changed to make sure it gets used on export from OpenStudio. I'm sure @macumber would be happy to discuss.

**Comment by JasonGlazer** [comment]
Ok, thanks. I see the following issue is already present for OpenStudio

https://github.com/NREL/OpenStudio/issues/3349

**Comment by mjwitte** [comment]
Does a non-enclosed zone result in a fatal error? If so, that seems too strict in general.

**Comment by JasonGlazer** [comment]
No, I don't think so. If I remember correctly, it tries several different back up strategies to determine the volume if it is not enclosed such as the floor area time the height of the zone, etc.. If all of those strategies fail, I don't remember what happens.

**Comment by macumber** [comment]
Is there any chance of the zone volume calculation being factored out as a module from EnergyPlus?  I avoided trying to make the OS calculation very robust because I wanted to share an implementation if possible.  

It appears that the default gbXML->OSM translator does not move the space volumes from gbXML to zone volumes in OSM, we do have a measure that does that as an extra import step.  We'll discuss to see if we should add that to the default translator.

Another option would be to add a space volume field in OSM and then map that to zone volume in the OSM->IDF translator.

**Comment by Myoldmopar** [comment]
> Is there any chance of the zone volume calculation being factored out as a module from EnergyPlus? I avoided trying to make the OS calculation very robust because I wanted to share an implementation if possible.

:+1: I'd say there's definitely a chance, but it's not going to be in the really short term. :+1:
