### ISSUE TITLE
Standard Effective Temperature (SET) outputs from Energyplus not available

### ISSUE THREAD

**Issue by Arezaei558** [NREL/EnergyPlus#7174]
Issue overview
--------------
SET calculations occur in the background Energyplus code calculations but not SET is not a direct output from simulations that modeler can request. Please see the Unmethours link below for more information. 

https://unmethours.com/question/37129/standard-effective-temperature-set-outputs-from-energyplus/

SET is a necessary output from simulations to calculate the Passive Survivability LEED Pilot Credit: https://www.usgbc.org/credits/passivesurvivability. Not having SET output directly reported from the results of an Energyplus simulation limits the modeler's use of the entire OS measures ecosystem to visualize the results in measures like ViewData. 

Although Ladybug tools have these calculations streamlined (https://mostapharoudsari.gitbooks.io/ladybug-primer/content/text/components/PMV_Comfort_Calculator.html ---- example file: https://github.com/ladybug-tools/ladybug/blob/comfort-utility/ladybug/comfort/pmv.py#L207-L411   -----source code: https://github.com/ladybug-tools/ladybug/blob/comfort-utility/ladybug/comfort/pmv.py#L207-L411 -----) it will be helpful to have SET as a direct output from E+ to feed into OS ecosystem. 

### Details
N/A

**Comment by RKStrand** [comment]
@Arezaei558 As pointed out in the unmethours discussion, there is a SET variable calculated for the Pierce model.  I will add the ability to output that variable.  To get SET you will have to select the Pierce model, but at least this will give you what you need.  I will add to the documentation so that it is clear you have to select the Pierce model to get SET.  The other models do not calculate SET internally so adding that for other models would require quite a bit more work.

**Comment by Arezaei558** [comment]
Any updates on when this output for SET will be added to a next release? Or has it already been added?

**Comment by Arezaei558** [comment]
Never mind, just realized it was released with 9.2 version. Thank you all!

**Comment by mjwitte** [comment]
. . . and this issue should have been closed. Addressed in #7431.
