### ISSUE TITLE
User file with Site:GroundDomain:Basement failing with NaN

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7269]
Issue overview
--------------
User file has Site:GroundDomain:Basement fails with a thermostat error message showing NaNs in the error. The problem is with the horizontal insulation material which is Material:NoMass which results in a zero thickness domain region during mesh development. This could likely be a problem with any of the insulation materials in Site:GroundDomain:*

Workaround
------------
Delete the insulation, or use a Material object which has thickness.

### Details
Some additional details for this issue (if relevant):
 - Win64
 - Version of EnergyPlus v9.1.0
 - Helpdesk ticket number 15127.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added in EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mjwitte It definitely cannot use a no mass material because of the grid spacing issue as you suggested.  Though on the Mac, it never gets to the NaN problem but crashes on line 3983 of PlantPipingSystemsManager.cc:

            assert(g.Max > g.Min);

where it fails this assert.  Changing the material to a non-no mass material allows it to run.  Two potential solutions include:

1. Flagging this on input and forcing the user to pick a material with mass.
2. Check the materials for thickness and assigning a nominal thickness if it is a no mass material.
3. Altering the ground heat transfer model to do something differently when a no mass material is selected.

My thoughts: I think 3 is way too ambitious and would probably require more effort than this is worth.  2 is probably not awful but a bit artificial.  I believe that 1 is the best option for right now and should be implemented in both Site:GroundDomain get input routines.  I will move forward with that solution unless I heard concerns about that approach.

I'm "CC-ing" @Myoldmopar here since his name is on at least some of the code in this area in case he had any additional thoughts.

**Comment by Myoldmopar** [comment]
Closed via #7446
