### ISSUE TITLE
Unit ventilator control problems

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7285]
Issue overview
--------------
ZoneHVAC:UnitVentilator controls do not work as advertised.

1. When there is no coil, VariablePercent is supposed to increase the OA to max when there is a cooling load and the outdoor air is colder than the zone. But the if logic is backwards for this case.

2. Where there is a cooling coil, VariablePercent currently stays at minimum OA when there is a cooling load, as described in the I/O Reference. But this isn't really useful - with VariablePercent, the OA should increase to provide free cooling if there is a cooling load and conditions are favorable.

3. If the user really wants a fan coil unit with economizer, the I/O Ref suggests using the unit ventilator. It would be better to just add some rudimentary economizer controls to the fan coil unit, because the fan coil unit has better control options in general.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.1.0
 - Helpdesk ticket number 15147.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
@mjwitte @Myoldmopar defect items 1 and 2 can be addressed here, but item 3 needs a separate issue, or even may be enhancement. What do you think?

**Comment by RKStrand** [comment]
@Nigusse I agree with you.  Items 1 and 2 are defect issues while Item 3 is a separate thing--more of a development project.  By the way, are you thinking of taking this on?  If not, I am interested in working on this.

**Comment by Nigusse** [comment]
@RKStrand You can have it as you are more familiar with this object.

**Comment by RKStrand** [comment]
Thanks, Bereket. I’ll try to look into this more next week.


On Jul 5, 2019, at 1:34 PM, Bereket Nigusse <notifications@github.com<mailto:notifications@github.com>> wrote:


@RKStrand<https://github.com/RKStrand> You can have it as you are more familiar with this object.

**Comment by RKStrand** [comment]
@mjwitte Do you agree with @Nigusse and @RKStrand that this should be separated into two separate issues (items 1 and 2 in your original problem statement stay here and item 3 gets moved to something else, possible a new feature)?

**Comment by RKStrand** [comment]
@mjwitte So, in item 1, you wrote:

"When there is no coil, VariablePercent is supposed to increase the OA to max when there is a cooling load and the outdoor air is colder than the zone. But the if logic is backwards for this case."

However, when I look at the code starting at line 3050 in UnitVentilator.cc (case where this is a cooling load and no coil is available), I see the following:

                        } else if (SELECT_CASE_var == VariablePercent) {
                            // This algorithm is probably a bit simplistic in that it just bounces
                            // back and forth between the maximum outside air and the minimum.  In
                            // REAL(r64)ity, a system *might* vary between the two based on the load in
                            // the zone.  This simple flow control might cause some overcooling but
                            // chances are that if there is a cooling load and the zone temperature
                            // gets above the outside temperature that overcooling won't be significant.
                            if (Tinlet <= Toutdoor) {

                                OAMassFlowRate = MinOAFrac * Node(OutsideAirNode).MassFlowRate;

                            } else { // Tinlet > Toutdoor

                                MaxOAFrac = GetCurrentScheduleValue(UnitVent(UnitVentNum).MaxOASchedPtr);
                                OAMassFlowRate = MaxOAFrac * Node(OutsideAirNode).MassFlowRate;
                            }

So, when Tinlet (the temperature coming into the unit or the zone conditions) is less than or equal to Toutdoor, OA is set to MinOAFrac otherwise it's set to MaxOAFrac.  Isn't that already doing what you are requesting?  Either I am missing something really obvious or the logic here is not backwards.  Are you referencing a different place in the code?

**Comment by RKStrand** [comment]
@mjwitte I definitely agree with your comment regarding Item 2 in your original problem statement.  This should allow more OA to help reduce the cooling coil load.  I am guessing that I did it this way because I was trying to match the unit ventilator description as provided in whatever ASHRAE handbook description was available at the time but it could also just be an error.  I think what makes sense is to implement something similar to what the no coil case is (or should be???).  In other words, use MinOA when the zone return temperature is below the outside temperature and use MaxOA if the outside temperature is below the zone return temperature.  What do you think?  I'd like to have some sort of agreement before I implement so that there are fewer issues later.  Thanks!

**Comment by mjwitte** [comment]
Yes regarding 1 and 2 here, 3 separate. In fact, 3 is covered by #6636.

**Comment by mjwitte** [comment]
Regarding item 2 (cooling coil with Variable Percent), MaxOA could be too much cooling in cold weather. So, this control should land in between MinOA and MaxOA if needed to match the load.

**Comment by mjwitte** [comment]
Regarding 1, I must have misread that code (or looked at the wrong block). So, the basics are good here, but this should modulate to match the load as suggested in the comments.

**Comment by RKStrand** [comment]
@mjwitte Ok, so I will implement a fix that will address Variable Percent with a cooling load with and without a coil.  Both with and without a coil will be the same and will vary the OA percentage (or is it fraction? :) ) to increase OA when outside air temperature is less than zone return but not go past meeting the load.  If that doesn't sound good, let me know.  Thanks!

**Comment by mjwitte** [comment]
Closed via #7386
