### ISSUE TITLE
IDFVersionUpdater  and EP-Launch-Lite not working on Mac for EnergyPlus V9.1

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#7298]
Issue overview
--------------
I have EnergyPlus V9.1 installed on a Mac running  MacOS Mojave Version 10.14.4 (18E226).  When I attempt to launch IDFVersionUpdater.app, I get the following error message:

"The application “IDFVersionUpdater.app” can’t be opened."

The application then does not run.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): MacOS Mojave V10.14.4
 - Version of EnergyPlus (if using an intermediate build, include SHA): Version 9.1
 - Unmethours link or helpdesk ticket number: NA

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I believe I know why this is happening. Previous to #7148 the packaging on mac was done with PackageMaker and was triggering the darinpostflight.sh script via the CPACK_POSTFLIGHT_SCRIPT variable. Now that it's using QtIFW, this script is not used and you can't launch the App because the content isn't `chmod +x`.

**As a workaround, manually do the `chmod +x` command on your installation.** With this I can open the apps just fine.

```
chmod +x /Applications/EnergyPlus-9-1-0/PreProcess/IDFVersionUpdater/IDFVersionUpdater.app/Contents/MacOS/IDFVersionUpdater
chmod +x /Applications/EnergyPlus-9-1-0/PreProcess/EP-Launch-Lite.app/Contents/MacOS/EP-Launch-Lite
chmod +x /Applications/EnergyPlus-9-1-0/PreProcess/EP-Launch-Lite.app/Contents/MacOS/python
chmod +x /Applications/EnergyPlus-9-1-0/PostProcess/EP-Compare/EP-Compare.app/Contents/MacOS/EP-Compare
```

**Comment by jmarrec** [comment]
EP-compare has another problem, cf https://github.com/NREL/EnergyPlus/issues/7324
