### ISSUE TITLE
Check if two surfaces are coplanar prior to issuing "not fully enclosed" warning

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#7383]
Issue overview
--------------

The warning message: 

** Warning ** CalculateZoneVolume: The Zone="X" is not fully enclosed. To be fully enclosed, each edge of a surface must also be an edge on one other surface.

Can get triggered even if the volume is fully enclosed but that one of the sides is made up of multiple coplanar pieces. 

Add an additional level of checking for this coplanar case to reduce the times this warning message is shown.

See #15210 on helpdesk.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mldichter** [comment]
I think I have this exact bug. I added ceiling cavities to models to correctly model duct leakage using the ZoneHVAC:AirDistributionUnit object. Here is a [google drive link](https://drive.google.com/file/d/1VMfBH3k6--5Js_fwaQrz6HZRZAbRQe5T/view?usp=sharing) with an example file.

I'm pretty sure all the vertices are specified correctly since the ceiling cavities were made with some ruby code, and they work fine with all the other buildings I tried it on. I've also checked the autocalculated floor area and volume of the ceiling cavities, which are correct. I'm confident I can get rid of the unenclosed warnings if I split up the floor and ceiling surfaces wherever the ceiling cavities walls have vertices. This has worked for me before, but is a lot of work.

My main concern is if EnergyPlus results will differ if I do or do not fix the unenclosed warnings. If this warning is just a helpful output for the user in case of wrong specification, then I will ignore it.

**Comment by mjwitte** [comment]
@mldichter These warnings are produced when attempting to auto-calculate the zone volume. You should be able to confirm what the autocalculated zone volume is even when it throws this warning. With an incorrect zone volume, zone capacitance is mildly affected, but any inputs or outputs in ACH will be wrong.

If you specify the volume in the Zone object, then these warnings may still appear, but the user input zone volume will be used so you can be sure it's what is should be.

**Comment by jmarrec** [comment]
After a lot of effort I finally figured out what was the issue. I never managed to replicate it by doing test models, so I ended up cleaning up @mldichter 's model down one bit at a time. I reimplemented most of the geometry functions in python so I could debug more easily... and it turns out it's a tolerance that's too high, coupled with the fact that @mldichter 's model has plenums that are VERY long, like 55m but only about 0.3m high.

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/5479063/169430514-14c35fe3-c375-4450-a36d-af2b51ca89f5.png">

This routine basically tries to add extra vertices to a surface to split it up, and it checks whether the vertex is not the same as start and end point, and whether it’s on the same line
https://github.com/NREL/EnergyPlus/blob/b5702d089be54f840a37973fede8d3d919d50cbd/src/EnergyPlus/SurfaceGeometry.cc#L12379

https://github.com/NREL/EnergyPlus/blob/b5702d089be54f840a37973fede8d3d919d50cbd/src/EnergyPlus/SurfaceGeometry.cc#L12700-L12707

Essentially the root of the problem is that some of the wall vertices that are supposed to match with the **floor** are added to the **roof** and vice versa, because the tolerance is too high compared with the width/height ratio of the zone

![image](https://user-images.githubusercontent.com/5479063/169430564-8affb71d-22c8-4d86-8fa6-83fa44f869ca.png)

**Comment by jmarrec** [comment]
I can now replicate with a shoebox model: a 30x10x0.3m zone. I split the south wall in two. I get the warning.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/5479063/169431495-ed463594-5f93-4b01-82dd-6af02d72fd08.png">
