### ISSUE TITLE
Use QtIFW on Windows

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#7396]
Issue overview
--------------
We recently moved from PackageMaker to QtIFW on Mac.  The CI systems are currently having an issue with building NSIS packages, and after a quick test, it looks like moving to QtIFW on Windows may be a great step forward on there too.  I have already installed QtIFW on our Windows CI box and created a successful test build.  We just need to do some polishing to make the installer look nice.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
@kbenne you wrote the NSIS stuff (https://github.com/jmarrec/EnergyPlus/blob/develop/cmake/CMakeCPackOptions.cmake.in#L67) . I'd like to make sure I'm understanding something correctly:

if 64bit (`\${If} \${RunningX64}`) you copy DLLs to C:\Windows\SysWOW64, and otherwise to C:\Windows\System32

Despite the names, System32 is full of 64-bit files and SysWOW64 is full of 32-bit files. I assume System32 is 32bit on a 32 bit system. So I'm concluding that the DLLs you are copying are all 32-bits. Is that correct? Or is this a confusion due to the (poorly-chosen) naming convention of windows?

**Comment by jmarrec** [comment]
To build this PR on Windows:

* Install QtIFW: https://download.qt.io/official_releases/qt-installer-framework/3.1.1/
* Add it to the path (eg: add `C:\Qt\QtIFW-3.1.1\bin` to the env variable system path)
* Change CMake configuration to use CPACK_GENERATOR_IFW=ON for windows
