### ISSUE TITLE
Load introduced by ZoneHVAC:EnergyRecoveryVentilator not always met by AirLoop systems

### ISSUE THREAD

**Issue by yzhou601** [NREL/EnergyPlus#7507]
Issue overview
--------------
When modeling an ERV with AirLoopHVAC:UnitarySystem, Even with zone equipment fraction set to 1.0, in some hours, hvac still didn't meet 100% load.

    ZoneHVAC:EquipmentList,
    living Equipment List,                     !- Name
    SequentialLoad,                            !- Load Distribution Scheme
    ZoneHVAC:AirDistributionUnit,              !- Zone Equipment 1 Object Type
    ADU central ac and furnace living terminal,  !- Zone Equipment 1 Name
    2,                       !- Zone Equipment 1 Cooling Sequence
    2,                       !- Zone Equipment 1 Heating or No-Load Sequence
    1,                       !- Zone Equipment 1 Sequential Cooling Fraction
    1,                       !- Zone Equipment 1 Sequential Heating Fraction
    ZoneHVAC:EnergyRecoveryVentilator,  !- Zone Equipment 2 Object Type
    mech vent erv,           !- Zone Equipment 2 Name
    1,                       !- Zone Equipment 2 Cooling Sequence
    1,                       !- Zone Equipment 2 Heating or No-Load Sequence
    1,                       !- Zone Equipment 2 Sequential Cooling Fraction
    1;                       !- Zone Equipment 2 Sequential Heating Fraction

![image](https://user-images.githubusercontent.com/32500275/65078387-2276b600-d95a-11e9-8b5b-e67fe477d88e.png)

If added an ideal system at the last sequence as a backup :

    ZoneHVAC:EquipmentList,
      living Equipment List,                  !- Name
      SequentialLoad,                         !- Load Distribution Scheme
      ZoneHVAC:AirDistributionUnit,           !- Zone Equipment Object Type 1
      ADU central ac and furnace living terminal, !- Zone Equipment Name 1
      2,                                      !- Zone Equipment Cooling Sequence 1
      2,                                      !- Zone Equipment Heating or No-Load Sequence 1
      1,                                      !- Zone Equipment Sequential Cooling Fraction 1
      1,                                      !- Zone Equipment Sequential Heating Fraction 1
      ZoneHVAC:EnergyRecoveryVentilator,      !- Zone Equipment Object Type 2
      mech vent erv,                          !- Zone Equipment Name 2
      1,                                      !- Zone Equipment Cooling Sequence 2
      1,                                      !- Zone Equipment Heating or No-Load Sequence 2
      1,                                      !- Zone Equipment Sequential Cooling Fraction 2
      1,                                      !- Zone Equipment Sequential Heating Fraction 2
      ZoneHVAC:IdealLoadsAirSystem,           !- Zone Equipment Object Type 2
      ideal,                                  !- Zone Equipment Name 2
      3,                                      !- Zone Equipment Cooling Sequence 2
      3,                                      !- Zone Equipment Heating or No-Load Sequence 2
      1,                                      !- Zone Equipment Sequential Cooling Fraction 2
      1;                                      !- Zone Equipment Sequential Heating Fraction 2

There's always some load( 0.9-1.0 GJ running in Denver) distributed to ideal loads air system no matter how large the airloop system is.

![image](https://user-images.githubusercontent.com/32500275/65079400-4d620980-d95c-11e9-8c72-fa36c0efac60.png)

So I guess zone equipment could handle ERV load while air loop is falling behind. 
Test files are ERV of 0 effectiveness (no heat recovery) with and without residual ideal loads air system, attached [here](https://drive.google.com/drive/folders/1zFN2dFPQg2JB9AvhGN_6CGbVygoI6ln7?usp=sharing)

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (both E+ 9.1 & 9.2)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
The problem here is the CurDeadBandOrSetback flag, and is updated before each zone equipment is simulated (which is why I think this worked for UnitarySytsem used as zone equipment). I removed the CurDeadBandOrSetback flag from this test in function UnitarySys::initLoadBasedControl and the problem looks to be corrected. I am not exactly sure of this but when the loads are intialized, I think prior to the air loops simulating, CurDeadBandOrSetback is set based on the initial zone loads, before any zone equipment (the ERV) operates. The air loop grabs the correct sequenced load (sequence = 2), but the CurDeadBandOrSetback flag is not in sync with those loads, it's in sync with the first equipment type (sequence = 1). So when the zone is in the deadband and the air loop operates, the UnitarySystem thinks it does not need to operate. Then the zone equipment is simulated. The ERV operates first and sends a load to the zone, which pushes the zone out of the deadband. Then the air terminal simulates, but the air delivered to the zone is based on the original CurDeadBandOrSetback flag and not what the zone needs to get back to the set point temperature. This makes me wonder if any other air loop equipment has this same issue.

void UnitarySys::initLoadBasedControl

```
        CoolingLoad = false;
        HeatingLoad = false;

        //if (QZnReq > Small5WLoad / this->ControlZoneMassFlowFrac && !DataZoneEnergyDemands::CurDeadBandOrSetback(this->ControlZoneNum)) {
        if (QZnReq > Small5WLoad / this->ControlZoneMassFlowFrac) {
            if (DataHeatBalFanSys::TempControlType(this->ControlZoneNum) != DataHVACGlobals::SingleCoolingSetPoint) {
                HeatingLoad = true;
            }
        //} else if (QZnReq < -Small5WLoad / this->ControlZoneMassFlowFrac && !DataZoneEnergyDemands::CurDeadBandOrSetback(this->ControlZoneNum)) {
        } else if (QZnReq < -Small5WLoad / this->ControlZoneMassFlowFrac) {
            if (DataHeatBalFanSys::TempControlType(this->ControlZoneNum) != DataHVACGlobals::SingleHeatingSetPoint) {
                CoolingLoad = true;
            }
        }
```

Results from balanced-erv-object defect file:

![image](https://user-images.githubusercontent.com/5778156/65606861-95df7f80-df79-11e9-93e0-99bfb15f5484.png)

**Comment by rraustad** [comment]
Furnaces and HVACMultiSpeedHeatPumps both use the CurDeadBandOrSetback flag so I suspect those models have a similar issue.
