### ISSUE TITLE
For some models, zone humidity levels change when zone multipliers are used

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#7558]
Issue overview
--------------
As a quick test in V9.2 I took example file 5ZoneSwimmingPool and compared that example to a 5x multiplier on the zone with the pool and the result, if everything is working correctly, should be the same zone conditions. Since they are different I suspect the zone multipliers are not applied correctly in a few places. I assume this would happen for any model that use these 3 LatentGain variables (ZoneLatentGain, SumLatentHTRadSys or SumLatentPool).

In function CalcPredictedHumidityRatio these 3 global variables are used to indicate other zone latent loads. The LatentGain variable here is not adjusted for zone multipliers (similar to NonAirSystemResponse in CalcPredictedSystemLoad which does account for zone multipliers).

    LatentGain = ZoneLatentGain(ZoneNum) + SumLatentHTRadSys(ZoneNum) + SumLatentPool(ZoneNum);

Example file 5ZoneSwimmingPool.idf:

  Zone,
    SPACE1-1,                !- Name
    5,                       !- Multiplier  <-- only change to example file

If 1x and 5x zone multiplier simulations are compared the results should be the same zone conditions, correct?

![image](https://user-images.githubusercontent.com/5778156/66779520-6c40b680-ee9c-11e9-8838-9097e36cbb72.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
This also seems odd. For the predicted loads reports, the sensible load to set point heat transfer rate should track one or the other of load to heating or cooling SPs (except when in the deadband?), which appears to happen. Yet for the moisture reports when the zone multipliers are used (10x on East Zone) this does not appear to happen. I had to add the predicted load reports to this example file and would rather have seen a humidification and dehumidification set point (but this was faster to get an answer).

![image](https://user-images.githubusercontent.com/5778156/66926990-0455b180-effd-11e9-9b87-cf86ce196d39.png)

**Comment by RKStrand** [comment]
@rraustad Ok, so this is not exactly what it seems.  I'm not sure that the equation you mentioned above is where the problem is for two reasons.  1) When I modify that equation to include the zone multipliers, the results aren't better--they are worse.  In fact, if you look at an annual run, the numbers in the summer are nearly identical between 1x and 5x for non-modified code.  But, if you look at winter when the people load is zero (during nighttime), then there are big differences. 2) Based on your graph above, that matches what I'm seeing in the annual run.  The winter design day is off (no people) but the summer design day results agree.  Now, why having no people in the winter (rather than summer) causes problems, that I am not sure of yet.
Now, the second series of graphs that you posted also seem strange at first, but the code actually explicitly nots that the moisture transfer rate variable does NOT have the multiplier associated with it by design.  There is a separate variable that has the multiplier applied.  Here's the code from lines ~4746 in ZoneTempPredictorCorrector:

        // Save the unmultiplied zone moisture load to a report variable
        MoisturePredictedRate(ZoneNum) = ZoneSysMoistureDemand(ZoneNum).TotalOutputRequired;

        // Apply the Zone Multiplier to the total zone moisture load
        ZoneSysMoistureDemand(ZoneNum).TotalOutputRequired *= Zone(ZoneNum).Multiplier * Zone(ZoneNum).ListMultiplier;
        ZoneSysMoistureDemand(ZoneNum).OutputRequiredToHumidifyingSP *= Zone(ZoneNum).Multiplier * Zone(ZoneNum).ListMultiplier;
        ZoneSysMoistureDemand(ZoneNum).OutputRequiredToDehumidifyingSP *= Zone(ZoneNum).Multiplier * Zone(ZoneNum).ListMultiplier;

So, I think the moisture load is actually doing what it is supposed to.  But, I'm still tracking down why the winter nighttime dew point temperature are off.

**Comment by RKStrand** [comment]
@rraustad But it is weird though because for the loads to setpoint, it reports the value that has not been multiplied by the zone multipliers (the opposite of what the humidity is doing).

**Comment by rraustad** [comment]
I imagine that this has never been seen before since sensible loads are typically used for sizing. I think the sensible and moisture reports should work identically. This came to my attention when I started thinking about sizing on latent loads. When I saw this I wondered how latent sizing would differ from sensible sizing or if there was some issue with how multipliers are applied to each.

If the autosized coil capacity is now correct with a multiplied zone (is it?) then isn't it the sensible that is working correctly? I know this will be a hard one to understand and resolve.

**Comment by RKStrand** [comment]
@rraustad Getting the moisture report to print out the same results as the sensible load (as far as whether or not they are using the zone multiplier or not) should be relatively straightforward.  But, yeah, figuring out why exactly the results are off for winter dew point may not be all that simple.  I suspect that diagnosing the problem will be most of the battle here.

**Comment by RKStrand** [comment]
@rraustad Oh...I think I have an explanation as to why the difference is being seen and now I actually think the difference should be there.  When you use a zone multiplier of 5 on just Space1-1 with the swimming pool, that means five times the return air from that zone that gets mixed with the other spaces that have a zone multiplier of 1.  When that hits the plenum, because the pool is in Space1-1, it gets a lot more humidity because of the zone multiplier of 5.  So, overall the humidity level should increase (1 part humid air mixed with 4 parts normal air should be less humid that 5 parts humid air mixed with 4 parts normal air).  Does that make sense?

I tested this theory by using a multiplier of 5 the other four spaces and that got close.  When I then also added a multiplier of 5 to the plenum, then I got nearly identical results (max diff for all hours over an annual simulation was 0.05C in the dew point temperature, average diff was 3E-05).  When the plenum had a multiplier of 1, my theory is that there is more flow through one plenum and that would be different from a heat transfer standpoint that having everything including the plenum using a multiplier of 5.

I checked this after pretty exhaustively looking through the code tracing the various components back and I simply could not find where a multiplier was either not being applied when it should or improperly applied.  What do you think?  Do you agree that the results actually make sense now?

If not, please let me know.  If you agree that, do you want me to just fix the predicted moisture load moisture transfer rate issue that you noted above?
