### ISSUE TITLE
Zone component load summary reports zero solar load when used with SizingPeriod:WeatherFileDays

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7608]
Issue overview
--------------
User file shows zero for Fenestration Solar in the Zone Component Load Summary report when used with SizingPeriod:WeatherFileDays. Switching to regular design days results in Fenestration Solar loads on the cooling day.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.2.0
 - Helpdesk ticket number 15302.

### Workaround
Use SizingPeriod:DesignDay instead of SizingPeriod:WeatherFileDays to generate the component loads report. Revert back to SizingPeriod:WeatherFileDays for final results.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added to EnergyPlusDevSupport\DefectFiles, run with Chicago weather
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mjwitte Actually, the problem is not just with the Fenestration Solar.  It is several of the other "delayed" values as well.  When I change the fraction radiant in people, lights, and equipment to something other than zero, the file with actual design days shows non-zero values in the delayed values for these items in the table while the file with the weather file period derived design days still show all zeroes.  It's clear something is wrong here because the peak loads for the actual design day are lower than the ones for the weather file period but the weather conditions for the weather file period are worse.  On the plus side, the delayed values for surfaces are non-zero.  Hoping this is a clue to what is wrong here...
