### ISSUE TITLE
VRF Condenser not simulated when one VRF TU not in Equipment List

### ISSUE THREAD

**Issue by ecoeficiente** [NREL/EnergyPlus#7651]
Issue overview
--------------
AirConditionar:VariableRefrigerantFlow with multiple terminal units is not simulated when a ZoneHVAC:TerminalUnit:VariableRefrigerantFlow terminal unit is not listed in the corresponding ZoneHVAC:EquipmentList.

In code, this unit IsSimulated property remains as false and the the condenser is not simulated according to code:
https://github.com/NREL/EnergyPlus/blob/775eef1f74efd67e959d4b15eb5061a3e3b80198/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L370-L386

**Comment by rraustad** [comment]
I would agree with this assessment. The TU would need to be removed from the TerminalUnitList or as suggested in the comments, code would need revision.

**Comment by jmarrec** [comment]
Hum, so I started investigating by creating a defect file  (https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/7000s/7651), only to realize it's already been taken care of:

https://github.com/NREL/EnergyPlus/blob/9ce5c3eda4dd9333e1dfa7ffa3690274e022584c/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L5249-L5279

eplusout.err extract:

```
   ** Severe  ** InitVRF: VRF Terminal Unit = [ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,TU5] is not on any ZoneHVAC:EquipmentList.  It will not be simulated.
   **   ~~~   ** ...The VRF AC System associated with this terminal unit may also not be simulated.
```

That portion of code is pretty redundant since it'll check TWICE (in the routine itself, then calling DataZoneEquipment::CheckZoneEquipmentList which does the same thing). And there are no unit tests to test if it works I guess. Is it worth me addressing this though?
