### ISSUE TITLE
Cannot build EnergyPlus docs without also building the EnergyPlus executable

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#7700]
Issue overview
--------------
Contributors working on documentation changes should be able to build and test the documentation without having to generate the rest of the EnergyPlus project and install the required dependencies (e.g., C++ compiler, python).

### Checklist
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@nealkruis On what platform?

**Comment by nealkruis** [comment]
@mjwitte I re-worded the description. The main idea is not requiring all of the EnergyPlus compilation tools. I am going to make an optional CMake option to not generate all the EnergyPlus targets.

**Comment by jmarrec** [comment]
I'd suggest doing it differently: Make the doc/ folder standalone instead, so one could just do `cmake ../EnergyPlus/doc` instead of `cmake ../EnergyPlus`.

refrain from using CMAKE_SOURCE_DIR / CMAKE_BINARY_DIR, but use variables PROJECT_SOURCE_DIR/PROJECT_BINARY_DIR. You can check if you have a parent if you need logic to set variables differently (such as finding EnergyPlus/cmake/BuildDocumentation.cmake, though the folder structure could change too).

I can take care of it if you want.

**Comment by nealkruis** [comment]
@jmarrec Good idea. I think it will work if we can get the EnergyPlus build information for the "title.tex.in" configuration file, too.

I'll take care of it.
