### ISSUE TITLE
Horizontal Infrared Radiation variable outputs 9999

### ISSUE THREAD

**Issue by matthew-larson** [NREL/EnergyPlus#7706]
Issue overview
--------------
Setting the Infrared Sky Radiation column in the weather file to zero results in value of 9999 being written out the Site Horizontal Infrared Radiation Rate per Area output variable.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@matthew-larson @ajscimone 9999 is the "missing value" for Horizontal Infrared Radiation Intensity, see Auxiliary Programs document, p. 64 (v9.3). So it's not clear if this is incorrect. Also, this behavior may have changed due to new options for WeatherProperty:SkyTemperature added in v9.3 https://github.com/NREL/EnergyPlus/pull/7562.

**Comment by nealkruis** [comment]
@mjwitte This was indeed fixed independently through the WeatherProperty:SkyTemperature PR. We still have some unit tests that we might as well contribute.
