### ISSUE TITLE
Scrub references to Example File Generator from documentation

### ISSUE THREAD

**Issue by amirroth** [NREL/EnergyPlus#7833]
Issue overview
EnergyPlus Example File Generator has not been available for some time. Yet, the documentation continues to reference it, creating confusion.

**Comment by RKStrand** [comment]
@amirroth I did a search on various PDFs for EnergyPlus (V9.2 docs).  The only PDF I found references to this were in the Tips and Tricks document.  Is that also what you found or are there more references to EEFG that you noticed elsewhere?  If so, I will go back through and do more searches.

**Comment by RKStrand** [comment]
@amirroth I've been looking at this document and it probably needs some updating.  A lot of the web site links in this document are not current (I click the link and get error messages).  So, if the answer to my previous comment is that the references are only in Tips and Tricks, do you want to convert this into a general clean-up of Tips and Tricks in addition to getting rid of the EEFG references?

**Comment by mjwitte** [comment]
@RKStrand I would say do as much as is reasonable without a lot of effort. At a minimum, fix or remove dead links.

**Comment by RKStrand** [comment]
@amirroth @mjwitte Looks like someone has already done some of this?  I'm creating a new Tips and Tricks from what's in develop and someone has clearly edited things here since V9.2.  I'm double checking on the various links to make sure they go to a live page.  I'll summarize when I finish the entire document.  One thing that I did notice: the following web page has not been updated since Version 8.4

https://energyplus.net/features

**Comment by RKStrand** [comment]
@amirroth @mjwitte There were quite a lot of things in Tips and Tricks that were still off.  I have fixed all of the bad hyperlinks and done some other edits in the process (glaring formatting issues, addition of language like where there was a totally blank chapter).  While not a full overhaul of the document, this is now up-to-date and looks better.
