### ISSUE TITLE
Address total/sensible/latent calculations issues for DX cooling coils and others 

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#7855]
Issue overview
--------------
The total/sensible/latent calculations in DX cooling coils needs to be revised to use most appropriate equation in calculating sensible and latent cooling rates. Currently, the DX cooling coils sensible cooling rate calculation is based on minimum humidity ratio of coils inlet and outlet node, when it should have been average of them. Using minimum humidity ratio sometimes may lead to incorrect sensible/latent split. Currently, only VRF DX cooling coil uses average Hum Rat. This issue will also review if there other places in the code that may need similar fix. This is not as such a defect but it is the moist appropriate approach and leads tractable sensible/latent split of the total cooling rate.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version 9.2 EnergyPlus 
 -  see comments in pull request https://github.com/NREL/EnergyPlus/pull/7850 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
added modified test files as defect file.

**Comment by mjwitte** [comment]
@Nigusse I follow the derivation in the attached pdf from [this comment in PR7861](https://github.com/NREL/EnergyPlus/pull/7861#issuecomment-616895307), but I feel like we're going in circles on this.

Looking back at the EnergyPlus Archive, the use of the minimum humidity ratio was intentional per comments in CR6772 ( #1561). The code changes are here in https://github.com/NREL/EnergyPlusArchive/commit/220cd285a2e456f6a0841385b875ecac28e51fe4 .

I think the difference in philosophy comes from the question of where to attribute the temperature change of the removed moisture: is that part of the latent load or part of the sensible load. If I'm following correctly, the current min humrat method attributes all of the incoming energy of the removed moisture to the latent load. The proposed average humrat method attributes (some? all?) the temperature change of the removed moisture to sensible rather than latent. In the case of a dry coil, the two give the same result.

I would be more comfortable with this if there was a 3rd party reference that discusses how to split the sensible and latent coil load for a wet coil. I've looked in the ASHRAE HVAC2 Toolkit, and a couple of other reference books, but I don't find this calculation. These sources are interested in the total coil load.

**Comment by Nigusse** [comment]
Below are three issues that need to be addressed here:
- *How to treat the sensible cooling component of the moisture removed.* The current method (minimum humidity ratio) assumes de-humidification occurs at constant temperature but real cooling de-humidification process is variable temperature due to change in dew-point as the humidity ratio in the moist air decreases. The proposed change implies that part of the moisture removed (may be half) goes through sensible cooled before it reaches it dew-point and removed. I think the proposed change is more closer to the actual cooling de-humidification process.

- *The current calculation does not guarantee sensible and latent split add up to the total when the process involves humidity ratio change.* However, the proposed change guarantees the latent/sensible split to sum up to the total regardless of the process.

- *The current latent heat rate calculation that uses Q_latent = h_fg * m_dot * (W_2 - W_1)*
This equation does not yield Q_latent that guarantee heat balance when used with Q_sensible calculated using the minimum humidity ratio and current h_fg function.

There is a book that I referred when I first investigated this problem for issue #6950. I borrowed this book from Gu and I do not have this book in my custody now. I tagged Gu and Rich @lgu1234 @rraustad to comment about this.

**Comment by mjwitte** [comment]
Where does this separate latent calculation occur? Every place I've looked at (just spot checking) just sets Latent = Total - Sensible.

**Comment by Nigusse** [comment]
I agree in most places I see Latent = Total - Sensible. But there are places where the latent is calculated in kgH20/s ( = m_dot * detlaW) like [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneAirLoopEquipmentManager.cc#L837-L838) and later it is multiplied by h_fg somewhere else to get the latent rate in W. Or in some places h_fg is used to back out HumRat from Q_latent and m_dot. For instance, in DXCoils.cc see the code below (I cannot  provide link):

`
     OutletAirHumRat = InletAirHumRat - DXCoil(DXCoilNum).LatCoolingEnergyRate / Hfg / DXCoil(DXCoilNum).InletAirMassFlowRate;`

Using Latent = total - sensible and the current h_fg is does not guarantee heat balance.

**Comment by lgu1234** [comment]
There are many ways to split sensible and latent from the total. The way Bereket used with average value is a choice from a text book I have. Unfortunately, the book is in my office and I am at home. The existing method using min W is a way also. One is not better than the other theoretically. I prefer to use the existing one, so that no more changes are needed, as long as a sum of sensible and latent is equal to the enthalpy difference between two points. 

If some latent calculation is not good, we only need to correct latent portion. For example, hfg should be replaced by hg.

**Comment by Nigusse** [comment]
Okay. I hear Mike and Gu prefer to keep the existing sensible heat rate calculation. The only thing that can be salvaged from this branch is common function for calculating total/sensible/latent rates albeit the sensible heat rate calculation should roll back to use the minimum *Hum Rat*. Please let me know what your thoughts are before me making any changes. @mjwitte @lgu1234
