### ISSUE TITLE
Final Prep for 9.3 Release

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#7878]
Any last minute items found during testing, or just general todo items.
- [ ] Generate and post API documentation on the release page or somewhere.
- [x] Four example files still have a v9.2 version object: 
PythonPluginLrgOff_GridStorageSmoothing.idf
PythonPluginWindowShadeControl.idf
SolarShadingTestGPU.idf
~_ExternalInterface-functionalmockupunit-to-schedule.idf~
- [ ] ~Add PythonPlugin:SearchPaths object to python examples so they'll run with ep-launch classic?~

**Comment by Myoldmopar** [comment]
@mjwitte I didn't see the version 9.3 in the ExternalInterface file.  Can you confirm?  I've fixed the version in the other 3 files.  

As for the search paths, that's tricky.  The best solution is for EPLaunch to grab the Python file and move it into the run folder.  I'm not sure what we would put in the search paths.  There are four possible places to put the Python code:
 - In the same folder as the EnergyPlus.exe (always available)
 - In the same folder as the input file (on by default, but can be disabled)
 - In the current working directory (on by default, but can be disabled)
 - In hardcoded paths listed in the search paths object.

For the next release, we should either:
 - Fix EPLaunch so that it copies in Python scripts
 - Add another field to the search paths object to find Python in the parent object -- but we'll need to figure out which parent.  Parent of IDF directory?  Parent of working directory?

For this release, we should just tell the intersection of users with "classic EPLaunch" and "Python plugins" to just copy the Python scripts into a valid location...maybe the install folder?

**Comment by mjwitte** [comment]
My search on `9.2;` probably picked up this line in the external interface file `    259.2;                   !- Volume {m3}` and I wasn't paying close attention. Crossed that file off the list.

Regarding the python search paths, this object would solve the problem for classic ep-launch. It shouldn't cause any other problems on other systems?
```
PythonPlugin:SearchPaths,
    Paths,                   !- Name
    Yes,                     !- Add Current Working Directory to Search Path
    Yes,                     !- Add Input File Directory to Search Path
    ..\;                     !- Search Path 1
```
But, yeah, since classic EP-Launch still makes a temporary folder and copies files into it, the cwd and input file directory are the same as the temporary folder. Copying the .py files into the root install folder works, so that's fine for now.
