### ISSUE TITLE
Documentation index.html is not installed on Windows

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7953]
Issue overview
--------------
The documentation index.html file isn't getting installed in the Documentation folder on Windows. So, the start menu link which points to it fails. Looks like this has been missing starting with v8.5.0.

### Details
Some additional details for this issue (if relevant):
 - Platform Windows
 - Version of EnergyPlus 9.3.0
 - Helpdesk ticket number 15454

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
oops, didn't mean to close it, clicked on the wrong button.

This is what happens in V920 (same in V930). The startup menu link is broken because index.html isn't installed indeed.

![image](https://user-images.githubusercontent.com/5479063/81586520-eb0bbc80-93b5-11ea-8b1c-194479fb6574.png)

![image](https://user-images.githubusercontent.com/5479063/81586570-f828ab80-93b5-11ea-80fb-d6712416e7ee.png)
