### ISSUE TITLE
ZoneHVAC:FourPipeFanCoil with electric heating coil and multispeed fan fatals out

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#8025]
Issue overview
--------------
ZoneHVAC:FourPipeFanCoil with electric heating coil and multispeed fan fatals out
```
   ** Severe  ** SetComponentFlowRate: trapped plant loop node id = 0
   **  Fatal  ** SimulateWaterCoilComponents: Coil not found=ZONE1FANCOILHEATINGCOIL
```

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.3.0-64d91887f6
 - Unmethours [44028](https://unmethours.com/question/44028/e-doas-night-cycle-control-and-fourpipefancoil-multispeedfan-control-questions/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached: 
[FanCoilAutoSize_MultiSpeedFan-ElectricHeat.idf.txt](https://github.com/NREL/EnergyPlus/files/4704695/FanCoilAutoSize_MultiSpeedFan-ElectricHeat.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
I stepped through the code using the defect file provided. I think, the MultiSpeedFan capacity control method in 4PipeFanCoil units was designed to work with hot-water heating coil type only. Since the current code does not have a check for heating coil type for this capacity control and does not anticipate electric heating coil, the simulation fatal out when the 4PipeFanCoil unit tries to simulate water-coil without the required water-coil input data. 

There are two approachs in addressing this issue:
(1) Trap when the heating coil type is not hot-water and the capacity control method is MultiSpeedFan and fatal out with appropriate sever error message. 
(2) Support electric heating coil type with MultiSpeedFan capacity control type.

@mjwitte which option do you recommend or have a different suggestion?

**Comment by mjwitte** [comment]
I would prefer (2) Support electric heating with multispeedfan. It may be worth checking the other capacity control types as well to see if they all work with electric heat. @rraustad would you agree?

**Comment by rraustad** [comment]
I think option 2 is the only way forward. If users want multi-speed fan and choose electric heating coil, and electric heating coils are allowed in 4PFC, it should work without a fatal error.

**Comment by Nigusse** [comment]
OK. will go with option 2. @mjwitte @rraustad Thanks.

**Comment by Nigusse** [comment]
@mjwitte @rraustad I tested *FanCoilUnits's* capacity control methods: *ConstantFanVariableFlow*, *CyclingFan*,   *VariableFanVariableFlow*, *VariableFanConstantFlow*, *MultiSpeedFan*, and *ASHRAE90VariableFan*. All methods run successfully using electric heating coil. However, the zone temperature are well controlled for all methods but *ASHRAE90VariableFan*.  I will post new issue for *ASHRAE90VariableFan* capacity control method.
