### ISSUE TITLE
Running EnergyPlus v9.3 through symlink produces DLL error

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#8037]
Issue overview
--------------
There are PATH related issues on unix systems when using a symlink to execute EnergyPlus:

```
**FATAL:DLL problem cause program termination
libc++abi.dylib: terminating with uncaught exception of type EnergyPlus::FatalError: DLL problem cause program termination
Abort trap: 6
```

This is related to needing to find the executable directory for the new API.

### Details
Some additional details for this issue (if relevant):
 - MacOS (symlink installed only through DMG installer)
 - EnergyPlus v9.3

**Comment by Myoldmopar** [comment]
Specifically it's for the Python Plugins, not the API, but that's a bit down in the weeds.  In any case, it's just due to the code that lazily loads the Python DLL wrapper, which it expects to find in the same directory as the currently running binary image.  This error is produced because the current file system implementation does not walk the symlink to find the target binary.  Instead it just gives back the directory of the symlink itself, which won't have the DLL in it. 

### Workaround
Just execute energyplus using the full path to the underlying binary:
 - Do: `/Applications/EnergyPlus-9-3-0/energyplus -D /path/to/myFile.idf`
 - Don't: `energyplus -D /path/to/myFile.idf`

### Fix
Either get the current file system implementation to walk through symlinks, or if we get to C++17, just use the C++FileSystem and eliminate the need for our hand-rolled code.
