### ISSUE TITLE
Unexpected behavior related to HVAC Sizing Summary: Zone Sensible Cooling table

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/EnergyPlus#8124]
Issue overview
--------------
**Observed Behavior**:  When simulating the attached file "**in-fails.idf**", the E+ "**HVAC Sizing Summary**" **Zone Sensible Cooling** table in the HTML output **fails to populate with ANY data**, which is causing issues with downstream SQL queries that retrieve data from this view , and which is post-processed by external tools.

![image](https://user-images.githubusercontent.com/5746765/86178842-1c238600-baf7-11ea-9e9b-92abc52f0de0.png)

**Desired Behavior**: When simulating using the file "**in-fails.idf**", the E+ "**HVAC Sizing Summary**" **Zone Sensible Cooling** table in the HTML output (and the SQLite tablular file used to render it) should populate with non - empty values. 

[in-works.zip](https://github.com/NREL/EnergyPlus/files/4854476/in-works.zip)
[in-fails.zip](https://github.com/NREL/EnergyPlus/files/4854477/in-fails.zip)

**Details**: 
To reproduce the issue, zip files including (2) idf files have been provided:

1. in-works.idf
2. in-fails.idf

In addition, the .err files and .html output reports generated from simulating the idf files, have been included in each zipfile. 

The "in-fails.err" file generated from "in-fails.idf" suggests (in lines 47/48) the following:

   **** Warning ** Calculated design cooling load for zone=LIVING SPACE is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.**

Inspecting "in-fails.idf", It is unclear to the user how the "calculated design load" for the living space thermal zone would be == 0.00. To this end, the "in-fails.idf" file has been carefully inspected - the "living space" thermal zone has been confirmed to have a valid cooling design day description, skin (envelope) loads, a dual setpoint thermostat object configured properly for cooling, including "summer design day" schedules, and internal gains (lights/equipment) with cooling design day values schedule set to 1.0. At a minimum, the user believes the "skin loads" should generate a non zero design cooling load. A value of 0 seems like a bug.   

As a comparative test, the "in-works.idf" file contains much of the same physical description of the "in-fails.idf" file,  - including IDENTICAL Sizing:Zone and ZoneControl:Thermostat objects.  Changes between the two .idf files include materials properties and construction, and thus reduced HVAC hard sized values, but nothing that would substantiate the observed behavior. The "in.works.idf file **does not produce the design cooling load warning**, and the tabular values in the HVAC Sizing Summary: Zone Sensible Cooling table for this .idf file are non zero. 

In both idf files, the Coil:Cooling:DX:SingleSpeed object (* a child of a AirLoopHVAC:UnitarySystem object) has it's capacity "hard sized". 

Some additional details for this issue : Windows 10 64 Bit 
 - Version of EnergyPlus: 9.3

**Comment by mdahlhausen** [comment]
@chrisbalbach I'm getting this error to in openstudio-standards builds.  For me, the chiller and pump sizing fields are empty except for 'None'.  So this is more than just zone sizing.  I would suggest renaming the issue "eplus html output fields set to 'None'" or something like this.

Developers - this is a major bug and a blocker for openstudio-standards.

**Comment by mdahlhausen** [comment]
Here is an example .idf that just runs the sizing run, so use any weather file.  The output html is missing sizing information for the pumps and chillers in the model. [example.zip](https://github.com/NREL/EnergyPlus/files/4887866/example.zip)

**Comment by lgu1234** [comment]
@chrisbalbach I am working on this issue and ran in-fails.idf with Chicago weather file. Here is what I got:

![Capture](https://user-images.githubusercontent.com/5970656/86966095-890dd000-c136-11ea-9ddb-3711dfe33d38.PNG)

Could you let me know which weather file you used, so that I can repeat what you got?

**Comment by lgu1234** [comment]
@chrisbalbach When Albany TMY3 weather file is used, I repeat what you got.

@Myoldmopar @mjwitte The empty results are caused by zero cooling sizing. Here is line extracted from err:

   ** Warning ** Calculated design cooling load for zone=LIVING SPACE is zero.

I also checked epluszsz.csv and find zero cooling load. When I use Chicago weather, there are cooling loads in the same sizing file, and reported results are OK (see my comment above).

My concern is that no report is intended when cooling load = 0.

Please let me know your concerns.

**Comment by mdahlhausen** [comment]
@lgu1234 the error in my file is related, but impacts the chiller and pump sizing - even though those objects are present in the model and are sized in early versions of EnergyPlus.

**Comment by lgu1234** [comment]
@mdahlhausen @chrisbalbach @Myoldmopar @mjwitte The existing outputs are intended to generate output with non-zero cooling loads. In order to generate non - empty values, I intend to report zero values as shown below. Are you OK with the changes?

![Revised](https://user-images.githubusercontent.com/5970656/87044447-85288f00-c1c4-11ea-81b6-3ac8babd5544.PNG)

**Comment by mjwitte** [comment]
@mdahlhausen You said 

> impacts the chiller and pump sizing - even though those objects are present in the model and are sized in early versions of EnergyPlus.

What version? Can you provide an idf that shows values in an older version but not now?

**Comment by mjwitte** [comment]
@mdahlhausen To be clear, I'm asking for the old version file. If the behavior has changed, we need to track down when. In the example attached above with v9.3, the chiller sizing shows in the Component Sizing Summary.

![image](https://user-images.githubusercontent.com/4991075/87047247-dc783080-c1bf-11ea-8706-dc7ea5e2f609.png)

Every autosized component value should be reported in the Component Sizing Summary.

**Comment by mdahlhausen** [comment]
@mjwitte here is the comparison between the .idf in [E+9.2 vs. E+9.3](https://github.com/NREL/EnergyPlus/files/4899117/E9_2_vs_E9_3.zip).  The difference is in the EquipmentSummary section - the E+9.3 version is missing the chiller and pump sizing information.
The main issue I'm facing is that with E+9.3 and OpenStudio 3.0, the OS API rated flow rate method for the pumps and rated capacity method for the chiller do no work after the sizing run.

**Comment by mjwitte** [comment]
@mdahlhausen Hmm, if I take your E9_2.idf and transition it to v9.3, the chiller, pumps, etc. do appear in the EquipmentSummary report. But for the E9_3.idf which has similar (same?) equipment, the chiller, pumps, etc. are *not* showing in the EquipmentSummary report.
@lgu1234 lobbing the ball back into your court!

**Comment by lgu1234** [comment]
I think this issue deals with Zone Sensible Cooling table. I am going to output zero values for the scenario of zero cooling load. It may need a new issue to deal with EquipmentSummary, so that each issue deals with a specific case.
@mdahlhausen Although I can post a new issue to deal with EquipmentSummary, it would be better for you to post it due to better understanding.
