### ISSUE TITLE
EnergyPlus distribution size with added Python-related files (9.3) - even when Python is not really needed

### ISSUE THREAD

**Issue by DavidHollman** [NREL/EnergyPlus#8194]
It looks as though Python dependencies are now required to be distributed with EnergyPlus, even in cases when they are not actually needed for runtime execution of the inputs.

This was actually previously mentioned in https://github.com/NREL/EnergyPlus/issues/7877#issuecomment-606047739:

> to run E+ 9.3 from the command line on Windows, you now need to have the python37.dll and the python_standard_lib directory in the same directory as your in.idf and in.epw (and the IDD, energyplus.exe, and energyplusapi.dll; but that was the same as before). I'm not totally sure if the IDD is required anymore, but I do it out of habit.
> 
> However, it'd be nice to see for the next release the python stuff be like expand objects - if there are no python IDD objects, the DLL and library directory are not needed. 

(I don't think there is another open issue already covering the same ground, and that comment seemed to be considered closed shortly after it was left.)

For people integrating EnergyPlus into other applications - which I understand is the scenario the recent API-oriented changes are meant for - being able to include a more minimal set of files would be a real benefit.

When using version 9.2.0 (32 bit) the set of EnergyPlus my project's included EneryPlus files were about 50 MB. Now with 9.3.0 it looks like that has increased to 116 MB altogether, most of which is the `python_standard_lib` subfolder.  That seems to be a pretty significant increase in size which ultimately will get passed on to every end-user of any application which includes EnergyPlus as a component. As far as I am aware there are a number of different projects / products out there which are doing that (or planning to).

The suggestion made in the comment above seems like the right general approach to me. Perhaps this would also tie into some of the work mentioned in https://github.com/NREL/EnergyPlus/issues/7888 to deal with cyclic dependencies (?)

Thanks

**Comment by Myoldmopar** [comment]
Thanks for this issue.

As for the initial comment there, indeed that comment was considered addressed when @bonnema replied with an understanding that he didn't need to copy things around anymore.  Thanks to the command line interface on EnergyPlus, you can pretty freely put IDF and EPW files in your desired directories, no need to copy a build of EnergyPlus around anywhere.

There are a couple things you could do to address the size of the EnergyPlus package.  For one thing, you could always build a custom version of EnergyPlus with `LINK_WITH_PYTHON` turned off, which would not include any of this extra stuff.  I know custom builds aren't for everyone, and that is totally fine.  (As an aside, our 32-bit Windows packages don't include the link to python, so that package would be much smaller if you don't need 64-bit.)  

Alternatively, if you can guarantee that your program will never try to leverage any of the E+ Python Plugin stuff, you could possibly delete the Python DLL and the Python standard library entirely.  You would need to use the fixes we made in the 9.3 bugfix release, as that fixed up the connection between EnergyPlus and Python dramatically.

Moving forward, I will look into adding non-python packages for all our configurations.

**Comment by DavidHollman** [comment]
I appreciate the quick reply. You've given us a couple of possible workarounds which we'll look into in the short term. Eventually if Python is more cleanly separated for cases like ours, so much the better.

I'm curious - what's the reason for the difference between the 32 and 64 bit packages?

**Comment by Myoldmopar** [comment]
Our CI build system only had Python 64 bit installed, and the bitness must match the bitness of EnergyPlus which will link to it.  I spent a few minutes trying to get it set up with both versions of Python, and then realized maybe there was some benefit to just building without linking to Python.  The 32-bit download is **not** heavily downloaded, and I would imagine we will stop producing it at some point, so I didn't feel like spending time getting it fixed up, and I left it at that.

**Comment by Myoldmopar** [comment]
I think my note about building a custom package still applies as a workaround to avoid the bulk of the Python interpreter and library.  And I feel I should note that has _nothing_ to do with being able to call EnergyPlus via API, so that would be fully available even if the Python "Plugin" system wasn't build into the package.  I think this issue is OK to close now, reopen if it needs more discussion!

**Comment by DavidHollman** [comment]
Also, I can confirm that running without python using the "9.3-bugfix" release works fine. Sorry I didn't remember to update back here sooner after I tried that out.
