### ISSUE TITLE
Unitary System Ancillary Electric Power inputs have no effect on results

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#8230]
Issue overview
--------------
I have two IDFs where the only difference between them is that I've set the `Ancillary On-Cycle Electric Power` and `Ancillary Off-Cycle Electric Power` fields to non-zero values for the Unitary System. I expect to see increased energy use but the simulation results are unchanged. The "Unitary System Ancillary Electric Power" output variable also reports zeroes, whereas I expect it to produce 100 W for every timestep.

[zero.idf.txt](https://github.com/NREL/EnergyPlus/files/5120459/zero.idf.txt)
[nonzero.idf.txt](https://github.com/NREL/EnergyPlus/files/5120461/nonzero.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - EnergyPlus 9.3

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Ancillary is only applied to multispeed and the new coil models. This should be expanded to allow ancillary power to be applied regardless of coil type.

**Comment by rraustad** [comment]
As a follow up to my previous comment regarding reporting of acilllary power.

    } else if (SELECT_CASE_var == CoilDX_MultiSpeedCooling || (SELECT_CASE_var == CoilDX_Cooling)) {
        SetupOutputVariable("Unitary System Cooling Ancillary Electricity Energy",

My plan here is to add the ancillary electric power report to all other coil types. This seems reasonable since all system types have ancillary power consumption. Even water coils could have an electric water valve actuator (which probably should be reported in the water coil object for coil-on-branch applications) and systems could have contactors and control transformers.

While reviewing this I also noticed that the unitary system total power/energy report was also specific to these 2 coil types:

    } else if (SELECT_CASE_var == CoilDX_MultiSpeedCooling || (SELECT_CASE_var == CoilDX_Cooling)) {
        SetupOutputVariable("Unitary System Electricity Rate",
        SetupOutputVariable("Unitary System Electricity Energy",

These reports sum the total electricity across all components in the UnitarySystem, for example:

    this->m_ElecPower = locFanElecPower + DataHVACGlobals::DXElecCoolingPower + DataHVACGlobals::DXElecHeatingPower +
                                    DataHVACGlobals::ElecHeatingCoilPower + this->m_TotalAuxElecPower;
    this->m_ElecPowerConsumption = this->m_ElecPower * ReportingConstant;

Of course these summations would be different depending on the coil type.

Regarding the "Unitary System Ancillary Electric Power" output variable, this defect file requests that information but it is not reported to the csv since that variable is specific to the 2 coil types previously described and this file uses:

  Coil:Heating:WaterToAirHeatPump:EquationFit, !- Heating Coil Object Type
  Coil:Cooling:WaterToAirHeatPump:EquationFit, !- Cooling Coil Object Type

In fact the csv wasn't even created until I added Output:Variable,*,Site Outdoor Air Drybulb Temperature, hourly; so not sure how ancillary energy could have shown 0's (description says "also reports zeroes"). FYI, I am testing in V9.4.

**Comment by rraustad** [comment]
I just checked that version 9.3.0-RC2 did have Unitary System Ancillary Electric Power and this report was removed for some reason. And it was always reported but would have shown 0 for the coil types uses in the input file.

Update: Nope, it wasn't removed, the name was changed to: Unitary System Ancillary Electricity Rate

![image](https://user-images.githubusercontent.com/5778156/94728552-6868a700-032e-11eb-8715-5cfb142945a1.png)

**Comment by rraustad** [comment]
Here's a plot of calculated Ancillary Power with OffPower = 50 and OnPower = 100 versus PLR.

![image](https://user-images.githubusercontent.com/5778156/94757536-85ba6700-0368-11eb-8f02-a470bc786710.png)

And here is the defect file (with off power = 50) for Jan 1 - Jan 31 with a time series plot and then scatter plot of power vs PLR.

![image](https://user-images.githubusercontent.com/5778156/94757957-daaaad00-0369-11eb-830b-f585ec613b04.png)
