### ISSUE TITLE
EnvironmentPeriods table in SQL output did not contain all environment data

### ISSUE THREAD

**Issue by hongyuanjia** [NREL/EnergyPlus#8268]
Issue overview
--------------
The `EnvironmentPeriods` table in SQL output did not contain data of all environment period index mentioned in the `Time` table.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10
 - Version of EnergyPlus: v9.2

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: 
[RefBldgLargeOfficeNew2004_Chicago.idf.txt](https://github.com/NREL/EnergyPlus/files/5200236/RefBldgLargeOfficeNew2004_Chicago.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

In the `Time` table, we have `4`, `5`, `6`, `7`, `1`, and `2`, six environment period indices in total, while in the `EnvironmentPeriods` table, there is only two environment periods: `1` and `2` which correspond to two sizing periods in the IDF files. So I have no ideas where the `4` to `7` environment periods came from. The IDF was the example file distributed with EnergyPlus with only 2 sizing periods. Note that in the output CSV file, there were 150 rows, the same number as the rows in the `Time` table.

Contents of `Time` table (pls ignore the cases of column names): 
```
#      time_index  year month   day  hour minute   dst interval
#           <int> <int> <int> <int> <int>  <int> <int>    <int>
#   1:          1     0     1    21     1      0     0       60
#   2:          2     0     1    21     2      0     0       60
#   3:          3     0     1    21     3      0     0       60
#   4:          4     0     1    21     4      0     0       60
#   5:          5     0     1    21     5      0     0       60
#  ---                                                         
# 146:        146     0     7    21    21      0     0       60
# 147:        147     0     7    21    22      0     0       60
# 148:        148     0     7    21    23      0     0       60
# 149:        149     0     7    21    24      0     0       60
# 150:        150     0     7    31    24      0    NA    44640
#      interval_type simulation_days        day_type
#              <int>           <int>          <char>
#   1:             1               1 WinterDesignDay
#   2:             1               1 WinterDesignDay
#   3:             1               1 WinterDesignDay
#   4:             1               1 WinterDesignDay
#   5:             1               1 WinterDesignDay
#  ---                                              
# 146:             1               1 SummerDesignDay
# 147:             1               1 SummerDesignDay
# 148:             1               1 SummerDesignDay
# 149:             1               1 SummerDesignDay
# 150:             3               1            <NA>
#      environment_period_index warmup_flag
#                         <int>       <int>
#   1:                        4          NA
#   2:                        4          NA
#   3:                        4          NA
#   4:                        4          NA
#   5:                        4          NA
#  ---                                     
# 146:                        2          NA
# 147:                        2          NA
# 148:                        2          NA
# 149:                        2          NA
# 150:                        2          NA
```

Contents of `EnvironmentPeriod` table:
```
#    environment_period_index simulation_index
#                       <int>            <int>
# 1:                        1                1
# 2:                        2                1
#                      environment_name environment_type
#                                <char>            <int>
# 1:    CHICAGO ANN HTG 99.6% CONDNS DB                1
# 2: CHICAGO ANN CLG .4% CONDNS WB=>MDB                1
```

**Comment by jmarrec** [comment]
Using a debugger to print the values, this is what the numbers in the "Time" table mean:

| DataEnvironment::CurEnvirNum | DataEnvironment::EnvironmentName                      |
|------------------------------|-------------------------------------------------------|
| 1                            | CHICAGO ANN HTG 99.6% CONDNS DB                       |
| 2                            | CHICAGO ANN CLG .4% CONDNS WB=>MDB                    |
| *3*                            | *RUN PERIOD 1*                                          |
| 4                            | CHICAGO ANN HTG 99.6% CONDNS DB HVAC Sizing Pass 1    |
| 5                            | CHICAGO ANN CLG .4% CONDNS WB=>MDB HVAC Sizing Pass 1 |
| 6                            | CHICAGO ANN HTG 99.6% CONDNS DB HVAC Sizing Pass 2    |
| 7                            | CHICAGO ANN CLG .4% CONDNS WB=>MDB HVAC Sizing Pass 2 |

3 isn't shown since it's not simulated for the Weather File run Period. The "Sizing passes" is because "Do HVAC Sizing Simulation for Sizing Periods" is set to "Yes".

```
  SimulationControl,
    YES,                     !- Do Zone Sizing Calculation
    YES,                     !- Do System Sizing Calculation
    YES,                     !- Do Plant Sizing Calculation
    YES,                     !- Run Simulation for Sizing Periods
    NO,                      !- Run Simulation for Weather File Run Periods
    YES,                     !- Do HVAC Sizing Simulation for Sizing Periods
    2;                       !- Maximum Number of HVAC Sizing Simulation Passes
```

**Should the "Sizing passes" periods be added to the "EnvironmentPeriods" table? It does feel weird seeing primary keys in a table that don't exist in said table.**

**Comment by hongyuanjia** [comment]
@jmarrec Thanks for the information. I did not know that enabling "Do HVAC Sizing Simulation for Sizing Periods" will introduce extra run periods.

It would be good if the EnvironmentPeriods could contain all run periods. Otherwise, the foreign key `EnvironmentPeriodIndex` in Time table will have values that do not exist in the original primary key in EnvironmentPeriods table.

**Comment by jmarrec** [comment]
Looking more into it, I think the fix is different actually. 

These HVAC Sizing Simulation passes should NOT end up in the Time table or anywhere else in the SQL at all. Unless you have set either the `REPORTDURINGHVACSIZINGSIMULATION=Yes` environment variable  or the equivalent `ReportDuringHVACSizingSimulation` option in `Output:Diagnostics` 

```
Output:Diagnostics,
  ReportDuringHVACSizingSimulation;
```

https://bigladdersoftware.com/epx/docs/9-4/module-developer/environment-variables-to-assist-running.html#reportduringhvacsizingsimulation-cause-sqlite-reporting-during-hvac-sizing-simulations

https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-simulation-parameters.html#outputdiagnostics

**Comment by hongyuanjia** [comment]
@jmarrec Thanks for looking into this.
