### ISSUE TITLE
Change EquationFit coils to reference curve objects

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#8352]
Issue overview
--------------
The EquationFit coil objects (like `Coil:Cooling:WaterToAirHeatPump:EquationFit` and `Coil:Heating:WaterToAirHeatPump:EquationFit`) have curve coefficients embedded in them as opposed to referencing standalone curve objects like all other coils. It would be nice if curves could be referenced instead, as this would provide additional flexibility to use EMS if needed.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
Alternatively, could add actuators directly to the Coil:Foo:WaterToAirHeatPump:EquationFit objects to allow the coefficients (curve outputs) to be actuated.

**Comment by mjwitte** [comment]
Changing this to reference curve objects also allows the user to use different equation forms and to use lookup tables. So that would be the preferred path. Are there any other objects that still have coefficients in the object rather than using curves? Fan:VariableVolume still has coefficients, but that object is planned to be removed (transitioned to Fan:SystemModel) so that's not worth updating. Not sure if there are any others lurking.
