### ISSUE TITLE
Ideal Loads with zero cooling capacity is reporting values for Zone Air System Sensible Cooling Rate

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#8365]
Issue overview
--------------
The defect file ideal loads system has cooling capacity set to zero, yet there are significant amounts of "Zone Air System Sensible Cooling Rate" being reported. These should be zero or very close to it.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.4.0 release
 - @shorowit e-mail 23 Oct 2020

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added in EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by matthew-larson** [comment]
@mjwitte 
The problem comes from the fact that even when the cooling capacity is set to zero, there is still a supply mass flow rate.  During the CorrectZoneAirTemp function in [ZoneTempPredictorCorrector.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneTempPredictorCorrector.cc#L5058), the zone air temperature is modified, which is then used to calculate the zone load comparing the `ZoneEnthalpyIn` (based on previous zone temperature) with the modified zone temperature and mass flow rate, resulting in a nonzero load.  From this result is where the "Zone Air System Sensible Cooling Rate" is being calculated.

```
                // SNLOAD is the single zone load, without Zone Multiplier or Zone List Multiplier
                SNLoad = ZoneEnthalpyIn - (Node(ZoneNodeNum).MassFlowRate / ZoneMult) * CpAir * Node(ZoneNodeNum).Temp +
                         NonAirSystemResponse(ZoneNum) / ZoneMult + SysDepZoneLoadsLagged(ZoneNum);
```

The easiest fix would be to make sure the mass flow rate is zero when the cooling capacity is zero during cooling.  The place to do this appears to be in the CalcPurchAirLoads function in [PurchasedAirManager.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PurchasedAirManager.cc#L2209) where the `SupplyMassFlowRateForCool` is set based on the zone cooling demand, the specified `.MinCoolSuppAirTemp`, and the zone temperature.  I'm thinking the `SupplyMassFlowRateForCool` should be constrained to the capacity limit if defined (`PurchAir(PurchAirNum).MaxCoolTotCap`), either by restricting the `DeltaT` (zero for when the capacity is zero for example) or have `QZnCoolSP` be the minimum of `QZnCoolSP` and the limited capacity.  This may only be necessary if the capacity is zero however.

```
                SupplyMassFlowRateForCool = 0.0;
                if (CoolOn) {
                    CpAir = PsyCpAirFnW(ZoneAirHumRat(ActualZoneNum));
                    DeltaT = (PurchAir(PurchAirNum).MinCoolSuppAirTemp - Node(ZoneNodeNum).Temp);
                    if (DeltaT < -SmallTempDiff) {
                        SupplyMassFlowRateForCool = QZnCoolSP / CpAir / DeltaT;
                    }
                }
```

The capacity isn't capped until later in the function [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PurchasedAirManager.cc#L2278) and adjusts the `SupplyEnthalpy` and `SupplyTemp`.  

```
                    // Check sensible load vs max total cooling capacity, if specified, and adjust supply temp before applying humidity controls
                    // Will check again later, too
                    if ((PurchAir(PurchAirNum).CoolingLimit == LimitCapacity) || (PurchAir(PurchAirNum).CoolingLimit == LimitFlowRateAndCapacity)) {
                        CpAir = PsyCpAirFnW(MixedAirHumRat);
                        CoolSensOutput = SupplyMassFlowRate * (MixedAirEnthalpy - SupplyEnthalpy);
                        if (CoolSensOutput >= PurchAir(PurchAirNum).MaxCoolTotCap) {
                            CoolSensOutput = PurchAir(PurchAirNum).MaxCoolTotCap;
                            SupplyEnthalpy = MixedAirEnthalpy - CoolSensOutput / SupplyMassFlowRate;
                            SupplyTemp = PsyTdbFnHW(SupplyEnthalpy, SupplyHumRat);
                            // This is the cooling mode, so SupplyTemp can't be more than MixedAirTemp
                            SupplyTemp = min(SupplyTemp, MixedAirTemp);
                        } // Capacity limit exceeded
                    }
```

I wanted to get your thoughts on the above before going forward with any changes.  Let me know if you have a preferred path forward or another suggestion for resolving this issue.

**Comment by mjwitte** [comment]
@matthew-larson Soo many different combinations of constraints. I agree if the cooling capacity is limited to zero, then `SupplyMassFlowRateForCool` , `SupplyMassFlowRateForDehum`, and `SupplyMassFlowRateForHumid` should be set to zero. How about adding that check [here](https://github.com/NREL/EnergyPlus/blob/7f35ab639d5a75b6e090a0db19ec83c3f0199025/src/EnergyPlus/PurchasedAirManager.cc#L2247) after the initial calculations for `SupplyMassFlowRate*`, but before the `max` with `OAMassFlowRate` and the EMS override. 

And likewise, we need a similar check for heating capacity [here](https://github.com/NREL/EnergyPlus/blob/7f35ab639d5a75b6e090a0db19ec83c3f0199025/src/EnergyPlus/PurchasedAirManager.cc#L2502) to zero out `SupplyMassFlowRateForHeat` , `SupplyMassFlowRateForDehum`, and `SupplyMassFlowRateForHumid` in the heating section.

Check me on this, but I think this will solve the issue without doing any harm.
