### ISSUE TITLE
Lowtemperatureradiant Autosizing Hydronic Tubing Length issue

### ISSUE THREAD

**Issue by jeannieboef** [NREL/EnergyPlus#8444]
Issue overview
--------------
Hi Team, I'm finding the autosizing routine for the cooling case for LowTemperatureRadiant objects drastically under estimate the total hydronic tubing length.

So for example, I have an active field (subsurface) with the imbedded piping that is 9.6x19.51 m. I defined a circuit length in the input definition of 95.45 m. The pipe diam. is defined with 18 mm at a spacing of 150 mm (default for the autosizing routine). Just with a rough check I get 14 circuits for a total length of 1336 meters. The eio file shows only 223 meters!

I have had this problem on actaul projects with "real" dimensions. My stupid excell table seems to do a better job than e+.

I have created a test file because my project file is too large for testing, but I don't know how to upload it here.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA) =  v8.9
 - Unmethours link or helpdesk ticket number  =   EnergyPlus #15575

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@jeannieboef Add ".txt" to the filename, and then you can drag it into a comment to upload (or copy/paste). e.g. testfile.idf.txt

**Comment by jeannieboef** [comment]
[testfiles.zip.txt](https://github.com/NREL/EnergyPlus/files/5770224/testfiles.zip.txt)

Hi Team, I think this zipped testfile package is uploaded, as Mike suggested. I've included my excel table that only I understand, but anyone can roughly work out how much pipe can fit in the active area, so it should illustrate the issue. 

I'd love to look at the bit of source code that does the sizing calculations for pipe length, but I wouldn't know where to start looking and I frankly don't have the time to search for it.

Thanks for the help,

Jean

**Comment by mjwitte** [comment]
Sizing calculations for ZoneHVAC:LowTemperatureRadiant:VariableFlow begin [here](https://github.com/NREL/EnergyPlus/blob/d48c555a343108d1db22c4e645e6269a6c0a2672/src/EnergyPlus/LowTempRadiantSystem.cc#L2567) in `LowTemperatureRadiant.cc::SizeLowTempRadiantSystem`. `TubeLengthDes` is set [here](https://github.com/NREL/EnergyPlus/blob/d48c555a343108d1db22c4e645e6269a6c0a2672/src/EnergyPlus/LowTempRadiantSystem.cc#L2905) using function [`sizeRadiantSystemTubeLength`](https://github.com/NREL/EnergyPlus/blob/d48c555a343108d1db22c4e645e6269a6c0a2672/src/EnergyPlus/LowTempRadiantSystem.cc#L3155-L3184).

**Comment by jeannieboef** [comment]
Okay, the way I read it, the total tube length is calculated per embedded surface.

So in [sizeRadiantSystemTubeLength](https://github.com/NREL/EnergyPlus/blob/d48c555a343108d1db22c4e645e6269a6c0a2672/src/EnergyPlus/LowTempRadiantSystem.cc#L3155-L3184)

This line (where the spacing is outside of limits) is an okay approximation: 
else { // if not in allowable limit, default back to 0.15m (15cm or 6 inches)
                tubeLength += thisHydrSysSurf.Area / 0.15;
            }   

These lines before it can't be right. It cuts the whole length in half!
if ((thisHydrSpacing > 0.005) && (thisHydrSpacing < 0.5)) { // limit allowable spacing to between 1cm and 1m
                tubeLength += thisHydrSysSurf.Area / (2.0 * thisHydrSpacing);     

I think it should be something like:
tubeLength += thisHydrSysSurf.Area / thisHydrSpacing; 


My final thoughts to this object for now is that Manufacturers tend to give data heating/cooling capacity for the active area, not by floor area. As a user, I would prefer to use subsurfaces to draw out the active areas, especially because it is far more relevant because of condensation analysis. So much of the floor/ceiling area becomes inactive due to structural supports, etc. that the by floor area method is less accurate and only used in beginning estimates.
One could also consider basing the max min volume flowrates on user input allowed pressure drops and estimated bends.

I

**Comment by RKStrand** [comment]
@jeannieboef I think the biggest issue here is that it is still unclear what specifically the parameter in Construction:InternalSource is measuring.  Is it the actual distance between the adjacent pipes or the "half-distance" which is used for the 2-dimensional solution space?  This needs to be clarified with code comments/changes and documentation updates.  It relates to the factor of 2 that you note, but clearly it's not obvious as to what the code and documentation are intending.  Once that is clarified, I think this issue will be fully resolved.  As you point out, the area divided by spacing calculation should be pretty decent--in the case you noted, it would give you around 1250m of length.  Why your file is showing in the eio file that the length is autosized to 223 meters is not clear, but I will look at that as well.

**Comment by jcyuan2020** [comment]
@RKStrand I had actually checked the section of area/(2*thisHydrSpacing) thing a few months ago and it was turned out that it is not the root cause here. The value thisHydrSpacing was the tubing distance divided by 2, which was done immediately after taking the Construction:InternalSource tube spacing input. A test unit existed to tested this sizing routing and it got the expected answer. Just FYI.

**Comment by jeannieboef** [comment]
I just tested with some interesting results. Turns out I was using 1D internal source, so that is what you'll need to check up. With 2D, including the spacing input, the correct length is calculated when I input 0.150 m as the spacing (within limits) and when I input 0.005 m spacing (without limits). So we'll want to check what is happening for the 1D case.

**Comment by jeannieboef** [comment]
Okay, I just checked my old idfs for the 1D case. Turns out DesignBuilder was silently entering a value of 0.3 m Tube spacing for that field because it was in a invisible input dialogue before I turned on the 2D method. 

However, as per the IOref, that field should be getting ignored. I had assumed a default 0.15 m would be getting used for the calcs but now I can't find where the default value is documented.

1.8.46.1.5  Field: Tube SpacingThis field defines how far apart in meters the hydronic tubing or electrical resistance wires are spacedin the direction perpendicular to the main direction of heat transfer. Note that this parameter is only usedfor two-dimensional solutions (see previous field).

**Comment by RKStrand** [comment]
Interesting.  Thanks for the additional information, @jeannieboef.  It will help diagnose what is going on.  Once I've had a chance to look into this, I will post here again with my recommended solution to this issue.

**Comment by RKStrand** [comment]
After looking at this further, a couple of problems exist.  As @jeannieboef points out, there is no default for the tube spacing and the documentation shows that this field is ignored.  Actually, the problem is "worse" because there are literally no checks on the input value for tube spacing.  You can literally put any number in--even a negative value.  The code doesn't seem to care--it just happily runs along and goes with it.  In fact, inside the CTF calculation routine, that negative value is preserved and it only survives because the formulas always use the square of the half-distance which gets rid of the negative sign.  Clearly that's not good practice.  So, I'll add traps in the code to avoid very small spacings (less than 0.001m).  I'll also clean up the code in the get routine for the construction with internal source data with some limit checking (currently there are no checks made).  E+ will produce a warning if the thickness is less that 0.01m or greater than 1.0m so that users haven't made a mistake.  These limits are already used in the code but never mentioned anywhere else.  Finally, I'll modify the documentation to clearly state the the tube spacing input is used for 1-D when autosizing is used as well as for 2-D.  That way, the user is aware that this value might be used if a value is placed there.  Will also note the limits above in the documentation and how they impact autosizing specifically.

Since we are past the IO Freeze right now, I won't mess with the IDD.  After the release, I'll circle back and make changes to the IDD (I'll file a separate GitHub issue to make sure this isn't forgotten).
