### ISSUE TITLE
Outdoor Air Details Followup

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#8550]
Issue overview
--------------
Unfinished items from #8529. Most of these were addressed in #8596 unless noted otherwise below.

 - [x] Documentation - Output Details and Examples
 - [x] Populate Times for Outdoor Air Limiting Factors During Occupancy subtable
 - [x] Populate Average Outdoor Air For Each Outdoor Air Limiting Factors During Occupancy subtable
 - [ ] Possibly reorganize new variables - seems like lots of different places, not sure all the new variables are in appropriate places
 - [x] Look for efficiency improvements (8529 was about -0.06% performance)
 - [x] Unit tests - added in #8685 
 - [x] QA the numbers in the report

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.5.0 I/O Freeze

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files added in EnergyplusDevSupport\DefectFiles
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by LipingWang** [comment]
1.  In the table for “Total Outdoor Air by Zone,”  "Time Above Zero When Unoccupied (hrs)" for total Facility was zero while this value for the thermal zones are non-zero. 

2. Please check the value for "Mechanical Ventilation" in the table "Total Outdoor Air by AirLoop." The value of "Mechanical Ventilation" in the table "Total Outdoor Air by AirLoop" is not consistent with the value of "Mechanical Ventilation" in the table " Outdoor Air Details: Total Outdoor Air by Zone" for total facility.

*Use 5ZoneAirCooled.idf to test or Comment1and2_5ZoneAirCooledHVACS_ExampleFile.*

**Comment by LipingWang** [comment]
3. Please check the whether the OA schedule in the object for Design Specification: Outdoor Air was considered when sizing outdoor air airflow. After the value in OA schedule was changed to 0.5 from default 1 (constant throughout the year), Design Zone Outdoor Airflow - Voz [m3/s] and Minimum Dynamic Target Ventilation - Voz-dyn-min [m3/s] stayed unchanged.

*MJW - 12 Mar 2021 - For the sizing calculations the schedule in the DesignSpecification:OutdoorAir is ignored, so I think this is correct.*

**Comment by LipingWang** [comment]
4. The "Time Above Voz-sum-dyn (hr)" needs to be checked. The "Time Above Voz-sum-dyn (hr)" is not consistent between the two tables: "Total Outdoor Air by AirLoop" and "Average Outdoor Air During Occupancy by Airloop" when occupancy schedule varies throughout the day.  

*MJW - 12 Mar 2021 - This appears to be correct, because every hour that counts as "Time Above Zero When Unoccupied" also counts as an hour for "time above Voz-sum-dyn". So for the comment 4 test file, time above during occupancy = 1044, time above zero when unoccupied = 5889, 1044+5889 = 6933 which is the time above during all hours. Maybe there's a better way to do this accounting?*

**Comment by mjwitte** [comment]
@LipingWang I've pushed some fixes to #8596 which should fix all of the problems 1-4 here. I've also added some explanations above.
