### ISSUE TITLE
Internal Mass is affected by the Building North Angle Axis variation

### ISSUE THREAD

**Issue by eugeniorodrigues** [NREL/EnergyPlus#8700]
Issue overview
--------------
Imagine a single thermal zone building (e.g., a cube) and we calculate the total annual energy consumption using a HVAC Template Zone Ideal Load Air System for every angle around 360° of the building north axis. If we plot the graph ([Fig1_Without_Internal_Mass](https://www.dropbox.com/s/m1vke18jvx3a3cw/Fig1_Without_Internal_Mass.png?dl=0)) we will have a smooth curve. However, if we add Internal Mass to the zone, the curve gets strangely disrupted ([Fig2_With_Internal_Mass](https://www.dropbox.com/s/zuvi5wxfh7f15cc/Fig2_With_Internal_Mass.png?dl=0)). This is awkward as the mass within a zone should not create such change when varying just one degree in the Building north.

### Details
Some additional details for this issue:
 - macOS Big Sur 11.2.3
 - EnergyPlus 9.5.0

### Checklist
 - [X] [IDF without Internal Mass](https://www.dropbox.com/s/epluk451s0j46c6/ESP_Toledo.082720_SWEC_hexahedron_WithoutInternalMass.idf?dl=0)
 - [X] [IDF with Internal Mass](https://www.dropbox.com/s/uh3phv47e7rlzl2/ESP_Toledo.082720_SWEC_hexahedron_WithInternalMass.idf?dl=0)

**Comment by mjwitte** [comment]
The internal mass surface area equals the total area of the other surfaces in the zone. This is causing problems with the radiant view factor calculations which are throwing a warning.
```
   ** Warning ** FixViewFactors: View factors not complete. Check for bad surface descriptions or unenclosed zone="SINGLE_ZONE".
   **   ~~~   ** Enforced reciprocity has tolerance (ideal is 0)=[1.233350E-002], Row Sum (ideal is 7)=[0.00].
   **   ~~~   ** If zone is unusual, or tolerance is on the order of 0.001, view factors are probably OK.
```
Splitting the internal mass into two smaller surfaces gets rid of the warning. Please try the simulation series again with 2 internal mass surfaces.

That said, there are a few things to clean up in the code:
1. Internal mass is not listed in the table Envelope Summary report, seems that is should be.
2. The warning message `Row Sum (ideal is 7)=[0.00].` appears to have the values reversed. Actually, RowSum is set [after the warnings](https://github.com/NREL/EnergyPlus/blob/29b5decc089394689a97932f66fa64d5a2fac062/src/EnergyPlus/HeatBalanceIntRadExchange.cc#L1710), needs to move up before the warning.
3. The `FixViewFactors` warnings should check for internal mass and mention it specifically.
4. Perhaps this warning should be a Severe error which halts the simulation when the view factor check is beyond a certain threshold.

**Comment by mjwitte** [comment]
A few more things to clean up:
~5. In the Initialization Summary table output the Solar View Factor and View Factor tables are incomplete and don't distinguish the original approximate view factors from the final view factors.~ See [note below](https://github.com/NREL/EnergyPlus/issues/8700#issuecomment-854884367)

6. @RKStrand question: If `OriginalCheckValue = 0` [here](https://github.com/NREL/EnergyPlus/blob/29b5decc089394689a97932f66fa64d5a2fac062/src/EnergyPlus/HeatBalanceIntRadExchange.cc#L1554) is there any reason to continue with corrected view factors?

**Comment by eugeniorodrigues** [comment]
Following the suggestion from @mjwitte, three series were run:

- Divided into two Internal Mass objects with half the surface area ([Fig3_With_Internal_Mass_splitted](https://www.dropbox.com/s/0qp81hgt3rgwysr/Fig3_With_Internal_Mass_splitted.png?dl=0)). The irregularity in the curve is gone. Nonetheless, **there is still a shift in the lower parts of the curve upward**.
- Using a single Internal Mass object and double of the surface area ([Fig4_With_Internal_Mass_double](https://www.dropbox.com/s/lynserunpxtuvum/Fig4_With_Internal_Mass_double.png?dl=0)), **a smaller shift occurs in the lower part of the curve**.
- Using a single Internal Mass object and half of the surface area ([Fig5_With_Internal_Mass_half](https://www.dropbox.com/s/8jbbrremh41c4g8/Fig5_With_Internal_Mass_half.png?dl=0)), **a small shift down occurs in the same power part of the curve**.

List of used IDF files:

- [X] [Two Internal Mass objects with half of the surface area each](https://www.dropbox.com/s/nigdij156wt2fk4/ESP_Toledo.082720_SWEC_hexahedron_WithInternalMass_splitted.idf?dl=0).
- [X] [Single Internal Mass object with double of the surface area](https://www.dropbox.com/s/yn22p9jq6uv9350/ESP_Toledo.082720_SWEC_hexahedron_WithInternalMass_double.idf?dl=0).
- [X] [Single Internal Mass object with half of the surface area](https://www.dropbox.com/s/xfssaddnh5fgx1o/ESP_Toledo.082720_SWEC_hexahedron_WithInternalMass_half.idf?dl=0).

**Comment by RKStrand** [comment]
@mjwitte Re: 6. above...it's been a while since I have looked at or worked with this code (20+ years?!).  I think for me the potential concern is that if a user enters their own view factors and those view factors satisfy completeness but not reciprocity that skipping this will potentially cause an issue.  I feel like that is the whole purpose of this routine--to make sure we've done everything we can to nail both completeness and reciprocity.  Again, this is just a recollection after quite a while.  Unless there is a compelling reason to alter this, I would not make a change here unless someone goes through it in more detail.  Anyway, just my thoughts.

**Comment by RKStrand** [comment]
7. Also need to fix a typo in DataErrorTracking.hh.  Look for "repciprocity" and correct.

**Comment by RKStrand** [comment]
Intermediate update: the initial problem where the file was generating a "view factors not complete" is a result of the internal mass area being almost the same but just barely smaller than the area of the remaining surfaces in the zone.  The problem when one surface's area is greater than the area of all the other surfaces is that you do not have an enclosure.  There is a section of the code the "fixes" it when this situation happens does not get used in this case because the internal mass is just slightly smaller.  If you bump up the internal mass area slightly, it would actually get this internal fix.  Initial testing at one of the step change points shows that when I change the code so that this file goes through this internal fix that the step change in results goes away.  So, I plan to implement a change to the code so that the condition for the internal fix happens more often.

@eugeniorodrigues Would you be willing to run one more series of runs?  From your initial version of the file with the thermal mass, simply increase the area of the thermal mass slightly so that its area is greater than the sum of all of the rest of the surfaces.  So, for example, the internal mass area right now is 2784.953360078546.  Could you try changing it to 2785 or 2800 and see if you are getting these same variations or not and then let us know?  Thanks!

**Comment by eugeniorodrigues** [comment]
@RKStrand I have run your suggestion with 2785m2 of internal mass surface area. It is smooth.

[Fig1](https://www.dropbox.com/s/eiewxa2w6g6z58y/Fig6_With_Internal_Mass_2785m2.png?dl=0) - Full graph

It seems to overestimate in 45°, 135°, 225°, and 315° and underestimate in 0°, 90°, 180°, and 270° (or overestimated the intervals 45°-89°, etc.) but probably is something else because shows the same behaviour as in without internal thermal mass.  See details in Fig 2 and 3.

[Fig2](https://www.dropbox.com/s/vtkc0p3jrhc8hju/Fig7_With_Internal_Mass_2785m2_detail_45.png?dl=0) - Detail in the 45° angle (44° is the minimum value and 45° is an overestimated value; repeats in all minimum values)
[Fig3](https://www.dropbox.com/s/u6k3a6hgvcfapld/Fig8_With_Internal_Mass_2785m2_detail_90.png?dl=0) - Detail in the 90° angle (89° is the maximum value and 90° is an underestimated value; repeats in all maximum values)

Do you want me to run any another test?

**Comment by RKStrand** [comment]
@eugeniorodrigues Thank you for running that additional series of runs and sharing the results.  I think that is what I needed to see because it appears to verify that the view factors are the problem.  I am going to implement a modified check to the code to trap cases like this one to avoid the strange variations that you saw in the initial case.  When implemented, your original file should have results like the 2785m2 case that you just ran.  While the slight imperfections in the curve at various points are strange and I don't have a great explanation for why that is happening at the moment, that is pretty minor in comparison to the fluctuations you were seeing in the original case.

**Comment by RKStrand** [comment]
@mjwitte Re: my previous post here regarding 6. OriginalCheckValue = 0.  After being in this code now a lot more, I think it solidifies my initial thought that skipping the routine when this is zero is not the right approach for the reason I gave.  It is totally possible for this parameter to be zero (meaning that is satisfies completeness) without satisfying the reciprocity requirement.  So, skipping out of this routine would potentially not correct those situations where the user's view factors satisfy complete without checking/fixing reciprocity would not be a good thing.  So, in my opinion, I think the code is correct the way it currently is on that issue and I will not make any changes for this point.

**Comment by mjwitte** [comment]
@RKStrand Regarding comment 5 [above](https://github.com/NREL/EnergyPlus/issues/8700#issuecomment-814937167)

> 5. In the Initialization Summary table output the Solar View Factor and View Factor tables are incomplete and don't distinguish the original approximate view factors from the final view factors.

The eio for the original defect file with one internal mass surface shows identical view factors for initial and final. But with 2 internal mass surfaces, the initial and final view factors are different. I don't see now why I thought the view factors were incomplete. So, disregard this comment (I've crossed it out above).
