### ISSUE TITLE
PythonPluginConstantVolumePurchasedAir.py has incorrect content

### ISSUE THREAD

**Issue by afridly** [NREL/EnergyPlus#8710]
Issue overview
--------------
I just installed EnergyPlus 9.5 and was looking over example files. It appears that "PythonPluginConstantVolumePurchasedAir.py" has incorrect content. The file installed has two classes: Set_Shade_Control_State and InitializeShadeControlFlags, which don't have anything to do with purchased air.,

### Details
Some additional details for this issue (if relevant):
 - Windows 10 Pro
 - EnergyPlus 9.5, downloaded 4/12/2021

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by bonnema** [comment]
This appears correct and exists in 9.4 (the first version with this file). I believe many of the PythonPlugin*.idf/py example files were developed from a corresponding EMS*.idf files. However, this does not mean the **entire** EMS*.idf was ported to the python plugin in all cases. Most of the time that is fine (it must have been a laborious process and I think the intent is to provide an example rather than a complete translation); however, in this case the traditional EMS that was ported was not related to ideal loads air system (f/k/a purchased air). The _EMSConstantVolumePurchasedAir.idf_ contains both ideal loads air system EMS and shade control EMS. I think the ideal loads EMS was simply (and understandably) missed. I see two solutions:
1. Rename .py file to better describe it contents
2. Expand .py file and port the ideal loads EMS to python

@Myoldmopar and @mitchute, thoughts?

**Comment by mitchute** [comment]
@bonnema nailed it.

I'm the one who did the conversion on this file. There are four EMS "Programs" in the original file. It looks like I only converted two of them and I'm sure that was simply due to time constraints. I'd rather keep the names consistent to show provenance. *Someone* should expand the file, but I'm not likely to get to it unless there's a real need other than for the purpose of expanding the example.

**Comment by bonnema** [comment]
\*looks up provenance in dictionary\* Since @mitchute already did half I can do the other half 😀.

**Comment by Myoldmopar** [comment]
@bonnema do you anticipate addressing this?  I'm not pressuring you to, but if you aren't, maybe we just close it as "wont-fix" unless someone else wants to volunteer their time.

**Comment by bonnema** [comment]
> @bonnema do you anticipate addressing this? I'm not pressuring you to, but if you aren't, maybe we just close it as "wont-fix" unless someone else wants to volunteer their time.

Sorry @Myoldmopar, I missed this. I am working on this now, hopefully there is still time to get it in before the next version?

**Comment by Myoldmopar** [comment]
Easily.  We haven't even reached input/output freeze yet.  Tweaks to input files can occur up until bug-fix freeze next month.
