### ISSUE TITLE
HVAC-Diagram.exe broken in v9.5

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8722]
Issue overview
--------------
The HVAC-Diagram.exe that comes with V9.5 installation (official release) does not work properly. In nearly all simulations runs with EP-Launch, the HVAC schematic diagram will not be properly generated.
 
This was tested to be the case in two PCs with Windows 10 installations. A further check with command line shows that the HVAC-Diagram.exe for v9.5 is somehow broken---when it runs (with properly eplusout file in place), it does not give any output. 

A temporary workaround is to copy the HVAC-Diagram.exe from v9.4 installation to place the one in v9.5. The version from v9.4 works fine, and it will also help generate the HVAC schematic diagrams properly for v9.5 runs. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): At least on Windows 10, both Pro and Home Editions
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.5
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I launched a clean windows VM and was able to reproduce the issue. I ran 5ZoneAircooled.idf, the BND is properly generated. HVAC-Diagram is called, but nothing is generated (no SVG)

Calling it directly, it cannot find `libgcc_s_seh-1.dll`

![image](https://user-images.githubusercontent.com/5479063/118811447-516ec900-b8ad-11eb-99f1-99d7e5a184e4.png)

`libwinpthread-1.dll `too

![image](https://user-images.githubusercontent.com/5479063/118814536-8af50380-b8b0-11eb-8cd1-f4b206918918.png)

`libquadmath-0.dll` as well.

This is likely caused by https://github.com/NREL/EnergyPlus/pull/8425.

In #8425 the same exact was reported (but for something else) by @Myoldmopar in: https://github.com/NREL/EnergyPlus/pull/8425#issuecomment-752764966

@lefticus then proceeded to revert some of his Fortran changes, but not all, and specifically not in the HVAC-Diagram subfolder.

I think it boils down to this

Before:

```
set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -static")
```

After
```
add_library(fortran_project_options INTERFACE)
target_compile_options(fortran_project_options INTERFACE -static)
target_link_library(HVAC-Diagram PRIVATE fortran_project_options)
```

Somehow, I think another subproject (possibly penumbra/vendor/glfw) project was also strapping `-static-libgcc` to the link flags, and now it's not.
