### ISSUE TITLE
System Nodes outputs setting up too late for the Python Plugin

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8768]
Issue overview
--------------
In some simulations with Python Plugins, the system node output variables are set up too late (not till DoOutputReporting is active and after “reporting surfaces”). However, if a Python plugin requests the system node values, the variable handle request could happen as early as the sizing stage. In this scenario, the Python code would not get a proper handle and may return unexpected results to terminate. 

The workaround is to write additional code in the Python plugin code to handle the situation. The basic idea is when a variable handle cannot be obtained, just do some Python code to recognized the condition and wait to use the value till it is available—and before that just use some alternative “default value”. The actual detailed implementation of ideal is up to the user based how exactly one would like to use the information. 

One possible solution on the development side is to split the original SetupNodeVarsForReporting() function into two new functions—the first will do the output variables setup exclusively. And then the second do the reporting only. By doing this, the first function can then be called earlier--for example, right after the manage branch input is done or the Python plugin manager is initiated. The second one of reporting can still be called at its original location. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.5, version with Python Plugin mode
 - Ref to helpdesk ticket number: 15712

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Does the `api_data_fully_ready` API method already cover this?  https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/api/datatransfer.py#L258

It's purpose is a convenient way for users to avoid accessing data until the simulation is fully ready to go, and we already utilize it in our examples.

**Comment by jcyuan2020** [comment]
@Myoldmopar Thanks! That bulk check for all the data worked well on this case. Obviously the user followed an example (looked like PythonPluginUserDefined5ZoneAirCooled.py) that does not use this `api_data_fully_ready' check function. Maybe trivial but  adding this check to this example file as well (or all there others if they are without the check)?

**Comment by Myoldmopar** [comment]
We can't change all of them to wait until that is true because there is at least one that needs to interact with the simulation very early -- the DiscreteAirSystemSizing example.  In this file the EMS and Python examples manipulate the autosized flow rate in the air system during the sizing process and if you wait until that flag is true it will be too late.  The others should _probably_ have the ready flag in there, but you'd have to just run them (annually to be sure) and see if you get any diffs.  If there aren't diffs then I'd support having it added to them.

**Comment by rraustad** [comment]
Reading this thread makes me think of all the dependencies for Node and other data. You can't have a node unless an object needs one, and you can't have an object until you read one, and you can't have a report variable until you know how many objects there are (and memory finalized), and some report variables are conditional on particular object information (e.g., child is 2-spd coil) etc. Would be nice to have a new function called initialObjectSetup (part of InputProcessor?) and there we could start to figure out all these dependencies. The only reason we have this problem now is that each object is responsible for setting up itself and objects are called in a certain order (e.g., air loop, zone equipment, plant, etc.). What if when an object is called most information is already set up? Just after the inputProcessor finishes, we already know how many of each object exist, we already know their names, we know their nodes, etc. I'm not saying I can think through all the dependencies here, but I know there is a call/timing issue in many places (e.g., if ZoneEquipInputsFilled). The get handle issue might just be solved. Easy, oh heck no.

**Comment by Myoldmopar** [comment]
@rraustad I think that is a valid assessment and would love to explore it more in a different context.  Perhaps it is a good fit for a [discussion](https://github.com/NREL/EnergyPlus/discussions)?

@jcyuan2020 it looks like most of the Python example files do utilize the `api_data_fully_ready` check, but the user defined doesn't (because it doesn't need to due to the nature of user-defined objects calling structure).  I will add a comment to the user defined Python script to illustrate that it could be used there.  I'll go ahead and close this as resolved though.  Reopen if needed.
