### ISSUE TITLE
Incident beam radiation calculation in the green roof model 

### ISSUE THREAD

**Issue by LipingWang** [NREL/EnergyPlus#8780]
Issue overview
--------------
In the current green roof (eco-roof) model, the solar incidence angle was not considered for the calculation of the shortwave radiation, specifically the incident beam radiation term. This shortwave radiation was used in both vegetation and soil energy balance equations in this model for green roofs. This could affect plant evapotranspiration and temperatures for soil surface and foliage predicted from the model. 

### Details
Some additional details for this issue (if relevant):
 - v9.5

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mitchute Question for you: both the EcoRoof and the Finite Difference Ground Temperature model use the variable BeamSolarRad.  In looking at the code, it seems like that variable is the amount of beam solar in the direction of solar radiation which would have to be modified by some sort of solar angle (cosine) to get the actual beam incident on the surface depending on the direction.  So, for the EcoRoof, it would seem like SurfQRadSWOutIncidentBeam would be the right term to use rather than BeamSolarRad in line 247 of EcoRoofManager.cc.  For the FD Ground Temp model, it would seem like maybe the same thing could be said for line 304?  Since you created the FD Ground Temp model, I was wondering if you could comment on that?  Thanks!

**Comment by mitchute** [comment]
@RKStrand I suspect you're right. I haven't verified the differences between BeamSolarRad and SurfQRadSWOutIncidentBeam myself,  but it looks like BeamSolarRad is what is being used in the PlantPipingSystems: https://github.com/NREL/EnergyPlus/blob/ccad7ddb99134ce8d6901fea16232d35d5632a18/src/EnergyPlus/PlantPipingSystemsManager.cc#L5656

**Comment by RKStrand** [comment]
@mitchute Interesting...doing some more digging and it appears that in the surface heat balances and the surface ground heat exchanger there is some acknowledgment that a direction cosine has to be used.  In the surface ground heat exchanger, line 1303, there is a directional cosine that is multiplied by the beam solar radiation.  Beam solar (normal) is the radiation on a surface perpendicular to the actual direction of the sun.  So, some direction cosine should be a factor on anything that uses BeamSolarRad.  In the case of the plant piping system manager, is it using this for an exposed pipe above the ground and then find a projected area?
@Myoldmopar Do you have any thoughts on all this?  You are listed as an author for at least some of the code in the plant piping system manager, so I thought I would see if you have any thoughts on the line 5656 of that model?

**Comment by RKStrand** [comment]
Taking this on to fix the three instances where the BeamSolarRad is not being used properly:

1. EcoRoofManager.cc line 247 (should multiply by direction cosine since this should be available since this is a surface like any other--do not need to assume that it is horizontal)
2. FiniteDifferenceGroundTemperatureModel.cc line 304  [should multiply by SOLCOS(3)]
3. PlantPipingSystemManager.cd line 5659 [should multiply by SOLCOS(3)]
