### ISSUE TITLE
Unexpected CO2 and relative humidity results for mixing zones

### ISSUE THREAD

**Issue by LipingWang** [NREL/EnergyPlus#8783]
Issue overview
--------------
An EnergyPlus model with mixing zone objects generated unexpected CO2 concentrations and relative humidity results. The model has four thermal zones and each zone has the same CO2 generation and infiltration rates. There are two non-mixing zones and two mixing zones. For the two mixing zones, each zone serves as both the "source" and "receiving" zone. With v9.5, CO2 concentrations for the two mixing zones vary with the design mixing flow rates. 
It is expected that CO2 concentration should not vary with the design mixing flows for the model. The CO2 mass balance equation (Eq.2.52) from Engineering Reference is listed below. Czi (CO2 concentration in the zone air being transferred into this zone)  and Czt (CO2 concentration in the zone air being transferred into this zone) should be the same in theory for both nearly identical mixing zones.

![image](https://user-images.githubusercontent.com/3977674/119187107-22d02a00-ba36-11eb-98f9-1d0ac4489762.png)

### Details
Some additional details for this issue (if relevant):
  - v9.5
  - ticket #15714

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@lgu1234 The situation described in this issue is that there are four identical zones except for one thing: there is mixing between two zones (both of these zones have their own identical mixing statements receiving air from the other zone in the mixing pair).  Two of the zones have no mixing.  When I look at the results, the CO2 levels for the zones without mixing are very close (differences in the 5th significant figure).  The CO2 levels for the zones with mixing are very similar to each other (again very small differences) but those zones have CO2 levels that LAG the zones without mixing.  Technically, they should be the same.  However, I am wondering if the reason why they are different is due to lagging.  When the MixingMassFlowCO2(ZoneNum) gets calculated in CalAirFlowSimple, it is using a value for the CO2 level of the "sending" zone that is likely from the previous time step and that does not get updated until the next time step.  This would mean some lag in the CO2 levels when mixing is added.  I'm going to do some more testing, but this seems like a logical explanation for what @LipingWang is noticing in the results.  What are your thoughts on this?

**Comment by RKStrand** [comment]
@lgu1234 A couple of extra things to note about this file.  The defect file itself has two time steps per hour.  Also, the mixing amount in the very high at over 70ACH.  When I decrease the mixing amount by ten to around 7-8ACH there is less lag in the CO2 level in the zones with mixing and less damping as well.    When I go to about 4ACH with 6 time steps per hour, the results are getting much closer.  There is still some lag and damping, but it is fairly trivial now.  I think this all points to that this is working as designed.  It would be good to get your thoughts though.
Incidentally, while trying to figure out what was happening here, I ran across what looks like a typo in the general contaminant code for refrigerated cases.  If you agree with my assessment here that the CO2 with mixing is actually functioning as it should and does not need any changes, I will still go ahead and fix the other bug that I ran across.
