### ISSUE TITLE
Surface wind exposure is affected inconsistently by the building North axis angle

### ISSUE THREAD

**Issue by eugeniorodrigues** [NREL/EnergyPlus#8785]
Issue overview
--------------
Following the exercise reported in issue #8700, a single thermal zone with a parallelepiped shape has its annual energy consumption for heating and cooling (HVAC Template Zone Ideal Load System) calculated for every angle of the 360° of the building North axis. When the building surfaces have their field for wind exposure with 'NoWind', we have a smooth curve ([Fig. 1](https://www.dropbox.com/s/yowkf7k0tgweuzy/Figure_example_no_wind_Toledo.png?dl=0)). However, when using 'WindExposed', the curve has spikes when the wind direction changes in the weather data file ([Fig. 2](https://www.dropbox.com/s/fugrdkl2xjztavs/Figure_example_wind_exposed_Toledo.png?dl=0)). These unexpected spikes are more evident in buildings with smaller buildings of the same shape ([Fig. 3](https://www.dropbox.com/s/1517cykii0vbaj9/Figure_example_wind_exposed_Toledo_smaller_building.png?dl=0)).

### Details
 - macOS Big Sur 11.3.1
 - EnergyPlus 9.5.0

### Checklist
 - [X] [EnergyPlus Weather File for Toledo, Spain](https://www.dropbox.com/s/76gm5x2t1q2qsjp/ESP_Toledo.082720_SWEC.epw?dl=0)
 - [X] [IDF with the field Wind Exposed 'NoWind'](https://www.dropbox.com/s/biz87yuyxva2ydj/ESP_Toledo.082720_SWEC_paralelepiped_4_h18m_s0_5_NoWind.idf?dl=0)
 - [X] [IDF with the field Wind Exposed 'WindExposed'](https://www.dropbox.com/s/fml57moetdyyzyy/ESP_Toledo.082720_SWEC_paralelepiped_4_h18m_s0_5_WindExposed.idf?dl=0)
 - [X] [IDF with the field Wind Exposed 'WindExposed' of smaller volume building](https://www.dropbox.com/s/4sqbx58wsgu5x0k/ESP_Toledo.082720_SWEC_paralelepiped_4_h18m_s0_5_Wind_Exposed_SmallerBuilding.idf?dl=0)

**Comment by RKStrand** [comment]
@eugeniorodrigues I'm starting to get a clearer picture as to what is going on here.  First, the weather file shows a constant wind speed and direction for the entire year.  That seems a bit odd, but perhaps that is due to the weather file source data?  In any case, the wind direction is always 0 and this plays a role in the phenomenon that you are seeing and I am also seeing on my computer.

The input file in question you have surfaces facing 0, 90, 180, and 270.  Basically, when you use a north axis of 0, 90, 180, or 270, what seems to be happening is that three of the exterior surfaces are calculated to be "windward".  That only happens for a north axis of 0, 90, 180, and 270 because that is where you have surfaces line up exactly with the wind direction.  At any other wind direction, you will always have two surfaces that were windward and two that were leeward.  If you had a wind direction that varied, you would never see this because it would be very rare that the wind direction.  However, in those four instances (north axis of 0, 90, 180, 270), due to the way that windward/leeward is determined, three surfaces are windward meaning that convection is increased which seems to be dropping the cooling load slightly.  Once the north axis varies from one of those four cardinal directions, then things go back to two windward and two leeward surfaces and everything returns to "normal".

So, in my analysis, you see this happen in this file specifically because the weather file wind direction never changes.  This seems to be further supported by the fact that when only the south facing wall is wind exposed, I only see the problems happen at two of the four cardinal north axis variations and the changes are step changes, not the spikes.  I am fairly certain that with a weather file that has varying wind directions, this won't be an issue.

@mjwitte While the weather file used for this has no wind direction variations, it did expose a slight issue here with the way in which EnergyPlus calculates windward vs. leeward.  For example, if you have a building with exterior surfaces facing north, south, east, and west and the wind direction is within 0.001 degrees of one of those directions, three of the four directions will be considered windward.  Granted, that is pretty rare.  The question now is: do we make any changes?  I can come up with an algorithm that would avoid the situation that is seen in this file.  Do you agree that this should be fixed?

**Comment by mjwitte** [comment]
@RKStrand The current test was part of a change from >100 to >90 in https://github.com/NREL/EnergyPlus/pull/7458. So, I think it's fine. If the wind is coming from the north, for example, then walls facing east and west will see the full wind flow across them, so they are just as windward (if not more) than the north facing wall. So, I think this is fine as-is.

**Comment by RKStrand** [comment]
@mjwitte Ok, we can leave it as is then.  I'll close this off when I log this comment.

**Comment by eugeniorodrigues** [comment]
I have run new series with a different weather file that has wind direction recorded up to 1° resolution. The existence of prevailing wind directions produces the same spikes ([Fig1 - Total Energy](https://www.dropbox.com/s/s56p4xarqp92efd/Figure_example_wind_direction.png?dl=0), [Fig2 - Cooling Energy](https://www.dropbox.com/s/oc5e1nfjceeqyyd/Figure_example_wind_direction_cooling.png?dl=0), [Fig3 - Heating Energy](https://www.dropbox.com/s/ck5krr23bb85x2f/Figure_example_wind_direction_heating.png?dl=0)). I have tested with other files and the effect is more notable with higher wind speeds.

@mjwitte and @RKStrand, I hope this helps.

Files:
[weather file](https://www.dropbox.com/s/2x5wylazk87wbr2/PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018.epw?dl=0)
[idf file](https://www.dropbox.com/s/2o0g57m8tieoatp/PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.idf?dl=0)

**Comment by RKStrand** [comment]
@eugeniorodrigues Thanks for following through with another weather file and taking it out to such resolution.  I'll admit that it is a little disappointing to see the spikes that you are finding.  I guess the thought that we might be hitting some random times when the wind speed is lining up close enough at various angles that it could be the two vs. three surfaces windward could still be valid.  However, I'm not so sure.  The spike pattern repeats--the response from 0-180 seems to be the same as 180-360.

@mjwitte What do you think of the newest graphs?  Should I reopen this and test to see if a new algorithm can eliminate the spikes?

**Comment by eugeniorodrigues** [comment]
@RKStrand Yes, the spikes repeat in a 180° pattern due to the parallelepiped shape of the building. If it is a cube, repeats in a 90° pattern, and so on for every extruded regular shape. In addition, the spikes also increase if the building is elevated in altitude due to the wind boundary layer wind speed adjustment.

**Comment by eugeniorodrigues** [comment]
@RKStrand Another information that might be relevant. The spikes are more evident in warm climate weather files than in cold ones (affects mainly cooling energy).

**Comment by RKStrand** [comment]
@eugeniorodrigues At the moment, it isn't clear what exactly is causing the blips in the data that you are seeing.  I am not seeing any flaw in the wind direction dependence.  A couple of things to think about: have you tried any other convection model available in EnergyPlus?  Also, have you tried regular construction walls/floors/roofs?  What you have right now is a no-mass material that makes up the entire exterior of the building.  These are just some things to potentially look at next.  For now, we will keep this issue closed but you can keep posting here if you come across any new findings.  Thanks!

**Comment by eugeniorodrigues** [comment]
@RKStrand Thank you for your time. I have run new five series covering all Outside Surface Convection Algorithms (SimpleCombined, TARP, MoWiTT, DOE-2, and AdaptiveConvectionAlgorithm). Previous runs used DOE-2. The [weather file](https://www.dropbox.com/s/2x5wylazk87wbr2/PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018.epw?dl=0) is the same. Results below.

Note: In this post and in the previous ones, all simulations use regular construction with five layers. The NoMass construction was only used in issue #8700.

1. SimpleCombined
[Figure](https://www.dropbox.com/s/hawyf585i8iskfy/Figure_example_wind_direction.png?dl=0)
[Table](https://www.dropbox.com/s/3v7y2ruojb48ghn/Table_PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.csv?dl=0)
[IDF](https://www.dropbox.com/s/1fh95l1edmkldz3/PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.idf?dl=0)

2. TARP
[Figure](https://www.dropbox.com/s/ttbz2lgoas4i4pv/Figure_example_wind_direction.png?dl=0)
[Table](https://www.dropbox.com/s/rk5c56qs76ood1c/Table_PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.csv?dl=0)
[IDF](https://www.dropbox.com/s/65lf9id0zlce71f/PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.idf?dl=0)

3. MoWITT
[Figure](https://www.dropbox.com/s/rov2sb9arkh9yxu/Figure_example_wind_direction.png?dl=0)
[Table](https://www.dropbox.com/s/qw10c59k0i2jus4/Table_PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.csv?dl=0)
[IDF](https://www.dropbox.com/s/zj8b4efkqk7thk3/PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.idf?dl=0)

4. DOE-2
[Figure](https://www.dropbox.com/s/ar4q49voywpq6m6/Figure_example_wind_direction.png?dl=0)
[Table](https://www.dropbox.com/s/tsu6qkn3v2d1bzw/Table_PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.csv?dl=0)
[IDF](https://www.dropbox.com/s/us7izz48syqr69j/PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.idf?dl=0)

5. AdaptiveConvectionAlgorithm
[Figure](https://www.dropbox.com/s/1cgzno06l9qufm4/Figure_example_wind_direction.png?dl=0)
[Table](https://www.dropbox.com/s/fhdf1ghx34qcav1/Table_PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.csv?dl=0)
[IDF](https://www.dropbox.com/s/yl0ezdebqrgoigf/PRT_LB_Lisboa.Portela.AP.085360_TMYx.2004-2018_paralelepiped_4_h30m_s0_7.idf?dl=0)

Summary of Results:
- SimpleCombined did not show any spikes. 
- All remaining algorithms show spikes.
