### ISSUE TITLE
Release workflows once again broken due to QtIFW: find more reliable option than aqtinstall

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#8837]
Issue overview
--------------

Release workflows once again broken due to QtIFW: find more reliable option than `aqtinstall`. Every time qt upgrades their latest version, it breaks down.

Test release on my fork showing the failure: https://github.com/jmarrec/EnergyPlus/runs/2889068571?check_suite_focus=true

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Github Actions CI machines for Linux, Mac, and Windows alike
 - Version of EnergyPlus (if using an intermediate build, include SHA): develop, between 9.5.0 and 9.6.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
I investigated this a bit and it's not broken because of an IFW version change, it's broken due to "4.1" no longer being a valid version string according to the Python semantic_version package.  The aqtinstall library doesn't pass the optional "partial" flag and so it fails to create a valid "Version" object.  I tested this locally by making it 4.1.0 and it got passed that error and started to install the QtIFW version.  

It looks like if we were willing to just roll with the latest and greatest QtIFW, we could check the same page that `aqtinstall` uses: https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/Updates.xml, and grab the version number from that and use it for our packages.
