### ISSUE TITLE
PhaseChangeHysteresis documentation

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/EnergyPlus#8900]
Issue overview
--------------
The input output reference text for Peak Freezing Temperature field says that it should be higher than the peak melting temperature field. This is also reflected in the example object shown below the field descriptions
https://energyplus.net/sites/all/modules/custom/nrel_custom/pdfs/pdfs_v9.5.0/InputOutputReference.pdf

1.9.9.1.13 Field: Peak Freezing Temperature
This is the center (peak) of the freezing curve, in Kelvin. This will be higher than the peak
melting temperature based on empirical data.

The example EnergyPlus file in doesn't follow this and shows the peak melting temperature higher than the peak freezing temperature. I have not used this object before, but it would seem that the object in this file is correct and the documentation text and example object text may be wrong.
https://github.com/NREL/EnergyPlus/blob/develop/testfiles/1ZoneUncontrolledWithHysteresisPCM.idf#L235-L249

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Hmm, I think this has been addressed as part of a recent doc PR. @RKStrand do you remember this?

**Comment by RKStrand** [comment]
Here is the new text that is currently in develop:

1.9.9.1.13 Field: Peak Freezing Temperature
This is the center (peak) of the freezing curve, in Celsius. This will generally be lower than
the peak melting temperature based on empirical data. Note, however, that EnergyPlus does allow
users to specify a peak freezing temperature that is higher than the peak melting temperature.

BUT for some reason, the example given in the text still shows a freezing temperature that is higher than the peak melting temperature.  I thought I had fixed that at the same time but it is not there.  So, whoever ends up dealing with this should make sure that the IDF example in the IORef that happens shortly after the text shown above gets changed so that the melting temperature is *higher* than the freezing temperature.

**Comment by RKStrand** [comment]
Ok, I've incorporated this very minor change to the IDF example in the IORef into something else I was currently working on.  This should be taken care of when PR#8889 gets accepted/merged.
