### ISSUE TITLE
Documentation 2021b

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#8902]
Issue overview
--------------
A place to collect requested documentation fixes. Add a new comment to the issue with new doc-change-only issues. Someone will eventually fix them all up at the same time once critical mass has been reached.

**Comment by mitchute** [comment]
- [x] PhaseChangeHysteresis #8900 
- [x] Rachet Tariff #8854 
- [x] UtilityCost:Ratchet #8854 
- [x] Surface outside face outdoor wind direction #8804

**Comment by shorowit** [comment]
- [x] Some confusion about whether multiple air loops are allowed in EnergyPlus due to the language in [ZoneHVAC:AirDistributionUnit](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-zone-equipment.html#zonehvacairdistributionunit): "therefore only one is allowed per zone". See [this Unmet Hours post](https://unmethours.com/question/56841/can-one-zone-have-multiple-air-distribution-units-multiple-airloops/?answer=56866#post-id-56866) for background.

**Comment by jcyuan2020** [comment]
- [x] Location of the `Connector:Mixer` and `Connector:Splitter` documentation in InputOutputReference.idf is currently still under the `Plant-Condenser Flow Control` group:

![image](https://user-images.githubusercontent.com/64040111/127029721-0c26cb63-0c67-46d9-a93c-9181ada9a27a.png)


These should be moved to the `Node and Branch Management` group and near the `ConnectorList` section (Sec 1.20.4 in v9.5).

**Comment by jcyuan2020** [comment]
- [x] There is a notation error in the HAMT nomenclature table (Page 77, Table 3.1 in Engineering Reference, v9.5): the vapor pressure should be lower case "p" instead of the current capital case "P":

![image](https://user-images.githubusercontent.com/64040111/127890733-9b63a2ec-6991-4bff-b31e-10724b88bf73.png)

And actually the capital case "P" is already used for Porosity some lines below in the same table:

![image](https://user-images.githubusercontent.com/64040111/127891122-2c7589a2-5f0e-404a-9220-7e3996ff37e7.png)

**Comment by shorowit** [comment]
- [x] [Generator:MicroTurbine documentation](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-electric-load-center-generator.html#outputs-7-002) says the outputs are "Generator Produced Electricity Rate" and "Generator Produced Electricity Energy" while the RDD says "Generator Produced **AC** Electricity Rate" and "Generator Produced **AC** Electricity Energy".

**Comment by shorowit** [comment]
- [x] [ElectricLoadCenter:Inverter:PVWatts documentation](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-electric-load-center-generator.html#outputs-description-electricloadcenterinverterpvwatts) has an extra section called "Outputs Description" that lists some output variables that I don't see in the RDD when using this inverter object. The output variables listed below it under "Outputs" appear to match the RDD.

**Comment by RKStrand** [comment]
Addresses issues listed here as well as a few other minor things that I noticed while fixing the above.  One of those was that the problem with "Generator Produced Electricity Rate" was not just in the Generator:MicroTurbine but other generators.  In addition, there was a missing DC group for one of the generators.  The documentation for this should now match the code.
