### ISSUE TITLE
Sizing:Zone below-zero (degree C) Zone Cooling Design Supply Air Temperature scenarios for freezer spaces

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8968]
Issue overview
--------------

For the Sizing:Zone object, there is a recent discussion on how to give warning messages on the zone cooling design supply air temperature that is below 0 degree C (#8855, #8827). A user recently sent in a simulation case modeling a freezer space which uses a -20 C design cooling supply temperature---which may call for the need to lift that restriction. 

Also, there is a running failure to report: 

During the process of diagnosing an issue the user reported (which is actually not related to Sizing:Zone design supply air temperature), the v9.5 case file was upgraded to pre-release v9.6 (commit ed3a9d36c8). Now there is another severe error message with “bad allocation”. The failing point seems to be an out-of-bound allocation at lines: 
https://github.com/NREL/EnergyPlus/blob/ed3a9d36c86aad48000128ae7975805818f1e207/src/EnergyPlus/SizingManager.cc#L3376-L3381

With this example file, the `(paramNum-2)` index will have a value of -1 (here `paramNum` is 1), which causes an out-of-bound (bad allocation) failure in this particular case. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): pre-release v9.6 only
 - Helpdesk ticket number: 15770

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/8000s/8968))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@jcyuan2020 I think that the recent work made it a warning message if the user's zone cooling design supply air temperature is below 0 degree C.  That's simply to warn a user that there could be a problem.  If the user does have a legitimate zone below 0C (like a freezer space), they can always ignore that warning message.

However, the crash because of a bad index is definitely a problem, one that clearly wasn't anticipated.  I will look at this issue next as I'm not sure how it passed this index value.
