### ISSUE TITLE
Out of memory when IDFEditor reads in a large IDF file

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9010]
Issue overview
--------------
There was a "Run-time error '7': out of meomory" warning when using IDFEditor to open a large idf file:  

![image](https://user-images.githubusercontent.com/64040111/130994536-6f31ca31-039c-46ea-abb5-c011f7e9da82.png)

The case file can finish running with EP-Launch tough. This warning is a rare occurrence and the file size may not be the single factor---there seemed to be larger files that can be opened ok without such a warning.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.6 IOFreeze
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9010))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
This is a little tricky to reproduce. If you select the file in EP-Launch and then click on the IDF Editor button it occurs, but does not occur when you open IDF Editor directly and then open the file in it. Another way to reproduce this issue is to at the CMD command line in the IDFEditor folder, type 

```
IDFEditor.exe "C:\EnergyPlusV9-6-0\test\9010-coolingenergy.idf"
```

or what ever is the appropriate path. I was able to reproduce the bug after updating the 9.6 defect file to 22.2 using the 1.51 version of IDF Editor.

**Comment by JasonGlazer** [comment]
Unfortunately, I have not been able to fix this issue but I do have a workaround: 

If you are using many Schedule:Compacts input objects in your file, one workaround so that you can open the file in IDF Editor, is to reduce the length of the Schedule:Compact that appears in the Energy+.idd file. Make a copy of the Energy+.idd file called ORIGINAL-Energy+.idd so you can always go back to it if you have to. Then open the Energ+.idd file with a text editor such as Notepad and find the section on Schedule:Compact. After A1000 change the comma to a semi-colon and delete the lines that start with A1001 to A9981, the end of that Schedule:Compact input object description. Save the modified Energy+.idd file and try opening the file in IDF Editor again.

This workaround will also be shown in IDF Editor in a dialog box when this out of memory error occurs.
