### ISSUE TITLE
New E+ 9.6 output variable warnings

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#9049]
Issue overview
--------------
The E+ 9.6 IO Freeze build is producing new warnings (see below) for our IDF files. These warnings did not occur in E+ 9.5.

```
   ** Warning ** setupIHGOutputs: Output variables=Zone Other Equipment Coal Rate and Energy are not available.
   **   ~~~   ** Only the first Other Equipment fuel type used in a zone is reported.
   ** Warning ** setupIHGOutputs: Output variables=Zone Other Equipment Electricity Rate and Energy are not available.
   **   ~~~   ** Only the first Other Equipment fuel type used in a zone is reported.
   ** Warning ** setupIHGOutputs: Output variables=Space Other Equipment Coal Rate and Energy are not available.
   **   ~~~   ** Only the first Other Equipment fuel type used in a space is reported.
   ** Warning ** setupIHGOutputs: Output variables=Space Other Equipment Electricity Rate and Energy are not available.
   **   ~~~   ** Only the first Other Equipment fuel type used in a space is reported.
```

IDF files:
9.5: [in.idf.txt](https://github.com/NREL/EnergyPlus/files/7130349/in.idf.txt)
9.6: [in.idf.txt](https://github.com/NREL/EnergyPlus/files/7130340/in.idf.txt)

I assume this is related to the new Space object? @mjwitte 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.6.0-82391071e9
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Yes, if I remember correctly, v9.5 simply ignored the additional other fuel types and did not create the additional output variables without warning. @shorowit please confirm.

**Comment by shorowit** [comment]
@mjwitte As far as I can tell, both E+ 9.5 and 9.6 create the additional output variables correctly and produce the same outputs. It's just that E+ 9.6 is generating new warnings.

It's also strange that E+ 9.6 is generating warnings about both Coal **and Electricity**. The IDF does have "Other Equipment Coal Energy" output variables but does not have any "Other Equipment Electricity Energy" output variables. So it's particularly confusing that there are warnings about Electricity.

**Comment by mjwitte** [comment]
OK, but does 9.5 create *Zone* Other Equipment Coal Energy?

**Comment by shorowit** [comment]
9.6 creates a Zone Other Equipment Coal Energy and 9.5 does not. Neither one produces a Zone Other Equipment Electricity Energy.

I'm totally not following here, sorry. Why does the warning say "Zone Other Equipment Coal Rate and Energy are not available." when these output variables are available in the 9.6 RDD?

**Comment by mjwitte** [comment]
@shorowit The warning's probably broken somehow. The goal for v9.6: If there are 2 or more OtherEquipment objects in the same zone which use different fuel types, only the first fuel type will be reportable at the Zone and Space level (because there's only one zone/space-level aggregate variable to be reported on). There should be warnings for the unreported fuel types. Will look into this and clean it up.

**Comment by mjwitte** [comment]
Or maybe the warnings aren't useful and they can be removed?

**Comment by shorowit** [comment]
Okay, thanks, I finally understand. Yes, I do have two OtherEquipment objects in the same zone but with different fuel types. It's weird to me that EnergyPlus can't create both zone/space-level aggregate variables, but I guess you're saying there is something structural in the code that prevents it.

So the summary is: 1) the warning about Other Equipment Coal Rate and Energy is erroneous, and 2) the warning about Other Equipment Electricity Rate and Energy is intended (but perhaps not useful).

**Comment by mjwitte** [comment]
> It's weird to me that EnergyPlus can't create both zone/space-level aggregate variables, but I guess you're saying there is something structural in the code that prevents it.

For the record, the code limitation shows [here](https://github.com/NREL/EnergyPlus/blob/f148fcd7da2ac8ae55fca42a52a6b439ccad3d7c/src/EnergyPlus/InternalHeatGains.cc#L5901-L5914). The `ZnRpt` struct only has one variable for Other equipment energy rate/use: `state.dataHeatBal->ZnRpt(zoneNum).OtherPower`. In order to report more fuel types, this would need to be an array or add additional variables for `OtherPower2` `OtherPower3` etc.

And looking at the code now, I see why there are more warnings than expected. [Here](https://github.com/NREL/EnergyPlus/blob/f148fcd7da2ac8ae55fca42a52a6b439ccad3d7c/src/EnergyPlus/InternalHeatGains.cc#L2406-L2408) repeated fuel types are added to the `otherEquipFuelTypes` but [here](https://github.com/NREL/EnergyPlus/blob/f148fcd7da2ac8ae55fca42a52a6b439ccad3d7c/src/EnergyPlus/InternalHeatGains.cc#L5899) it throws warnings for any fuel type beyond the first one in the list, even if it's a repeat. I know what needs to be fixed now.
