### ISSUE TITLE
Unexpected behavior when using shading surfaces with transmittance schedule and PixelCounting

### ISSUE THREAD

**Issue by marctavenier** [NREL/EnergyPlus#9059]
Issue overview
--------------
When using shading surfaces with a transmittance schedule and the PixelCounting shading calculation method, the transmittance schedule seems to be ignored and all surfaces are made fully opaque. To me this seems to be a bug or at least unexpected behavior. When using PolygonClipping the transmittance schedule works as expected.

### Details
Some additional details for this issue:
 - Windows 10
 - EnergyPlus 9.5 via OpenStudio 3.2.0 via Ladybug Tools 1.3.0 in Grasshopper.
 - As indicated on the Ladybug Tools Discourse [here](https://discourse.ladybug.tools/t/tip-dont-use-pixelcounting-in-combination-with-transmittance-schedule/15871)

**Comment by shorowit** [comment]
As far as I can tell, EnergyPlus uses [penumbra](https://github.com/bigladder/penumbra) for the PixelCounting shading calculation, and according to @nealkruis, penumbra currently [can't handle shading surfaces with any transparency](https://github.com/bigladder/penumbra/issues/2).

At a minimum, it seems like there should be a warning (if there isn't already, I haven't checked).

**Comment by aaron-boranian** [comment]
[Related Unmet Hours post](https://unmethours.com/question/72921/pixel-counting-for-adaptive-shading/).

**Comment by rafael-a** [comment]
I just accidentally found this issue through the Unmet Hours post linked above.

As a user, this issue is critical as it biases the solar load without any alert/warning and can lead to the overestimation of heating loads unknowingly.
For context, we use transparency schedules quite often to model deciduous Trees over the year.

From my own point of view, it would be very appreciated to have a Severe warning show when this issue is encountered in a model.

**Comment by chriswmackey** [comment]
Oh wow. If this is true, I can't believe that I have been using this `PixelCounting` method for over a year and I have been completely unaware of this. This is probably one of the most dangerous cases of an error passing silently that I've encountered in recent E+ history.

I can support the lack of a `FatalError` since I imagine a lot of people would still like there simulation to continue for this case. However, there needs to at least be a `SevereError` in the .err file if we don't want more cases of people like me who have been using this method with transmittance schedules for several projects.

**Comment by rafael-a** [comment]
Hi @nealkruis, @shorowit,

I know this issue has now been closed as the Severe warning got implemented. 

However, are there any plans to overcome PixelCounting limitation with translucent shading surfaces?

As a user, we use translucent shading surfaces when there are decidious trees that could have a significant impact on the building's solar gains. This means that a large portion of the buildings simulated with E+ can't make use of the speed up PixelCounting provides and still remain on the PolygonClipping era - in some cases we are talking about a x100 simulation time, which largely limits the amount of iterations we can make on a building design.

I imagine this is not an easy one to address, but it would have a large impact of a signficant number of cases.

**Comment by nealkruis** [comment]
@rafael-a I have thought about how this could be done with PixelCounting, but unfortunately there are no immediate plans (or funding) to work on this.

**Comment by rafael-a** [comment]
I understand, thanks @nealkruis! 

Let me know if there is something we can do or any site to put a request?
I don't really know what is the process to develop/fund these modifications/new features.

**Comment by tkdogan** [comment]
We have implemented a pixel counter that does support transparency here https://doi.org/10.26868/25222708.2017.287
Would be happy to share the code so that it can be integrated in E+

**Comment by nealkruis** [comment]
@tkdogan can you share the shader source for the probabilistic pixel removal?
