### ISSUE TITLE
workflow for adding new object type

### ISSUE THREAD

**Issue by xixihaha1995** [NREL/EnergyPlus#9098]
Issue overview
--------------
I want to create an new object type(which is modified version of **WindowMaterial:GlazingGroup:Thermochromic**). I have referred to  #9094 #6999. However, I do have the following questions.

### Question
 - Although #9094 has been closed, I came across other issues which were apparently not related to "adding new object entry into Energy.idd.in".
 - Do we have some tutorial or standard available to "add new object into EnergyPlus(such as, Material:NoMass)?

**Comment by mjwitte** [comment]
A few comments here:
1. Issues can be reopened if there are follow up comments or the problem is not resolved.
2. Issues are intended to be used for bug (defect) reports or new feature requests.
3. User support options are listed [here](https://energyplus.net/support-training).
4. I am not aware of any such tutorial. Some examples of recent new objects: #8495, and this commit https://github.com/NREL/EnergyPlus/pull/8394/commits/5c27cd02236252b30b7d3e81f3633f5455da9163 which added Space and SpaceList.
