### ISSUE TITLE
Typo in Chilled Ceiling Input Routine

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#9113]
As I converted the sizing method variables into an enum class, there were many expected compiler errors showing up, but then this line caused an unexpected one:
https://github.com/NREL/EnergyPlus/blob/2ad67318cfe34c038d73081846e141c43440678b/src/EnergyPlus/ChilledCeilingPanelSimple.cc#L414

The sizing method is currently stored as an integer, which lets you do all sorts of fun stuff, like mistakenly compare it to zero with a binary operator.  If you look at the context of this line, you'll see it was just a typo, and the actual sizing input value should have been compared.

**Comment by jcyuan2020** [comment]
(In an effort to bundle a few small issues) I replaced the line with: 
```
if (ThisCP.ScaledCoolingCapacity <= 0.0) {
```
by looking through the context. 

Also, by looking through the context, a couple of other similar places actually used `<` rather than `<=` for the comparison with `0.0`. Probably not going to make too much difference, but do you have any preference what to use here: `<` or `<=` here? @Myoldmopar
