### ISSUE TITLE
Why did the variable changed by set_actuator_value not exactly the same as predicted

### ISSUE THREAD

**Issue by waynetsu** [NREL/EnergyPlus#9127]
Issue overview
--------------
I am learning to use the API (Library Mode) to exchange data with EnergyPlus while running.
I am following the example in part 1.4.4 of InputOutputReference.pdf.

The Python Code should have changed the outdoor dew point to the value of (outdoor drybulb temperature - 4).

However, I found that outdoor dew point was always not precisely the same as expected.

For example, when outdoor drybulb temperature is 4.4℃ in weather data, the output outdoor dew point is 0.8℃.   0.4℃ error.
When the the outdoor dew point was changed to a constant value, it was precisely the same.

Could anybody help me to understand what happened?
Attach was the Python Code and IDF file (I don't why *.py and *.idf cannot be uploaded, so I upload the zip file).

Thanks!

### Details
Some additional details for this issue :
 - Platform (Windows 7, x64)
 - Version of EnergyPlus (9.4.0)
 - Python 3.8 (Pycharm)

[main.zip](https://github.com/NREL/EnergyPlus/files/7330380/main.zip)
[ModelHouse.zip](https://github.com/NREL/EnergyPlus/files/7330389/ModelHouse.zip)

**Comment by Myoldmopar** [comment]
I'll have to think about the root cause, but you are doing everything right.  It is definitely something about averaging, or something getting stomped on at the beginning of each timestep/hour, or something.  If I run your file as-is, with the 1 hour timestep, I get this for the calculated dry-bulb minus dew-point, which should be a steady 4.0:

![image](https://user-images.githubusercontent.com/849824/136973815-69c9749a-b156-496e-9bbc-f76d17a03394.png)

But then if I make the timestep small (3 minutes), that choppiness gets washed away in the hourly time series output:

![image](https://user-images.githubusercontent.com/849824/136973713-293618ea-507f-4a98-b3af-ad1ddd07f5bb.png)

Anyway, for this toy project slash learning experience, I think you are on the right track and have got the hang of it.  Have fun in Python!

**Comment by bonnema** [comment]
I have not looked at the files. Typically the EPW weather data is hourly, and I believe that E+ interpolates between the hourly values when sub-hourly timesteps are simulated. I would bet the interpolation is more sophisticated that just linear between two hourly values in the EPW.

**Comment by mjwitte** [comment]
The interpolations are linear, but "hourly" output is averaged across the hour, so timestep reporting is needed to match the weather data once per hour. But the user file here is using a 1 hour timestep, so interpolation isn't the issue. 

I think the problem is [here](https://github.com/NREL/EnergyPlus/blob/9390173ed70ba249b54a64061dbc47c0894c3829/src/EnergyPlus/WeatherManager.cc#L2219-L2241). `OutDewPointTemp` can be changed after the override is applied. It appears that `OutRelHumValue` can overrule the override on dew point. It appears that the relative humidity needs to be actuated along with (or instead of) dewpoint given the current logic.

Having two measures of humidity (RH and dewpoint) in the incoming weather data and available as separate overrides is a problem that needs clarification and some better logic to allow one of the other to produce a consistent set of weather values.

**Comment by rraustad** [comment]
@waynetsu, you might try to calculate and set your dew point temp and then using that Tdp to also actuate the outdoor humidity ratio using the psychrometric function psyWTdpPB(state, Tdp, PB).

**Comment by bonnema** [comment]
> @waynetsu, you might try to calculate and set your dew point temp and then using that Tdp to also actuate the outdoor humidity ratio using the psychrometric function psyWTdpPB(state, Tdp, PB).

[with the python plugin](https://nrel.github.io/EnergyPlus/api/python/func.html#func.Psychrometrics.humidity_ratio_b)

**Comment by Myoldmopar** [comment]
Great additions @rraustad and @bonnema.  I'd suggest using the ReadTheDocs [live documentation](https://energyplus.readthedocs.io/en/stable/func.html#func.Psychrometrics.humidity_ratio_b) which will be more up to date than that github.io one, which I should just remove.

**Comment by waynetsu** [comment]
> I'll have to think about the root cause, but you are doing everything right. It is definitely something about averaging, or something getting stomped on at the beginning of each timestep/hour, or something. If I run your file as-is, with the 1 hour timestep, I get this for the calculated dry-bulb minus dew-point, which should be a steady 4.0:
> 
> ![image](https://user-images.githubusercontent.com/849824/136973815-69c9749a-b156-496e-9bbc-f76d17a03394.png)
> 
> But then if I make the timestep small (3 minutes), that choppiness gets washed away in the hourly time series output:
> 
> ![image](https://user-images.githubusercontent.com/849824/136973713-293618ea-507f-4a98-b3af-ad1ddd07f5bb.png)
> 
> Anyway, for this toy project slash learning experience, I think you are on the right track and have got the hang of it. Have fun in Python!

Wow!! Thanks for your fabulous answer, with such persuasive descriptive figures. Besides the timestep issue, I think something might happen within the flowchart of the EnergyPlus Program. The dewpoint temperature may be changed a little bit after it was actuated. I am trying to figure out the clear picture of how it works.
Plus, thanks for your encouragement^_^

**Comment by waynetsu** [comment]
> I have not looked at the files. Typically the EPW weather data is hourly, and I believe that E+ interpolates between the hourly values when sub-hourly timesteps are simulated. I would bet the interpolation is more sophisticated that just linear between two hourly values in the EPW.

I

**Comment by waynetsu** [comment]
> @waynetsu, you might try to calculate and set your dew point temp and then using that Tdp to also actuate the outdoor humidity ratio using the psychrometric function psyWTdpPB(state, Tdp, PB).

Thanks for your advice. I tried but it seems the humidity ratio was not available in the Actuator list.
However, I tried to actuator the relative humidity using [psychrometric library](https://pypi.org/project/PsychroLib/#modal-close). The relative humidity changed only a little bit (e.g.78%-->79.9% or 80%-->79.2% ). And the dew point output was almost the same as before.
