### ISSUE TITLE
EnergyPlus v9.6.0 on Windows 11 missing dlls

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#9264]
Issue overview
--------------
Installing EnergyPlus v9.6 on a new Windows 11 machine results in errors from missing DLLs, e.g. vcomp140.dll

Workaround:
Installing the [Visual C++ Redistributable library](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) should fix things.
Specifically this version: https://aka.ms/vs/17/release/vc_redist.x64.exe

### Details
Some additional details for this issue (if relevant):
 - Platform Windows 11
 - Version of EnergyPlus 9.6.0
 - [Unmethours link](https://unmethours.com/question/68651/dll-errors-installing-os-and-e-on-windows-11/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here) n/a
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
A first attempt fix would be to use the newer Windows base image on Github Actions to build our release packages.  Specifically adding `windows-2022` would be my first step.  Having that alone may get CMake to grab the right DLLs for Windows 11.  Not sure, as I haven't tested it, but that's where I would start.

**Comment by jmarrec** [comment]
This is actually a problem due to cpgfunctionEP... by default it does this:

https://github.com/NREL/EnergyPlus/blob/1cb2067a9c73a29b78daf5062e3b34ce4346d98b/third_party/cpgfunctionEP/CMakeLists.txt#L31-L37

On Github, the openmp is definitely found. But it doesn't handle at all shipping the `vcomp{v}.dll` to match. This is something you can do via `CMAKE_INSTALL_OPENMP_LIBRARIES` and InstallRequiredSystemLibraries: https://cmake.org/cmake/help/latest/module/InstallRequiredSystemLibraries.html

> CMAKE_INSTALL_OPENMP_LIBRARIES
>  Set to TRUE to install the MSVC OpenMP runtime libraries


Source code bit, to show that vcomp140.dll would be picked up: https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/InstallRequiredSystemLibraries.cmake#L598-L614

```cmake
  # MSVC 8 was the first version with OpenMP
  # Furthermore, there is no debug version of this
  if(CMAKE_INSTALL_OPENMP_LIBRARIES AND _IRSL_HAVE_MSVC)
    set(_MSOMP_DLL_VERSION ${_MSVC_DLL_VERSION})
    set(_MSOMP_IDE_VERSION ${_MSVC_IDE_VERSION})

    if(_MSOMP_DLL_VERSION)
      set(v "${_MSOMP_DLL_VERSION}")
      set(vs "${_MSOMP_IDE_VERSION}")
      set(MSVC_OPENMP_DIR "${MSVC_REDIST_DIR}/${CMAKE_MSVC_ARCH}/Microsoft.${MSVC_REDIST_NAME}.OPENMP")

      if(NOT CMAKE_INSTALL_DEBUG_LIBRARIES_ONLY)
        set(__install__libs ${__install__libs}
          "${MSVC_OPENMP_DIR}/vcomp${v}.dll")
      endif()
    endif()
  endif()
```

**Comment by mitchute** [comment]
We should probably just take all of that openmp stuff out of there. Do you want me to tackle that?

**Comment by mbadams5** [comment]
Won't this still be an issue for ConvertInputFormat since that uses OpenMP if the compiler supports it? Although I see julien seems to have a fix for this on his fork...
https://github.com/NREL/EnergyPlus/blob/5e982ed7101ced40361baedf8f41cde3e9771832/src/ConvertInputFormat/CMakeLists.txt#L10-L15

**Comment by jmarrec** [comment]
@mbadams5 Yeah ConvertInputFormat was on my todo as well. For this one it's kinda easier, it's added via add_subdirectory so I can just do `set(CMAKE_INSTALL_OPENMP_LIBRARIES TRUE PARENT_SCOPE)`

Anyways, the fact that the energyplus.exe is affected is unrelated to ConvertInputFormat (which is standalone IIUC), it's really due to cpgfunctionEP.

**Comment by mbadams5** [comment]
@jmarrec Yeah, I get that ConvertInputFormat does not affect energyplus.exe, however, I bet the standalone ConvertInputFormat did not work under Windows 11 either due to the same issue. Either way, both issues are fixed now in your PR.
