### ISSUE TITLE
Python version linked to on Github Actions is inconsistent

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#9281]
Issue overview
--------------

While we do use actions/setup-python@v2, cmake is likely going to find another version.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by bonnema** [comment]
Maybe this has been fixed behind the scenes? I "rebuilt" the 9.6 tag the other day and it worked. Instead of grabbing the latest python, it got the latest patch for the specified major and minor version. I think this may have been a windows-only issue? I agree it was an issue:

E+ 9.6 Release:
![image](https://user-images.githubusercontent.com/1991971/154729278-4f21e3f9-686c-4f8d-8ced-7d10884be2ba.png)

OpenStudio 3.3 Release (slightly different E+ for the space thing):
![image](https://user-images.githubusercontent.com/1991971/154729518-96a57074-50c7-4560-b4e6-9b13294e1a96.png)

**Comment by jmarrec** [comment]
White pinning it, so last week, Mac was the one giving me most trouble. I bumped to python 3.8, but that is also currently what's installed as system python.
Even by asking cmake to find 3.8.12 EXACT, it was throwing because it found the python 3.8.9 from system. I had to also pass Python_ROOT_DIR, and now it should hopefully be future proof

**Comment by bonnema** [comment]
Never mind, it did the same thing (built with 3.10). Ignore my comment.
