### ISSUE TITLE
Crash on Kiva error messaging

### ISSUE THREAD

**Issue by matthew-larson** [NREL/EnergyPlus#9309]
Issue overview
--------------
A Kiva model was crashing when hitting the warning "The weights of associated Kiva instances do not add to unity--check exposed perimeter values."  The error was tracked back to and error in the `Kiva::setMessageCallback` function and the second argument needing to be a `std::pair` instead of a `std::string`.

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v9.6

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by nealkruis** [comment]
@mitchute FYI, we missed this when we were setting up the callback functions to also take in the `state` pointer. I believe there is only one place where we set the context pointer for the callback. Turns out you can cast anything to a `void*` and then to anything else, so the so there was nothing wrong from the compiler's perspective.

@matthew-larson to prevent this in the future, we could create a wrapper function in EnergyPlus around `Kiva::setMessageCallback` that only takes arguments of a `state` and a `std::string`.
