### ISSUE TITLE
FMU running problem for v9.5 and newer

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9315]
Issue overview
--------------
Reported from the NIST CONTAM team, this is the second issue about FMI running in v9.5 following the issue reported related to FMI in v9.6 and v22.1 IOFreeze. For v9.5, it will directly show the symptoms below when running the case. For v9.6 and v22.1 IOFreeze, an additional code problem precedes this(see #9313); but after fixing #9313, the same following symptoms similar to v9.5 will then appear:

In running the FMU case which includes an FMU, an IDF and an EPW files for a simple 3-zone test case, the fmu log file indicates that ContamFMU calls to fmiSetReal() obtained only zero values for all (16) variables. This will cause ContamX to fail due to a zero ambient pressure meant to be obtained from the EPW file via the E+ output variable `Site Outdoor Air Barometric Pressure`. 

The EnergyPlus error message shows the following: 
```
** Severe ** ExternalInterface/GetSetVariablesAndDoStepFMUImport: Error when trying to 
** ~~~ ** do the coSimulation with instance "ContamFMU"
** ~~~ ** of FMU "ContamFMU.fmu"
** ~~~ ** Error Code = "1"
** Fatal ** ExternalInterface/StopExternalInterfaceIfError: Error in ExternalInterface: Check EnergyPlus *.err file.
```
The FMU log file shows the following segment of log information which indicate that the 16 variables failed to obtain adequate update information from EnergyPlus:
```
==================== fmiSetReal(nvr: 16) ==================== 
vr[ 0]= 1: 0, WTH_AmbientTemp 
vr[ 1]= 2: 0, WTH_BarometricPressure 
vr[ 2]= 3: 0, WTH_WindSpeed 
vr[ 3]= 4: 0, WTH_WindDirection 
vr[ 4]= 6: 0, TAIR_1_ZoneA 
vr[ 5]= 8: 0, TAIR_1_ZoneB 
vr[ 6]= 10: 0, TAIR_1_ZoneC 
vr[ 7]= 12: 0, AHS_supply_1_ZoneC 
vr[ 8]= 13: 0, AHS_return_1_ZoneC 
vr[ 9]= 16: 0, TAIR_1_ahs1(Sup) 
vr[ 10]= 15: 0, TAIR_1_ahs1(Rec) 
vr[ 11]= 14: 0, PCTOA_ahs1 
vr[ 12]= 9: 0, HRAIR_1_ZoneB 
vr[ 13]= 5: 0, WTH_HumidityRatio 
vr[ 14]= 11: 0, HRAIR_1_ZoneC 
vr[ 15]= 7: 0, HRAIR_1_ZoneA 
==================== fmiDoStep(300 s) ====================
```

For EnergyPlus versions 9.1-9.4, the co-simulations between EnergyPlus and NIST ContamFMU.DLL are working fine. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9313))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by wsdols** [comment]
The issue related to all zeros being passed out of EnergyPlus after the initial time step still exists.  
Therefore, the simulation is still terminating due to the errors this causes in CONTAM after it receives these zero values.  

Further investigation into the EnergyPlus code reveals the source of this error in the file _ExternalInterface.cc_ in the `GetSetVariablesAndDoStepFMUImport()` function.  
There is a call to `GetInternalVariableValueExternalInterface()` after the initial timestep, i.e., in the else clause of the following:   
```
if (state.dataExternalInterface->FirstCallGetSetDoStep)
{
    ...
    GetInternalVariableValue() 
} 
else 
{
    ...
    GetInternalVariableValueExternalInterface() 
}
```

If the call to `GetInternalVariableValueExternalInterface()` is replaced  with `GetInternalVariableValue()` then the co-simulation achieves full completion.  

It would seem the only difference in these two functions is that one sets the return value to:  
```
resultVal = (varType == VariableType::Integer) ? 
    (double)*(dynamic_cast<OutVarInt *>(op->outVars[keyVarIndex]))->Which: 
    (double)*(dynamic_cast<OutVarReal *>(op->outVars[keyVarIndex]))->Which;

```
and the other (which does not work properly) to:  
`resultVal = (double)op->outVars[keyVarIndex]->EITSValue
`

I will leave it to the developers to take determine the proper corrective action, as I am not familiar enough to know if the issue lies in the setting of the `EITSValue` ...
