### ISSUE TITLE
Crash if window construction is zero due to bad construction name

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#9331]
Issue overview
--------------
If a window has an illegal construction name, it will crash with a zero construction number here:

https://github.com/NREL/EnergyPlus/blob/d93483085694987b6e2b4aeb8e294d2b2060d844/src/EnergyPlus/SurfaceGeometry.cc#L5936-L5944

This is actually a redundant check that happens earlier except this spot doesn't reset the divider num to zero so that could be added here and then delete the failing if block?

https://github.com/NREL/EnergyPlus/blob/d93483085694987b6e2b4aeb8e294d2b2060d844/src/EnergyPlus/SurfaceGeometry.cc#L5898-L5903

Stumbled across this while testing #9324 because I added a space to the Construction:WindowDataFile name, but forgot to change the construction name in the window and ran with a debug build.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 22.1-IOFreeze-Plus

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added - should fail with any file with a bad window construction name
     - MCVE at https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9331/mcve.idf   
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by ykabusalah** [comment]
Could I have a shot at fixing this?

**Comment by jmarrec** [comment]
@ykabusalah still interested in fixing it? otherwise I may take a crack at it.

**Comment by jmarrec** [comment]
This is mostly due to the fact that we keep trying to process individual subsurfaces when we already found an error earlier.

More widely, we also keep processing types of surfaces even if the previous types failed. Is this something we actually want, in order to provide more context in the `eplusout.err`, or should we exit early?

`GetRectDetShdSurfaceData`, `GetHTSurfaceData`, `GetRectSurfaces`, etc will only switch `&ErrorsFound` to true (never reset to false, this is enforced via https://github.com/NREL/EnergyPlus/blob/develop/scripts/dev/find_byref_bool_override.py), and eventually a FatalError will be issued, so aside from having more info in eplusout.err, no value is provided by trying to continue to process following types.

cf https://github.com/NREL/EnergyPlus/blob/4872b63adc2630585108b0c9d0c5ebc492ca29e3/src/EnergyPlus/SurfaceGeometry.cc#L1284-L1347

For an example, assuming I have a Wall with a wrong construction, and a window with a wrong construction, do I want to see:

```shell
   ** Severe  ** BuildingSurface:Detailed="SURFACE 1", invalid Construction Name="WRONG CONSTRUCTION".
   ** Severe  ** FenestrationSurface:Detailed="SUB SURFACE 1", invalid Construction Name="WRONG SUBCONSTRUCTION".
   **  Fatal  ** GetSurfaceData: Errors discovered, program terminates
```

Or am I ok just having:

```shell
   ** Severe  ** BuildingSurface:Detailed="SURFACE 1", invalid Construction Name="WRONG CONSTRUCTION".
   **  Fatal  ** GetSurfaceData: Errors discovered, program terminates
```


@mjwitte @Myoldmopar thoughts please?
