### ISSUE TITLE
Air film R-value for semi-exterior surfaces not used

### ISSUE THREAD

**Issue by lymereJ** [NREL/EnergyPlus#9470]
Issue overview
--------------
Section A9.4.1.2 in ASHRAE Standard 90.1-2019 states that "semi-exterior surfaces are protected surfaces that face attics, crawlspaces and parking garages with natural or mechanical ventilation".

EnergyPlus currently uses the prescribed semi-exterior surface air film R-value as the default in the following `switch` statement used to calculate the U-value of opaque interior surfaces. This value ends up not being used for what it is intended to represent. For example, the U-value with film for the small office prototype building model should be calculated using this value but is currently calculated using the R-value for  "interior horizontal surfaces, heat flow up" and "interior horizontal surfaces, heat flow down".

https://github.com/NREL/EnergyPlus/blob/317b0c131df2eacad09c2224236658ab45b3afa4/src/EnergyPlus/DataHeatBalance.cc#L1321-L1340

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: 22.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@JasonGlazer I'm looking at this and I see the point that @lymereJ is making.  Since you are listed as the author of the code in this area, do you know (I know--the code date is almost 10 years old) why the semi-exterior value was used for anything with an exterior side that is "interior" and is not classified as a wall, roof, or floor?  Maybe the assignment is ok in line 1339?  But shouldn't it default back to something else like a vertical surface if it's not a floor or roof/ceiling?  I can fix this, but I want to make sure I'm not missing anything.  Thanks!

**Comment by JasonGlazer** [comment]
My memory of something a decade ago is useless. And I think the last time I looked at this code it was in Fortran. I don't remember why but it seems like line 1339 should really never be hit, if it is something else seems to be broken related to how surfaces are being classified. KivaFoundation should probably be added to the list after Ground and GroundFCFactorMethod. The other SurfaceClass's like Window and GlassDoor should be added so they are explicit. The block below it overrides the outsideFilm to zero if it is not a wall, door, floor or roof. My guess is that code evolved around it and this was just not updated. Overall it could use some cleaning up.

**Comment by RKStrand** [comment]
@JasonGlazer Yes, I agree that some clean-up is in order.   I will work on that clean-up and also some documentation edits.

@lymereJ The use of the semi-heated film coefficients as a default is not correct and I will take care of that.  However, the situation that you mention in the small office reference building would require additional input and data structure to track which surfaces have a semi-heated exterior side.  There is nothing in the input or code to track whether a zone is conditioned or not since it would require knowledge of thermostats and HVAC to figure all of this out.  My concern is that it would be a mess and a hard sell to the rest of the development team.  That all said, the code can be cleaned up in this area and the use of the semi-heated coefficient eliminated.  In addition, I will clarify the documentation in the Output Details document so that it is clearer what is happening in this report.  On the positive side of things, since this reports both U-values with and without film coefficients, a user could easily take the value without films and then factor them in.

**Comment by lymereJ** [comment]
Thanks for the follow-up @RKStrand! I assume that you meant "semi-exterior" surfaces instead of "semi-heated". I understand the challenges associated with identifying these surfaces. So to clarify, are you saying this is a "won't fix" type of issue?

**Comment by RKStrand** [comment]
@lymereJ Yes, I meant "semi-exterior".  And yes, I am thinking this is a "won't fix"--not because it can't be done but rather because of the impact on the code/input I envision it would have.  The fix will at least avoid using the wrong exterior film coefficient.  Hope that clarifies things.

**Comment by lymereJ** [comment]
Got it, thanks!
