### ISSUE TITLE
Connecting Energyplus simulation with OpenAI Gym Environment through Python API

### ISSUE THREAD

**Issue by AltoTechGithub** [NREL/EnergyPlus#9599]
Issue overview
--------------
I'm trying to implement  OpenAI Gym environment (for reinforcement learning training) with EnergyPlus building environment. I recently made an effort to achieve this by connecting Python with EnergyPlus through Python API. Currently, my understanding is that E+ simulation is run with a single line of code as below 

```
ARGS = [
    '--weather',
    weather_file_path,
    '--output-directory',
    output_dir,
    '--readvars',
    idf_file_path
]

api = EnergyPlusAPI()
state = api.state_manager.new_state()
api.runtime.run_energyplus(state, ARGS)
```

and the only way I can interact with each timestep is through callback functions provided by Runtime API. 

OpenAI Gym environment requires us to implement a "step" function in a class which will be repeatedly called during RL model training. A pseudo-code of what flow inside a step function with EnergyPlus Python API should look like is shown below

```
def step(self, action)

  set_eplus_actuators_at_start_timestep(action)
  
  new_state = get_eplus_sensor_values_at_end_timestep(.....)

  reward = calculate_reward_or_penalty(new_state)

  return new_state, reward
```

However, since each action towards EnergyPlus running simulation can only be done through callback functions, the step function above cannot be achieved through typical single-process programming. 

Any suggestion on how to solve this?

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10 64-bit)
 - Version of EnergyPlus (EnergyPlus 22.1)
 - [Unmethours link](https://unmethours.com/question/78546/connecting-energyplus-simulation-with-openai-gym-environment-through-python-api/)

**Comment by Myoldmopar** [comment]
This sounds like a very cool project.  You are probably going to want to run EnergyPlus in its own thread, and track the simulation time of EnergyPlus separately.  When EnergyPlus calls back, in that separate thread, you can decide whether to hold the simulation and wait, get data from the simulation, or actuate conditions in the simulation, all before releasing the loop and letting EnergyPlus continue another step.  The OpenAI Gym step function can be in charge of knowing how far along EnergyPlus should be, so that it can set flags in the separate thread to signal what EnergyPlus should do.

All that said, this is not an issue with EnergyPlus, and does not belong as a GitHub issue on our repo.  For open ended questions like this, please use the peer-to-peer site https://unmethours.com to get tips and tricks.

(Note to self: There have been a few questions like this popping up, I will try to improve our API examples to do some things like this since there seems to be a very large demand for it.)

**Comment by AltoTechGithub** [comment]
Thank you very much for your response!!
