### ISSUE TITLE
GetInternalHeatGainsInput is broken

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#9680]
Issue overview
--------------

I have a file that used to run fine and now it doesn't.

```
   ** Severe  ** GetInternalHeatGains: Lights="HEAT EXCHANGER AIR TO AIR SENSIBLE AND LATENT 1", invalid Supply Air Outlet Temperature Control =NO
   **   ~~~   ** No matching Zone Return Air Node found.
   ** Severe  ** GetInternalHeatGains: Lights="HEAT EXCHANGER AIR TO AIR SENSIBLE AND LATENT 1", invalid Heat Exchanger Type = PLATE
   **   ~~~   ** No matching Zone Exhaust Air Node found.
   **  Fatal  ** GetInternalHeatGains: Errors found in Getting Internal Gains Input, Program Stopped
```

This is my Lights object:

```
Lights,
  Baseline Model Lights,                  !- Name
  Baseline Model Space Type,              !- Zone or ZoneList or Space or SpaceList Name
  Baseline Model People Lights and Equipment Schedule, !- Schedule Name
  Watts/Area,                             !- Design Level Calculation Method
  ,                                       !- Lighting Level {W}
  10.7639104167097,                       !- Watts per Zone Floor Area {W/m2}
  ,                                       !- Watts per Person {W/person}
  ,                                       !- Return Air Fraction
  ,                                       !- Fraction Radiant
  ,                                       !- Fraction Visible
  1,                                      !- Fraction Replaceable
  General;                                !- End-Use Subcategory
!    ,                        !- Return Air Fraction Calculated from Plenum Temperature
!    ,                        !- Return Air Fraction Function of Plenum Temperature Coefficient 1
!    ,                        !- Return Air Fraction Function of Plenum Temperature Coefficient 2 {1/K}
!    ,  !- Return Air Heat Gain Node Name.    -> A7
!    ;  !- Exhaust Air Heat Gain Node Name.   -> A8
```

On this line it finds that A8 is **NOT** blank: https://github.com/NREL/EnergyPlus/blob/c249759bad26d4b4f4badab0062643276c7cc2bf/src/EnergyPlus/InternalHeatGains.cc#L1300 

(lldb) p AlphaName(8)
(std::basic_string<char, std::char_traits<char>, std::allocator<char> >) $25 = "PLATE"

```
(lldb) p AlphaName(8)
(std::basic_string<char, std::char_traits<char>, std::allocator<char> >) $25 = "PLATE"
(lldb) p AlphaName(1)
(std::basic_string<char, std::char_traits<char>, std::allocator<char> >) $26 = "HEAT EXCHANGER AIR TO AIR SENSIBLE AND LATENT 1"
(lldb) p AlphaName(2)
(std::basic_string<char, std::char_traits<char>, std::allocator<char> >) $27 = "ALWAYS ON DISCRETE"
(lldb) p AlphaName(3)
(std::basic_string<char, std::char_traits<char>, std::allocator<char> >) $28 = "ZONE HVAC PACKAGED TERMINAL AIR CONDITIONER 8 MIXED AIR NODE"
(lldb) p AlphaName(4)
(std::basic_string<char, std::char_traits<char>, std::allocator<char> >) $29 = "COIL SYSTEM COOLING DX HEAT EXCHANGER ASSISTED 1 HX SUPPLY AIR OUTLET - COOLING INLET NODE"
```

A couple of lines before: https://github.com/NREL/EnergyPlus/blob/c249759bad26d4b4f4badab0062643276c7cc2bf/src/EnergyPlus/InternalHeatGains.cc#L1288

which calls https://github.com/NREL/EnergyPlus/blob/c249759bad26d4b4f4badab0062643276c7cc2bf/src/EnergyPlus/DataZoneEquipment.cc#L1212

Which again calls getObjectItem.

Problem is that both calls are using the state.dataIPShorcuts, so it just overrides everything:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/InternalHeatGains.cc#L264

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): 22.2.0 official

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
> Problem is that both calls are using the state.dataIPShorcuts, so it just overrides everything:

Yep, we should move far away from DataIPShortCuts at this point.  We can pass variable size vectors around all day, no need to pre-size vectors before calling GetObjectItem, and definitely no need to rely on some random global variables to hold the contents either.

**Comment by amirroth** [comment]
> 

FWIW Jason and Mark are going to be demoing the epJSON automatically generated object-creation code in the next week or two. I am not saying to not fix this thing, because it needs to be fixed, I'm just pointing out that this is happening.

**Comment by jmarrec** [comment]
Ok, let's go for a minimal fix then.

**Comment by mjwitte** [comment]
@jmarrec Defect file? I'm curious what's special about the defect file vs the regression test files which aren't failing.

**Comment by jcyuan2020** [comment]
@mjwitte The general pattern when this would happen is when you are in the middle of processing an object, then for one or more fields there is a need to process another object to get updated information. This the most common scenario this problem will show up, if both processing codes used the "global" dataIP shortcut---as they will point to the same location. Then the unfinished processing procedure will be flushed away. The symptom will be very unpredictable---usually the program will soon crash due to complete incorrect inputs; or sometimes it will take some unexpected input values and then come up with very unexpected results.

This is very dangerous issue and actually I've encountered a couple of times before---one recent such scenario showed up in the development of PR #9653. Here [this commit](https://github.com/NREL/EnergyPlus/pull/9653/commits/36d892e517e887c1f42816f61f6a81d827c7725b) is an example---here the problem was address in the commits followed ([here](https://github.com/NREL/EnergyPlus/pull/9653/commits/509e4923b0a2227503a78604b041e4bcbd259118)) by moving the second object processing part up to the beginning of the processing of the first object (so that it was done completely before the first processing starts). Although finally for this PR a complete different approached is taken and there no longer need to deal with the problem this way. But the [commit](https://github.com/NREL/EnergyPlus/pull/9653/commits/36d892e517e887c1f42816f61f6a81d827c7725b) above could  be an illustration about the scenario that this problem will occur.

**Comment by jmarrec** [comment]
#9681 fixes it and adds a test file. I'll convert to a unit test but I'm short on time right now
