### ISSUE TITLE
Fatal Error when North Facing Wall and Window Azimuth differ only 0.1 Degrees

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#9757]
Issue overview
--------------
In the attached example, I have window on a north facing wall with the following coordinates. 

![image](https://user-images.githubusercontent.com/7797674/204665101-27970cea-233c-445f-9756-957cab81cecb.png)
![image](https://user-images.githubusercontent.com/7797674/204665193-4f9d760c-4efb-4b9c-a29d-5c3fd6407588.png)

The wall is not exactly north facing, but very close (Y coordinate changed 2 cm over a 15.24 m length).

When I run simulation, I get the following fatal error:
![image](https://user-images.githubusercontent.com/7797674/204665657-b6b96c95-0095-44a4-8249-2018c921648f.png)

Looks like the checkSubSurfAzTiltNorm program is treating the difference between 359.9 Degrees and 0 Degrees to be larger than 90 Degrees, while in reality they only differ by 0.1 degrees.  I tried this on walls facing other directions and they all simulated without problem.

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (22-2-0)
 - NA

### Checklist
 - [X] Defect file added ([1ZoneUncontrolled_NorthWindow.idf](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/1ZoneUncontrolled_NorthWindow.idf))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@TiejunWu @Myoldmopar This seems to be fixed already.  I ran the defect file in V23.1 (on a Mac) and the error message does not show up.  In the debugger, this case goes through a Real64 function called rotAzmDiffDeg which corrects the difference in the angles so that it is less than 0.1 degree.  Now, why checkSubSurfAzTiltNorm only insists that the differences in the tilt and azimuth only have to be within 90 degrees I don't know.  However, it seems like someone may have already fixed this.  If someone could double check to make sure it's not just a Windows thing, then we could close this off.

**Comment by TiejunWu** [comment]
@RKStrand  This may have been fixed by @jcyuan2020 when working on #9907 .

**Comment by RKStrand** [comment]
@Myoldmopar As this has been fixed, I am closing it.
