### ISSUE TITLE
SurfaceProperty:ExteriorNaturalVentedCavity results in convection model errors

### ISSUE THREAD

**Issue by msfer86** [NREL/EnergyPlus#9901]
Issue overview
--------------

When applying the **SurfaceProperty:ExteriorNaturalVentedCavity** object to roof surfaces to simulate the ventilated air cavity between the roof tiles and the underlying surfaces, it results in convection model errors. This happens when the AdaptiveConvectionAlgorithm is selected in the **SurfaceConvectionAlgorithm:Outside** object, and if the following roof convection models are chosen in the **SurfaceConvectionAlgorithm:Outside:AdaptiveModelSelections** object (field Wind Convection Horizontal Roof Equation Source):

Model -> Error
ClearRoof (default) -> CalcClearRoof: Convection model not evaluated (bad value for distance to roof edge)
TARPWindward -> CalcSparrowWindward: Convection model not evaluated (bad face area)
BlockenWindward -> CalcBlockenWindward: Convection model wind angle calculation suspect (developer issue)

Other models and algorithms work fine.

An IDF file with the error example is attached along with the specific weather file. However, the error is not dependent on the weather conditions/file.

### Details
Some additional details for this issue (if relevant):
 - Windows 11 64-bit (10.0.22621) & Mac OS 13.1 (22C65)
 - EnergyPlus v22.2

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

[Files.zip](https://github.com/NREL/EnergyPlus/files/11017592/Files.zip)

**Comment by Nigusse** [comment]
Investigated the defect file provided in develop and found that the roof surface area and other data are not filled in (by design) when the exterior boundary condition is not `OtherSideCondModeledExt`. The offending roof surface `ZN_11_ATTIC_ROOF_1` has `OtherSideCondModeledExt` as its outside boundary, which leads to `0.0` surface area in `state.dataSurface->SurfOutConvFaceArea(SurfNum)` variable. This finally leads to the error as the area is used to calculate the exterior convection coefficient [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ConvectionCoefficients.cc#L8807-L8825). So, this is a defect that needs to add a protection to avoid throwing the severe error message.
