### ISSUE TITLE
Version updater needs a manual filling of a default value, otherwise err with [json.exception.out_of_range.403] key 'two_dimensional_temperature_calculation_position' not found

### ISSUE THREAD

**Issue by yujiex** [NREL/EnergyPlus#9960]
Issue overview
--------------
Version updater converting a file from version 9.4 to version 23.1 encounters an error message of
```
 ** Severe  ** [json.exception.out_of_range.403] key 'two_dimensional_temperature_calculation_position' not found
```

This error can be manually fixed by filling in a default value as follows

```
  ConstructionProperty:InternalHeatSource,
    Realstic_Synikia_FlooronGarager_U-value_0.16 Heat Source,  !- Name
    Realstic_Synikia_FlooronGarager_U-value_0.16,  !- Construction Name
    2,                       !- Thermal Source Present After Layer Number
    2,                       !- Temperature Calculation Requested After Layer Number
    1,                       !- Dimensions for the CTF Calculation
    0.3,                     !- Tube Spacing {m}
    0.0;                     !- Two-Dimensional Temperature Calculation Position {dimensionless} <-- fill in default value here

  Construction,
    Realstic_Synikia_FlooronGarager_U-value_0.16,  !- Name
    EPS Expanded Polystyrene (Heavyweight)_.185,  !- Outside Layer
    _DBC_reinforced_concrete_1.55W/m2_1,  !- Layer 2
    _Onterulo_aljzatkiegyenlito_.005;  !- Layer 3
```
 
The error starts to occur since version 9.5

The idf files of the original version (_V940.idf) and the intermediate versions are here:
[debug version updater-20230413T182230Z-001.zip](https://github.com/NREL/EnergyPlus/files/11225338/debug.version.updater-20230413T182230Z-001.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (Version 9.4 to 23.1)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Interesting, in v9.4 the object is
```
Construction:InternalSource,
       \min-fields 7
...
  N5 , \field Two-Dimensional Temperature Calculation Position
       \required-field
       \minimum 0.0
       \maximum 1.0
       \default 0.0
```
In v9.5+ it's a new object 
```
ConstructionProperty:InternalHeatSource,
<no min-fields tag>
...
  N5;  \field Two-Dimensional Temperature Calculation Position
       \required-field
       \minimum 0.0
       \maximum 1.0
       \default 0.0
```

1. A field with a default should never be a required-field.
2. But the new object doesn't have a min-fields tag, so the default won't get filled in (but it would be zero anyway).
3. In `HeatBalanceManager::GetConstructData` the `ConstructionProperty:InternalHeatSource` object is processed with raw epJSON, so min-fields won't matter. But the epJSON processing expects every field to be there, so it won't fill in a default.
4. Even though this field is required in v9.4, it runs without error because it has a min-fields tag and it was probably using `GetObjectItem` which fill fill in the default.
5. It looks like this error is tripping during `GetConstructData`, not during the initial IP processing?
6. So, `GetConstructData` should be fixed to check for `.end` for this field and use the default if it's not there. That's the real error here (transitioning with a blank should be ok).
7. But the 9.4->9.5 transition should be change also to check if this field is blank and insert 0.0. in case someone wants to transition up to something before v23.2.

**Comment by mjwitte** [comment]
And 8. Remove the require-field tag from this for v23.2 and beyond.

**Comment by yujiex** [comment]
Thanks for analyzing the issues @mjwitte. I'll create a PR and fix it. Although I'm not sure how to do the 9.4->9.5 transition change part (I assume it's Fortran related?).

**Comment by nomisela** [comment]
I converted IDF from 8.0.0 to V23.1 but when I import into OpenStudio I get the following error below. ( I just started learning so if you could be very specific on how I should fix the error please. I am not caught up with the abbreviations yet)

I downloaded the IDF v8  from DOE (https://www.energycodes.gov/prototype-building-models)

The collection is INVALID at strictness level 'Draft', because of the errors:
Field      level data error of type DataType          .
Error is in an object of type 'RunPeriod', named 'annual', in field 5.
Additional information about the error type: field-level data is of an incorrect type.
Field      level data error of type DataType          .
Error is in an object of type 'Schedule:Week:Compact', named 'RefrigeratorWeek', in field 1.
Additional information about the error type: field-level data is of an incorrect type.
Field      level data error of type NumericBound      .
Error is in an object of type 'RunPeriod', named 'annual', in field 4.
Additional information about the error type: numeric data violates a min or max bound.
