### ISSUE TITLE
Water-to-Air Heat Pump Cycling Model Issues

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#9966]
Issue overview
--------------
The cycling model for Water-to-Air Heat Pumps have several issues:

1. At very low Part Load Ratios, the Runtime Fraction can be significantly larger. The source side mass flow rate scaled by the Part Load Ratio instead of the Runtime Fraction, which can result in unreasonable outlet temperatures on the source side of the equipment. Because the source-side valves likely operate in conjunction with the compressor, the mass flow rate should be scaled by the Runtime Fraction instead.
2. The `heatPumpRunFrac()` method adjusts the PLF (and therefore the RTF) to account for [off-cycle power consumption](https://bigladdersoftware.com/epx/docs/22-2/input-output-reference/group-unitary-equipment.html#field-fraction-of-on-cycle-power-use-000) for, e.g., crankcase heaters. This is problematic since off-cycle power really should not impact the runtime fraction of the compressor and the resulting heat from off-cycle power definitely shouldn't be added to the refrigerant heat balance in calculating Q_source.
3. This is on top of the other input [off-cycle](https://bigladdersoftware.com/epx/docs/22-2/input-output-reference/group-unitary-equipment.html#field-ancillary-off-cycle-electric-power) power in the Unitary System object, which I suspect will double count off-cycle power.
4. It is not clear why `heatPumpRunFrac()` is used for water source heat pumps, when it comes from an old DOE-2 paper for air source heat pumps. It seems strange that we would use this very specific model for PLF when many other objects just have a PLF f(PLR) curve.
5. Why are the inputs for the PLF calculation in the parent object instead of the coil, like it is for air source equipment?
6. The `Coil:*:WaterToAirHeatPump:VariableSpeedEquationFit` coils have their own PLF curve, even though their parent objects ask for inputs for the alternative `heatPumpRunFrac()` formulation.

This issue may need to be split up, since points 2-6 above likely require deeper structural changes that will break compatibility.

Here are the implied input changes:

- `AirLoopHVAC:UnitarySystem`, `AirLoopHVAC:UnitaryHeatPump:WaterToAir`, and `ZoneHVAC:WaterToAirHeatPump` (and `HVACTemplate:Zone:WaterToAirHeatPump`?):
    - Remove field for  "Fraction of On-Cycle Power Use".
    - Move "Maximum Cycling Rate", "Heat Pump Time Constant" to respective coils for latent degradation model (rename to be consistent with air-source coil inputs) 
    - Move "Heat Pump Fan Delay Time" to the respective coils (as "Fan Delay Time"). It is not specific to water-source coils, and maybe should be added to air-source coils as well.
- Add PLF curve to EquationFit (not EquationFitVariableSpeed) and ParameterEstimation coil objects.

```
HVACTemplate:Zone:WaterToAirHeatPump,
  ...,
  Supplemental Heating Coil Capacity,
  -Maximum Cycling Rate,
  -Heat Pump Time Constant,
  -Fraction of On-Cycle Power Use,
  -Heat Pump Fan Delay Time,
  Dedicated Outdoor Air System Name,
  ...;

ZoneHVAC:WaterToAirHeatPump,
  ...,
  Cooling Coil Name,
  -Maximum Cycling Rate,
  -Heat Pump Time Constant,
  -Fraction of On-Cycle Power Use,
  -Heat Pump Fan Delay Time,
  Supplemental Heating Coil Object Type,
  ...;

AirLoopHVAC:UnitarySystem,
  ...,
  Outdoor Dry-Bulb Temperature Sensor Node Name,
  -Maximum Cycling Rate,
  -Heat Pump Time Constant,
  -Fraction of On-Cycle Power Use,
  -Heat Pump Fan Delay Time,
  Ancillary On-Cycle Electric Power,
  ...;

AirLoopHVAC:UnitaryHeatPump:WaterToAir,
  ...,
  Cooling Convergence,
  -Maximum Cycling Rate,
  -Heat Pump Time Constant,
  -Fraction of On-Cycle Power Use,
  -Heat Pump Fan Delay Time,
  Supplemental Heating Coil Object Type,
  ...;

Coil:Cooling:WaterToAirHeatPump:ParameterEstimation,
  ...,
  Source Side Heat Transfer Resistance2,
  +Part Load Fraction Correlation Curve Name,
  +Maximum Cycling Rate,
  +Latent Capacity Time Constant,
  +Fan Delay Time;

Coil:Heating:WaterToAirHeatPump:ParameterEstimation,
  ...,
  Source Side Heat Transfer Resistance2,
  +Part Load Fraction Correlation Curve Name;

Coil:Cooling:WaterToAirHeatPump:EquationFit,
  ...,
  Cooling Power Consumption Curve Name,
  +Part Load Fraction Correlation Curve Name,
  Nominal Time for Condensate Removal to Begin,
  Ratio of Initial Moisture Evaporation Rate and Steady State Latent Capacity,
  +Maximum Cycling Rate,
  +Latent Capacity Time Constant,
  +Fan Delay Time;

Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit,
  ...,
  Nominal Time for Condensate to Begin Leaving the Coil,
  Initial Moisture Evaporation Rate Divided by Steady-State AC Latent Capacity,
  +Maximum Cycling Rate,
  +Latent Capacity Time Constant,
  +Fan Delay Time,
  Flag for Using Hot Gas Reheat, 0 or 1,
  Energy Part Load Fraction Curve Name,
  ...;

Coil:Heating:WaterToAirHeatPump:EquationFit,
  ...,
  Heating Power Consumption Curve Name,
  +Part Load Fraction Correlation Curve Name;

```

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Regarding the PLR and RTF definitions, the PLR is the performance side of the model as load / capacity. Because of the startup losses the system has to run longer to meet the load. Even though the system runs longer, the load is still capacity * PLR. If a fan were cycling to meet this load the air flow would be max airflow * PLR. The difference between cycling and constant fan is the outlet condition and mass flow rate. Cycling always has full output and average mass flow as max mass flow * PLR. Constant fan has max mass flow with average outlet as PLR * full outlet condtion (at PLR=1) + (1-PLR) * inlet condtion. All these performance attributes are PLR based. RTF is applid to the energy side of the model. RTF = PLR/PLF. That way you get the correct heat transfer and energy consumption. For a WSHP, the water side flow rate would be PLR based while the pumping power would be RTF based. I do realize that this is the intent of the issue so maybe we need to discuss more that part of this discussion.

Regarding heatPumpRunFrac(), I never understood where that came from or why it was different than the simple and proven PLF method. I don't think it would be too hard to sell the elimination of that RunFrac model and substitute the same model used for other coil types. For UnitarySystem, which accepts all types of coils, the PLF curve is in the child. If a parent object did decide to manage energy transfer, the parent would need to know what the RTF is, whether it is calculated by the parent or child. The other coil models calculate RTF and pass OnOffFanPartLoadFrac to the fan. I don't see why the same thing could not happen with the WSHP, except for the fact that this parent should not need to know what RTF is (I did not look what RTF is used for in this parent). The only RTF variables I see in UnitarySystem are for AFN, the fan model, and WSHP. It may be time to revisit RTF usage in a parent object. A parent needs to meet a load or a setpoint, which is PLR based.

Regarding latent capacity inputs, yes, those should reside with the cooling coil model.
